return {
	{
		id = 117543193644510,
		name = "Red Seraph Wings",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 92047174550398,
		name = "Blue Seraph Wings",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 137685573908604,
		name = "Halloween Seraph Wings",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 101579225039457,
		name = "Black Warlord Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 73228227707947,
		name = "Green Warlord Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 130582275658616,
		name = "Halloween Warrior Cape",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 91279320887900,
		name = "Halloween Warlord Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 71430243108874,
		name = "Halloween Hunter Cape",
		cost = 0,
		category = "Stream",
		setKey = "HalloweenHunter",
		setName = "Halloween Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 128280141276474,
		name = "Halloween Hunter Helmet",
		cost = 0,
		category = "Stream",
		setKey = "HalloweenHunter",
		setName = "Halloween Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 94319066583678,
		name = "Blue Warlord Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 139939957244129,
		name = "Red Dragon Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 113261091624773,
		name = "Purple Hunter Helmet",
		cost = 0,
		category = "Stream",
		setKey = "PurpleHunter",
		setName = "Purple Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 99925578896119,
		name = "Purple Hunter Cape",
		cost = 0,
		category = "Stream",
		setKey = "PurpleHunter",
		setName = "Purple Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 90857102926650,
		name = "Purple Hunter Scythe",
		cost = 0,
		category = "Stream",
		setKey = "PurpleHunter",
		setName = "Purple Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 125237994315945,
		name = "Pink Emperor Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 121629012516987,
		name = "Red Warlord Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 96753747670664,
		name = "Blue Emperor Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 105836267163727,
		name = "Green Dragon Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 121015528365304,
		name = "Purple Dragon Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 133255915785579,
		name = "Red Champion's Helmet",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 135102381960095,
		name = "Warrior Helmet",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 106915763007585,
		name = "Red Emperor Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 98815729958987,
		name = "Black Dragon Horns",
		cost = 0,
		category = "Stream",
		ownershipKnown = false,
		available = false
	},
	{
		id = 118027218576315,
		name = "Hunter Helmet",
		cost = 0,
		category = "Stream",
		setKey = "Hunter",
		setName = "Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 124109745715874,
		name = "Hunter Cape",
		cost = 0,
		category = "Stream",
		setKey = "Hunter",
		setName = "Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 127572823721524,
		name = "Hunter Scythe",
		cost = 0,
		category = "Stream",
		setKey = "Hunter",
		setName = "Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 99318830266599,
		name = "Black Storm Wings",
		cost = 2250,
		category = "Coins",
		ownershipKnown = false,
		available = false
	},
	{
		id = 136778335495727,
		name = "Green Champion Helmet",
		cost = 2250,
		category = "Coins",
		ownershipKnown = false,
		available = false
	},
	{
		id = 128041598099066,
		name = "White Emperor Cape",
		cost = 2250,
		category = "Coins",
		ownershipKnown = false,
		available = false
	},
	{
		id = 87379136297250,
		name = "Red Emperor Cape",
		cost = 2250,
		category = "Coins",
		ownershipKnown = false,
		available = false
	},
	{
		id = 70370147122812,
		name = "Red Skull Sword",
		cost = 2250,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 71067443260463,
		name = "Blue Hunter Scythe",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 71225217856119,
		name = "Red Mori Sword",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 73981095361398,
		name = "Green Hunter Helmet",
		cost = 0,
		category = "Stream",
		setKey = "GreenHunter",
		setName = "Green Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 91588089462772,
		name = "Red Hunter Cape",
		cost = 2750,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 92705928690421,
		name = "Blue Hunter Cape",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 94312813166829,
		name = "Deluxe Scythe",
		cost = 0,
		category = "Stream",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 96079126839794,
		name = "Black Greatsword",
		cost = 2250,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 96957689992180,
		name = "Onyx Hunter Helmet",
		cost = 0,
		category = "Stream",
		setKey = "OnyxHunter",
		setName = "Onyx Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 98295460327995,
		name = "Black Slayer Sword",
		cost = 2250,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 99547137886988,
		name = "Onyx Hunter Scythe",
		cost = 0,
		category = "Stream",
		setKey = "OnyxHunter",
		setName = "Onyx Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 99688224990739,
		name = "Evil Sword",
		cost = 0,
		category = "Stream",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 100165472458579,
		name = "Red Hunter Scythe",
		cost = 2750,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 102923492358419,
		name = "Red Mori Helmet",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 107401656947628,
		name = "Onyx Hunter Cape",
		cost = 0,
		category = "Stream",
		setKey = "OnyxHunter",
		setName = "Onyx Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 112891470318837,
		name = "Red Royal Scythe",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 113632982392052,
		name = "Black Axe",
		cost = 2000,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 113894675264336,
		name = "Blue Hunter Helmet",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 114986728188050,
		name = "White Skull Sword",
		cost = 2250,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 115300401229343,
		name = "Red Katana",
		cost = 0,
		category = "Stream",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 118499401287179,
		name = "Green Slayer Scythe",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 120688898969735,
		name = "Red Hunter Helmet",
		cost = 2750,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 120830135034559,
		name = "Red Greatsword",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 121329445706932,
		name = "Skull Sword",
		cost = 2000,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 128760805526094,
		name = "Black Sword",
		cost = 1750,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 131787792152031,
		name = "Gold Cape",
		cost = 0,
		category = "Stream",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 135208134309739,
		name = "Red Ruby Crown",
		cost = 2500,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 137293845395698,
		name = "Green Hunter Cape",
		cost = 0,
		category = "Stream",
		setKey = "GreenHunter",
		setName = "Green Hunter Set",
		ownershipKnown = false,
		available = false
	},
	{
		id = 138609251401934,
		name = "Black Void Katana",
		cost = 0,
		category = "Stream",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	},
	{
		id = 140281374237199,
		name = "Toebuu Lil Waffle",
		cost = 1750,
		category = "Coins",
		setKey = nil,
		setName = nil,
		ownershipKnown = false,
		available = false
	}
}