return {
	NEUROTOXIN_DURATION = 3,
	NEUROTOXIN_MOVEMENT_FACTOR = -0.35,
	NEUROTOXIN_ATTACK_SPEED_FACTOR = -0.1,
	VIRAL_DECAY_DURATION = 4,
	VIRAL_DECAY_START_PERCENT = 0.02,
	VIRAL_DECAY_GROW_PERCENT = 0.01,
	VIRAL_DECAY_MAX_PERCENT = 0.05,
	BOSS_VIRAL_DECAY_SCALE = 0.5
}