local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TrailUISystem = require(ReplicatedStorage:WaitForChild("TrailUISystem"))
local AuraUISystem = require(ReplicatedStorage:WaitForChild("UISystems"):WaitForChild("AuraUISystem"))
local RobuxShopUISystem = require(ReplicatedStorage:WaitForChild("UISystems"):WaitForChild("RobuxShopUISystem"))
local EventUISystem = require(ReplicatedStorage:WaitForChild("EventUISystem"))
local NextEventTimerSystem = require(ReplicatedStorage:WaitForChild("NextEventTimerSystem"))
local RadarSystem = require(ReplicatedStorage:WaitForChild("RadarSystem"))
local NotificationSystem = require(ReplicatedStorage:WaitForChild("NotificationSystem"))
local remotes = ReplicatedStorage:WaitForChild("Remotes")
TrailUISystem:InitLogic()
AuraUISystem:InitLogic()
RobuxShopUISystem:InitLogic()
EventUISystem:Init()
NextEventTimerSystem:Init()
RadarSystem:Init()
remotes:WaitForChild("CurrencyCollect").OnClientEvent:Connect(function(data)
	NotificationSystem:ShowCurrencyCollect(data.icon, data.label, data.amount, data.rarity)
end)