local createVector = vector.create
local Config = {
	MOUSE_RANGE = 80,
	STARTUP_SPEED = 1.35,
	RELEASE_SPEED = 2.7,
	FREEZE_MARK = 0.5
}
Config.SHOT_DELAY = 1.35 / Config.RELEASE_SPEED
Config.RELEASE_DELAY = 0.27
Config.PROJECTILE_SPEED = 200
Config.PROJECTILE_DURATION = 1.25
Config.PROJECTILE_SIZE = createVector(8, 8, 18)
Config.PROJECTILE_AOE_SIZE = createVector(32, 15, 32)
Config.PROJECTILE_DAMAGE = 8
Config.PROJECTILE_STUN = 0.75
Config.UPDRAFT_HEIGHT = 25
Config.UPDRAFT_DURATION = 5
Config.BARRAGE_ANIM_SPEED = 1.35
Config.BARRAGE_AIM_DURATION = Config.PROJECTILE_DURATION + 2.57 / Config.BARRAGE_ANIM_SPEED
Config.BARRAGE_HIT_COUNT = 12
Config.BARRAGE_CLOSE_WAVE_SIZE = createVector(12, 12, 20)
Config.BARRAGE_CLOSE_WAVE_FINISH_SIZE = createVector(12, 12, 18)
Config.BARRAGE_CLOSE_WAVE_DAMAGE = 1.5
Config.BARRAGE_CLOSE_WAVE_KNOCKBACK = 4
Config.BARRAGE_CLOSE_WAVE_FINISH_KNOCKBACK = 50
Config.POS_PART_NAME = "PosPart" .. script.Parent.Name
return Config