local createVector = vector.create
return {
	SETUP_DELAY = 0.05,
	PHASE_GAP = 0.5,
	POST_HIT_LOCK = 0.3,
	SEQUENCE_LOCK_DURATION = 1.2,
	SETUP_HITBOX_SIZE = createVector(20, 25, 20),
	SETUP_DAMAGE = 8.1,
	SETUP_STUN = 1,
	SETUP_KNOCKBACK = 7,
	AIR_COMBO_Y = 20,
	AIR_COMBO_DURATION = 0.5,
	SWEEP_HITBOX_SIZE = createVector(25, 25, 65),
	SWEEP_DAMAGE = 16.2,
	SWEEP_KNOCKBACK = 40,
	IMPACT_STUN = 1,
	BLOCK_BREAK = 1
}