local createVector = vector.create
local Config = {
	HOLD_DURATION = 0.3,
	MOUSE_RANGE = 500,
	HOLD_FREEZE_AT = 0.2,
	RELEASE_LOCK_DUR = 2,
	TAP_DAMAGE = 16,
	TAP_HIT_COUNT = 10,
	TAP_HIT_DUR = 0.7,
	TAP_STUN = 1.8,
	TAP_BLOCK_BREAK = 2,
	TAP_HITBOX_SIZE = createVector(22, 25, 22),
	TAP_HITBOX_OFFSET = CFrame.new(0, 7.5, 0),
	TAP_WHIFF_UPTILT_DUR = 0.6,
	TAP_RECOVER_DUR = 0.5,
	BASIN_DASH_DELAY = 0,
	BASIN_DASH_SPEED = 65,
	BASIN_DASH_DUR = 0.8,
	BASIN_START_AT = 0.255,
	BASIN_SLAM_INTERVAL = 0.45,
	BASIN_SLAM_OFFSETS = { -10, -10 },
	BASIN_DAMAGE = 13,
	BASIN_STUN = 2.25,
	BASIN_RAGDOLL = 2.25,
	BASIN_KNOCKBACK = 30,
	BASIN_KNOCKUP_RATIO = 0.6,
	BASIN_BLOCK_BREAK = 1,
	BASIN_HITBOX_SIZE = createVector(16, 24, 40)
}
Config.BASIN_HITBOX_OFFSET = CFrame.new(0, Config.BASIN_HITBOX_SIZE.Y / 2 - 3, -2)
Config.SLOW_VALUE = "WhirlPoolUndertow"
Config.BASIN_SLOW_DURATION = 3
Config.BASIN_SLOW_FACTOR = -0.25
Config.PVP = {
	RankedCooldown = 1.1538461538461537
}
return Config