return {
	Tidefall = {
		"I thought it was just another drop. Turns out Tidefall doesn’t really let you back up.",
		"My compass keeps spinning. Guess directions don’t mean much down here.",
		"Water’s calm, but everything around it feels like it’s watching me.",
		"I surfaced into this cavern and realized the ceiling just keeps going. No daylight anywhere.",
		"These vines weren’t here when I passed through earlier… or maybe I didn’t notice.",
		"Tidefall branches out like a maze. Every tunnel feels like it leads somewhere important.",
		"The plants grow thick here, like the cave itself is alive and breathing.",
		"I keep hearing water moving far away. Can’t tell if it’s an exit or a warning.",
		"Light doesn’t travel right down here. Shadows stretch where they shouldn’t.",
		"Found an opening covered in roots and kelp. Feels like something sealed it on purpose.",
		"My air’s fine—for now. It’s the time that feels wrong.",
		"Currents pull in strange directions. Almost like the cave is guiding me.",
		"Some areas glow faintly, others swallow light completely.",
		"I marked my path, but the marks don’t line up anymore.",
		"There’s more than one Tidefall. Each section feels… different.",
		"The vines tighten the deeper I go. Hard to tell what’s natural anymore.",
		"Water drips from above, but I can’t see where it’s coming from.",
		"I swear I’ve swum past this formation already.",
		"Everything echoes, even thoughts I didn’t say out loud.",
		"There are paths here that don’t feel meant for divers.",
		"I stopped trying to find the way out. Now I’m just mapping what’s left.",
		"Some tunnels feel ancient. Others feel newly opened.",
		"The bushes here grow underwater, yet they sway like there’s wind.",
		"Tidefall doesn’t feel empty. Just quiet.",
		"If there’s a surface down here, it’s hiding well.",
		"The deeper chambers feel heavier, like the water itself remembers something.",
		"I followed the vines thinking they’d lead upward. They didn’t.",
		"Every turn feels deliberate. Like the cave wants choices made.",
		"I came down expecting ruins. Found something much older.",
		"As long as I keep moving, Tidefall hasn’t swallowed me yet."
	},
	CollapsedRuins = {
		"Everything here looks like it fell all at once.",
		"Stone blocks pile up like the ground gave out.",
		"I had to squeeze through gaps that weren’t meant to exist.",
		"The ruins don’t line up anymore.",
		"Every movement stirs dust and old debris.",
		"I hear shifting stone, even when I stop.",
		"This place doesn’t forgive mistakes.",
		"Passages end abruptly, crushed flat.",
		"I keep finding pieces that clearly belonged together—once.",
		"The collapse feels recent. Or maybe it just never settled.",
		"Currents slip through cracks in unpredictable ways.",
		"Nothing here feels stable for long.",
		"I’m careful where I rest. Even the floor can give way.",
		"This area feels abandoned by force.",
		"The ruins didn’t age. They broke."
	},
	CoralBastion = {
		"The coral here grows like it’s protecting something.",
		"Every wall feels reinforced by time and living stone.",
		"I brushed past a branch and it snapped back into place behind me.",
		"This place doesn’t crumble—it holds.",
		"Fish move carefully here, like they know the rules.",
		"The coral layers stack higher than I expected. Like ramparts.",
		"Light filters in, but only where the coral allows it.",
		"I found shelter without meaning to. The Bastion closes around you.",
		"Nothing rushes here. Even the currents slow down.",
		"The structures feel grown, not built.",
		"Some coral glows faintly, like it’s still awake.",
		"I get the sense this area was meant to last.",
		"Paths form naturally, then disappear just as fast.",
		"It’s quiet in a guarded kind of way.",
		"The Bastion feels patient. Unmovable."
	},
	CrownedRuins = {
		"Gold still shines down here. That’s unsettling.",
		"The structures are intact—almost proud.",
		"I’ve never seen metal hold up like this underwater.",
		"Every surface reflects light back at me.",
		"It feels ceremonial, even in ruin.",
		"Gold inlays trace patterns I don’t recognize.",
		"This place looks safe. I don’t trust that.",
		"The crowns and crests are everywhere.",
		"Some doors are sealed with gold, not stone.",
		"It feels like wealth tried to outlast the ocean.",
		"I expected decay. Found splendor instead.",
		"The ruins gleam like they’re waiting to be claimed.",
		"Even the rubble is decorated.",
		"This area feels watched in a different way.",
		"Gold doesn’t mean power anymore… but it remembers when it did."
	},
	SunkenReliquary = {
		"The shelves are still standing. That feels intentional.",
		"Books shouldn’t survive this long underwater.",
		"Symbols line the walls, glowing just enough to read—almost.",
		"This place hums, like it remembers every word spoken here.",
		"I swam past a lectern that hadn’t tipped over.",
		"The water feels thicker in here. Heavy with thought.",
		"Some texts are sealed shut. Others drift freely.",
		"It feels wrong to rush through this place.",
		"The light here isn’t natural, but it’s steady.",
		"I swear the runes rearranged when I wasn’t looking.",
		"This was a library… or something pretending to be one.",
		"Knowledge sinks deep, I guess.",
		"I touched a page and felt a pulse.",
		"Even the ruins seem careful not to disturb anything.",
		"This place wants to be remembered."
	}
}