return function(p)
	local Base = require(script.Base)
	local base = Base(p)
	local Field = require(script.Field)
	local field = Field(p, base)
	local Box = require(script.Box)
	local v3 = {
		Box = Box(p, base),
		Button = 0,
		Checkbox = 0,
		Dropdown = 0,
		BigDropdown = 0,
		Field = 0,
		NumberField = 0,
		ShortenedNumberField = 0,
		NumberRangeField = 0,
		Vector2Field = 0,
		Vector3Field = 0,
		CFrameField = 0,
		List = 0,
		Slider = 0,
		Split = 0,
		Tab = 0,
		Text = 0,
		Title = 0,
		Viewport = 0,
		Graph = 0,
		SequenceEditor = 0,
		Color = 0,
		Image = 0,
		Separator = 0,
		Expandable = 0,
		RichtextEditor = 0,
		Time = 0
	}
	local Button = require(script.Button)
	v3.Button = Button(p, base)
	local Checkbox = require(script.Checkbox)
	v3.Checkbox = Checkbox(p, base)
	local Dropdown = require(script.Dropdown)
	v3.Dropdown = Dropdown(p, base)
	local BigDropdown = require(script.BigDropdown)
	v3.BigDropdown = BigDropdown(p, base)
	v3.Field = field
	local NumberField = require(script.SpecificFields.NumberField)
	v3.NumberField = NumberField(p, base, field)
	local ShortenedNumberField = require(script.SpecificFields.ShortenedNumberField)
	v3.ShortenedNumberField = ShortenedNumberField(p, base, field)
	local NumberRangeField = require(script.SpecificFields.NumberRangeField)
	v3.NumberRangeField = NumberRangeField(p, base, field)
	local Vector2Field = require(script.SpecificFields.Vector2Field)
	v3.Vector2Field = Vector2Field(p, base, field)
	local Vector3Field = require(script.SpecificFields.Vector3Field)
	v3.Vector3Field = Vector3Field(p, base, field)
	local CFrameField = require(script.SpecificFields.CFrameField)
	v3.CFrameField = CFrameField(p, base, field)
	local List = require(script.List)
	v3.List = List(p, base)
	local Slider = require(script.Slider)
	v3.Slider = Slider(p, base)
	local Split = require(script.Split)
	v3.Split = Split(p, base)
	local Tab = require(script.Tab)
	v3.Tab = Tab(p, base)
	local Text = require(script.Text)
	v3.Text = Text(p, base)
	local Title = require(script.Title)
	v3.Title = Title(p, base)
	local Viewport = require(script.Viewport)
	v3.Viewport = Viewport(p, base)
	local Graph = require(script.Graph)
	v3.Graph = Graph(p, base)
	local SequenceEditor = require(script.SequenceEditor)
	v3.SequenceEditor = SequenceEditor(p, base)
	local Color = require(script.Color)
	v3.Color = Color(p, base)
	local Image = require(script.Image)
	v3.Image = Image(p, base)
	local Separator = require(script.Separator)
	v3.Separator = Separator(p, base)
	local Expandable = require(script.Expandable)
	v3.Expandable = Expandable(p, base)
	local RichtextEditor = require(script.RichtextEditor)
	v3.RichtextEditor = RichtextEditor(p, base)
	local Time = require(script.Time)
	v3.Time = Time(p, base)
	return v3
end