local ListData = {
	Items = {
		"Coin",
		"Gun",
		"TNT",
		"Jet Black",
		"Soda",
		"Banana Peel",
		"Tinted Glasses",
		"Hazenoki's Eye",
		"Voice Recorder",
		"Transfigured Human",
		"Transfigured Flesh",
		"Playful Cloud",
		"Sniper",
		"Broom",
		"Flashlight",
		"Snowball",
		"Bowling Ball",
		"Naginata",
		"Crowbar",
		"Tiantui Star's Blade",
		"Tiansha Star's Blade"
	},
	MoveList = {
		{
			{ "HONORED ONE", Color3.fromRGB(170, 255, 255) },
			"Lapse Blue",
			"Reversal Red",
			"Rapid Punches",
			"Twofold Kick",
			"Lapse Blue MAX",
			"Reversal Red MAX",
			"Hollow Purple",
			"Infinite Void"
		},
		{
			{ "VESSEL", Color3.fromRGB(255, 155, 155) },
			"Cursed Strikes",
			"Crushing Blow",
			"Divergent Fist",
			"Manji Kick",
			"Dismantle",
			"Open",
			"Rush",
			"Malevolent Shrine"
		},
		{
			{ "RESTLESS GAMBLER", Color3.fromRGB(170, 255, 127) },
			"Reserve Balls",
			"Shutter Doors",
			"Rough Energy",
			"Fever Breaker",
			"Lucky Volley",
			"Lucky Rushdown",
			"Overwhelming Luck",
			"Energy Surge"
		},
		{
			{ "TEN SHADOWS", Color3.fromRGB(120, 120, 120) },
			"Rabbit Escape",
			"Nue",
			"Toad",
			"Divine Dog: Totality",
			"Max Elephant",
			"Great Serpent",
			"Shadow Swarm",
			"Mahoraga"
		},
		{
			{ "MAHORAGA", Color3.fromRGB(255, 255, 255) },
			"Divine Pummel",
			"Ground Pitch",
			"Earthquake",
			"Takedown",
			"Adaptation",
			"World Slash"
		},
		{
			{ "PERFECTION", Color3.fromRGB(255, 170, 255) },
			"Stockpile",
			"Soul Fire",
			"Focus Strike",
			"Body Repel",
			"Idle Transfiguration",
			"Body Disfigure",
			"Spike Wrath",
			"Embodiment of Self Perfection",
			"Widespread Strikes",
			"Face Blitz",
			"Crushing Rushdown",
			"Head Splitter"
		},
		{
			{ "BLOOD MANIPULATOR", Color3.fromRGB(170, 75, 75) },
			"Piercing Blood",
			"Flowing Red Scale",
			"Supernova",
			"Blood Edge",
			"Slicing Exorcism",
			"Wing King",
			"Blood Rain",
			"Plasma Wave"
		},
		{
			{ "SWITCHER", Color3.fromRGB(170, 255, 255) },
			"Swift Kick",
			"Brute Force",
			"Pebble Throw",
			"Elbow Drop",
			"Idol's Debut",
			"Climax Jumping",
			"Dreams",
			"Brothers"
		},
		{
			{ "LOCUST", Color3.fromRGB(170, 255, 127) },
			"Crushing Jaws",
			"Clever",
			"Wing Throw",
			"Black Mucus"
		},
		{
			{ "DEFENSE ATTORNEY", Color3.fromRGB(115, 99, 77) },
			"Extended Swings",
			"Justice Served",
			"Judgement's Reach",
			"Pressing Charges",
			"Execution",
			"Final Judgement",
			"Verdict",
			"Triple Sentence",
			"Grapple"
		},
		{
			{ "STAR RAGE", Color3.fromRGB(170, 170, 255) },
			"Garuda Rebound",
			"Rising Rage",
			"Mass Breaker",
			"Garuda Stab"
		},
		{
			{ "HEIAN", Color3.fromRGB(255, 85, 0) },
			"Strong Dismantle",
			"Open FURNACE",
			"Cleave Rush",
			"Kamutoke"
		},
		{
			{ "CURSED PARTNERS", Color3.fromRGB(255, 170, 255) },
			"Severing Path",
			"Resolute Slash",
			"Veilstep",
			"Second Wind",
			"Outburst",
			"Revolve",
			"Rika Downslam",
			"Rika Launch",
			"Rika Slam",
			"Rika Haymaker",
			"Rika Grab",
			"Rika Throw",
			"Rika Smash",
			"True Love Beam",
			"Authentic Mutual Love",
			"Elbow Rush",
			"Copy",
			"Energy Ripple"
		},
		{
			{ "ASPIRING MANGAKA", Color3.fromRGB(255, 235, 235) },
			"Despair",
			"Shut Up!",
			"Eye Catching",
			"Sacrilege"
		},
		{
			{ "PUPPET MASTER", Color3.fromRGB(225, 10, 75) },
			"Ultra Spin",
			"Boost On",
			"Ultra Cannon",
			"Heat Emission",
			"Miracle Cannon",
			"Pigeon Viola",
			"Absolute Destruction",
			"Technique Charge",
			"Boost On OLD",
			"Ultra Cannon OLD"
		},
		{
			{ "HEAD OF THE HEI", Color3.fromRGB(128, 126, 255) },
			"Projection Breaker",
			"Bleedout",
			"Decisive Strike",
			"Cursory Impact",
			"Top Speed",
			"Flash Freezing",
			"Tendril Grab",
			"Time Cell Moon Palace",
			"Decisive Strike OLD"
		},
		{
			{ "SALARYMAN", Color3.fromRGB(94, 191, 255) },
			"Cleaving Whirlwind",
			"Severance Kick",
			"Blunt Cut",
			"Stabilize",
			"Ratio Breaker",
			"Sharpen",
			"Interrogate",
			"Collapse"
		},
		{
			{ "MONKEY KID", Color3.fromRGB(255, 21, 52) },
			"Kamehameha",
			"Ki Spam",
			"Staff Extend",
			"Staff Uppercut"
		},
		{
			{ "LUCKY COWARD", Color3.fromRGB(167, 125, 203) },
			"Ambush",
			"Backstab",
			"Trip",
			"Cheap Shot",
			"Ankle Cutter",
			"High Time",
			"Dirty Play"
		},
		{
			{ "CROW CHARMER", Color3.fromRGB(35, 40, 80) },
			"Impetus Updraft",
			"Circling",
			"Gliding Flight",
			"Bird Control"
		},
		{
			{ "DISASTER PLANTS", Color3.fromRGB(172, 203, 163) },
			"Root Swarm",
			"Surging Thorns",
			"Bud Shot",
			"Defense Response",
			"Cursed Buds",
			"Shining Sea of Growing Branches",
			"Flower Field",
			"Root Rampage"
		},
		{
			{ "TRUE CANNON", Color3.fromRGB(170, 255, 255) },
			"Granite Blast",
			"Unsatisfied",
			"Second Helping",
			"Appetizer",
			"\"What are you after?\"",
			"\"I had no idea...\"",
			"\"This is what dessert is like!\"",
			"\"You weren't invited.\""
		},
		{
			{ "BLACK DEATH", Color3.fromRGB(101, 35, 44) },
			"Festering Strikes",
			"Detach",
			"Chokehold",
			"Roach Swarm"
		},
		{
			{ "REGISTER", Color3.fromRGB(255, 255, 255) },
			"Gushing Wound",
			"Homerun",
			"Littering",
			"Coupon",
			"Piano Drop",
			"Garage Sale",
			"Blunt Trauma",
			"Fleche",
			"Drone Strike",
			"Pole Vault"
		},
		{
			{ "SKY ASSASSIN", Color3.fromRGB(255, 165, 165) },
			"Blind Rage",
			"Sky Distortion",
			"Thin Ice Breaker"
		}
	},
	SpecialList = {
		Limitless = 1,
		["Combat Instincts"] = 2,
		Cleave = 2,
		["Door Guard"] = 3,
		Rhythm = 3,
		["Lurking Shadow"] = 4,
		["Adaptation Wheel"] = 5,
		["Self Transfiguration"] = 6,
		Convergence = 7,
		["Boogie Woogie"] = 8,
		["Fluttering Pounce"] = 9,
		["No Escape"] = 10,
		["Domain Amplification"] = 10,
		["Mass Buildup"] = 11,
		Incantation = 12,
		Rika = 13,
		Clairvoyance = 14,
		Offload = 15,
		["Energy Output"] = 15,
		["Projection Sorcery"] = 16,
		Acceleration = 16,
		["Ratio Point"] = 17,
		["Instant Transmission"] = 18,
		["Helping Hand"] = 19,
		Flock = 20,
		["Flower Field"] = 21,
		Restyle = 22,
		["Earthen Insect Trance"] = 23,
		Discard = 24
	},
	AttackTypes = {
		"Melee",
		"Bullet",
		"Explosion",
		"Swarm",
		"Domain"
	},
	States = {
		"Cancel",
		"Stun",
		"IFrame",
		"NoM1",
		"NoSprint",
		"NoJump",
		"NoDash",
		"NoBlock",
		"NoParkour",
		"NoMass",
		"NoDeath",
		"DisableChase",
		"Block",
		"DirectionLock",
		"SpeedMultiplier",
		"JumpMultiplier",
		"DamageMultiplier",
		"HealthMultiplier",
		"KnockbackMultiplier",
		"Scale",
		"InSkill",
		"CameraMaxZoomDistance",
		"Wakeup",
		"Ragdoll",
		"Character",
		"Projection",
		"Bleed",
		"LastHit"
	},
	Characters = {
		"Gojo",
		"Itadori",
		"Hakari",
		"Megumi",
		"Mahoraga",
		"Mahito",
		"Choso",
		"Todo",
		"Locust",
		"Hiromi",
		"Yuki",
		"Heian",
		"Yuta",
		"Charles",
		"Mechamaru",
		"Naoya",
		"Nanami",
		"Goku",
		"Haruta",
		"MeiMei",
		"Hanami",
		"Ryu",
		"Kurourushi",
		"Reggie",
		"Uro"
	},
	Materials = {
		Enum.Material.Plastic,
		Enum.Material.SmoothPlastic,
		Enum.Material.Neon,
		Enum.Material.Wood,
		Enum.Material.WoodPlanks,
		Enum.Material.Marble,
		Enum.Material.Slate,
		Enum.Material.Concrete,
		Enum.Material.CrackedLava,
		Enum.Material.Basalt,
		Enum.Material.Limestone,
		Enum.Material.Granite,
		Enum.Material.Pavement,
		Enum.Material.Brick,
		Enum.Material.Pebble,
		Enum.Material.Cobblestone,
		Enum.Material.Rock,
		Enum.Material.Sandstone,
		Enum.Material.CorrodedMetal,
		Enum.Material.DiamondPlate,
		Enum.Material.Foil,
		Enum.Material.Metal,
		Enum.Material.Grass,
		Enum.Material.LeafyGrass,
		Enum.Material.Sand,
		Enum.Material.Fabric,
		Enum.Material.Snow,
		Enum.Material.Mud,
		Enum.Material.Ground,
		Enum.Material.Asphalt,
		Enum.Material.Salt,
		Enum.Material.Ice,
		Enum.Material.Glacier,
		Enum.Material.Glass,
		Enum.Material.ForceField,
		Enum.Material.Air,
		Enum.Material.Water,
		Enum.Material.Cardboard,
		Enum.Material.Carpet,
		Enum.Material.CeramicTiles,
		Enum.Material.ClayRoofTiles,
		Enum.Material.RoofShingles,
		Enum.Material.Leather,
		Enum.Material.Plaster,
		Enum.Material.Rubber
	}
}
local animations = game.ReplicatedStorage.Animations
ListData.AnimList = {
	{
		animations.Gojo.HollowPurple,
		animations.Gojo.InfiniteVoid,
		animations.Gojo.LapseBlue,
		animations.Gojo.LapseBlueMaximum,
		animations.Gojo.RapidPunches,
		animations.Gojo.ReversalRed,
		animations.Gojo.ReversalRedMaximum,
		animations.Gojo.Teleport,
		animations.Gojo.TwofoldHit,
		animations.Gojo.TwofoldKick,
		animations.Gojo.Ultimate,
		animations.Gojo.ShortVoid,
		animations.Gojo.Melee.Melee1,
		animations.Gojo.Melee.Melee2,
		animations.Gojo.Melee.Melee3,
		animations.Gojo.Melee.Melee4,
		animations.Gojo.Melee.Up,
		animations.Gojo.Melee.Down,
		animations.Gojo.Melee.Chase
	},
	{
		animations.Itadori.CursedStrike,
		animations.Itadori.CursedStrikeHit,
		animations.Itadori.CrushingBlow,
		animations.Itadori.Variants.DivergentFist1,
		animations.Itadori.Variants.DivergentFist2,
		animations.Itadori.Variants.DivergentFist3,
		animations.Itadori.Variants.DivergentFist4,
		animations.Itadori.ManjiKick,
		animations.Itadori.ManjiKickHit,
		animations.Itadori.Cleave,
		animations.Itadori.Dismantle,
		animations.Itadori.FlameArrow,
		animations.Itadori.Rush,
		animations.Itadori.RushHit,
		animations.Itadori.MalevolentShrine,
		animations.Itadori.SlaughterDemon,
		animations.Itadori.Ultimate,
		animations.Itadori.UltimateEnchain,
		animations.Itadori.Instincts,
		animations.Itadori.Melee.Melee1,
		animations.Itadori.Melee.Melee2,
		animations.Itadori.Melee.Melee3,
		animations.Itadori.Melee.Melee4
	},
	{
		animations.Hakari.Counter,
		animations.Hakari.EnergySurge,
		animations.Hakari.FeverBreaker,
		animations.Hakari.IdleDeath,
		animations.Hakari.LuckyRushdown,
		animations.Hakari.LuckyVolley,
		animations.Hakari.OverLuck,
		animations.Hakari.ReserveBalls,
		animations.Hakari.Rhythm,
		animations.Hakari.RoughEnergy,
		animations.Hakari.ShutterDoors,
		animations.Hakari.Melee.Melee1,
		animations.Hakari.Melee.Melee2,
		animations.Hakari.Melee.Melee3,
		animations.Hakari.Melee.Melee4,
		animations.Hakari.Melee.Up,
		animations.Hakari.Melee.Chase
	},
	{
		animations.Megumi.DivineDog,
		animations.Megumi.GreatSerpent,
		animations.Megumi.MahoragaSummon,
		animations.Megumi.MahoragaUse,
		animations.Megumi.MaxElephant,
		animations.Megumi.Nue,
		animations.Megumi.RabbitEscape,
		animations.Megumi.Shadow,
		animations.Megumi.ShadowSwarm,
		animations.Megumi.ShadowSwarm1,
		animations.Megumi.ShadowSwarm2,
		animations.Megumi.ShadowSwarmHit,
		animations.Megumi.ShadowSwarmRun,
		animations.Megumi.Ultimate,
		animations.Megumi.Melee.Melee1,
		animations.Megumi.Melee.Melee2,
		animations.Megumi.Melee.Melee3,
		animations.Megumi.Melee.Melee4
	},
	{
		animations.Megumi.Mahoraga.Adaptation,
		animations.Megumi.Mahoraga.DivinePummel,
		animations.Megumi.Mahoraga.Earthquake,
		animations.Megumi.Mahoraga.GroundPitch,
		animations.Megumi.Mahoraga.Parry,
		animations.Megumi.Mahoraga.Takedown,
		animations.Megumi.Mahoraga.WorldSlash,
		animations.Megumi.Mahoraga.Melee.Melee1,
		animations.Megumi.Mahoraga.Melee.Melee2,
		animations.Megumi.Mahoraga.Melee.Melee3,
		animations.Megumi.Mahoraga.Melee.Melee4,
		animations.Megumi.Mahoraga.Melee.Up,
		animations.Megumi.Mahoraga.Melee.Down
	},
	{
		animations.Mahito.BodyRepel,
		animations.Mahito.CrushingRushdown,
		animations.Mahito.CrushingRushdownHit,
		animations.Mahito.DrillSplit,
		animations.Mahito.FaceBlitz,
		animations.Mahito.FocusStrike,
		animations.Mahito.ForceGrab,
		animations.Mahito.HeadSplitter,
		animations.Mahito.HeadSplitterHit,
		animations.Mahito.HeartPiercer,
		animations.Mahito.IdleTransfig,
		animations.Mahito.SelfPerfection,
		animations.Mahito.Soulfire,
		animations.Mahito.SpikeWrath,
		animations.Mahito.Stockpile,
		animations.Mahito.Ultimate,
		animations.Mahito.Ultimate2,
		animations.Mahito.WideStrike,
		animations.Mahito.WideStrikeHit,
		animations.Mahito.Variants.ChaseClub,
		animations.Mahito.Variants.ChaseSword,
		animations.Mahito.Variants.ChaseArmor,
		animations.Mahito.Melee.Melee1,
		animations.Mahito.Melee.Melee2,
		animations.Mahito.Melee.Melee3,
		animations.Mahito.Melee.Melee4,
		animations.Mahito.Melee.Up,
		animations.Mahito.Variants.MeleeClub.Melee1,
		animations.Mahito.Variants.MeleeClub.Melee2,
		animations.Mahito.Variants.MeleeClub.Melee3,
		animations.Mahito.Variants.MeleeClub.Melee4,
		animations.Mahito.Variants.MeleeClub.Down,
		animations.Mahito.Variants.MeleeSword.Melee1,
		animations.Mahito.Variants.MeleeSword.Melee2,
		animations.Mahito.Variants.MeleeSword.Melee3,
		animations.Mahito.Variants.MeleeSword.Melee4
	},
	{
		animations.Choso.BloodEdge,
		animations.Choso.BloodEdgeVictim,
		animations.Choso.BloodRain,
		animations.Choso.Convergence,
		animations.Choso.PiercingBlood,
		animations.Choso.PlasmaWave,
		animations.Choso.RedScale,
		animations.Choso.RedScaleAir,
		animations.Choso.RedScaleVictim,
		animations.Choso.SlicingExorcism,
		animations.Choso.Supernova,
		animations.Choso.SupernovaCounter,
		animations.Choso.Ultimate,
		animations.Choso.WingKing,
		animations.Choso.WingKingVictim,
		animations.Choso.Melee.Melee1,
		animations.Choso.Melee.Melee2,
		animations.Choso.Melee.Melee3,
		animations.Choso.Melee.Melee4
	},
	{
		animations.Todo.Brothers,
		animations.Todo.BruteForce,
		animations.Todo.ClimaxJump,
		animations.Todo.ClimaxJumpHit,
		animations.Todo.Dreams,
		animations.Todo.ElbowDrop,
		animations.Todo.IdolDebut,
		animations.Todo.PebbleThrow,
		animations.Todo.PebbleThrowHit,
		animations.Todo.SwiftKick,
		animations.Todo.SwiftKickHit,
		animations.Todo.Ultimate,
		animations.Todo.UltimateSummon,
		animations.Todo.TakadaJoint.JumpStart,
		animations.Todo.TakadaJoint.JumpEnd,
		animations.Todo.TakadaJoint.TakadaIdle,
		animations.Todo.TakadaJoint.Emote,
		animations.Todo.Clap.Clap1,
		animations.Todo.Clap.Clap2,
		animations.Todo.Clap.Clap3,
		animations.Todo.Melee.Melee1,
		animations.Todo.Melee.Melee2,
		animations.Todo.Melee.Melee3,
		animations.Todo.Melee.Melee4
	},
	{
		animations.Locust.BlackMucus,
		animations.Locust.BugFlight,
		animations.Locust.Flight,
		animations.Locust.FourArmed,
		animations.Locust.SnapChomp,
		animations.Locust.SnapChompHit,
		animations.Locust.Ultimate,
		animations.Locust.Melee.Melee1,
		animations.Locust.Melee.Melee2,
		animations.Locust.Melee.Melee3,
		animations.Locust.Melee.Melee4
	},
	{
		animations.Hiromi.DeadlySentence,
		animations.Hiromi.Execution,
		animations.Hiromi.ExecutionHit1,
		animations.Hiromi.ExecutionHit2,
		animations.Hiromi.ExecutionHit3,
		animations.Hiromi.ExtendSwing,
		animations.Hiromi.FinalJudgement,
		animations.Hiromi.FinalJudgementHit,
		animations.Hiromi.Grapple,
		animations.Hiromi.JusticeServed,
		animations.Hiromi.JusticeServedHit,
		animations.Hiromi.TwirlingStrikes,
		animations.Hiromi.Ultimate,
		animations.Hiromi.Dodge.Dodge1,
		animations.Hiromi.Dodge.Dodge2,
		animations.Hiromi.Dodge.Dodge3,
		animations.Hiromi.Dodge.Dodge4,
		animations.Hiromi.Dodge.Dodge5,
		animations.Hiromi.Verdict,
		animations.Hiromi.TripleSentence,
		animations.Hiromi.TripleSentenceHit,
		animations.Hiromi.JudgeReach,
		animations.Hiromi.JudgeReachHit,
		animations.Hiromi.JudgeReachHit2,
		animations.Hiromi.GavelThrow,
		animations.Hiromi.Melee.Melee1,
		animations.Hiromi.Melee.Melee2,
		animations.Hiromi.Melee.Melee3,
		animations.Hiromi.Melee.Melee4,
		animations.Hiromi.Melee2.Melee1,
		animations.Hiromi.Melee2.Melee2,
		animations.Hiromi.Melee2.Melee3,
		animations.Hiromi.Melee2.Melee4,
		animations.Hiromi.Melee2.Chase,
		animations.Hiromi.JudgeReach2,
		animations.Hiromi.PressingCharges
	},
	{
		animations.Yuki.GarudaRebound,
		animations.Yuki.GarudaStab,
		animations.Yuki.GarudaStabHit,
		animations.Yuki.MassBreaker,
		animations.Yuki.RisingStar,
		animations.Yuki.Ultimate,
		animations.Yuki.MeleeOld.Melee1,
		animations.Yuki.MeleeOld.Melee2,
		animations.Yuki.MeleeOld.Melee3,
		animations.Yuki.MeleeOld.Melee4,
		animations.Yuki.Melee.Melee1,
		animations.Yuki.Melee.Melee2,
		animations.Yuki.Melee.Melee3,
		animations.Yuki.Melee.Melee4
	},
	{
		animations.Heian.Chant,
		animations.Heian.Cleave,
		animations.Heian.Dismantle,
		animations.Heian.FlameArrow,
		animations.Heian.Kamutoke,
		animations.Heian.MalevolentShrine,
		animations.Heian.WCS
	},
	{
		animations.Yuta.ResoluteSlash,
		animations.Yuta.Revolve,
		animations.Yuta.SeveringPath,
		animations.Yuta.Sheath,
		animations.Yuta.Veilstep,
		animations.Yuta.VeilstepDive,
		animations.Yuta.SeveringPathAir,
		animations.Yuta.RevolveReaction,
		animations.Yuta.YutaBeam,
		animations.Yuta.Launch,
		animations.Yuta.Ultimate,
		animations.Yuta.JacobLadder,
		animations.Yuta.JacobLadderTarget,
		animations.Yuta.ElbowBeatdown,
		animations.Yuta.ElbowBeatdownTarget,
		animations.Yuta.RunSlash,
		animations.Yuta.CursedSpeech,
		animations.Yuta.Melee.Melee1,
		animations.Yuta.Melee.Melee2,
		animations.Yuta.Melee.Melee3,
		animations.Yuta.Melee.Melee4,
		animations.Yuta.Melee.Chase,
		animations.Yuta.Melee.Up,
		animations.Yuta.Melee.Down,
		animations.Yuta.SeveringSwing,
		animations.Yuta.Outburst,
		animations.Yuta.QuickdrawAerial,
		animations.Yuta.SecondWind,
		animations.Yuta.EnergyRipple,
		animations.Yuta.MeleeUlt.Melee1,
		animations.Yuta.MeleeUlt.Melee2,
		animations.Yuta.MeleeUlt.Melee3,
		animations.Yuta.MeleeUlt.Melee4,
		animations.Yuta.Ultimate2,
		animations.Yuta.SeveringPathSwordAir,
		animations.Yuta.LaunchGround,
		animations.Yuta.LaunchGroundMelee,
		animations.Yuta.RunPierce
	},
	{
		animations.Charles.Despair,
		animations.Charles.EyeCatch,
		animations.Charles.ShutUp,
		animations.Charles.ShutUpVictim,
		animations.Charles.Sacrilegious,
		animations.Charles.SacrilegiousHit,
		animations.Charles.Ultimate,
		animations.Charles.UltimateHit,
		animations.Charles.UltimateAfter,
		animations.Charles.Mark,
		animations.Charles.Melee.Melee1,
		animations.Charles.Melee.Melee2,
		animations.Charles.Melee.Melee3,
		animations.Charles.Melee.Melee4,
		animations.Charles.Melee.Up
	},
	{
		animations.Mechamaru.BoostOnStart,
		animations.Mechamaru.BoostOnEnd,
		animations.Mechamaru.BoostOnTarget,
		animations.Mechamaru.UltraSpin,
		animations.Mechamaru.UltraSpinHit,
		animations.Mechamaru.UltraCannon,
		animations.Mechamaru.PuppetBarrage.User,
		animations.Mechamaru.PuppetBarrage.Grab,
		animations.Mechamaru.PuppetBarrage.Kick,
		animations.Mechamaru.Offloads.FunnyFall,
		animations.Mechamaru.Offloads.SmoothLanding1,
		animations.Mechamaru.Offloads.SmoothLanding2,
		animations.Mechamaru.Offloads.BackSlide,
		animations.Mechamaru.Offloads.SupermanLanding,
		animations.Mechamaru.Offloads.ArmsFlyIn,
		animations.Mechamaru.BoostOn,
		animations.Mechamaru.BoostOnHit,
		animations.Mechamaru.HeatEmission,
		animations.Mechamaru.MiracleCannon,
		animations.Mechamaru.PigeonViola,
		animations.Mechamaru.AbsoluteDestructionOLD,
		animations.Mechamaru.Absolute.GunShot,
		animations.Mechamaru.Absolute.Kick,
		animations.Mechamaru.Absolute.JumpCrouch,
		animations.Mechamaru.Absolute.Stagger,
		animations.Mechamaru.Absolute.Spawn,
		animations.Mechamaru.Absolute.UltEnd,
		animations.Mechamaru.Melee.Melee1,
		animations.Mechamaru.Melee.Melee2,
		animations.Mechamaru.Melee.Melee3,
		animations.Mechamaru.Melee.Melee4,
		animations.Mechamaru.Absolute.Melee.Melee1,
		animations.Mechamaru.Absolute.Melee.Melee2,
		animations.Mechamaru.Absolute.Melee.Melee3,
		animations.Mechamaru.Absolute.Melee.Melee4,
		animations.Mechamaru.Absolute.Melee.Up,
		animations.Mechamaru.AbsoluteDestruction,
		animations.Mechamaru.AbsoluteDestructionAir
	},
	{
		animations.Naoya.Bleedout,
		animations.Naoya.BleedoutHit,
		animations.Naoya.CursoryImpact,
		animations.Naoya.DecisiveStrike,
		animations.Naoya.DecisiveStrikeHit,
		animations.Naoya.Flicker,
		animations.Naoya.ProjectionBreaker,
		animations.Naoya.Ultimate,
		animations.Naoya.UltimateHit,
		animations.Naoya.TopSpeed,
		animations.Naoya.FlashFreezing,
		animations.Naoya.TendrilGrab,
		animations.Naoya.MoonPalace,
		animations.Naoya.Acceleration,
		animations.Naoya.Melee.Melee1,
		animations.Naoya.Melee.Melee2,
		animations.Naoya.Melee.Melee3,
		animations.Naoya.Melee.Melee4,
		animations.Naoya.Melee2.Melee1,
		animations.Naoya.Melee2.Melee2,
		animations.Naoya.Melee2.Melee3,
		animations.Naoya.Melee2.Melee4
	},
	{
		animations.Nanami.CleavingWhirlwind,
		animations.Nanami.SeveranceKick,
		animations.Nanami.BluntCut,
		animations.Nanami.Stabilize,
		animations.Nanami.StabilizeTarget,
		animations.Nanami.StabilizeTargetShort,
		animations.Nanami.RatioBreaker.RatioBreak1,
		animations.Nanami.RatioBreaker.RatioBreak2,
		animations.Nanami.RatioBreaker.RatioBreak3,
		animations.Nanami.RatioBreaker.RatioBreak4,
		animations.Nanami.RatioBreakStun,
		animations.Nanami.Ultimate,
		animations.Nanami.Melee.Melee1,
		animations.Nanami.Melee.Melee2,
		animations.Nanami.Melee.Melee3,
		animations.Nanami.Melee.Melee4,
		animations.Nanami.Melee.Up,
		animations.Nanami.Melee.Down,
		animations.Nanami.MeleeUlt.Melee1,
		animations.Nanami.MeleeUlt.Melee2,
		animations.Nanami.MeleeUlt.Melee3,
		animations.Nanami.MeleeUlt.Melee4,
		animations.Nanami.Sharpen,
		animations.Nanami.Interrogate,
		animations.Nanami.InterrogateHit,
		animations.Nanami.InterrogateFinalHit,
		animations.Nanami.Collapse
	},
	{
		animations.Goku.Kamehameha,
		animations.Goku.KiSpam,
		animations.Goku.StaffExtend,
		animations.Goku.StaffUppercut,
		animations.Goku.Ultimate,
		animations.Goku.Melee.Melee1,
		animations.Goku.Melee.Melee2,
		animations.Goku.Melee.Melee3,
		animations.Goku.Melee.Melee4
	},
	{
		animations.Haruta.Ambush,
		animations.Haruta.Stinger,
		animations.Haruta.Backstab,
		animations.Haruta.BackstabTargetBack,
		animations.Haruta.BackstabTargetFront,
		animations.Haruta.Trip,
		animations.Haruta.CheapShot,
		animations.Haruta.DirtyPlay,
		animations.Haruta.Hand.JawbreakerHit,
		animations.Haruta.Hand.JawbreakerVictim,
		animations.Haruta.Melee.Melee1,
		animations.Haruta.Melee.Melee2,
		animations.Haruta.Melee.Melee3,
		animations.Haruta.Melee.Melee4,
		animations.Haruta.Melee.Melee4Victim,
		animations.Haruta.Melee.MeleeChase,
		animations.Haruta.Melee.SwordChase,
		animations.Haruta.Melee.Up,
		animations.Haruta.Melee.Down,
		animations.Haruta.Taunt1,
		animations.Haruta.Taunt2,
		animations.Haruta.Taunt3,
		animations.Haruta.Taunt4
	},
	{
		animations.MeiMei.BirdCall,
		animations.MeiMei.BirdHold,
		animations.MeiMei.Bounding,
		animations.MeiMei.BoundingVictim,
		animations.MeiMei.Circling,
		animations.MeiMei.CirclingVictim,
		animations.MeiMei.CirclingVictimFinisher,
		animations.MeiMei.Flock,
		animations.MeiMei.GlidingFlight,
		animations.MeiMei.GlidingFlightVictim,
		animations.MeiMei.ImpetusUpdraft,
		animations.MeiMei.Melee.Melee1,
		animations.MeiMei.Melee.Melee2,
		animations.MeiMei.Melee.Melee3,
		animations.MeiMei.Melee.Melee4,
		animations.MeiMei.Melee.Up,
		animations.MeiMei.Melee.Down,
		animations.MeiMei.Melee.Chase,
		animations.MeiMei.ImpetusNew,
		animations.MeiMei.Murmurate,
		animations.MeiMei.Teleport,
		animations.MeiMei.Ultimate
	},
	{
		animations.Hanami.BudShot,
		animations.Hanami.DefenseResponse,
		animations.Hanami.FlowerField,
		animations.Hanami.RootSwarm,
		animations.Hanami.SurgingThorns,
		animations.Hanami.Melee.Melee1,
		animations.Hanami.Melee.Melee2,
		animations.Hanami.Melee.Melee3,
		animations.Hanami.Melee.Melee4,
		animations.Hanami.Melee.Chase,
		animations.Hanami.MeleeUlt.Melee1,
		animations.Hanami.MeleeUlt.Melee2,
		animations.Hanami.MeleeUlt.Melee3,
		animations.Hanami.MeleeUlt.Melee4,
		animations.Hanami.Empower,
		animations.Hanami.Ultimate,
		animations.Hanami.Domain,
		animations.Hanami.CursedBuds,
		animations.Hanami.Beam
	},
	{
		animations.Ryu.Appetizer,
		animations.Ryu.GraniteBlast,
		animations.Ryu.HadNoIdea,
		animations.Ryu.HadNoIdeaHit,
		animations.Ryu.Recovery,
		animations.Ryu.Recovery2,
		animations.Ryu.SecondHelping,
		animations.Ryu.ThisDessert,
		animations.Ryu.ThisDessertHit,
		animations.Ryu.Ultimate,
		animations.Ryu.Unsatisfied,
		animations.Ryu.WhatAreYouAfter,
		animations.Ryu.WhatAreYouAfterHit,
		animations.Ryu.Melee.Chase,
		animations.Ryu.Melee.Melee3_2,
		animations.Ryu.WerentInvited,
		animations.Ryu.Recovery3
	},
	{
		animations.Kurourushi.FesteringStrikes,
		animations.Kurourushi.Detach,
		animations.Kurourushi.Reattach,
		animations.Kurourushi.ChokeholdHit,
		animations.Kurourushi.ChokeholdVictim,
		animations.Kurourushi.EarthenTrance,
		animations.Kurourushi.RoachSwarm,
		animations.Kurourushi.Melee.Melee1,
		animations.Kurourushi.Melee.Melee2,
		animations.Kurourushi.Melee.Melee3,
		animations.Kurourushi.Melee.Melee4,
		animations.Kurourushi.MeleeDetach.Melee1,
		animations.Kurourushi.MeleeDetach.Melee2,
		animations.Kurourushi.MeleeDetach.Melee3,
		animations.Kurourushi.MeleeDetach.Melee4,
		animations.Kurourushi.Parthenogenesis,
		animations.Kurourushi.Eat,
		animations.Kurourushi.EatVictim,
		animations.Kurourushi.Melee.Down
	},
	{
		animations.Reggie.GushingWound,
		animations.Reggie.Homerun,
		animations.Reggie.Littering,
		animations.Reggie.Coupon,
		animations.Reggie.PianoDrop,
		animations.Reggie.GarageSale,
		animations.Reggie.BluntTrauma,
		animations.Reggie.BluntTraumaHit,
		animations.Reggie.Discard,
		animations.Reggie.Melee.Melee1,
		animations.Reggie.Melee.Melee2,
		animations.Reggie.Melee.Melee3,
		animations.Reggie.Melee.Melee4,
		animations.Reggie.Drone.DroneStrikeStart,
		animations.Reggie.PoleVault,
		animations.Reggie.Fleche,
		animations.Reggie.SpeedCrash,
		animations.Reggie.SpeedCrashHit
	},
	{
		animations.Uro.Melee.Melee1,
		animations.Uro.Melee.Melee2,
		animations.Uro.Melee.Melee3,
		animations.Uro.Melee.Melee4,
		animations.Uro.BlindRage,
		animations.Uro.BlindRageHit,
		animations.Uro.ThinIceBreaker,
		animations.Uro.ThinIceBreaker2,
		animations.Uro.SkyDistortion,
		animations.Uro.Ultimate,
		animations.Uro.Melee.Chase
	}
}
return ListData