local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local TestLibrary = require(ReplicatedStorage:WaitForChild("Modules"):WaitForChild("TestLibrary"))
local v = {
	"PRIVATE_SERVER_ID",
	"PRIVATE_SERVER_OWNER_ID",
	"IS_PUBLIC_SERVER",
	"IS_RESERVED_SERVER",
	"IS_PRIVATE_SERVER",
	"IS_PRIVATE_HUB_SERVER"
}
local requestConstants = ReplicatedStorage:WaitForChild("Remotes"):WaitForChild("Misc"):WaitForChild("RequestConstants")
local testAttribute = TestLibrary:GetTestAttribute("StudioIsPrivateServerOwner")
local testAttribute2 = TestLibrary:GetTestAttribute("StudioIsPrivateServer")
local testAttribute3 = TestLibrary:GetTestAttribute("StudioPlaceID")
local CONSTANTS = {
	GAME_VERSION = 30,
	MAIN_HUB_PLACE_ID = 17625359962,
	MAIN_MOBILE_PLACE_ID = 18126510175,
	MAIN_MATCHMAKING_PLACE_ID = 117398147513099,
	MAIN_ARCADE_TEAMDEATHMATCH_PLACE_ID = 71874690745115,
	MAIN_ARCADE_FREEFORALL_PLACE_ID = 129604661913557,
	MAIN_ARCADE_GUNGAME_PLACE_ID = 133215910299950,
	TESTING_HUB_PLACE_ID = 12011504191,
	TESTING_MOBILE_PLACE_ID = 18126498684,
	TESTING_MATCHMAKING_PLACE_ID = 136907445582634,
	TESTING_ARCADE_TEAMDEATHMATCH_PLACE_ID = 139242311442282,
	TESTING_ARCADE_FREEFORALL_PLACE_ID = 83743252354420,
	TESTING_ARCADE_GUNGAME_PLACE_ID = 90728399170029,
	IS_RUNNING = RunService:IsRunning(),
	IS_STUDIO = RunService:IsStudio(),
	IS_SERVER = RunService:IsServer(),
	IS_CLIENT = RunService:IsClient(),
	DEVICE = "Server"
}

if not (CONSTANTS.IS_STUDIO and testAttribute3 > 0) then
	testAttribute3 = game.PlaceId
end

CONSTANTS.PLACE_ID = testAttribute3
CONSTANTS.JOB_ID = game.JobId
CONSTANTS.PRIVATE_SERVER_ID = CONSTANTS.IS_SERVER and game.PrivateServerId
CONSTANTS.PRIVATE_SERVER_OWNER_ID = CONSTANTS.IS_SERVER and game.PrivateServerOwnerId
CONSTANTS.IS_MAIN_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.MAIN_HUB_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MAIN_MOBILE_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MAIN_MATCHMAKING_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MAIN_ARCADE_TEAMDEATHMATCH_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MAIN_ARCADE_FREEFORALL_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MAIN_ARCADE_GUNGAME_PLACE_ID
CONSTANTS.IS_TESTING_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.TESTING_HUB_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.TESTING_MOBILE_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.TESTING_MATCHMAKING_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.TESTING_ARCADE_TEAMDEATHMATCH_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.TESTING_ARCADE_FREEFORALL_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.TESTING_ARCADE_GUNGAME_PLACE_ID
CONSTANTS.HUB_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_HUB_PLACE_ID or CONSTANTS.TESTING_HUB_PLACE_ID
CONSTANTS.MOBILE_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_MOBILE_PLACE_ID or CONSTANTS.TESTING_MOBILE_PLACE_ID
CONSTANTS.MATCHMAKING_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_MATCHMAKING_PLACE_ID or CONSTANTS.TESTING_MATCHMAKING_PLACE_ID
CONSTANTS.ARCADE_TEAMDEATHMATCH_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_ARCADE_TEAMDEATHMATCH_PLACE_ID or CONSTANTS.TESTING_ARCADE_TEAMDEATHMATCH_PLACE_ID
CONSTANTS.ARCADE_FREEFORALL_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_ARCADE_FREEFORALL_PLACE_ID or CONSTANTS.TESTING_ARCADE_FREEFORALL_PLACE_ID
CONSTANTS.ARCADE_GUNGAME_PLACE_ID = CONSTANTS.IS_MAIN_SERVER and CONSTANTS.MAIN_ARCADE_GUNGAME_PLACE_ID or CONSTANTS.TESTING_ARCADE_GUNGAME_PLACE_ID
local v2

if CONSTANTS.IS_STUDIO then
	v2 = not testAttribute2
else
	v2 = CONSTANTS.IS_SERVER and CONSTANTS.PRIVATE_SERVER_ID == ""
end

CONSTANTS.IS_PUBLIC_SERVER = v2
local v3

if CONSTANTS.IS_STUDIO then
	v3 = testAttribute2
else
	v3 = CONSTANTS.IS_SERVER and not CONSTANTS.IS_PUBLIC_SERVER and CONSTANTS.PRIVATE_SERVER_OWNER_ID == 0
end

CONSTANTS.IS_RESERVED_SERVER = v3

if not CONSTANTS.IS_STUDIO then
	testAttribute2 = CONSTANTS.IS_SERVER and not CONSTANTS.IS_PUBLIC_SERVER and CONSTANTS.PRIVATE_SERVER_OWNER_ID ~= 0
end

CONSTANTS.IS_PRIVATE_SERVER = testAttribute2
CONSTANTS.IS_HUB_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.HUB_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.MOBILE_PLACE_ID
CONSTANTS.IS_MOBILE_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.MOBILE_PLACE_ID
CONSTANTS.IS_ARCADE_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.ARCADE_TEAMDEATHMATCH_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.ARCADE_FREEFORALL_PLACE_ID or CONSTANTS.PLACE_ID == CONSTANTS.ARCADE_GUNGAME_PLACE_ID
CONSTANTS.IS_MATCHMAKING_SERVER = CONSTANTS.PLACE_ID == CONSTANTS.MATCHMAKING_PLACE_ID
CONSTANTS.IS_PRIVATE_HUB_SERVER = CONSTANTS.IS_HUB_SERVER and CONSTANTS.IS_PRIVATE_SERVER
CONSTANTS.GROUP_ID = 3461453
CONSTANTS.TEAM_GROUP_ROLE_ID = 816494002

function CONSTANTS.IS_PRIVATE_SERVER_OWNER(p)
	return testAttribute or CONSTANTS.IS_TESTING_SERVER and not CONSTANTS.IS_STUDIO or CONSTANTS.IS_PRIVATE_HUB_SERVER and (CONSTANTS.IS_STUDIO or CONSTANTS.PRIVATE_SERVER_OWNER_ID == p)
end

function CONSTANTS.SHOULD_ALWAYS_REPLICATE(_)
	return CONSTANTS.IS_ARCADE_SERVER or CONSTANTS.IS_MATCHMAKING_SERVER
end

CONSTANTS.DEFAULT_WEAPONS = {
	"Assault Rifle",
	"Handgun",
	"Fists",
	"Grenade"
}
CONSTANTS.DEFAULT_MAPS = {
	"Arena",
	"Backrooms",
	"Construction",
	"Docks"
}
CONSTANTS.QUEUES_ACTIVE = CONSTANTS.IS_HUB_SERVER
CONSTANTS.SHOOTING_RANGE_ACTIVE = CONSTANTS.IS_HUB_SERVER or CONSTANTS.IS_MATCHMAKING_SERVER
CONSTANTS.BASE_HEALTH = 150
CONSTANTS.BASE_WALKSPEED = 16
CONSTANTS.BASE_JUMPPOWER = 20
CONSTANTS.BASE_GRAVITY = 0.25
CONSTANTS.BASE_MASS = 14.381
CONSTANTS.SELF_DAMAGE_MULTIPLIER = 0
CONSTANTS.MAX_RAYCAST_DISTANCE = 400
CONSTANTS.RENDER_DISTANCE = 500
CONSTANTS.MAX_PARTY_SIZE = 5
CONSTANTS.BEGINNER_QUEUE_NAME = "2v2_beginner"
CONSTANTS.BEGINNER_QUEUE_WINS = 10
CONSTANTS.WEAPON_REVEAL_TIME_OFFSET = 604800
CONSTANTS.WEAPON_EARLY_ACCESS_TIME_OFFSET = 86400
CONSTANTS.HEADSHOT_IMAGE = "https://www.roblox.com/headshot-thumbnail/image?userId=%s&width=420&height=420&format=png"
CONSTANTS.CONTROLS_IMAGES = {
	MouseKeyboard = "rbxassetid://17136633356",
	Touch = "rbxassetid://17136633510",
	Gamepad = "rbxassetid://17136633629",
	VR = "rbxassetid://17136765745"
}
CONSTANTS.CONTROLS_IMAGES_CENTERED = {
	MouseKeyboard = "rbxassetid://88012714630436",
	Touch = "rbxassetid://113510944677126",
	Gamepad = "rbxassetid://110291144710849",
	VR = "rbxassetid://99115398611290"
}
CONSTANTS.AIRBORNE_HUMANOID_STATES = {
	[Enum.HumanoidStateType.FallingDown] = true,
	[Enum.HumanoidStateType.Jumping] = true,
	[Enum.HumanoidStateType.Freefall] = true,
	[Enum.HumanoidStateType.Flying] = true,
	[Enum.HumanoidStateType.Jumping] = true,
	[Enum.HumanoidStateType.PlatformStanding] = true
}
CONSTANTS.DUEL_HISTORY_MAX_SIZE = 20
CONSTANTS.MAX_BACKPACK_USE_QUANTITY = 100
CONSTANTS.MAX_EQUIPPABLE_WEAPONS = 4
CONSTANTS.MAX_EQUIPPABLE_EMOTES = 8
CONSTANTS.COSMETIC_IMAGES = {
	NONE_COSMETIC = "rbxassetid://17562770037",
	RANDOM_COSMETIC = "rbxassetid://94238795177693"
}
CONSTANTS.MAX_DUEL_PAD_WINS_PER_DAY_BEFORE_BEING_BLOCKED = 25
CONSTANTS.DEFAULT_HEAD_ASSET_ID = 2432102561
CONSTANTS.LEVEL_REQUIRED_FOR_REWARDS_FROM_ARCADE_SERVERS = 100
CONSTANTS.MAX_STREAK_GAIN_FROM_DUEL_PADS = 50

function CONSTANTS.INIT()
	if CONSTANTS.IS_SERVER then
		local result = {}

		for _, v5 in pairs(v) do
			result[v5] = CONSTANTS[v5]
		end

		requestConstants.OnServerInvoke = function()
			return result
		end
	else
		if not CONSTANTS.IS_CLIENT then
			return
		end

		local result

		while true do
			local success
			success, result = pcall(requestConstants.InvokeServer, requestConstants)

			if success then
				break
			end

			warn("Constants failed to fetch, error:", result)
			wait(1)
		end

		for k, v5 in pairs(result) do
			CONSTANTS[k] = v5
		end
	end
end

return CONSTANTS