local ReplicatedStorage = game:GetService("ReplicatedStorage")
local StatisticsLibrary = require(ReplicatedStorage.Modules.StatisticsLibrary)
local CosmeticLibrary = require(ReplicatedStorage.Modules.CosmeticLibrary)
local DuelLibrary = require(ReplicatedStorage.Modules.DuelLibrary)
local ItemLibrary = require(ReplicatedStorage.Modules.ItemLibrary)
local EnumLibrary = require(ReplicatedStorage.Modules.EnumLibrary)
local Utility = require(ReplicatedStorage.Modules.Utility)
local v = {
	"ReplicationAdded",
	"ReplicationChanged",
	"ReplicationRemoved",
	"ReplicationRequest",
	"Ammo",
	"BulkDataValueChanged",
	"DataValueChanged",
	"ItemChanged",
	"EntityChanged",
	"ItemRemoved",
	"ItemAdded",
	"EntityAdded",
	"SafeUpdateLocalEquippedItemID",
	"UserID",
	"ShootEffect",
	"ProjectileEffect",
	"ServerInputWorkDone",
	"Died",
	"BurnEffect",
	"ExplosionEffect",
	"MolotovExplode",
	"HealEffect",
	"HurtEffect",
	"Skin",
	"DeflectHit",
	"PlayAnimation",
	"StartShooting",
	"StartReloading",
	"StartAiming",
	"StartInspecting",
	"EliminationFeed",
	"StartSprinting",
	"FinishShooting",
	"FinishReloading",
	"FinishAiming",
	"FinishInspecting",
	"FinishSprinting",
	"HitEffect",
	"SwitchItemsCount",
	"SwitchItemsMax",
	"EliminationEffect",
	"ViewModelChanged",
	"DuelerAdded",
	"DuelerChanged",
	"DuelerRemoved",
	"CameraMimicRotation",
	"RoundStart",
	"RoundFinish",
	"BatchUpdateWeaponXP",
	"CameraLean",
	"IsCrouching",
	"IsSprinting",
	"IsSliding",
	"ExtinguishEffect",
	"SplatEffect",
	"IsAirborne",
	"PlayMechanicsSound",
	"Slide",
	"DoubleJump",
	"BlindedEffect",
	"BackstabEffect",
	"EliminatedEffect",
	"RoundStarting",
	"MouseKeyboard",
	"Gamepad",
	"Touch",
	"VR",
	"HardenEffect",
	"NumReloadsSoFar",
	"ThrowEffect",
	"MineExplosion",
	"MapAdded",
	"KnockbackEffect",
	"CanTrackStatistics",
	"PlaySourceName",
	"ClientFighterCharacter",
	"ClientBaseGame",
	"ClientDuel",
	"ClientDueler",
	"ClientDestructable",
	"LogID",
	"ClientEnemy",
	"ClientEntity",
	"ClientFighter",
	"ClientPlayerData",
	"CameraRotation",
	"DecodedNetworkID",
	"IsSpectating",
	"LocalEquippedItemID",
	"IsInDuel",
	"FOVOffset",
	"ItemIndex",
	"Controls",
	"NetworkID",
	"EnvironmentID",
	"TeamID",
	"TeamkillEnabled",
	"ItemsLocked",
	"CanPickWeapons",
	"LastPickedWeapons",
	"EquippedItemID",
	"OctoCount",
	"InfiniteAmmo",
	"Name",
	"Scale",
	"ShowWhileAiming",
	"ClearQuickAttackState",
	"Level",
	"QuickAttackQueued",
	"SkipEquipAnimation",
	"Charm",
	"AmmoReserve",
	"IdleAnimation",
	"ThawFreezeEffect",
	"RunAnimation",
	"Damage",
	"DamageTaken",
	"Status",
	"ClientCustomEntity",
	"StatisticsBatchUpdate",
	"ShowWhileInspecting",
	"Timer",
	"Wave",
	"EnemyCount",
	"EnemiesByID",
	"MapName",
	"MapFolder",
	"VoteOptions",
	"Scores",
	"NumTeams",
	"LastVote",
	"AssistEffect",
	"PingEffect",
	"Eliminations",
	"Deaths",
	"Assists",
	"MatchPoint",
	"SuddenDeath",
	"ClientHumanoidEntity",
	"NumSpectators",
	"CanSwitchItems",
	"RoundNum",
	"IsInShootingRange",
	"RegisterDPS",
	"IsDisabled",
	"IsStatic",
	"BarsDisabled",
	"BarsSpacing",
	"BarsLength",
	"BarsThickness",
	"BarsTransparency",
	"DotDisabled",
	"DotThickness",
	"DotTransparency",
	"OutlineDisabled",
	"OutlineThickness",
	"OutlineTransparency",
	"DotColor",
	"BarsColor",
	"OutlineColor",
	"Rotation",
	"Override",
	"CompressedCrosshairAppearance",
	"OutlineType",
	"CircleDisabled",
	"CircleColor",
	"CircleSize",
	"CircleThickness",
	"CircleTransparency",
	"CircleShape",
	"WarpTo",
	"OnyxLavaSplash",
	"MapChanged",
	"CreateSound",
	"SendChat",
	"Shutdown",
	"BarsTopDisabled",
	"BarsBottomDisabled",
	"BarsRightDisabled",
	"BarsLeftDisabled",
	"WeaponDataChanged",
	"ConnectionLevel",
	"NukeEffect",
	"SpectatingDuelObjectID",
	"ClientReplicatedClassType",
	"Data",
	"ViewModel",
	"Player",
	"Model",
	"RootPart",
	"Humanoid",
	"Duelers",
	"Map",
	"ObjectID",
	"Items",
	"Entity",
	"Wrap",
	"EntityRemoved",
	"FinalResults",
	"LootboxEffect",
	"DEBUG_OCTO_MODE",
	"ChallengeRequest",
	"ClientDPSDummy",
	"DotShape",
	"BarsShape",
	"DamageNumberEffect",
	"FreezeEffect",
	"ScoresBehavior",
	"DuelerID",
	"IsFrozen",
	"IsMatchmaking",
	"PartyRequest",
	"MatchmadeCountdown",
	"FinisherEffect",
	"IsInvincible",
	"ArcadeMode",
	"CancelUse",
	"RematchAvailable",
	"RematchCount",
	"RematchGoal",
	"ConsecutiveRematches",
	"QueueName",
	"SetBoost",
	"NumSatchels",
	"SatchelAttached",
	"AbsorbedHit",
	"TransformProjectile",
	"MiniExplosionEffect",
	"ExtinguishEffect",
	"Countdown",
	"Mode",
	"BlindEffect",
	"WeaponPool",
	"WeaponPoolFilterType",
	"CanUseLockedWeapons",
	"IsCurrentArcadeDuel",
	"RematchSuccess",
	"IsGrabbingSnowball",
	"ThrowSnowball",
	"StopHolding",
	"StopUsing",
	"WasSelfQueued",
	"PauseTimer",
	"DuelResultsRunnerUpsEnabled",
	"MaxMapBansPerTeam",
	"VoteBansRemaining",
	"NoRandomMap",
	"MaxMapOptions",
	"MaxWeaponBansPerTeam",
	"VoteOptionsType",
	"AutoShootRestriction",
	"AimAssistRestriction",
	"ThirdPersonOverride",
	"ChosenMapEffect",
	"SetCooldown",
	"SummaryDetails",
	"ExternalDuelTimer",
	"ExternalDuelWinningScore",
	"ExternalKeepDuelGoing",
	"ExternalDrawsAreLosses",
	"PlayPreloadedAnimation",
	"TracerEffect",
	"FlashbangEffect",
	"Interrupted",
	"CheaterMode",
	"IsAprilFools",
	"AprilFoolsCharkAttack",
	"BladeCriticalHit",
	"WeaponClassRestrictionDisabled",
	"KeepDuelAliveTimeout",
	"DontDisableRematchingOnLeave",
	"VoteSelectionMode",
	"ScoreNeededToWin",
	"ClientQueuePad",
	"PlayersWaiting",
	"IsLocked",
	"IsStarting",
	"InfinitePlayersPerTeam",
	"PlayersPerTeam",
	"NumTeams",
	"CanSelfQueue",
	"RefillAmmoEffect",
	"CollectEffect",
	"RespawnDelay",
	"JustSwitchedTeam",
	"SetupDrop",
	"OverrideQuickAttacks",
	"RespawnNowAnimation",
	"UnlimitedTime",
	"ExternalCanPlayAllMaps",
	"BaseHealth",
	"Gravity",
	"DisableSprinting",
	"DisableSliding",
	"DashOnAim",
	"StaggeredSpawns",
	"StaggeredSpawnsOrder",
	"ExternalEndDuelNow",
	"ChickenGamesRedLight",
	"ChickenGamesGreenLight",
	"ChickenGamesElimination",
	"ChickenGamesStop",
	"EventEndTime",
	"SpecialChallengesEnabled",
	"RollResult",
	"IsHeadHoncho",
	"InvincibilityDurationOnSpawn",
	"ExternalDisableTimerAliveCheck",
	"IsTranslucent",
	"ClaimCheckpoint",
	"ObbyStartPosition",
	"ObbyFinishPosition",
	"TimerStopwatchStarted",
	"TimerStopwatchFinished",
	"FreeToUseStandardWeapons",
	"FreeToUsePrimeWeapons",
	"EmotePlayed",
	"EmoteStopped",
	"ExternalRematchProperties",
	"IsGunGame",
	"DisableAnticheatPositionVerificationLoop",
	"BlipEffect",
	"Warp",
	"MatchPointVisualDisabled",
	"InfiniteAmmoReserve",
	"ClientHelmetZombie",
	"DinkEffect",
	"DropFlagEffect",
	"ClientFlagZombie",
	"ZombieExplosionEffect",
	"ClientExplosiveZombie",
	"HideMostDuelInterfaceElements",
	"DisableDoubleJumping",
	"SprintingSpeedBoost",
	"SlidingSpeedMax",
	"EmpowerOtherEntityEffect",
	"ExternalMaxEquippableWeapons",
	"DuelSeed",
	"ChickenTrojanEffect",
	"GiantChombieCutscene",
	"FinishGiantChombieCutscene",
	"ExternalIsHidden",
	"BackToNormal",
	"ClientGiantChombie",
	"SlamEffect",
	"HunterLeapEffect",
	"ClientHunterZombie",
	"CameraFlashlightEnabled",
	"ZombieSpawn",
	"JoinCooldown",
	"SeasonEndTime",
	"SettingChanged",
	"HitmarkerDisabled",
	"HitmarkerColor",
	"HitmarkerColorCrit",
	"ResetReloadState",
	"ReplicatedExternalGameplayData",
	"SlamAttack",
	"FreeToUseContrabandWeapons",
	"CancelSlam",
	"ScopedRedDotDisabled",
	"HitmarkerTransparencyCrit",
	"HitmarkerScale",
	"HitmarkerRotation",
	"HitmarkerTransparency",
	"SpectateThisPlayer",
	"MapPool",
	"OriginalQueueName",
	"ExternalMapPoolPlaySourceName",
	"ClientSpleefTile",
	"SpleefTileShake",
	"ImmuneDamageEffect",
	"ClientRubble",
	"DisableOOB",
	"ExternalDisableOOB",
	"AddReceipt",
	"GrapplerPull",
	"ClientSatchelEntity",
	"ScopedDisabled",
	"ScopedBarsDisabled",
	"ScopedRedDotColor",
	"Throw",
	"ThrowFinal",
	"GrapplerMiss",
	"GrapplerTrackPart",
	"GrapplerCooldown",
	"CancelKnockbackEffect",
	"PaintballSplatter",
	"FreeWeaponTrials",
	"QuickAttackSystemOnReEquip",
	"SlowEffect",
	"Seed",
	"MapPoolGamemode",
	"MapPoolSpecific",
	"ExternalMapPoolSpecificMap"
}
local v2 = {
	"DuelerAdded",
	"EntityAdded",
	"MapAdded",
	"ItemRemoved",
	"DuelerRemoved",
	"DataValueChanged",
	"SafeUpdateLocalEquippedItemID",
	"Died"
}

-- equivalent calls inferred from this helper; original call sites unknown
local function add_dump()
	for _, v3 in pairs(v) do
		EnumLibrary:AddEnum(v3)
	end
end

local function add_viewmodels()
	for _, v3 in pairs(ItemLibrary.ViewModelOrder) do
		EnumLibrary:AddEnum(v3)
	end

	for _, viewModel in pairs(ItemLibrary.ViewModels) do
		local v3 = {}

		for k in pairs(viewModel.Animations) do
			table.insert(v3, k)
		end

		table.sort(v3, function(a, b)
			return Utility:StringLessThan(a, b)
		end)

		for _, v4 in pairs(v3) do
			EnumLibrary:AddEnum(v4)
			EnumLibrary:AddEnum(viewModel.Animations[v4])
		end
	end
end

-- equivalent calls inferred from this helper; original call sites unknown
local function add_statistics()
	for _, v3 in pairs(StatisticsLibrary.Order) do
		EnumLibrary:AddEnum(v3)
	end
end

local function add_cosmetics()
	local v3 = {}

	for k, cosmetic in pairs(CosmeticLibrary.Cosmetics) do
		if cosmetic.Type == "Finisher" then
			table.insert(v3, k)
		end
	end

	table.sort(v3, function(a, b)
		return Utility:StringLessThan(a, b)
	end)

	for _, v4 in pairs(v3) do
		EnumLibrary:AddEnum(v4)
	end
end

-- equivalent calls inferred from this helper; original call sites unknown
local function add_maps()
	for _, v3 in pairs(DuelLibrary.HiddenMapOrder) do
		EnumLibrary:AddEnum(v3)
	end
end

local function finish()
	for _, v3 in pairs(v2) do
		EnumLibrary.AlwaysReplicateToEveryone[v3] = true
		EnumLibrary.AlwaysReplicateToEveryone[EnumLibrary:ToEnum(v3)] = true
	end

	EnumLibrary:EnumBuilderCompleted()
end

add_dump() -- equivalent call inferred; original call site unknown
add_viewmodels()
add_statistics() -- equivalent call inferred; original call site unknown
add_cosmetics()
add_maps() -- equivalent call inferred; original call site unknown
finish()
return {}