local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local CONSTANTS = require(ReplicatedStorage.Modules.CONSTANTS)
local v = {
	"Check out Treasure Quest!",
	"Check out Super Golf!",
	"The game (RIVALS) was released on June 28, 2024",
	"The game (RIVALS) was originally going to be a PvE zombie game",
	"The group (Nosniy Games) has been making games since 2018",
	"Find all of the Jump Shards to craft the Jump Pad",
	"The bell in Graveyard can ring",
	"You can play secret maps in Private Servers",
	"You can use locked weapons in Private Servers",
	"There's something odd about the targets",
	"Spray can penetrate through Katanas & Riot Shields",
	"You can earn special rewards for eliminating developers & influencers",
	"00bandoboy wuz here",
	"Auto Shoot and Aim Assist are getting buffed tomorrow by ×100",
	"Arena is being deleted on February 30th",
	"Some weapons and skins have secret inspect animations",
	"You can earn free rewards by watching video ads in the Shop",
	"The red figure will find you",
	"The teams represent two rival companies; Nosniy Inc. + Sensei Global",
	"You can extinguish all sorts of fires using a Smoke Grenade",
	"Explosions allow you to fly across the map",
	"Quickly use your melee weapon's ability by pressing Quick Melee",
	"Quickly use your utility weapon's ability by pressing Quick Utility",
	"Some weapons, such as the Sniper & Shotgun, can pierce through enemies",
	"Redeem code \"BONUS\"",
	"Redeem code \"BOOST\"",
	"Redeem code \"ELBILLUG\" for a free Skin Case",
	"Sniper is not OP",
	"Cheating results in a permanent ban with no chance of appealing",
	"Abusing FFlags is the same as cheating and may result in permanent bans",
	"There be charks in these waters",
	"There are new gamemodes every day in the Play page",
	"Complete your tasks for free keys",
	"Complete weapon contracts for free keys & cosmetics",
	"Please vote for something other than Arena",
	"Find out how good you really are by playing Ranked",
	"The Patch Notes page contains all of the new content & balance changes",
	"You can change your crosshair & hotkeys in the Settings page",
	"Don't look at the flashbang",
	"Some weapons let you double jump",
	"Beware of spontaneous stick bug sightings",
	"Airborne Satchels don't deal much damage",
	"Climb the crane",
	"Switching to your secondary is faster than reloading",
	"Your choice of Melee could completely change how you play",
	"The Riot Shield can protect you from behind",
	"The majority vote doesn't always win when you're voting for a map",
	"Some splash-damage weapons deal more damage if you land a direct hit",
	"Arena was originally a test map and was made in 5 minutes",
	"Frozen enemies fall through the water in Splash",
	"Don't be a meanie",
	"Airblast downwards to launch yourself up with the Flamethrower",
	"The Knife's backstab eliminates in one hit",
	"Frozen enemies only receive half as much damage",
	"The Arcade Servers feature classic shooter gamemodes such as Team Deathmatch",
	"The default loadout is actually really good",
	"The cheapest weapon, Spray, only costs 5 keys",
	"Double dash with Gunblade and Scythe",
	"Something spooky happens during Match Point in Graveyard",
	"Satchels can stick onto Riot Shields",
	"Sniper hitboxes are much smaller than other weapons",
	"You can earn free cosmetics by winning duels & reaching streak milestones",
	"Earn bonus rewards by keeping up your Daily Task Streak",
	"The team with the highest total health wins the round if time runs out",
	"Your win streak is safe in most gamemodes",
	"Thanks for playing, " .. (CONSTANTS.IS_CLIENT and Players.LocalPlayer.Name or "Server") .. "!",
	"You can switch modes with Gunblade by breaking windows",
	"The traffic cones in Docks can be used to quickly reach the rooftops",
	"00nly my followers can play my secret gamemode in Private Servers",
	"Screenshots of your logs help us fix bugs — press [F9] or say \"/console\"",
	"Aiming with a projectile weapon makes the projectile spawn from the center of your screen",
	"Tap the icon in the Player List to see everyone's Win Streak, Level, or Rank",
	"If you ask for something from a developer, you won't be given anything",
	"You can inspect & aim your gun at the same time",
	"Downloading a cheat program can hack your computer",
	"Cheat programs are made by bad people that spy on your computer"
}
return function()
	return v[math.random(#v)]
end