return {
	MAX_DISTANCE = 75,
	MOUSE_RANGE = 500,
	ANIM_FREEZE_AT = 0.925,
	ENDLAG = 0.5,
	STARTUP_DUR = 0.36,
	DASH_HITBOX_WIDTH = 18,
	DASH_HITBOX_HEIGHT = 10,
	DASH_DAMAGE = 12.5,
	DASH_STUN = 3,
	DASH_BLOCK_BREAK = 2,
	DASH_VICTIM_IFRAME = 2,
	DASH_KNOCKUP = 0.25,
	DASH_KNOCKUP_DUR = 2,
	GRAB_DURATION = 2.25,
	LASTSLASH_AT = 0.65,
	FINAL_HIT_DELAY = 1,
	FINAL_DAMAGE = 12.5,
	FINAL_RAGDOLL = 1.5,
	FINAL_KNOCKBACK = 50,
	FINAL_KNOCKUP = 20,
	FINAL_KNOCKBACK_DUR = 0.3,
	PVP = {
		Base = 0.8
	}
}