return function()
	local parentModule = require(script.Parent)
	describe("Some", function()
		it("should create some option", function()
			local some = parentModule.Some(true)
			expect(some:IsSome()).to.equal(true)
		end)
		it("should fail to create some option with nil", function()
			expect(function()
				parentModule.Some(nil)
			end).to.throw()
		end)
		it("should not be none", function()
			local some = parentModule.Some(10)
			expect(some:IsNone()).to.equal(false)
		end)
	end)
	describe("None", function()
		it("should be able to reference none", function()
			expect(function()
				local _ = parentModule.None
			end).never.to.throw()
		end)
		it("should be able to check if none", function()
			local none = parentModule.None
			expect(none:IsNone()).to.equal(true)
		end)
		it("should be able to check if not some", function()
			local none = parentModule.None
			expect(none:IsSome()).to.equal(false)
		end)
	end)
	describe("Equality", function()
		it("should equal the same some from same options", function()
			local some = parentModule.Some(32)
			expect(some).to.equal(some)
		end)
		it("should equal the same some from different options", function()
			local some = parentModule.Some(32)
			local some2 = parentModule.Some(32)
			expect(some).to.equal(some2)
		end)
	end)
	describe("Assert", function()
		it("should assert that a some option is an option", function()
			expect(parentModule.Is(parentModule.Some(10))).to.equal(true)
		end)
		it("should assert that a none option is an option", function()
			expect(parentModule.Is(parentModule.None)).to.equal(true)
		end)
		it("should assert that a non-option is not an option", function()
			expect(parentModule.Is(10)).to.equal(false)
			expect(parentModule.Is(true)).to.equal(false)
			expect(parentModule.Is(false)).to.equal(false)
			expect(parentModule.Is("Test")).to.equal(false)
			expect(parentModule.Is({})).to.equal(false)
			expect(parentModule.Is(function() end)).to.equal(false)
			expect(parentModule.Is(coroutine.create(function() end))).to.equal(false)
			expect(parentModule.Is(parentModule)).to.equal(false)
		end)
	end)
	describe("Unwrap", function()
		it("should unwrap a some option", function()
			local some = parentModule.Some(10)
			expect(function()
				some:Unwrap()
			end).never.to.throw()
			expect(some:Unwrap()).to.equal(10)
		end)
		it("should fail to unwrap a none option", function()
			local none = parentModule.None
			expect(function()
				none:Unwrap()
			end).to.throw()
		end)
	end)
	describe("Expect", function()
		it("should expect a some option", function()
			local some = parentModule.Some(10)
			expect(function()
				some:Expect("Expecting some value")
			end).never.to.throw()
			expect(some:Unwrap()).to.equal(10)
		end)
		it("should fail when expecting on a none option", function()
			local none = parentModule.None
			expect(function()
				none:Expect("Expecting some value")
			end).to.throw()
		end)
	end)
	describe("ExpectNone", function()
		it("should fail to expect a none option", function()
			local some = parentModule.Some(10)
			expect(function()
				some:ExpectNone("Expecting some value")
			end).to.throw()
		end)
		it("should expect a none option", function()
			local none = parentModule.None
			expect(function()
				none:ExpectNone("Expecting some value")
			end).never.to.throw()
		end)
	end)
	describe("UnwrapOr", function()
		it("should unwrap a some option", function()
			local some = parentModule.Some(10)
			expect(some:UnwrapOr(20)).to.equal(10)
		end)
		it("should unwrap a none option", function()
			local none = parentModule.None
			expect(none:UnwrapOr(20)).to.equal(20)
		end)
	end)
	describe("UnwrapOrElse", function()
		it("should unwrap a some option", function()
			local unwrapOrElse = parentModule.Some(10):UnwrapOrElse(function()
				return 30
			end)
			expect(unwrapOrElse).to.equal(10)
		end)
		it("should unwrap a none option", function()
			local unwrapOrElse = parentModule.None:UnwrapOrElse(function()
				return 30
			end)
			expect(unwrapOrElse).to.equal(30)
		end)
	end)
	describe("And", function()
		it("should return the second option with and when both are some", function()
			local some = parentModule.Some(1)
			local some2 = parentModule.Some(2)
			expect(some:And(some2)).to.equal(some2)
		end)
		it("should return none when first option is some and second option is none", function()
			local some = parentModule.Some(1)
			local none = parentModule.None
			expect(some:And(none):IsNone()).to.equal(true)
		end)
		it("should return none when first option is none and second option is some", function()
			local none = parentModule.None
			local some = parentModule.Some(2)
			expect(none:And(some):IsNone()).to.equal(true)
		end)
		it("should return none when both options are none", function()
			local none = parentModule.None
			local none2 = parentModule.None
			expect(none:And(none2):IsNone()).to.equal(true)
		end)
	end)
	describe("AndThen", function()
		it("should pass the some value to the predicate", function()
			parentModule.Some(32):AndThen(function(p)
				expect(p).to.equal(32)
				return parentModule.None
			end)
		end)
		it("should throw if an option is not returned from predicate", function()
			local some = parentModule.Some(32)
			expect(function()
				some:AndThen(function() end)
			end).to.throw()
		end)
		it("should return none if the option is none", function()
			local none = parentModule.None
			expect(none:AndThen(function()
				return parentModule.Some(10)
			end):IsNone()).to.equal(true)
		end)
		it("should return option of predicate if option is some", function()
			local v = parentModule.Some(32):AndThen(function()
				return parentModule.Some(10)
			end)
			expect(v:IsSome()).to.equal(true)
			expect(v:Unwrap()).to.equal(10)
		end)
	end)
	describe("Or", function()
		it("should return the first option if it is some", function()
			local some = parentModule.Some(10)
			local some2 = parentModule.Some(20)
			expect(some:Or(some2)).to.equal(some)
		end)
		it("should return the second option if the first one is none", function()
			local none = parentModule.None
			local some = parentModule.Some(20)
			expect(none:Or(some)).to.equal(some)
		end)
	end)
	describe("OrElse", function()
		it("should return the first option if it is some", function()
			local some = parentModule.Some(10)
			local some2 = parentModule.Some(20)
			expect(some:OrElse(function()
				return some2
			end)).to.equal(some)
		end)
		it("should return the second option if the first one is none", function()
			local none = parentModule.None
			local some = parentModule.Some(20)
			expect(none:OrElse(function()
				return some
			end)).to.equal(some)
		end)
		it("should throw if the predicate does not return an option", function()
			local none = parentModule.None
			expect(function()
				none:OrElse(function() end)
			end).to.throw()
		end)
	end)
	describe("XOr", function()
		it("should return first option if first option is some and second option is none", function()
			local some = parentModule.Some(1)
			local none = parentModule.None
			expect(some:XOr(none)).to.equal(some)
		end)
		it("should return second option if first option is none and second option is some", function()
			local none = parentModule.None
			local some = parentModule.Some(2)
			expect(none:XOr(some)).to.equal(some)
		end)
		it("should return none if first and second option are some", function()
			local some = parentModule.Some(1)
			local some2 = parentModule.Some(2)
			expect(some:XOr(some2)).to.equal(parentModule.None)
		end)
		it("should return none if first and second option are none", function()
			local none = parentModule.None
			local none2 = parentModule.None
			expect(none:XOr(none2)).to.equal(parentModule.None)
		end)
	end)
	describe("Filter", function()
		it("should return none if option is none", function()
			local none = parentModule.None
			expect(none:Filter(function() end)).to.equal(parentModule.None)
		end)
		it("should return none if option is some but fails predicate", function()
			local some = parentModule.Some(10)
			expect(some:Filter(function(_)
				return false
			end)).to.equal(parentModule.None)
		end)
		it("should return self if option is some and passes predicate", function()
			local some = parentModule.Some(10)
			expect(some:Filter(function(_)
				return true
			end)).to.equal(some)
		end)
	end)
	describe("Contains", function()
		it("should return true if some option contains the given value", function()
			local some = parentModule.Some(32)
			expect(some:Contains(32)).to.equal(true)
		end)
		it("should return false if some option does not contain the given value", function()
			local some = parentModule.Some(32)
			expect(some:Contains(64)).to.equal(false)
		end)
		it("should return false if option is none", function()
			local none = parentModule.None
			expect(none:Contains(64)).to.equal(false)
		end)
	end)
	describe("ToString", function()
		it("should return string of none option", function()
			local none = parentModule.None
			expect((tostring(none))).to.equal("Option<None>")
		end)
		it("should return string of some option with type", function()
			local v = {
				10,
				true,
				false,
				"test",
				{},
				function() end,
				coroutine.create(function() end),
				workspace
			}

			for _, v2 in ipairs(v) do
				local formatted = ("Option<%s>"):format((typeof(v2)))
				expect((tostring(parentModule.Some(v2)))).to.equal(formatted)
			end
		end)
	end)
end