local Config = {
	MOUSE_RANGE = 500,
	STARTUP_ANIM_SPEED = 2,
	STARTUP_PAUSE_AT = 0.25,
	PRE_HITBOX_DELAY = 0.12,
	CATCH_HITBOX_SIZE = vector.create(24, 28, 24),
	CATCH_HITBOX_OFFSET = CFrame.new(0, 0, -3),
	CATCH_DAMAGE = 11.7,
	CATCH_STUN = 1,
	CATCH_BLOCK_BREAK = 1.95,
	POST_CATCH_WAIT_BEFORE_ANIM = 0.2,
	POST_CATCH_WAIT_AFTER_ANIM = 0.7,
	DOWNSLAM_ANIM_SPEED = 1.25,
	RELEASE_HITBOX_WIDTH = 26,
	RELEASE_HITBOX_HEIGHT = 24,
	RELEASE_HITBOX_LENGTH = 46,
	SLAM_OFFSET = CFrame.new(0, -16, -22.5),
	SLAM_DAMAGE = 22.1,
	SLAM_STUN = 1.5,
	SLAM_BLOCK_BREAK = 3.9,
	GUST_TRAVEL_TIME = 1
}
Config.SEQUENCE_LOCK_DURATION = Config.PRE_HITBOX_DELAY + Config.POST_CATCH_WAIT_BEFORE_ANIM + Config.POST_CATCH_WAIT_AFTER_ANIM + 1
return Config