return {
	"Magnet Mech Untransform",
	"MagnetM4DefaultR",
	"MagnetM3DefaultR",
	"MagnetM2DefaultR",
	"MagnetM2DefaultL",
	"MagnetM3DefaultL",
	"MagnetM4DefaultL",
	"MagnetM4DefaultR15",
	"MagnetM3DefaultR15",
	"MagnetM2DefaultR15",
	"MagnetM1DefaultR15",
	"MagnetM1Tier1R",
	"MagnetM1Tier1L",
	"MagnetSlamTier1R",
	"MagnetSlamTier1L",
	"MagnetM1Tier2L",
	"MagnetM1Tier2R",
	"MagnetSlamTier2R",
	"MagnetSlamTier2L",
	"MagnetM1Tier3L",
	"MagnetM1Tier3R",
	"MagnetSlamTier3R",
	"MagnetSlamTier3L",
	"MagnetSlamTier3R15",
	"MagnetSlamTier2R15",
	"MagnetSlamTier1R15",
	"MagnetTier1Idle_Right",
	"MagnetTier1Idle_Left",
	"MagnetTier2Idle_Left",
	"Magnet_ Tier 2 L Motion",
	"MagnetTier2Idle_Right",
	"Magnet_ Tier 2 R Motion",
	"MagnetTier3Idle_Left",
	"MagnetTier3Idle_Right",
	"Untr_ R15 Z Tap Hold",
	"Untr_ R15 Z Tap Release",
	"Untr_ R15 Z Tap Start",
	"Untr_ Z Tap Held L",
	"Untr_ Z Tap Held R",
	"Untr_ Z Tap Release L",
	"Untr_ Z Tap Release R",
	"Untr_ Z Tap Start L",
	"Untr_ Z Tap Start R",
	"UnTr_ Jetpack Assemble",
	"UnTr_ Magnet F Backward L",
	"UnTr_ Magnet F Backward R",
	"UnTr_ Magnet F Backward R15",
	"UnTr_ Magnet F Downward L",
	"UnTr_ Magnet F Downward R",
	"UnTr_ Magnet F Downward R15",
	"UnTr_ Magnet F Forward L",
	"UnTr_ Magnet F Forward R",
	"UnTr_ Magnet F Forward R15",
	"UnTr_ Magnet F Left L",
	"UnTr_ Magnet F Left R",
	"UnTr_ Magnet F Left R15",
	"UnTr_ Magnet F Neutral L",
	"UnTr_ Magnet F Neutral R",
	"UnTr_ Magnet F Neutral R15",
	"UnTr_ Magnet F Right L",
	"UnTr_ Magnet F Right R",
	"UnTr_ Magnet F Right R15",
	"UnTr_ Magnet F Upward L",
	"UnTr_ Magnet F Upward R15",
	"UnTr_ Magnet F upward R",
	"UnTr_ jetpack Looped Fly",
	"Untr_ Magnet C Tap Start",
	"Untr_ Magnet C Tap Release",
	"Untr_Magnet C Tap Loop",
	"Untr_ Magnet C Hold Start",
	"Untr_ Magnet C Hold Loop",
	"Untr_ Magnet C Held Start R",
	"Untr_ Magnet C Held Start L",
	"Untr_ Magnet C Held Loop R",
	"Untr_ Magnet C Held Loop L",
	"Untr_ Magnet C Held End R",
	"Untr_ Magnet C Held End L",
	"Untr_ Magnet C End R15",
	"Untr_ R15 C Tap Loop",
	"Untr_ R15 C Tap Release",
	"Untr_ R15 C Tap Start",
	"Untr_ X Held End L",
	"Untr_ X Held End R",
	"Untr_ X Held End R15",
	"Untr_ X Held Loop L",
	"Untr_ X Held Loop R",
	"Untr_ X Held Loop R15",
	"Transformed Magnet XTap Attract Loop",
	"Transformed Magnet XTap Attract Start",
	"Transformed Magnet XTap Repel Loop",
	"Transformed Magnet XTap Repel Start",
	"Magnet Cannon Z+V Hold Loop",
	"Magnet Cannon Z+V Hold Release",
	"Magnet Cannon Z+V Hold Start",
	"Magnet Mech Z + V Tap Loop",
	"Magnet Mech Z + V Tap Release",
	"Magnet Mech Z + V Tap Start",
	"Magnet Mech Z+V Hold Loop",
	"Magnet Mech Z+V Hold Release",
	"Magnet Mech Z+V Hold Start",
	"Magnet Rockets Z+V Tap Charge",
	"Magnet Rockets Z+V Tap Release",
	"Magnet Rockets Z+V Tap Start",
	"Transformed Magnet Mech Dash B L",
	"Transformed Magnet Mech Dash B R",
	"Transformed Magnet Mech Dash F L",
	"Transformed Magnet Mech Dash F R",
	"Transformed Magnet Mech Dash L",
	"Transformed Magnet Mech Dash R",
	"Transformed Magnet Mech Fall",
	"Transformed Magnet Mech Geppo",
	"Transformed Magnet Mech Idle",
	"Transformed Magnet Mech Jump L",
	"Transformed Magnet Mech Jump R",
	"Transformed Magnet Mech Land",
	"Transformed Magnet Mech Run",
	"Transformed Magnet Mech Super Jump",
	"Transformed Magnet Mech Walk",
	"Magnet Mech C Hold Hammer Jump Loop",
	"Magnet Mech C Hold Jump",
	"Magnet Mech C Hold Jump End",
	"Magnet Mech C Hold Loop",
	"Magnet Mech C Hold Start",
	"Magnet Mech Hammer C Hold Jump End",
	"Magnet Mech Hammer C Hold Jump Loop",
	"Magnet Mech Hammer C Hold Jump Start",
	"Magnet Mech Hammer C Hold Loop",
	"Magnet Mech Hammer C Hold Start",
	"Magnet Mech C Tap Start",
	"Magnet Mech C Tap Loop",
	"Magnet Mech C Tap Release",
	"Magnet Mech MagnetModel Loop",
	"Magnet Mech MagnetModel Start",
	"Transformed Magnet Mech F Hold Charge",
	"Transformed Magnet Mech F Hold Release",
	"Transformed Magnet Mech X Tap Start",
	"Transformed Magnet Mech X Tap Release",
	"Transformed Magnet Mech X Tap Metal Start",
	"Transformed Magnet Mech X Tap Metal Loop",
	"Transformed Magnet Mech X Tap Loop",
	"Transformed Magnet Mech X Hold Release",
	"Transformed Magnet Mech X Hold Charge",
	"Magnet Mech Transformation",
	"Magnet Mech Transformation Landing",
	"Magnet Mech Transformation Loop Fall",
	"Magnet Transformation R15",
	"Magnet Mech M1_1",
	"Magnet Mech M1_2",
	"Magnet Mech M1_3",
	"Magnet Mech M1_4",
	"Transformed Magnet Mech F Hold Explode",
	"Untr_Magnet F Dash L",
	"Untr_Magnet F Dash L Hit",
	"Untr_Magnet F Dash R",
	"Untr_Magnet F Dash R Hit",
	"Untr_Magnet R15 Magnet F Dash",
	"Untr_Magnet R15 Magnet F Dash Hit",
	"Magnet Transformed Jetpack Boost Activate",
	"Magnet Transformed Jetpack Boost Flight Loop",
	"Magnet Transformed Jetpack F Fly Loop",
	"Magnet Transformed Jetpack F Fly Start",
	"Magnet Transformed Mech F Boost Loop",
	"Magnet Transformed Mech F Fly Boost Activate",
	"Magnet Transformed Mech F Fly Loop",
	"Magnet Transformed Mech F Fly Start",
	"Magnet C Tap Charge Arm Loop",
	"Magnet C Tap Charge Arm Start",
	"Magnet C Tap Release Arm Loop",
	"Magnet C Tap Release Arm Start",
	"Magnet C Tap Release Land Arm",
	"Magnet NEW Z Hold Arm End L",
	"Magnet NEW Z Hold Arm End R",
	"Magnet NEW Z Hold Arm Loop L",
	"Magnet NEW Z Hold Arm Loop R",
	"Magnet NEW Z Hold Arm Start L",
	"Magnet NEW Z Hold Arm Start R",
	"Magnet NEW Z Hold Player Loop",
	"Magnet NEW Z Hold Player Start",
	"Magnet New C Tap Charge Loop",
	"Magnet New C Tap Charge Start",
	"Magnet New C Tap Release Land",
	"Magnet New C Tap Release Loop",
	"Magnet New C Tap Release Start",
	"Magnet New Z Hold Player End",
	"Transformed Magnet Mech X Hold Start",
	"Magnet Detransform Eject",
	"Arcsteel Transformed Magnet Mech Dash B L",
	"Arcsteel Transformed Magnet Mech Dash B R",
	"Arcsteel Transformed Magnet Mech Dash F L",
	"Arcsteel Transformed Magnet Mech Dash F R",
	"Arcsteel Transformed Magnet Mech Dash L",
	"Arcsteel Transformed Magnet Mech Dash R",
	"Arcsteel Transformed Magnet Mech Fall",
	"Arcsteel Transformed Magnet Mech Geppo",
	"Arcsteel Transformed Magnet Mech Idle",
	"Arcsteel Transformed Magnet Mech Jump L",
	"Arcsteel Transformed Magnet Mech Jump R",
	"Arcsteel Transformed Magnet Mech Land",
	"Arcsteel Transformed Magnet Mech Run",
	"Arcsteel Transformed Magnet Mech Super Jump",
	"Arcsteel Transformed Magnet Mech Walk",
	"Arcsteel Magnet Cannon Z+V Hold Loop",
	"Arcsteel Magnet Cannon Z+V Hold Release",
	"Arcsteel Magnet Cannon Z+V Hold Start",
	"Arcsteel Magnet Mech C Hold Hammer Jump Loop",
	"Arcsteel Magnet Mech C Hold Jump",
	"Arcsteel Magnet Mech C Hold Jump End",
	"Arcsteel Magnet Mech C Hold Loop",
	"Arcsteel Magnet Mech C Hold Start",
	"Arcsteel Magnet Mech C Tap Loop",
	"Arcsteel Magnet Mech C Tap Release",
	"Arcsteel Magnet Mech C Tap Start",
	"Arcsteel Magnet Mech M1_1",
	"Arcsteel Magnet Mech M1_2",
	"Arcsteel Magnet Mech M1_3",
	"Arcsteel Magnet Mech M1_4",
	"Arcsteel Magnet Mech Z + V Tap Loop",
	"Arcsteel Magnet Mech Z + V Tap Release",
	"Arcsteel Magnet Mech Z + V Tap Start",
	"Arcsteel Magnet Mech Z+V Hold Loop",
	"Arcsteel Magnet Mech Z+V Hold Release",
	"Arcsteel Magnet Mech Z+V Hold Start",
	"Arcsteel Magnet Rockets Z+V Tap Charge",
	"Arcsteel Magnet Rockets Z+V Tap Release",
	"Arcsteel Magnet Rockets Z+V Tap Start",
	"Arcsteel Magnet Transformed Mech F Boost Loop",
	"Arcsteel Magnet Transformed Mech F Fly Loop",
	"Arcsteel Magnet Transformed Mech F Fly Start",
	"Arcsteel Magnet Transformed Mech F Fly Boost Activate",
	"Arcsteel Transformed Magnet Mech F Hold Charge",
	"Arcsteel Transformed Magnet Mech F Hold Explode",
	"Arcsteel Transformed Magnet Mech F Hold Release",
	"Arcsteel Transformed Magnet Mech X Hold Charge",
	"Arcsteel Transformed Magnet Mech X Hold Release",
	"Arcsteel Transformed Magnet Mech X Hold Start",
	"Arcsteel Transformed Magnet Mech X Tap Loop",
	"Arcsteel Transformed Magnet Mech X Tap Release",
	"Arcsteel Transformed Magnet Mech X Tap Start",
	"Transformed Arcsteel Transformation",
	"Transformed Arcsteel Transformation Landing",
	"Transformed Arcsteel Transformation Loop Fall"
}