return function(p)
	local Maid = require(game.ReplicatedStorage.Util.Maid)
	local maid = Maid.new()
	task.spawn(function()
		task.wait()
		local parentModule = require(script.Parent)
		local Window = require(script.Parent.Dialogue.Window)
		Window.setMountTarget(p)
		maid:GiveTask(function()
			parentModule.close()
			Window.setMountTarget(nil)
		end)
		local v = parentModule.getDialogueConstructor():setTitle("Recruiter"):setTitleSprite("Sword", {
			wiggle = true
		}):setSubtitle("Rip Family"):addPage("top", function(object)
			object:addText("The <color=\"Red\">Red Army</color> is planning an invasion. They're trying to destroy our realm by taking our <AnimateEffect=Shake><Yellow>Spirit Tree</Yellow>.<AnimateEffect=/>")
			object:addText("We need your help defending the island!<AnimateYield=0.5> Bring your <sprite=\"Sword\"/> -- can I count on you during the invasion?")
			object:addOption(function(object2)
				object2:setText("Yes, my <sprite=\"Sword\"/> is ready"):setIcon(function(object3)
					object3:setImage("rbxassetid://82902746806768"):setEffect("Wiggle")
				end):onSelected(function()
					parentModule.playAction("Positive")
					print("[story] would InvokeServer(SpiritTree, AttemptRegistration)")
				end):jumpToPage(function(object3)
					object3:addText("Thanks for agreeing to help. I'll bring you to the island when the invasion starts.")
				end)
			end)
			object:addOption(function(object2)
				object2:setText("Change Teams"):jumpTo("swapTeams")
			end)
			object:addOption(function(object2)
				object2:setText("What's in it for me?"):setIcon(function(object3)
					object3:setImage("rbxassetid://110886030681086"):setEffect("Wiggle")
				end):jumpToPage(function(object3)
					object3:addText("The satisfaction of a safe realm. And maybe a <Legendary>Legendary</Legendary> reward.")
				end)
			end)
			object:addOption(function(object2)
				object2:setText("Tell me about the Red Army"):jumpToPage(function(object3)
					object3:addText("Ruthless. Organized. <color=\"Red\">Very red</color>.")
				end)
			end)
			object:addOption(function(object2)
				object2:setText("Secret Armory"):setLocked()
			end)
		end):addPage("swapTeams", function(object)
			parentModule.playAction("Observe")
			object:addText("Ready to join us?")
			object:addOption(function(object2)
				object2:setText("Yes"):jumpToPage(function(object3)
					parentModule.playAction("Welcome")
					object3:addText("Welcome to the <Purple>Rip Family</Purple>!")
					object3:onFinished(function()
						print("[story] would InvokeServer(SetTeam2, Rip Family)")
					end)
				end)
			end)
		end):build()
		parentModule.start(v)
	end)
	return function()
		maid:Destroy()
	end
end