return function()
	local screenGui = Instance.new("ScreenGui")
	screenGui.DisplayOrder = 1000
	screenGui.Name = "Cmdr"
	screenGui.ResetOnSpawn = false
	screenGui.AutoLocalize = false
	local scrollingFrame = Instance.new("ScrollingFrame")
	scrollingFrame.BackgroundColor3 = Color3.fromRGB(17, 17, 17)
	scrollingFrame.BackgroundTransparency = 0.4
	scrollingFrame.BorderSizePixel = 0
	scrollingFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
	scrollingFrame.Name = "Frame"
	scrollingFrame.Position = UDim2.new(0.025, 0, 0, 25)
	scrollingFrame.ScrollBarThickness = 6
	scrollingFrame.ScrollingDirection = Enum.ScrollingDirection.Y
	scrollingFrame.Selectable = false
	scrollingFrame.Size = UDim2.new(0.95, 0, 0, 0)
	scrollingFrame.Visible = false
	scrollingFrame.AutomaticCanvasSize = Enum.AutomaticSize.Y
	scrollingFrame.Parent = screenGui
	local scrollingFrame2 = Instance.new("ScrollingFrame")
	scrollingFrame2.BackgroundColor3 = Color3.fromRGB(59, 59, 59)
	scrollingFrame2.BackgroundTransparency = 0.5
	scrollingFrame2.BorderSizePixel = 0
	scrollingFrame2.CanvasSize = UDim2.new(0, 0, 0, 0)
	scrollingFrame2.Name = "Autocomplete"
	scrollingFrame2.Position = UDim2.new(0, 167, 0, 75)
	scrollingFrame2.ScrollBarThickness = 6
	scrollingFrame2.ScrollingDirection = Enum.ScrollingDirection.Y
	scrollingFrame2.Selectable = false
	scrollingFrame2.Size = UDim2.new(0, 200, 0, 200)
	scrollingFrame2.Visible = false
	scrollingFrame2.AutomaticCanvasSize = Enum.AutomaticSize.Y
	scrollingFrame2.Parent = screenGui
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = scrollingFrame
	local textBox = Instance.new("TextBox")
	textBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textBox.BackgroundTransparency = 1
	textBox.Font = Enum.Font.Code
	textBox.Name = "Line"
	textBox.Size = UDim2.new(1, 0, 0, 20)
	textBox.AutomaticSize = Enum.AutomaticSize.Y
	textBox.TextColor3 = Color3.fromRGB(255, 255, 255)
	textBox.TextSize = 14
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.TextEditable = false
	textBox.ClearTextOnFocus = false
	textBox.Parent = scrollingFrame
	local uIPadding = Instance.new("UIPadding")
	uIPadding.PaddingBottom = UDim.new(0, 10)
	uIPadding.PaddingLeft = UDim.new(0, 10)
	uIPadding.PaddingRight = UDim.new(0, 10)
	uIPadding.PaddingTop = UDim.new(0, 10)
	uIPadding.Parent = scrollingFrame
	local frame = Instance.new("Frame")
	frame.BackgroundTransparency = 1
	frame.LayoutOrder = 999999999
	frame.Name = "Entry"
	frame.Size = UDim2.new(1, 0, 0, 20)
	frame.Parent = scrollingFrame
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = scrollingFrame2
	local frame2 = Instance.new("Frame")
	frame2.BackgroundColor3 = Color3.fromRGB(59, 59, 59)
	frame2.BackgroundTransparency = 0.2
	frame2.BorderSizePixel = 0
	frame2.LayoutOrder = -2
	frame2.Name = "Title"
	frame2.Size = UDim2.new(1, 0, 0, 40)
	frame2.Parent = scrollingFrame2
	local frame3 = Instance.new("Frame")
	frame3.BackgroundColor3 = Color3.fromRGB(59, 59, 59)
	frame3.BackgroundTransparency = 0.2
	frame3.BorderSizePixel = 0
	frame3.LayoutOrder = -1
	frame3.Name = "Description"
	frame3.Size = UDim2.new(1, 0, 0, 20)
	frame3.Parent = scrollingFrame2
	local textButton = Instance.new("TextButton")
	textButton.BackgroundColor3 = Color3.fromRGB(59, 59, 59)
	textButton.BackgroundTransparency = 0.5
	textButton.BorderSizePixel = 0
	textButton.Font = Enum.Font.Code
	textButton.Size = UDim2.new(1, 0, 0, 30)
	textButton.Text = ""
	textButton.TextColor3 = Color3.fromRGB(255, 255, 255)
	textButton.TextSize = 14
	textButton.TextXAlignment = Enum.TextXAlignment.Left
	textButton.Parent = scrollingFrame2
	local uIListLayout3 = Instance.new("UIListLayout")
	uIListLayout3.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout3.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout3.Padding = UDim.new(0, 7)
	uIListLayout3.Parent = frame
	local textBox2 = Instance.new("TextBox")
	textBox2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textBox2.BackgroundTransparency = 1
	textBox2.ClearTextOnFocus = false
	textBox2.Font = Enum.Font.Code
	textBox2.LayoutOrder = 999999999
	textBox2.Position = UDim2.new(0, 140, 0, 0)
	textBox2.Size = UDim2.new(1, 0, 0, 20)
	textBox2.Text = "x"
	textBox2.TextColor3 = Color3.fromRGB(255, 255, 255)
	textBox2.TextSize = 14
	textBox2.TextXAlignment = Enum.TextXAlignment.Left
	textBox2.Selectable = false
	textBox2.Parent = frame
	local textLabel = Instance.new("TextLabel")
	textLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel.BackgroundTransparency = 1
	textLabel.Font = Enum.Font.Code
	textLabel.Size = UDim2.new(0, 0, 0, 20)
	textLabel.AutomaticSize = Enum.AutomaticSize.X
	textLabel.Text = ""
	textLabel.TextColor3 = Color3.fromRGB(255, 223, 93)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.Parent = frame
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel2.BackgroundTransparency = 1
	textLabel2.Font = Enum.Font.SourceSansBold
	textLabel2.Name = "Field"
	textLabel2.Size = UDim2.new(0, 37, 1, 0)
	textLabel2.Text = "from"
	textLabel2.TextColor3 = Color3.fromRGB(255, 255, 255)
	textLabel2.TextSize = 20
	textLabel2.TextXAlignment = Enum.TextXAlignment.Left
	textLabel2.Parent = frame2
	local uIPadding2 = Instance.new("UIPadding")
	uIPadding2.PaddingLeft = UDim.new(0, 10)
	uIPadding2.Parent = frame2
	local textLabel3 = Instance.new("TextLabel")
	textLabel3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel3.BackgroundTransparency = 1
	textLabel3.Font = Enum.Font.SourceSansLight
	textLabel3.Name = "Label"
	textLabel3.Size = UDim2.new(1, 0, 1, 0)
	textLabel3.Text = "The players to teleport. The players to teleport. The players to teleport. The players to teleport. "
	textLabel3.TextColor3 = Color3.fromRGB(255, 255, 255)
	textLabel3.TextSize = 16
	textLabel3.TextWrapped = true
	textLabel3.TextXAlignment = Enum.TextXAlignment.Left
	textLabel3.TextYAlignment = Enum.TextYAlignment.Top
	textLabel3.Parent = frame3
	local uIPadding3 = Instance.new("UIPadding")
	uIPadding3.PaddingBottom = UDim.new(0, 10)
	uIPadding3.PaddingLeft = UDim.new(0, 10)
	uIPadding3.PaddingRight = UDim.new(0, 10)
	uIPadding3.Parent = frame3
	local textLabel4 = Instance.new("TextLabel")
	textLabel4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel4.BackgroundTransparency = 1
	textLabel4.Font = Enum.Font.Code
	textLabel4.Name = "Typed"
	textLabel4.Size = UDim2.new(1, 0, 1, 0)
	textLabel4.Text = "Lab"
	textLabel4.TextColor3 = Color3.fromRGB(131, 222, 255)
	textLabel4.TextSize = 14
	textLabel4.TextXAlignment = Enum.TextXAlignment.Left
	textLabel4.Parent = textButton
	local uIPadding4 = Instance.new("UIPadding")
	uIPadding4.PaddingLeft = UDim.new(0, 10)
	uIPadding4.Parent = textButton
	local textLabel5 = Instance.new("TextLabel")
	textLabel5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel5.BackgroundTransparency = 1
	textLabel5.Font = Enum.Font.Code
	textLabel5.Name = "Suggest"
	textLabel5.Size = UDim2.new(1, 0, 1, 0)
	textLabel5.Text = "   el"
	textLabel5.TextColor3 = Color3.fromRGB(255, 255, 255)
	textLabel5.TextSize = 14
	textLabel5.TextXAlignment = Enum.TextXAlignment.Left
	textLabel5.Parent = textButton
	local textLabel6 = Instance.new("TextLabel")
	textLabel6.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	textLabel6.BackgroundTransparency = 1
	textLabel6.BorderColor3 = Color3.fromRGB(255, 153, 153)
	textLabel6.Font = Enum.Font.SourceSans
	textLabel6.Name = "Type"
	textLabel6.Position = UDim2.new(1, 0, 0, 0)
	textLabel6.Size = UDim2.new(0, 0, 1, 0)
	textLabel6.Text = ": Players"
	textLabel6.TextColor3 = Color3.fromRGB(255, 255, 255)
	textLabel6.TextSize = 15
	textLabel6.TextXAlignment = Enum.TextXAlignment.Left
	textLabel6.Parent = textLabel2
	screenGui.Parent = game:GetService("StarterGui")
	return screenGui
end