return {
	TOTAL_TICKETS_REWARDED_FOR_AD = 500,
	MAX_TICKETS_REWARDED_FOR_AD_PER_DAY = 3,
	TIME_OF_DAILY_RESET = 18,
	AD_ITEM_ID = "Christmas2025MoreTickets",
	CLAIM_SNOWFLAKES_AD_DESCRIPTION = "Watch an ad and earn %d snowflakes for free!",
	CLAIM_SNOWFLAKES_AD_TITLE = "Get more Snowflakes!",
	CLAIM_SNOWFLAKES_AD_ICON = "rbxassetid://125769679889094",
	CLAIM_SNOWFLAKES_AD_BUTTON_DESCRIPTION = "%d/%d Left"
}