local ReplicatedStorage = game:GetService("ReplicatedStorage")
local BonusManager = require(ReplicatedStorage:WaitForChild("BonusManager"))
local BonusDisplay = require(script.Parent:WaitForChild("BonusDisplay"))
BonusManager:Init()
BonusDisplay.Init()