local Reader = require(script.Parent.Buffer.Reader)
local Writer = require(script.Parent.Buffer.Writer)
local Vlq = require(script.Parent.Vlq)
return function(p)
	local function check(p2: number)
		local v = Writer.new()
		Vlq.encode(v, p2)
		local v2 = v.finish()
		local v3 = math.max(math.ceil((math.log(p2 + 1, 128))), 1)
		assert(buffer.len(v2) == v3, "buffer length didn't match expected bytes")
		local v4 = Reader.new(v2)
		assert(Vlq.decode(v4) == p2, "lengths don't match")
	end

	p.test("check different lengths", function()
		check(0)
		check(60)
		check(127)
		check(128)
		check(240)
		check(523)
		check(3218932)
	end)
end