local parent = script.Parent.Parent.Parent.Parent.Parent
local JestGlobals = require(parent.Dev.JestGlobals)
local expect = JestGlobals.expect
local jest = JestGlobals.jest
local it = JestGlobals.it
local describe = JestGlobals.describe
local SingleEventManager = require(script.Parent.Parent.SingleEventManager)
local waitForEvents = require(script.Parent.waitForEvents)
describe("new", function()
	it("should create a SingleEventManager", function()
		local bindableEvent = Instance.new("BindableEvent")
		expect((SingleEventManager.new(bindableEvent))).never.toBeNil()
	end)
end)
describe("connectEvent", function()
	it("should connect to events", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = jest.fn()
		v:connectEvent("Event", function(...)
			v2(...)
		end)
		v:resume()
		bindableEvent:Fire("foo")
		waitForEvents()
		expect(v2).toBeCalledTimes(1)
		expect(v2).toBeCalledWith(bindableEvent, "foo")
		bindableEvent:Fire("bar")
		waitForEvents()
		expect(v2).toBeCalledTimes(2)
		expect(v2).toBeCalledWith(bindableEvent, "bar")
		v:connectEvent("Event")
		bindableEvent:Fire("baz")
		waitForEvents()
		expect(v2).toBeCalledTimes(2)
	end)
	it("should drop events until resumed initially", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = jest.fn()
		v:connectEvent("Event", function(...)
			v2(...)
		end)
		bindableEvent:Fire("foo")
		waitForEvents()
		expect(v2).never.toBeCalled()
		v:resume()
		bindableEvent:Fire("bar")
		waitForEvents()
		expect(v2).toBeCalledTimes(1)
		expect(v2).toBeCalledWith(bindableEvent, "bar")
	end)
	it("should invoke suspended events when resumed", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = jest.fn()
		v:connectEvent("Event", function(...)
			v2(...)
		end)
		v:resume()
		bindableEvent:Fire("foo")
		waitForEvents()
		expect(v2).toBeCalledTimes(1)
		expect(v2).toBeCalledWith(bindableEvent, "foo")
		v:suspend()
		bindableEvent:Fire("bar")
		waitForEvents()
		expect(v2).toBeCalledTimes(1)
		v:resume()
		expect(v2).toBeCalledTimes(2)
		expect(v2).toBeCalledWith(bindableEvent, "bar")
	end)
	it("should invoke events triggered during resumption in the correct order", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = {}
		local v3 = jest.fn(function(_, p)
			table.insert(v2, p)

			if p == 2 then
				bindableEvent:Fire(3)
			elseif p == 3 then
				bindableEvent:Fire(4)
			end
		end)
		v:connectEvent("Event", function(...)
			v3(...)
		end)
		v:suspend()
		bindableEvent:Fire(1)
		bindableEvent:Fire(2)
		waitForEvents()
		v:resume()
		waitForEvents()
		waitForEvents()
		expect(v3).toBeCalledTimes(4)
		expect(v2).toEqual({
			1,
			2,
			3,
			4
		})
	end)
	it("should not invoke events fired during suspension but disconnected before resumption", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = jest.fn()
		v:connectEvent("Event", function(...)
			v2(...)
		end)
		v:suspend()
		bindableEvent:Fire(1)
		waitForEvents()
		v:connectEvent("Event")
		v:resume()
		expect(v2).never.toBeCalled()
	end)
	it("should not yield events through the SingleEventManager when resuming", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		v:connectEvent("Event", function()
			coroutine.yield()
		end)
		v:resume()
		local thread = coroutine.create(function()
			bindableEvent:Fire(5)
			waitForEvents()
		end)
		assert(coroutine.resume(thread))
		waitForEvents()
		expect(coroutine.status(thread)).toBe("dead")
		v:suspend()
		bindableEvent:Fire(5)
		waitForEvents()
		local thread2 = coroutine.create(function()
			v:resume()
		end)
		assert(coroutine.resume(thread2))
		expect(coroutine.status(thread2)).toBe("dead")
	end)
	it("should not throw errors through SingleEventManager when resuming", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		v:connectEvent("Event", function()
			error("Error from SingleEventManager test")
		end)
		v:resume()
		v:suspend()
		bindableEvent:Fire(5)
	end)
	it("should not overflow with events if manager:resume() is invoked when resuming a suspended event", function()
		local bindableEvent = Instance.new("BindableEvent")
		local v = SingleEventManager.new(bindableEvent)
		local v2 = jest.fn(function(_, p)
			if p == 1 then
				v:suspend()
				bindableEvent:Fire(2)
				v:resume()
			end
		end)
		v:connectEvent("Event", function(...)
			v2(...)
		end)
		v:suspend()
		bindableEvent:Fire(1)
		v:resume()
		waitForEvents()
		waitForEvents()
		expect(v2).toBeCalledTimes(2)
	end)
end)
describe("connectPropertyChange", function()
	it("should connect to property changes", function()
		local folder = Instance.new("Folder")
		local v = SingleEventManager.new(folder)
		local v2 = jest.fn()
		v:connectPropertyChange("Name", function(...)
			v2(...)
		end)
		v:resume()
		folder.Name = "foo"
		waitForEvents()
		expect(v2).toBeCalledTimes(1)
		expect(v2).toBeCalledWith(folder)
		folder.Name = "bar"
		waitForEvents()
		expect(v2).toBeCalledTimes(2)
		expect(v2).toBeCalledWith(folder)
		v:connectPropertyChange("Name")
		folder.Name = "baz"
		waitForEvents()
		expect(v2).toBeCalledTimes(2)
	end)
	it("should throw an error if the property is invalid", function()
		local folder = Instance.new("Folder")
		local v = SingleEventManager.new(folder)
		expect(function()
			v:connectPropertyChange("foo", function() end)
		end).toThrow()
	end)
end)