local createVector = vector.create
return {
	FLOWER_STARTUP_DURATION = 1.67,
	SHOOT_DURATION = 5,
	AIM_DROP_ANGLE = 15,
	ORB_COUNT = 25,
	ORB_INTERVAL = 0.2,
	ORB_SPEED = 120,
	ORB_SIZE = createVector(8, 8, 8),
	ORB_LIFETIME = 1.5,
	ORB_SCATTER = 5,
	ORB_DAMAGE = 1,
	ORB_STUN = 0.3,
	ORB_BLOCK_BREAK = 1,
	BEAM_WIDTH = 12,
	BEAM_RANGE = 100,
	BEAM_DEFAULT_TRAVEL_TIME = 0.3,
	BEAM_DAMAGE = 12,
	BEAM_STUN = 1,
	BEAM_KNOCKBACK = 12,
	BEAM_BLOCK_BREAK = 3,
	BEAM_IMPACT_SIZE = createVector(35, 35, 35),
	BEAM_IMPACT_DAMAGE = 8,
	BEAM_IMPACT_STUN = 1.5,
	BEAM_IMPACT_KNOCKBACK = 50,
	BEAM_IMPACT_BLOCK_BREAK = 5,
	RANKED_BEAM_IMPACT_BLOCK_BREAK = 4,
	PVP = {
		AdScale = 0.8333333333333334
	}
}