local Config = {
	MAX_DURATION = 5,
	DEPLOY_DELAY = 0.5,
	MOUSE_RANGE = 100,
	THROW_TIME = 0.25,
	UMBRELLA_FORWARD = 16,
	UMBRELLA_HEIGHT = 3,
	DEPLOY_RANGE = 25,
	DEPLOY_BACK = 3
}
Config.DEPLOY_HITBOX_SIZE = Vector3.new(12, 12, Config.DEPLOY_RANGE + Config.DEPLOY_BACK)
Config.DEPLOY_HITBOX_OFFSET = CFrame.new(0, Config.UMBRELLA_HEIGHT, -(Config.DEPLOY_RANGE - Config.DEPLOY_BACK) / 2)
Config.BARRAGE_INTERVAL = 0.3
Config.DEPLOY_KNOCKBACK = 4
Config.DEPLOY_DAMAGE = 2
Config.DEPLOY_STRICT_STUN = 1
Config.DEPLOY_KNOCKBACK_DURATION = Config.DEPLOY_STRICT_STUN
Config.DEPLOY_BLOCK_BREAK = 0.25
Config.RETURN_TIME = 0.3
Config.PULL_FRONT_DIST = 4
Config.RELEASE_DURATION = 1.33
return Config