local Config = {
	AUTHORED_BARRAGE_AT = 0.9,
	AUTHORED_BARRAGE_TIMESCALE_AT = 1.2833333333333334,
	AUTHORED_FINISHER_AT = 2.183333333333333,
	AUTHORED_END_AT = 2.566666666666667,
	WINDUP_SPEED = 1.95
}
local v = Config.AUTHORED_BARRAGE_AT - Config.AUTHORED_BARRAGE_AT / Config.WINDUP_SPEED
Config.BARRAGE_AT = Config.AUTHORED_BARRAGE_AT / Config.WINDUP_SPEED
Config.BARRAGE_TIMESCALE_AT = Config.AUTHORED_BARRAGE_TIMESCALE_AT - v
Config.FINISHER_AT = Config.AUTHORED_FINISHER_AT - v
Config.END_AT = Config.AUTHORED_END_AT - v
Config.WALK_SPEED = 10
Config.MOUSE_RANGE = 100
Config.HITBOX_SIZE = vector.create(14, 11, 16)
Config.HITBOX_OFFSET = CFrame.new(0, 0, -4)
Config.BARRAGE_HIT_COUNT = 9
Config.BARRAGE_DAMAGE = 1.75
Config.BARRAGE_STUN = 0.35
Config.BARRAGE_KNOCKUP = 1
Config.BARRAGE_BLOCK_BREAK = 0.5
Config.FINISHER_DAMAGE = 12
Config.FINISHER_STUN = 1.4
Config.FINISHER_RAGDOLL = 1.4
Config.FINISHER_KNOCKBACK = 50
Config.FINISHER_UPWARD = 8
Config.FINISHER_BLOCK_BREAK = 3
return Config