return {
	CHARACTER_STATE_EVENT = "CharacterReplicationState",
	FLAG_YOUNG_RODDO = 1,
	FLAG_YOUNG_RODDO_NAME = 2,
	TICK_RATE = 0.1,
	INTERPOLATION_DELAY = 6,
	RESYNC_MIN_HISTORY = 0.3,
	RESYNC_MAX_LEAD = 8,
	RESYNC_STALE_FRAMES = 20,
	RESYNC_LIVE_WINDOW = 2.4,
	REPLICA_OFFSET = vector.create(0, 0, 0)
}