local ReplicatedStorage = game:GetService("ReplicatedStorage")
local BanjoCricket = require(ReplicatedStorage.Shared.Types.BanjoCricket)
local BossMastery = require(ReplicatedStorage.Shared.Types.BossMastery)
local Guards = require(ReplicatedStorage.Data.Guards)
local MonsterParasite = require(ReplicatedStorage.Shared.Types.MonsterParasite)
local OnboardingQuestline = require(ReplicatedStorage.Shared.Types.OnboardingQuestline)
local Rift = require(ReplicatedStorage.Shared.Types.Rift)
local Sakura = require(ReplicatedStorage.Shared.Types.Sakura)
local Scramble = require(ReplicatedStorage.Shared.Types.Scramble)
local ScrambleFinalHits = require(ReplicatedStorage.Shared.Types.ScrambleFinalHits)
local TreadmillUtil = require(ReplicatedStorage.Shared.Util.TreadmillUtil)
require(script.Parent.Types.Interface)
return {
	Money = 0,
	PeakBaseRate = 0,
	CashPackQuote = {
		Day = -1,
		PeakBaseRate = 0,
		Amounts = {}
	},
	CashPackReceipts = {},
	PendingCashPackPurchases = {},
	SakuraCrystals = 0,
	BossTokens = 0,
	SpeedPower = TreadmillUtil.DEFAULT_BASE_SPEED_POWER,
	SpeedBoostTierIndex = 0,
	BaseUpgradeLevel = 0,
	TreadmillUpgradeLevel = 1,
	BestRollDenominator = 0,
	BestGuardRunDistance = 0,
	MonetizationRobuxSpentTotal = 0,
	Inventory = {},
	EquippedAssets = {},
	EggInventory = {},
	LuckyBlockInventory = {},
	TrailInventory = {},
	GearInventory = {},
	GearAutoBuys = {},
	VisitedGears = {},
	AutoSellRarities = {},
	Index = {},
	IndexClaimedCategories = {},
	Gamepasses = {},
	Products = {},
	ProductCredits = {},
	GiftReceipts = {},
	ReceivedGiftReceipts = {},
	GiftedOwnership = {},
	RollbackRewards = {},
	StarterPackOfferExpires = 0,
	StarterPackOfferPending = false,
	StarterPackOfferFinished = false,
	StarterPackOfferPausedSeconds = 0,
	StarterPackOfferPlaytimeSeconds = 0,
	VIPOfferExpires = 0,
	VIPOfferStarted = false,
	LastLogout = 0,
	LastJoinedPlaceVersion = 0,
	PendingOfflineMoney = 0,
	PendingOfflineAnchorLogoutAt = 0,
	EarningsBoostExpiresAt = 0,
	AdEggBoostExpiresAt = 0,
	TemporarySpeedBoostRemainingSeconds = 0,
	TemporarySpeedBoostActiveStartedAt = 0,
	FusionSlots = {},
	FusionLocked = false,
	FusionDuration = 0,
	VIPFusionSlots = {},
	VIPFusionLocked = false,
	VIPFusionDuration = 0,
	PrivateFusionSlots = {},
	PrivateFusionLocked = false,
	PrivateFusionDuration = 0,
	FusionEggReward = false,
	FusionInfoAcknowledged = false,
	ShrineFusion = {
		Divine = false,
		Eternal = false
	},
	ClaimedCodes = {},
	ClaimedLikeMilestoneIds = {},
	ClaimedGroupReward = false,
	DismissedGroupRewardPrompt = false,
	FreeGiftsStartedAt = 0,
	FreeGiftsTime = 0,
	FreeGiftsActiveStartedAt = 0,
	FreeGiftsClaimed = {},
	FreeGiftsLastResetDay = 0,
	CreatorSandboxMoney = 0,
	CreatorSandboxTokens = 0,
	CreatorSandboxProgress = {},
	LatestTreadmillMediaIndex = 0,
	TreadmillMediaFeedState = {
		Seed = 0,
		CurrentIndex = 0,
		AlgorithmVersion = 3,
		ReleaseTrackingInitialized = false,
		FullFeedReleaseVersion = 0,
		CompletedReleaseVersion = 0,
		PendingReleaseVersion = 0,
		SeenPendingMediaKeys = {}
	},
	LikedTreadmillMedia = {},
	LikedCommentIds = {},
	CommentedTreadmillMedia = {},
	HasRiddenTreadmill = false,
	GuardTutorialProgress = {
		Completed = false
	},
	HasEquippedPhone = false,
	HasPlacedFirstEgg = false,
	GuardSpeedWarningsSeen = {},
	PetPenCapacityGuidance = {
		Triggered = false,
		PetsTabAcknowledged = false,
		EquipBestAcknowledged = false
	},
	VisitedGuardAreas = {
		[Guards.Directory.Forest._id] = true
	},
	VisitedEvents = {},
	OnboardingQuestline = OnboardingQuestline.Blank(),
	Settings = {
		SFX = true,
		Music = true,
		AFK = false,
		HideOtherPets = false,
		HideSelfPets = false,
		DisableVideos = false,
		VirtualCursor = false,
		SeenNavigationHint = false,
		CreatorPanel = true
	},
	CurrentAreaEggClaims = {
		PeriodIndex = 0,
		Slots = {}
	},
	Scramble = Scramble.Blank(),
	ScrambleFinalHits = ScrambleFinalHits.Blank(),
	MechaScramblerObtained = false,
	MonsterParasite = MonsterParasite.DefaultState(),
	Sakura = Sakura.Blank(),
	Rift = Rift.Blank(),
	BossMastery = BossMastery.Blank(),
	BanjoCricket = BanjoCricket.Blank(),
	LimitedTimePopupsSeen = {}
}