local frame = Instance.new("Frame")
frame.Name = "Badge"
frame.AnchorPoint = Vector2.new(1, 0)
frame.BackgroundTransparency = 1
frame.Position = UDim2.fromOffset(20, 0)
frame.Size = UDim2.fromOffset(24, 24)
local frame2 = Instance.new("Frame")
frame2.Name = "Background"
frame2.BackgroundColor3 = Color3.fromRGB(35, 37, 39)
frame2.BorderColor3 = Color3.fromRGB(0, 0, 0)
frame2.BorderSizePixel = 0
frame2.Size = UDim2.fromScale(1, 1)
frame2.ZIndex = 2
local uICorner = Instance.new("UICorner")
uICorner.Name = "UICorner"
uICorner.CornerRadius = UDim.new(1, 0)
uICorner.Parent = frame2
frame2.Parent = frame
local frame3 = Instance.new("Frame")
frame3.Name = "Inner"
frame3.AnchorPoint = Vector2.new(0.5, 0.5)
frame3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
frame3.BorderColor3 = Color3.fromRGB(0, 0, 0)
frame3.BorderSizePixel = 0
frame3.Position = UDim2.fromScale(0.5, 0.5)
frame3.Size = UDim2.new(1, -4, 1, -4)
frame3.ZIndex = 3
local uICorner2 = Instance.new("UICorner")
uICorner2.Name = "UICorner"
uICorner2.CornerRadius = UDim.new(1, 0)
uICorner2.Parent = frame3
local textLabel = Instance.new("TextLabel")
textLabel.Name = "TextLabel"
textLabel.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json")
textLabel.Text = "0"
textLabel.TextColor3 = Color3.fromRGB(57, 59, 61)
textLabel.TextSize = 14
textLabel.TextWrapped = true
textLabel.AnchorPoint = Vector2.new(0.5, 0.5)
textLabel.BackgroundTransparency = 1
textLabel.Position = UDim2.fromScale(0.5, 0.5)
textLabel.Size = UDim2.fromScale(1, 1)
textLabel.ZIndex = 100
textLabel.Parent = frame3
frame3.Parent = frame
return frame