local imageButton = Instance.new("ImageButton")
imageButton.Name = "MenuObject"
imageButton.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
imageButton.BackgroundTransparency = 1
imageButton.BorderSizePixel = 0
imageButton.LayoutOrder = 13
imageButton.Size = UDim2.new(1, 0, 0, 56)
local uIListLayout = Instance.new("UIListLayout")
uIListLayout.Name = "UIListLayout"
uIListLayout.Padding = UDim.new(0, 8)
uIListLayout.FillDirection = Enum.FillDirection.Horizontal
uIListLayout.VerticalAlignment = Enum.VerticalAlignment.Center
uIListLayout.Parent = imageButton
local textLabel = Instance.new("TextLabel")
textLabel.Name = "StyledTextLabel"
textLabel.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
textLabel.LineHeight = 1.4
textLabel.RichText = true
textLabel.Text = ""
textLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
textLabel.TextScaled = true
textLabel.TextSize = 19
textLabel.TextTruncate = Enum.TextTruncate.AtEnd
textLabel.TextWrapped = true
textLabel.TextXAlignment = Enum.TextXAlignment.Left
textLabel.BackgroundTransparency = 1
textLabel.Size = UDim2.fromOffset(101, 21)
local uITextSizeConstraint = Instance.new("UITextSizeConstraint")
uITextSizeConstraint.Name = "UITextSizeConstraint"
uITextSizeConstraint.MaxTextSize = 19
uITextSizeConstraint.MinTextSize = 14
uITextSizeConstraint.Parent = textLabel
textLabel.Parent = imageButton
local uIPadding = Instance.new("UIPadding")
uIPadding.Name = "UIPadding"
uIPadding.PaddingLeft = UDim.new(0, 24)
uIPadding.PaddingRight = UDim.new(0, 8)
uIPadding.Parent = imageButton
local frame = Instance.new("Frame")
frame.Name = "IconHost"
frame.BackgroundTransparency = 1
frame.BorderSizePixel = 0
frame.LayoutOrder = 13
frame.Size = UDim2.fromOffset(44, 44)
frame.ZIndex = 13
local frame2 = Instance.new("Frame")
frame2.Name = "IntegrationIconFrame"
frame2.BackgroundTransparency = 1
frame2.BorderSizePixel = 0
frame2.Size = UDim2.fromScale(1, 1)
local uIListLayout2 = Instance.new("UIListLayout")
uIListLayout2.Name = "UIListLayout"
uIListLayout2.FillDirection = Enum.FillDirection.Horizontal
uIListLayout2.HorizontalAlignment = Enum.HorizontalAlignment.Center
uIListLayout2.VerticalAlignment = Enum.VerticalAlignment.Center
uIListLayout2.Parent = frame2
local imageLabel = Instance.new("ImageLabel")
imageLabel.Name = "IntegrationIcon"
imageLabel.BackgroundTransparency = 1
imageLabel.Size = UDim2.fromOffset(36, 36)
imageLabel.Parent = frame2
frame2.Parent = frame
local frame3 = Instance.new("Frame")
frame3.Name = "SelectedHighlighter"
frame3.AnchorPoint = Vector2.new(0.5, 0.5)
frame3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
frame3.BackgroundTransparency = 0.9
frame3.BorderSizePixel = 0
frame3.Position = UDim2.fromScale(0.5, 0.5)
frame3.Size = UDim2.fromOffset(36, 36)
frame3.Visible = false
local uICorner = Instance.new("UICorner")
uICorner.Name = "corner"
uICorner.CornerRadius = UDim.new(1, 0)
uICorner.Parent = frame3
frame3.Parent = frame
local frame4 = Instance.new("Frame")
frame4.Name = "Highlighter"
frame4.AnchorPoint = Vector2.new(0.5, 0.5)
frame4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
frame4.BackgroundTransparency = 0.9
frame4.BorderSizePixel = 0
frame4.Position = UDim2.fromScale(0.5, 0.5)
frame4.Size = UDim2.fromOffset(36, 36)
frame4.Visible = false
local uICorner2 = Instance.new("UICorner")
uICorner2.Name = "corner"
uICorner2.CornerRadius = UDim.new(1, 0)
uICorner2.Parent = frame4
frame4.Parent = frame
local frame5 = Instance.new("Frame")
frame5.Name = "5"
frame5.BackgroundTransparency = 1
frame5.Size = UDim2.fromScale(1, 1)
frame5.ZIndex = 2
frame5.Parent = frame
frame.Parent = imageButton
return imageButton