local canvasGroup = Instance.new("CanvasGroup")
canvasGroup.Name = "Tooltip"
canvasGroup.AnchorPoint = Vector2.new(0.5, 0)
canvasGroup.AutomaticSize = Enum.AutomaticSize.XY
canvasGroup.BackgroundTransparency = 1
canvasGroup.BorderSizePixel = 0
canvasGroup.GroupTransparency = 1
canvasGroup.Position = UDim2.fromOffset(0, 0)
canvasGroup.Size = UDim2.fromOffset(32, 53)
canvasGroup.Visible = false
local frame = Instance.new("Frame")
frame.Name = "Box"
frame.AutomaticSize = Enum.AutomaticSize.XY
frame.BackgroundColor3 = Color3.fromRGB(101, 102, 104)
frame.Position = UDim2.fromOffset(4, 7)
frame.ZIndex = 2
local textLabel = Instance.new("TextLabel")
textLabel.Name = "Header"
textLabel.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json", Enum.FontWeight.Medium, Enum.FontStyle.Normal)
textLabel.Text = "dsadasdsada"
textLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
textLabel.TextSize = 14
textLabel.TextTruncate = Enum.TextTruncate.AtEnd
textLabel.TextWrapped = true
textLabel.TextXAlignment = Enum.TextXAlignment.Left
textLabel.AutomaticSize = Enum.AutomaticSize.X
textLabel.BackgroundTransparency = 1
textLabel.LayoutOrder = 1
textLabel.Size = UDim2.fromOffset(0, 16)
textLabel.Parent = frame
local uIListLayout = Instance.new("UIListLayout")
uIListLayout.Name = "Layout"
uIListLayout.Padding = UDim.new(0, 8)
uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout.Parent = frame
local uICorner = Instance.new("UICorner")
uICorner.Name = "Corner"
uICorner.Parent = frame
local uIPadding = Instance.new("UIPadding")
uIPadding.Name = "Padding"
uIPadding.PaddingBottom = UDim.new(0, 12)
uIPadding.PaddingLeft = UDim.new(0, 12)
uIPadding.PaddingRight = UDim.new(0, 12)
uIPadding.PaddingTop = UDim.new(0, 12)
uIPadding.Parent = frame
local frame2 = Instance.new("Frame")
frame2.Name = "Hotkeys"
frame2.AutomaticSize = Enum.AutomaticSize.Y
frame2.BackgroundTransparency = 1
frame2.LayoutOrder = 3
frame2.Size = UDim2.fromScale(1, 0)
frame2.Visible = false
local uIListLayout2 = Instance.new("UIListLayout")
uIListLayout2.Name = "Layout"
uIListLayout2.Padding = UDim.new(0, 6)
uIListLayout2.FillDirection = Enum.FillDirection.Vertical
uIListLayout2.HorizontalAlignment = Enum.HorizontalAlignment.Center
uIListLayout2.HorizontalFlex = Enum.UIFlexAlignment.None
uIListLayout2.ItemLineAlignment = Enum.ItemLineAlignment.Automatic
uIListLayout2.VerticalFlex = Enum.UIFlexAlignment.None
uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout2.Parent = frame2
local imageLabel = Instance.new("ImageLabel")
imageLabel.Name = "1"
imageLabel.Image = "rbxasset://textures/ui/Controls/key_single.png"
imageLabel.ImageTransparency = 0.7
imageLabel.ScaleType = Enum.ScaleType.Slice
imageLabel.SliceCenter = Rect.new(5, 5, 23, 24)
imageLabel.AutomaticSize = Enum.AutomaticSize.X
imageLabel.BackgroundTransparency = 1
imageLabel.LayoutOrder = 1
imageLabel.Size = UDim2.fromOffset(0, 30)
local uIPadding2 = Instance.new("UIPadding")
uIPadding2.Name = "Inset"
uIPadding2.PaddingLeft = UDim.new(0, 8)
uIPadding2.PaddingRight = UDim.new(0, 8)
uIPadding2.Parent = imageLabel
local textLabel2 = Instance.new("TextLabel")
textLabel2.Name = "LabelContent"
textLabel2.FontFace = Font.new(
	"rbxasset://fonts/families/GothamSSm.json",
	Enum.FontWeight.Medium,
	Enum.FontStyle.Normal
)
textLabel2.Text = ""
textLabel2.TextColor3 = Color3.fromRGB(189, 190, 190)
textLabel2.TextSize = 14
textLabel2.AutomaticSize = Enum.AutomaticSize.X
textLabel2.BackgroundTransparency = 1
textLabel2.Position = UDim2.fromOffset(0, -1)
textLabel2.Size = UDim2.fromScale(1, 1)
textLabel2.Parent = imageLabel
imageLabel.Parent = frame2
frame2.Parent = frame
frame.Parent = canvasGroup
local imageLabel2 = Instance.new("ImageLabel")
imageLabel2.Name = "Caret"
imageLabel2.Image = "rbxasset://LuaPackages/Packages/_Index/UIBlox/UIBlox/AppImageAtlas/img_set_1x_1.png"
imageLabel2.ImageColor3 = Color3.fromRGB(101, 102, 104)
imageLabel2.ImageRectOffset = Vector2.new(260, 440)
imageLabel2.ImageRectSize = Vector2.new(16, 8)
imageLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
imageLabel2.BackgroundTransparency = 1
imageLabel2.Position = UDim2.new(0, 0, 0, 4)
imageLabel2.Rotation = 180
imageLabel2.Size = UDim2.fromOffset(16, 8)
imageLabel2.ZIndex = 2
imageLabel2.Parent = canvasGroup
local imageLabel3 = Instance.new("ImageLabel")
imageLabel3.Name = "DropShadow"
imageLabel3.Image = "rbxasset://LuaPackages/Packages/_Index/UIBlox/UIBlox/AppImageAtlas/img_set_1x_1.png"
imageLabel3.ImageColor3 = Color3.fromRGB(0, 0, 0)
imageLabel3.ImageRectOffset = Vector2.new(217, 486)
imageLabel3.ImageRectSize = Vector2.new(25, 25)
imageLabel3.ImageTransparency = 0.5
imageLabel3.ScaleType = Enum.ScaleType.Slice
imageLabel3.SliceCenter = Rect.new(12, 12, 13, 13)
imageLabel3.BackgroundTransparency = 1
imageLabel3.Position = UDim2.fromOffset(0, 5)
imageLabel3.Size = UDim2.fromOffset(32, 48)
imageLabel3.Parent = canvasGroup
return canvasGroup