local screenGui = Instance.new("ScreenGui")
screenGui.Name = "TopBarApp"
screenGui.DisplayOrder = 1000000000
screenGui.IgnoreGuiInset = true
screenGui.ScreenInsets = Enum.ScreenInsets.TopbarSafeInsets
screenGui.ResetOnSpawn = false
local frame = Instance.new("Frame")
frame.Name = "TopBarFrame"
frame.AnchorPoint = Vector2.new(0, 1)
frame.BackgroundTransparency = 1
frame.BorderColor3 = Color3.fromRGB(27, 42, 53)
frame.Position = UDim2.new(0, 0, 1, 2)
frame.Size = UDim2.new(1, 0, 0, 48)
local frame2 = Instance.new("Frame")
frame2.Name = "LeftFrame"
frame2.BackgroundTransparency = 1
frame2.Position = UDim2.fromOffset(12, 0)
frame2.Size = UDim2.new(0.5, -12, 1, 0)
local uIListLayout = Instance.new("UIListLayout")
uIListLayout.Name = "Layout"
uIListLayout.Padding = UDim.new(0, 12)
uIListLayout.FillDirection = Enum.FillDirection.Horizontal
uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout.Parent = frame2
frame2.Parent = frame
local frame3 = Instance.new("Frame")
frame3.Name = "RightFrame"
frame3.BackgroundTransparency = 1
frame3.Position = UDim2.fromScale(0.5, 0)
frame3.Size = UDim2.new(0.5, -12, 1, 0)
local uIListLayout2 = Instance.new("UIListLayout")
uIListLayout2.Name = "Layout"
uIListLayout2.Padding = UDim.new(0, 12)
uIListLayout2.FillDirection = Enum.FillDirection.Horizontal
uIListLayout2.HorizontalAlignment = Enum.HorizontalAlignment.Right
uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout2.Parent = frame3
frame3.Parent = frame
frame.Parent = screenGui
return screenGui