local createVector = vector.create
local Config = {
	MOUSE_RANGE = 80,
	SPHERECAST_RADIUS = 10,
	DOWNCAST = 15,
	DETECT_HITBOX_SIZE = createVector(35, 35, 35),
	BRANCH_SIGNAL_TIMEOUT = 0.3,
	CLOSE_HOLD_FREEZE_MARK = 0.25,
	CLOSE_EXPLOSION_DELAY = 0.25,
	CLOSE_TOTAL_ANIM_DURATION = 1.08,
	CLOSE_TAIL_DURATION = 0.83,
	CLOSE_HITBOX_SIZE = createVector(35, 35, 35),
	CLOSE_DAMAGE = 24,
	CLOSE_STUN = 1.5,
	CLOSE_KNOCKBACK = 40,
	FAR_PREP_DELAY = 0.25,
	FAR_PROJECTILE_DELAY_TIMES = { 0.2, 0.4, 0.46 },
	FAR_TOTAL_ANIM_DURATION = 1.8,
	FAR_MAX_TAIL_GRACE = 0.2,
	FAR_PROJECTILE_SPEED = 80,
	FAR_PROJECTILE_SIZE = createVector(2, 2, 2),
	PROJECTILE_AOE_SIZE = createVector(18, 18, 18),
	FAR_PROJECTILE_DURATION = 3,
	FAR_AIM_RANGE = 500,
	FAR_SPHERECAST_RADIUS = 10,
	FAR_DOWNCAST = 15,
	FAR_TRACK_TICK = 0.05,
	FAR_DAMAGE = 9.6,
	FAR_STUN = 1,
	FAR_BLOCK_BREAK = 2,
	FAR_KNOCKBACK = 25,
	FAR_SLOW_VALUE = "MelodicWhisperSlow",
	FAR_SLOW_FACTOR = -0.3,
	FAR_SLOW_DURATION = 5
}
local total = 0

for _, v in Config.FAR_PROJECTILE_DELAY_TIMES do
	total += v
end

Config.FAR_PAUSE_DURATION = Config.FAR_PREP_DELAY + total + Config.FAR_PROJECTILE_DURATION
Config.UPDRAFT_HEIGHT = 20
Config.UPDRAFT_DURATION = 2
Config.POS_PART_NAME = "PosPart" .. script.Parent.Name
Config.PVP = {
	Base = 0.8333333333333334
}
return Config