return {
	NUMBER_OF_RAYCASTS = 2.5,
	RAYCAST_RADIUS = 7,
	TRANSPARENCY_THRESHOLD = 0.5,
	SUN_ANGLE_THRESHOLD = 30,
	SUN_BRIGHTNESS_THRESHOLD = 5,
	SUN_EXPOSURE_ADJUSTMENT = 0,
	SUN_EXPOSURE_TIME = 0.25
}