return {
	THROW_INTERVAL = 0.35,
	MAX_HOLD_DURATION = 6,
	POS_PART_NAME = "PosPartMeteor",
	AIM_RANGE = 100,
	MOUSE_RANGE = 500,
	FLOOR_PROBE_UP = 3,
	FLOOR_PROBE_DOWN = 10,
	METEOR_TRAVEL_TIME = 0.25,
	HITBOX_SIZE = vector.create(25.5, 25.5, 25.5),
	HITBOX_HEIGHT_OFFSET = 2,
	THROW_DAMAGE = 3,
	THROW_STUN = 0.6,
	THROW_BLOCK_BREAK = 0.5
}