local parent = script.Parent.Parent.Parent.Parent.Parent
local JestGlobals = require(parent.Dev.JestGlobals)
local expect = JestGlobals.expect
local it = JestGlobals.it
local getDefaultInstanceProperty = require(script.Parent.Parent.getDefaultInstanceProperty)
it("should get default name string values", function()
	local _, v = getDefaultInstanceProperty("StringValue", "Name")
	expect(v).toBe("Value")
end)
it("should get default empty string values", function()
	local _, v = getDefaultInstanceProperty("StringValue", "Value")
	expect(v).toBe("")
end)
it("should get default number values", function()
	local _, v = getDefaultInstanceProperty("IntValue", "Value")
	expect(v).toBe(0)
end)
it("should get nil default values", function()
	local _, v = getDefaultInstanceProperty("ObjectValue", "Value")
	expect(v).toBe(nil)
end)
it("should get bool default values", function()
	local _, v = getDefaultInstanceProperty("BoolValue", "Value")
	expect(v).toBe(false)
end)