local createVector = vector.create
return {
	GameVersion = "1.0.7",
	UpdateNumber = 52,
	FeasterMaxHunger = 1.5,
	OverfedHungerRate = 8,
	FeasterDamageMultiplier = 1.15,
	ChildTreeCuttingRange = 100,
	ChildLakeFishingRange = 200,
	DeerIsInjured = false,
	NightsWithoutMonster = 0,
	TurretRangedDamageMultiplier = 0.2,
	ExplosiveAmmoDamageMult = 1.3,
	MaxTurrets = 3,
	TurretPrices = {
		5,
		10,
		10,
		20,
		20,
		30
	},
	ChristmasMap = game.ReplicatedStorage:GetAttribute("ChristmasMap"),
	SnowClearZone = 60,
	UpdateLandmarks = {
		FurnitureTrader = true,
		ToolWorkshopMeteorShower = true,
		HalloweenCarnival = true
	},
	CanBurn = {
		Item = true,
		Tool = true
	},
	EnergyReturnPerSecond = 8,
	OverheatDuration = 10,
	SnowBiomeTemperatureChangePerSecond = -10,
	NormalBiomeTemperatureChangePerSecond = 10,
	FireTemperatureChangePerSecond = 20,
	SnowBiomeWarmZoneTemperatureChangePerSecond = 10,
	SnowBiomeBlizzardColdMultiplier = 1.4,
	BlizzardTemperatureChangePerSecond = -1,
	WarmthInsulationScale = 15,
	BaseElementalProcChance = 0.08,
	BaseElementalProcChanceInBiome = 0.15,
	InteractionDistance = 15,
	ServerMaxInteractionDist = 80,
	MaxTapAssistRadius = 6,
	FloatingItemActions = false,
	MobileButtonEditor = true,
	GridOffset = createVector(0, 0, 0),
	OnReplaceTool = "Destroy",
	FireSpeedMultiplier = {
		0.85,
		1,
		1.1,
		1.2,
		1.3
	},
	FireGoalMultiplier = {
		1,
		1,
		1.4,
		1.6,
		1.7
	},
	AlienClassEnergyRechargeMultiplier = 1.15,
	AlienScientistClassEnergyRechargeMultiplier = 0.2,
	BerserkerRageDuration = 30,
	HeadshotMultiplier = 1.5,
	MaxSimultaneousEnemiesAtNight = 1,
	TimeBetweenEnemySpawns = { 60, 75 },
	FireInnerZoneSize = 9,
	FireOuterZoneSize = 50,
	FireNoSpawningEnemiesZone = 300,
	CampsiteTorchAddDiameter = 10,
	MaxHunger = 200,
	ReviveHungerRatio = 0.4,
	MedicReviveHungerRatio = 0.7,
	HungerLossPerMinute = 16,
	HealingDebuffFromDamage = 6,
	DefaultHealingPerSecond = 0.3,
	FireHealingPerSecond = 2,
	MinReviveTime = 0,
	AutoReviveTime = 15,
	ReviveFuelConsumption = 60,
	SelfReviveTime = 25,
	ReviveEveryoneTime = 30,
	TimeToWetItem = 15,
	TimeToDryItem = 15,
	BuildingGridSize = 0,
	BuildingGridOffset = createVector(0, 0, 0),
	MinBuildingRadius = 8,
	TorchBuildingRange = 30,
	TeleporterOwnerOnly = false,
	CultistStrongholdDiamondQuantity = 5,
	CultistStrongholdMinStartTime = 20,
	CultistStrongholdResetTime = 20,
	BoostpadSprintSpeed = 50,
	MapTesting = false
}