local require2 = require
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local require3 = require2(ReplicatedStorage:WaitForChild("RequireProxy")).CreateRequire(script, function(p)
	return require2(p)
end)
local v = {
	Explosion = {
		"Frostburst Fury",
		"Blackhole Blue",
		"Blackhole Green",
		"Blackhole Normal",
		"Blackhole Red",
		"Blackhole White",
		"Blackhole Whitehole",
		"Blackhole Yellow",
		"Explosion Blue",
		"Explosion Green",
		"Explosion Normal",
		"Explosion Purple",
		"Explosion Red",
		"Explosion White",
		"Lightning Green",
		"Lightning Normal",
		"Lightning Purple",
		"Lightning Red",
		"Lightning White",
		"Lightning Yellow",
		"Matrix Blast",
		"Runic Blast",
		"Sakura Blue",
		"Sakura Green",
		"Sakura Normal",
		"Sakura Purple",
		"Sakura Red",
		"Sakura Yellow",
		"Waterblast Black",
		"Waterblast Green",
		"Waterblast Normal",
		"Waterblast Purple",
		"Waterblast Red",
		"Waterblast Yellow",
		"Exorcist Combustion",
		"Pumpkin Fire",
		"Hell Dragon Beam",
		"Evil Deal",
		"Purgatory Flames",
		"Demon Fangs",
		"Portal To Hell",
		"Hungry Shadows",
		"Evil Teleportation",
		"Evil Spike Pit",
		"Poison Bomb",
		"Ghost Grenade",
		"VIP Explosion",
		"Ice Explosion",
		"Viper's Vengeance",
		"Blinding Frost",
		"Polar Explosion",
		"Rainbow Frost",
		"Avalanche",
		"Smoke Screen",
		"Frost Trap",
		"Heavenly Barrier",
		"Icarus Fall",
		"Frost Dragon Beam",
		"Gobbler Explosion",
		"Serpent's Rage",
		"Arctic Blast",
		"Arctic Avalanche Blitz",
		"Glacial Ember",
		"Golden Reserve",
		"Solstice Wall",
		"Sunset",
		"Yin Yang",
		"Vibrant Burst",
		"Tricolor Slash",
		"Undead Explosion",
		"Infernal Slash",
		"Christmas Present",
		"Super Sakura",
		"Super Blackhole",
		"Carnival Eye",
		"Christmas Destroyer",
		"Explosive Presents",
		"Candy Cane Trap",
		"Snowflake",
		"Coal",
		"Evil Blast",
		"Candy Cane Explosion",
		"Gift Explosion",
		"Christmas Tree",
		"Christmas Rift",
		"Santa Beam",
		"Kurogin Destruction",
		"Singularity Expulsion",
		"Solar Sparkler",
		"Shooting Starburst",
		"Raven Blast",
		"Crimson Explosion",
		"Prismatic Explosion",
		"2024 Explosion",
		"Happy New Year Explosion",
		"Crowned Ending",
		"Aetherial Explosion",
		"Nebulas Explosion",
		"Infection Breakout",
		"Zombie Annihilation",
		"Futuristic Explosion",
		"Banana Aura",
		"Dragon Explosion",
		"L Explosion",
		"Ultimate Firework",
		"Chinese Dragon",
		"Clockwise",
		"Confetti Rain",
		"Fire Cracker",
		"Firework Beam",
		"Fireworks Road",
		"Party Portal",
		"Red Firework",
		"Rocket Explosion",
		"Gold Burst",
		"Dragon Beam",
		"Disco Ball",
		"Crystal Explosion",
		"Dark Matter Explosion",
		"Violin Explosion",
		"Voltfire Explosion",
		"Nuclear Explosion",
		"Butterfly Explosion",
		"Hacker Explosion",
		"Pastel Rainbow",
		"Elemental",
		"Chained Dragon",
		"Lunar Burst",
		"BOOM Paper",
		"Lunar Fireworks",
		"Kyoi Pond",
		"Lantern Glow",
		"Heart Blast",
		"Heart Explosion",
		"Shadow Vortex",
		"Lucky Coin Burst",
		"Lava Beam",
		"Magma Burst",
		"RIP",
		"Crystal Reveal",
		"Comic Boom Explosion",
		"Void Blast",
		"Rainbow Starburst",
		"Cloud Puff",
		"Dove Scatter",
		"UFO Abduction",
		"Slime Burst",
		"Planetary Explosion",
		"Triple Planetary Explosion",
		"Chocolate Egg",
		"Eggs Explosion",
		"Giant Egg",
		"Eggsplosive Exit",
		"Easter Explosion",
		"Blossom Season",
		"Cherry Blossom Tree",
		"Slime Egg",
		"Sand Dust",
		"Pyramid Scheme",
		"Arcane Burst",
		"Warrior's Beckoning"
	},
	Sword = {
		"Stratocaster Electric Guitar",
		"Hotdog Sword",
		"princ2",
		"Equinox Ball Kebab",
		"giveable apex",
		"Party Popper",
		"Bowtie Blade",
		"Pumpkin PieBlade",
		"SentinelStaff",
		"Cyber Cleaveblade",
		"RAPIER_PLACEHOLDER",
		"Nothing",
		"Light of the Illumina",
		"1B Sword",
		"Ball on a Stick",
		"Demonblade",
		"Ancient Cutlass",
		"Ancient Spear",
		"Gladiator Sword",
		"Festive Sword",
		"Fantasy Katana",
		"Firework Spear",
		"New Years Blade",
		"Time Stopper",
		"Dragon Sword",
		"Viral Edge",
		"Biohazard Sword",
		"Skeletal Slicer",
		"Inferno Axe",
		"New Year's Katana",
		"Spring Blade",
		"Fortune Blade",
		"Harmony Blade",
		"Wealth Cutter",
		"Festive Valor Sword",
		"Lantern Rapier",
		"Winged Sword",
		"Lava Blade",
		"Molten Slayer",
		"Magma Blade",
		"Silver Blade",
		"Bronze Sword",
		"Golden Sword",
		"Titan Blade",
		"Nimbus Spear",
		"Cloud Rapier",
		"Stratus Blade",
		"Sky Edge",
		"Solarflare Saber",
		"Pink Dagger",
		"Toxic Greatsword",
		"Celestial Greatsword",
		"Heavenly Blade",
		"Comet Shard",
		"Meteoric Spike",
		"Galactical Rapier",
		"Void Slicer",
		"Nebula Slasher",
		"Cyborg Sword",
		"Guardian Blade",
		"Nemesis Blade",
		"Divine Blade",
		"Empyreal Sweep",
		"Sol's Edge",
		"Skeleton's Cutlass",
		"Spiked Club",
		"Ghostwalker's Vengeance",
		"Springtide Edge",
		"Spring's Guardian",
		"Spring Bloom",
		"Morning Dew",
		"Egg's Blossom",
		"Bunny's Edge",
		"Hare's Honor",
		"Dawn Petal",
		"Tulip's Tempest",
		"Scaled Longsword",
		"Galactic Halberd",
		"Tundra's Tooth",
		"The Lost Venomshank",
		"Sunfire's Flare",
		"The Ice Dagger",
		"Remastered Linked Sword",
		"Darkheart's Fury",
		"Reaver Blade",
		"Wind's Breath",
		"Phoenix's Edge",
		"Blessed Blade",
		"Bloodthirster",
		"Cerberus' Fang",
		"Crimson Sorrow",
		"Doryu's Blade",
		"Dragonborne",
		"Dragonheart Greatsword",
		"Dune's Edge",
		"Elven Moonblade",
		"Fairy's Edge",
		"Lycan's Claw",
		"Fireforge Dagger",
		"Griffon's Clasp",
		"Mythical Remnant",
		"Nightblade",
		"Overseer's Gaze",
		"Phoenix Saber",
		"Aether's Dagger",
		"Redcliff Claymore",
		"Firebrand's Fury",
		"Gothic Squire's Sword",
		"Staff of the Worthy",
		"Blade of Order",
		"Blazing Edge",
		"Gaia's Edge",
		"Glacier Blade",
		"Shadow's Maw",
		"Stonecarver",
		"Truthseeker",
		"Color Changing Sword Test"
	},
	Ability = {
		"Wind Cloak",
		"Absolute Confidence",
		"Thunder Dash",
		"Telekinesis",
		"Tact",
		"Swap",
		"Super Jump",
		"Shadow Step",
		"Reaper",
		"Rapture",
		"Raging Deflection",
		"Quad Jump",
		"Pulse",
		"Pull",
		"Platform",
		"Phase Bypass",
		"Martyrdom",
		"Invisibility",
		"Freeze Trap",
		"Freeze",
		"Forcefield",
		"Flash Counter",
		"Dash",
		"Blink",
		"Hell Hook",
		"Qi-Charge",
		"Luck",
		"Scopophobia",
		"Blade Trap"
	},
	Finisher = {},
	SwordAccessory = {},
	Emote = {
		"Emote1",
		"Emote2",
		"Emote3",
		"Emote4",
		"Emote5",
		"Emote6",
		"Emote7",
		"Emote8",
		"Emote9",
		"Emote10",
		"Emote11",
		"Emote12",
		"Emote13",
		"Emote14",
		"Emote34",
		"Emote16",
		"Emote17",
		"Emote18",
		"Emote19",
		"Emote20",
		"Emote21",
		"Emote22",
		"Emote23",
		"Emote24",
		"Emote25",
		"Emote26",
		"Emote27",
		"Emote28",
		"Emote29",
		"Emote30",
		"Emote31",
		"Emote32",
		"Emote33",
		"Emote15",
		"Emote35",
		"Emote36",
		"Emote37",
		"Emote38",
		"Emote39",
		"Emote40",
		"Emote41",
		"Emote42",
		"Emote44",
		"Emote45",
		"Emote46",
		"Emote47",
		"Emote48",
		"Emote49",
		"Emote50",
		"Emote51",
		"Emote52",
		"Emote57",
		"Emote54",
		"Emote55",
		"Emote56",
		"Emote53",
		"Emote58",
		"Emote59",
		"Emote60",
		"Emote61",
		"Emote62",
		"Emote63",
		"Emote64",
		"Emote65",
		"Emote66",
		"Emote67",
		"Emote68",
		"Emote69",
		"Emote70",
		"Emote71",
		"Emote72",
		"Emote73",
		"Emote74",
		"Emote75",
		"Emote76",
		"Emote77",
		"Emote78",
		"Emote79",
		"Emote99",
		"Emote98",
		"Emote80",
		"Emote81",
		"Emote82",
		"Emote83",
		"Emote84",
		"Emote85",
		"Emote86",
		"Emote87",
		"Emote88",
		"Emote89",
		"Emote100",
		"Emote102",
		"Emote101",
		"Emote103",
		"Emote104",
		"Emote106",
		"Emote105",
		"Emote107",
		"Emote108",
		"Emote110",
		"Emote109",
		"Emote111",
		"Emote113",
		"Emote112",
		"Emote114",
		"Emote115",
		"Emote116",
		"Emote91",
		"Emote117",
		"Emote118",
		"Emote119",
		"Emote120",
		"Emote121",
		"Emote122",
		"Emote123",
		"Emote124",
		"Emote125",
		"Emote129",
		"Emote128",
		"Emote127",
		"Emote126",
		"Emote140",
		"Emote130",
		"Emote132",
		"Emote131",
		"Emote133",
		"Emote134",
		"Emote135",
		"Emote136",
		"Emote137",
		"Emote138",
		"Emote139",
		"Emote141",
		"Emote142",
		"Emote146",
		"Emote145",
		"Emote147",
		"Emote148",
		"Emote149",
		"Emote151",
		"Emote150",
		"Emote152",
		"Emote153",
		"Emote157",
		"Emote155",
		"Emote156",
		"Emote158",
		"Emote159",
		"Emote161",
		"Emote162",
		"Emote165",
		"Emote168",
		"Emote166",
		"Emote167",
		"Emote169",
		"Emote170",
		"Emote171",
		"Emote172",
		"Emote173",
		"Emote174",
		"Emote176",
		"Emote177",
		"Emote178",
		"Emote181",
		"Emote182",
		"Emote183",
		"Emote184",
		"Emote185",
		"Emote186",
		"Emote187",
		"Emote188",
		"Emote189",
		"Emote190",
		"Emote192",
		"Emote193",
		"Emote194",
		"Emote195",
		"Emote196",
		"Emote197",
		"Emote201",
		"Emote202",
		"Emote203",
		"Emote204",
		"Emote205",
		"Emote206",
		"Emote212",
		"Emote213",
		"Emote214",
		"Emote215",
		"Emote219",
		"Emote221",
		"Emote222",
		"Emote223",
		"Emote224",
		"Emote225",
		"Emote226",
		"Emote227",
		"Emote228",
		"Emote229",
		"Emote230",
		"Emote231",
		"Emote232",
		"Emote233",
		"Emote234",
		"Emote236",
		"Emote237",
		"Emote238",
		"Emote239",
		"Emote241",
		"Emote242",
		"Emote243",
		"Emote244",
		"Emote246",
		"Emote248",
		"Emote249",
		"Emote250",
		"Emote251",
		"Emote252",
		"Emote253",
		"Emote254",
		"Emote255",
		"Emote256",
		"Emote257",
		"Emote258",
		"Emote259",
		"Emote260",
		"Emote261",
		"Emote262",
		"Emote263",
		"Emote264",
		"Emote268",
		"Emote269",
		"Emote505",
		"Emote271",
		"Emote272",
		"Emote273",
		"Emote274",
		"Emote275",
		"Emote279",
		"Emote277",
		"Emote281",
		"Emote283",
		"Emote297",
		"Emote285",
		"Emote286",
		"Emote287",
		"Emote288",
		"Emote289",
		"Emote291",
		"Emote294",
		"Emote295",
		"Emote296",
		"Emote284",
		"Emote298",
		"Emote299",
		"Emote300",
		"Emote301",
		"Emote303",
		"Emote304",
		"Emote305",
		"Emote306",
		"Emote307",
		"Emote308",
		"Emote309",
		"Emote310",
		"Emote312",
		"Emote311",
		"Emote313",
		"Emote316",
		"Emote317",
		"Emote318",
		"Emote319",
		"Emote320",
		"Emote321",
		"Emote322",
		"Emote323",
		"Emote324",
		"Emote325",
		"Emote326",
		"Emote327",
		"Emote328",
		"Emote330",
		"Emote331",
		"Emote332",
		"Emote334",
		"Emote336",
		"Emote338",
		"Emote337",
		"Emote339",
		"Emote340",
		"Emote341",
		"Emote342",
		"Emote343",
		"Emote344",
		"Emote346",
		"Emote348",
		"Emote350",
		"Emote351",
		"Emote352",
		"Emote353",
		"Emote355",
		"Emote349",
		"Emote357",
		"Emote358",
		"Emote359",
		"Emote360",
		"Emote361",
		"Emote362",
		"Emote363",
		"Emote364",
		"Emote366",
		"Emote367",
		"Emote368",
		"Emote369",
		"Emote370",
		"Emote371",
		"Emote375",
		"Emote376",
		"Emote377",
		"Emote378",
		"Emote379",
		"Emote380",
		"Emote381",
		"Emote382",
		"Emote383",
		"Emote384",
		"Emote385",
		"Emote388",
		"Emote389",
		"Emote390",
		"Emote391",
		"Emote392",
		"Emote393",
		"Emote394",
		"Emote396",
		"Emote397",
		"Emote398",
		"Emote399",
		"Emote400",
		"Emote402",
		"Emote403",
		"Emote404",
		"Emote405",
		"Emote406",
		"Emote407",
		"Emote408",
		"Emote410",
		"Emote411",
		"Emote412",
		"Emote413",
		"Emote414",
		"Emote415",
		"Emote417",
		"Emote418",
		"Emote419",
		"Emote420",
		"Emote421",
		"Emote422",
		"Emote426",
		"Emote427",
		"Emote428",
		"Emote431",
		"Emote432",
		"Emote433",
		"Emote434",
		"Emote435",
		"Emote436",
		"Emote437",
		"Emote438",
		"Emote440",
		"Emote439",
		"Emote442",
		"Emote443",
		"Emote444",
		"Emote445",
		"Emote447",
		"Emote448",
		"Emote449",
		"Emote450",
		"Emote451",
		"Emote452",
		"Emote453",
		"Emote454",
		"Emote455",
		"Emote456",
		"Emote457",
		"Emote458",
		"Emote459",
		"Emote460",
		"Emote461",
		"Emote462",
		"Emote463",
		"Emote464",
		"Emote465",
		"Emote466",
		"Emote468",
		"Emote469",
		"Emote470",
		"Emote471",
		"Emote472",
		"Emote476",
		"Emote477",
		"Emote478",
		"Emote479",
		"Emote480",
		"Emote481",
		"Emote482",
		"Emote483",
		"Emote484",
		"Emote485",
		"Emote486",
		"Emote487",
		"Emote488",
		"Emote489",
		"Emote490",
		"Emote494",
		"Emote495",
		"Emote496",
		"Emote497",
		"Emote498",
		"Emote499",
		"Emote500",
		"Emote501",
		"Emote503",
		"Emote504",
		"Emote270"
	}
}
local ReplicatedStorage2 = game:GetService("ReplicatedStorage")
local v2 = require3(ReplicatedStorage2.Common.Utils.Utilities.FFlag)
local result = require3(ReplicatedStorage2.Shared.DeepCopy)(v)

local function updateItems()
	local instantFFlag = v2.GetInstantFFlag("ExistCountDisabledItems", {})

	for k, v3 in result do
		for _, v4 in v3 do
			if v[k] and table.find(v[k], v4) or not result[k] or not table.find(result[k], v4) then
				continue
			end

			if instantFFlag[k] and table.find(instantFFlag[k], v4) then
				continue
			end

			result[k] = result[k] or {}
			local index = table.find(result[k], v4)

			if index then
				table.remove(result[k], index)
			end
		end
	end

	for k, v3 in instantFFlag do
		for _, v4 in v3 do
			if v[k] and table.find(v[k], v4) or result[k] and table.find(result[k], v4) then
				continue
			end

			result[k] = result[k] or {}
			table.insert(result[k], v4)
		end
	end
end

v2.OnChange(updateItems)
task.spawn(updateItems)
return result