local require2 = require
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local require3 = require2(ReplicatedStorage:WaitForChild("RequireProxy")).CreateRequire(script, function(p)
	return require2(p)
end)
local v = {
	Explosion = { "Astral Arcane", "Oceanic Tempest" },
	Emote = {
		"Emote277",
		"Emote400",
		"Emote198",
		"Emote191",
		"Emote199",
		"Emote280",
		"Emote200",
		"Emote207",
		"Emote208",
		"Emote211",
		"Emote209",
		"Emote210",
		"Emote216",
		"Emote217",
		"Emote218",
		"Emote282",
		"Emote354",
		"Emote356",
		"Emote648"
	},
	Sword = {
		"Godsaber",
		"giveable champ",
		"Borealis",
		"Skib",
		"HardRockStick",
		"Apex Blade",
		"Midas Thorn",
		"Bobber",
		"Vishram",
		"Champion Scythe",
		"Flowing Fists",
		"Pillar",
		"Shattered Sword",
		"Anime Sword",
		"Spooky Sightblade",
		"giveable apex",
		"Pretty Princess Wand",
		"Play Sword",
		"Nothing",
		"Voltage",
		"Tsunami Blade",
		"Dual Elemental Masterblade",
		"Ranked Season 1 Top 1 Sword",
		"Ranked Season 1 Top 200 Sword",
		"Ranked Season 1 Top 50 Sword",
		"Eternal Piercer",
		"Aurum Etherius",
		"Dual Aurum Etherius",
		"Great Axe",
		"Halberd",
		"Azure Thunderbolt",
		"Laser Twinblade",
		"Siam Ember Axe",
		"Siamese Edgeblade",
		"BAH",
		"Avis Scythe",
		"Plasma Blasters",
		"Frozen Doomblade",
		"Ultimate Ruby",
		"Ice Breaker",
		"Ranked Season 2 Top 1 Sword",
		"Ranked Season 2 Top 200 Sword",
		"Sword of Order",
		"Hallow's Wrath",
		"Elemental Masterblade",
		"Ranked Season 3 Top 200 Sword",
		"Crown Scythe",
		"Santa's Wrecker",
		"Ranked Season 3 Top 1 Sword",
		"Dual Nebula Fan",
		"Flowing Katana",
		"Ranked Season 3 Top 50 Sword",
		"COAL",
		"Princess Fan",
		"Boreal Frostreaver",
		"Peppermint Slasher",
		"Fire Katana",
		"Dual Fire Katana",
		"Champion's Excalibur",
		"Dragon Katana",
		"Progression Scythe",
		"Resolution Blade",
		"New Year's Spear",
		"New Year's Edge",
		"Regal Radianceblade",
		"Venom Blade",
		"Elemental Sword",
		"Spirit Blade",
		"Valor's Rage",
		"Dual Emperor's Lance",
		"Titan Blade",
		"Ranked NA Season 2 Top 25 Sword",
		"Sci Fi Blade",
		"Ranked Season 4 Top 100 Sword",
		"Ranked Season 4 Top 25 Sword",
		"Ranked Season 4 Top 1 Sword",
		"Ranked NA Season 2 Top 1 Sword",
		"Ranked NA Season 2 Top 100 Sword",
		"Sci Fi Axe",
		"Horizon Reaper",
		"Plasma Beam Blade",
		"Ranked Season 5 Champion",
		"Dual Lucky Fan",
		"Ogre's Axe",
		"Cosmic Starblade",
		"Hare's Halberd",
		"Bunny",
		"Eggscalibur",
		"Dual Easter Fans",
		"Forsaken Riftide",
		"Frostshard Blade",
		"Blade of the Damned",
		"Small Sapling",
		"Allseeing Seer",
		"Unstable Blade",
		"Angelic Blaster",
		"Holy Trident",
		"Reaper's Scythe",
		"Frog",
		"Ancient Dagger",
		"Dragon's Spine",
		"Fallen Sword",
		"Overgrown Scythe",
		"Seraph's Blade",
		"Vanguard's Blade",
		"Wolf Gladius",
		"Ranked Season 2 Top 50 Sword",
		"Ranked Season 6 Top 200",
		"Ranked Season 5 Top 1",
		"Ranked Season 5 Top 200",
		"Ranked Season 5 Top 50",
		"Ranked Season 6 Champion",
		"Ranked Season 6 Top 1",
		"Ranked Season 6 Top 50",
		"Triple Devil Katana",
		"InceptionTime's Hammer",
		"Dual Devil Katana",
		"Dual Frog Blasters",
		"Good Fan",
		"Dual Good Fans",
		"Dual Evil Fans",
		"Eternum Galepiercer",
		"Chimera's Bane",
		"Icarus' Scythe",
		"Mortal's Demise",
		"Cosmic Wrath",
		"Dual Chroma Energy Sword",
		"Celestial Lance",
		"Royal Duality",
		"Dragon Scythe",
		"Frost Dragon",
		"Dual Fire Blasters",
		"Fire Blaster",
		"Dual Frost Blasters",
		"Frost Blaster",
		"Fire Dragon",
		"Revenant's Vow",
		"Dawnblade",
		"Dual Chroma Blasters",
		"Ranked Season 7 Champion",
		"Ranked Season 7 Top 1",
		"Ranked Season 7 Top 50",
		"Ranked Season 7 Top 200",
		"Dual Summer Scythe",
		"Ocean's Fury",
		"Sandstorm Slasher",
		"Poseidon's Trident",
		"Color Changing Sword Test",
		"Dual Cyber Sickle",
		"SpyderSammy",
		"Blackhole Gauntlets",
		"Oni Claws",
		"Empyrean Greatblade",
		"Wavelight Greatblade",
		"Prince Blade",
		"Dual Ether Blade",
		"Ether Blade",
		"Dragon Slayer",
		"Dual Dragon Slayer",
		"Wispwind Reaper",
		"Dual Wispwind Reaper",
		"Frostblade",
		"Nebula Blaster",
		"Dual Nebula Blasters",
		"Dual Royal Blades",
		"Noob",
		"Ocean's Lament",
		"Devil Greatsword",
		"Angel Greatsword",
		"Dual Eternal Greatsword",
		"Chroma Blade",
		"Chroma Scythe",
		"Dual Chroma Set",
		"Yin Yang Greatsword",
		"Dual Yin Yang Greatsword",
		"Shark",
		"Black Ninja Katana",
		"Blue Ninja Katana",
		"Pink Ninja Katana",
		"Red Ninja Katana",
		"Green Ninja Katana",
		"Chroma Ninja Katana",
		"Yin Yang Parasol",
		"Awakened Void Hammer",
		"Awakened Righteous Blade",
		"Awakened Emperor's Axe",
		"Awakened Lunar Hammer",
		"Awakened Emerald Katana",
		"Awakened Sky Axe",
		"Awakened Crystal Staff",
		"Awakened Lunar Protector",
		"Awakened Anchored Crusher",
		"Awakened Blazing Darkblade",
		"Awakened Sunburst Axe",
		"Awakened Eggquinox Blade",
		"Awakened Empyreal Blade",
		"Awakened Staff of Despair",
		"Staff of Despair",
		"Awakened Celestial Aegis",
		"Celestial Aegis",
		"Awakened Medusa's Wraith",
		"Awakened Venomweaver",
		"Awakened Winter's Touch",
		"Medusa's Wraith",
		"Venomweaver",
		"Winter's Touch",
		"Awakened Periastron's Glory",
		"Awakened Ancient Defender",
		"Ranked Season 8 Champion",
		"Ranked Season 8 Top 1 Sword",
		"Ranked Season 8 Top 50 Sword",
		"Ranked Season 8 Top 200 Sword",
		"Starfall",
		"Serpent's Katana",
		"Katana of the Red Flames",
		"Storm Slicer",
		"Leafsong",
		"Ban Hammer",
		"Sinister Scythe",
		"Headless Horror",
		"Mummy's Curse",
		"Doom's Whisper",
		"Mummy's Slasher",
		"Turkey Slayer",
		"Gilded Harvest",
		"Dual Iced Energy Blades",
		"Dual Astral Vanguard",
		"Spring Sun Scythe",
		"Sunkissed Scythe",
		"Aquatic Greatsword"
	}
}
local ReplicatedStorage2 = game:GetService("ReplicatedStorage")
local v2 = require3(ReplicatedStorage2.Common.Utils.Utilities.FFlag)
local result = require3(ReplicatedStorage2.Shared.DeepCopy)(v)

local function updateItems()
	local instantFFlag = v2.GetInstantFFlag("NonGiveableItems", {})

	for k, v3 in result do
		for _, v4 in v3 do
			if v[k] and table.find(v[k], v4) or not result[k] or not table.find(result[k], v4) then
				continue
			end

			if instantFFlag[k] and table.find(instantFFlag[k], v4) then
				continue
			end

			result[k] = result[k] or {}
			local index = table.find(result[k], v4)

			if index then
				table.remove(result[k], index)
			end
		end
	end

	for k, v3 in instantFFlag do
		for _, v4 in v3 do
			if v[k] and table.find(v[k], v4) or result[k] and table.find(result[k], v4) then
				continue
			end

			result[k] = result[k] or {}
			table.insert(result[k], v4)
		end
	end
end

v2.OnChange(updateItems)
task.spawn(updateItems)
return result