local module = require("../../../tests/test")
module.describe("spring", function()
	require("@self/spring.test")
end)
module.describe("tween", function()
	require("@self/tween.test")
end)
module.describe("motion", function()
	require("@self/motion.test")
end)
module.describe("easing", function()
	require("@self/easing.test")
end)
module.describe("utils", function()
	module.describe("interpolate", function()
		require("@self/utils/interpolate.test")
	end)
	module.describe("oklab", function()
		require("@self/utils/oklab.test")
	end)
end)
return {}