local Config = {
	MOUSE_RANGE = 80,
	GROUND_SNAP = 18,
	ZONE_RADIUS = 22.5,
	ZONE_HEIGHT = 30,
	TARGET_JITTER_RADIUS = 3,
	DROP_HITBOX_SIZE = vector.create(13, 13, 12)
}
Config.EXPLOSION_HITBOX_SIZE = Vector3.new(Config.ZONE_RADIUS * 2, Config.ZONE_RADIUS * 2, Config.ZONE_HEIGHT / 2)
Config.ZONE_DURATION = 3
Config.RANKED_WINDUP = 0.2
Config.DROP_INTERVAL_MIN = 0.25
Config.DROP_INTERVAL_MAX = 0.35
Config.DROP_DAMAGE = 2
Config.DROP_STUN = 0.75
Config.EXPLOSION_DAMAGE = 10
Config.EXPLOSION_STUN = 1.25
Config.EXPLOSION_KNOCKBACK = 55
return Config