require(game.ReplicatedStorage.BuildInfo)
local RunService = game:GetService("RunService")
local isStudio = RunService:IsStudio()
local RunService2 = game:GetService("RunService")
local Flags = {
	ENVIRONMENTS_ENABLED = true,
	ENVIRONMENT_MUSIC_ENABLED = false,
	CREWS_ENABLED = true,
	WEATHER_ENABLED = true,
	SUBCLASSES_ENABLED = true,
	FRUIT_SKINS_ENABLED = true,
	FRUIT_ACCESSORIES_ENABLED = true,
	DRAGON_QUEST_ENABLED = true,
	SUBCLASSES = {
		Helmsman = false,
		Shipwright = true
	},
	GIFTING_ENABLED = true,
	OFFLINE_GIFTING_ENABLED = true,
	OLD_COMBAT_SYSTEM_VISUALIZE_HITBOXES = false,
	NEW_COMBAT_SYSTEM_VISUALIZE_HITBOXES = RunService2:IsStudio(),
	ANGEL_QUEST_ENABLED = false,
	NEW_MOBILE_CONTROLS_OPTION_ENABLED = true,
	NEW_MOBILE_HUD_ENABLED = false,
	XMAS_RAID_ENABLED = false,
	CUSTOM_ANALYTICS_ENABLED = false,
	ROBLOX_ANALYTICS_ENABLED = true,
	ROBUX_SKINS_REQUIRE_PERMANENT = false,
	CHROMATIC_SKINS_ENABLED = true,
	ALLOW_VIRTUAL_REMOTES = true,
	COMBAT_REMOTE_THREAD = true,
	ATOMIC_ENEMIES = false,
	ENEMY_NETWORK_PROTECTIONS = true,
	HIDDEN_SKILLS_ENABLED = true,
	HIDDEN_ABILITY_QUESTS_ON_HUD = false,
	ENCHANT_USES_NEW_SERVICE = true,
	FISHING_FLAGS = {
		ENABLE_SPECIAL_FISHING_SPOTS = true,
		ENABLE_SUBMERGED_ISLAND_FISHING_SPOTS = true
	},
	ENABLE_SUBMERGED_ISLAND_LOW_TIDE = true,
	SUMMER_TOKEN_LIGHTNING_EVENT_ENABLED = false,
	RED_CORRUPTION_EVENT_ENABLED = false,
	CELESTIAL_DOMAIN_EVENT_ENABLED = false,
	SUMMER_TOKEN_SLAP_BATTLES = false,
	PVP_ARENA_FLAGS = {
		SUMMER_TOKENS_ENABLED = false
	},
	CELEBRATION_REALM = {
		ENABLED = false,
		TELEPORTATION_ENABLED = false
	},
	GACHA = {
		PREMIUM_GACHA_ENABLED = false,
		EMBERWEST_AWARDS_BOTH_SKINS = true,
		APRIL_FOOLS_GACHA_ENABLED = true
	}
}
RunService:IsServer()

if not Flags.SUBCLASSES_ENABLED then
	for k, _ in pairs(Flags.SUBCLASSES) do
		Flags.SUBCLASSES[k] = false
	end
end

if not isStudio then
	Flags.OLD_COMBAT_SYSTEM_VISUALIZE_HITBOXES = false
	Flags.NEW_COMBAT_SYSTEM_VISUALIZE_HITBOXES = false
end

return Flags