local v = {
	Unknown = 0,
	["Ancient Clock"] = 1,
	["Beautiful Pirate Domain"] = 2,
	["Castle on the Sea"] = 3,
	["Dragon Dojo"] = 4,
	["Floating Turtle"] = 5,
	["Friendly Arena"] = 6,
	["Great Tree"] = 7,
	["Haunted Castle"] = 8,
	["Heavenly Dimension"] = 9,
	["Hell Dimension"] = 10,
	["Hydra Island"] = 11,
	Mansion = 12,
	["North Pole"] = 13,
	["Port Town"] = 14,
	Sea = 15,
	["Sea of Treats"] = 16,
	["Sealed Cavern"] = 17,
	["Secret Temple"] = 18,
	["Sharkman Arena"] = 19,
	["Submerged Island"] = 20,
	["Temple of Time"] = 21,
	["Tiki Outpost"] = 22,
	["Trial of Carnage"] = 23,
	["Trial of Flames"] = 24,
	["Trial of Speed"] = 25,
	["Trial of Strength"] = 26,
	["Trial of Water"] = 27,
	["Trial of the King"] = 28,
	["Trial of the Machine"] = 29,
	["l'Église de Prophétie"] = 30,
	["Swan's Room"] = 31,
	["Snow Mountain"] = 32,
	["Kingdom of Rose"] = 33,
	["Ice Castle"] = 34,
	["Hot  and Cold"] = 35,
	["Green Zone"] = 36,
	["Graveyard Island"] = 37,
	["Forgotten Island"] = 38,
	Factory = 39,
	["Dark Arena"] = 40,
	["Cursed Ship"] = 41,
	Colosseum = 42,
	["Café"] = 43,
	["???"] = 44,
	Desert = 45,
	["Fountain City"] = 46,
	["Frozen Village"] = 47,
	Jungle = 48,
	["Magma Village"] = 49,
	["Marine Fortress"] = 50,
	["Marine Starter"] = 51,
	["Middle Town"] = 52,
	["Pirate Starter"] = 53,
	["Pirate Village"] = 54,
	Prison = 55,
	Skylands = 56,
	["Underwater City"] = 57,
	Whirlpool = 58,
	["Oni Realm"] = 59,
	["Celestial Domain"] = 60,
	["Grand Colosseum"] = 61
}
local v2 = {}

for k, v3 in v do
	v2[v3] = k
end

return table.freeze({
	ValueToId = table.freeze(v),
	IdToValue = table.freeze(v2)
})