return {
	Controls = require(script.Controls),
	CategorizedDropdownGrid = require(script.CategorizedDropdownGrid),
	FloatingCollapseButton = require(script.FloatingCollapseButton),
	Formatter = require(script.Formatter),
	HeaderBar = require(script.HeaderBar),
	InputUtils = require(script.InputUtils),
	KeyCodeSelector = require(script.KeyCodeSelector),
	LayoutMetrics = require(script.LayoutMetrics),
	LogContent = require(script.LogContent),
	LogLine = require(script.LogLine),
	LogList = require(script.LogList),
	LogText = require(script.LogText),
	LogWindow = require(script.LogWindow),
	Popout = require(script.Popout),
	ResizeGrip = require(script.ResizeGrip),
	Root = require(script.Root),
	TabBar = require(script.TabBar),
	TextMetrics = require(script.TextMetrics),
	Theme = require(script.Theme),
	ThreadPanel = require(script.ThreadPanel),
	ToastStack = require(script.ToastStack),
	Toolbar = require(script.Toolbar),
	WindowDragContext = require(script.WindowDragContext)
}