return {
	LazyTag = "LazyLoadableModel",
	HouseTag = "HasLazyInterior",
	LotIdAttribute = "LazyInteriorLotId",
	TriggerAreasFolder = "LotLazyLoadingTriggerAreas",
	FeatureFlag = "HouseLazyLoading",
	ABTestExperiment = "houses-lazy-loading",
	ABTestVariable = "isEnabled",
	ABTestTimeoutSeconds = 10,
	ServerExtractPerStep = 50,
	ServerExtractInterval = 0.03,
	ReparentInstancesPerSecond = 250,
	OwnerSpawnLoadSeconds = 20,
	AreaUnloadCooldownSeconds = 8,
	ReleaseInteriorDebounceSeconds = 0.5,
	ReleaseInteriorRetrySeconds = 1,
	ForceInteriorDebounceSeconds = 0.5,
	ForceAllInteriorsDebounceSeconds = 1,
	InteriorToClient = "House:InteriorToClient",
	UnloadInterior = "House:UnloadInterior",
	ReleaseInterior = "House:ReleaseInterior",
	ForceInterior = "House:ForceInterior",
	ForceAllInteriors = "House:ForceAllInteriors"
}