local Config = {
	RANGE = 64.32,
	BEAM_ARC_HEIGHT = 25,
	HOLD_FREEZE_AT = 0.15,
	HOLD_NR_DURATION = 6,
	TRAVEL_SEGMENTS = 10,
	MAX_TRAVEL_TIME = 0.625,
	TRAVEL_RESPONSIVENESS = 137,
	TRAVEL_MAX_FORCE = 30000,
	TRAVEL_LOCK_DURATION = 1.25,
	UNHOLD_NR_DURATION = 1,
	UNHOLD_CANCEL_WINDOW = 1,
	IMPACT_HITBOX_SIZE = vector.create(15.5, 25, 15.5),
	IMPACT_BLOCK_BREAK = 3,
	IMPACT_STUN = 1.85,
	ANIM_SPEED = 1
}
Config.ANIM_DURATION = 1.48 / Config.ANIM_SPEED
Config.CUTSCENE_FOV = 50
Config.THRUST_DAMAGE_AT = 0.117
Config.THRUST_DAMAGE = 3
Config.EXPLOSION_DELAY = 0.95
Config.EXPLOSION_STUN = 1
Config.EXPLOSION_DAMAGE = 18
Config.SLOW_VALUE = "FlutteringStingSlow"
Config.SLOW_FACTOR = -0.3
Config.SLOW_DURATION = 4
return Config