local RunService = game:GetService("RunService")
local v = {}
local GameSettings = {
	EVENTNAME = "HatchMutationsAndSolaris",
	SIMULATEUPDATEONSTUDIO = "",
	SIMULATEEVENTONSTUDIO = "",
	STUDIOPLAYERSAREFRIENDSONSTUDIO = true,
	SHOWRIDEPETININVENTORYONSTUDIO = false,
	STRIKEPICKEDUPEGGALWAYSONSTUDIO = false,
	PUT3RAREEGGSINFRONTOFPLOTONTUTORIALONSTUDIO = false,
	SHOWNONESTONBOARDINGONSTUDIO = false,
	SHOWCHEATTELEPORTBUTTONONSTUDIO = false,
	GIVEALLEGGSINSTUDIO = true,
	GIVEALLPETSINSTUDIO = false,
	GIVEALLFUSEPETSINSTUDIO = true,
	GIVEALLDIAMONDPETSINSTUDIO = false,
	GIVEALLGOLDPETSINSTUDIO = false,
	NOGAMEPASSONSTUDIO = false,
	SKIPTUTORIALONSTUDIO = false,
	PRINTPETLIGHTNINGPLANINSTUDIO = true,
	THUNDERALWAYSHITPETSONSTUDIO = false,
	THUNDERVARIANTTOSPAWNONSTUDIO = "",
	GIVEPLAYERCHERUBEGGONSTUDIO = false,
	GIVEPLAYERMAXKGEGGSONSTUDIO = false,
	GIVEPLAYERLOWESTKGEGGSONSTUDIO = false,
	ALWAYSHATCHMUTATIONONSTUDIO = "",
	ALWAYSHATCHPETONSTUDIO = "",
	GIVESPECIFICPETSONSTUDIO = "",
	GIVEBIGGESTPETONSTUDIOMAXAGE = "",
	MAXAGEPETSNEEDEDINSTUDIO = { "Griffin", "Phoenix" },
	NEWAGEPETSNEEDEDINSTUDIO = { "Griffin", "Volkaris" },
	SPAWNETERNALTOTHEFURTHESTINSTUDIO = false,
	SPAWNETERNALTOTHENEARESTINSTUDIO = true,
	RELEASEUPDATESONSTUDIO = true,
	NOSHOWLANTERNSONSHOP = true,
	MUTATEALLEGGSONWEATHER = false,
	PROMPTEVENTONRETURNEGG = false,
	LIGHTNINGDONTHITANYTHINGONPLOT = false,
	RIGGEDCARRYEGGSTRIKECHANCE = true,
	DISABLETAPTOHATCH = true,
	SHOWBASKETTRACKER = false,
	RAINBOWMUTATIONUSESOLIDCOLORS = true,
	IsDevPlace = function()
		return v[game.PlaceId] == true
	end
}

function GameSettings.IsTestEnvironment()
	return RunService:IsStudio() or GameSettings.IsDevPlace()
end

function GameSettings.Enabled(p: string)
	return GameSettings.IsTestEnvironment() and GameSettings[p] == true
end

return GameSettings