local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Observers = require(ReplicatedStorage.Packages.Observers)
local Utils = require(ReplicatedStorage.Common.Utils)
local EasterEvent = require(ReplicatedStorage.Shared.Easter.EasterEvent)
return Observers.observeTagNoAncestry("EasterEventExpiresTime", function(p)
	local connection = Utils.Thread.Every(1, function()
		p.Text = Utils.ValueConvertor:FormatTimeWithDaysFull(EasterEvent.EndTime.UnixTimestamp - workspace:GetServerTimeNow())
	end)
	return function()
		connection:Disconnect()
	end
end)