return {
	RACE_WORLDS = { 1, 2, 3 },
	MIN_RACE_TIME = { 50, 40, 80 },
	MIN_RACE_TIME_DEFAULT = 180,
	DATA_KEY = "RaceData",
	STAGE_ZONE_ID = "SAS",
	STAGE_ATTRIBUTE = "SAS",
	MODE_FASTEST = "fastest",
	MODE_MOST_TIME = "most_time",
	MODES = { "fastest", "most_time" },
	SCOPE_GLOBAL = "global",
	SCOPE_LOCAL = "local",
	SCOPES = { "global", "local" },
	LB_USE_ODS = false,
	LB_USE_LOCAL = true,
	LB_REFRESH_INTERVAL = 300,
	LB_FLUSH_INTERVAL = 900,
	LB_STAGGER = 2,
	LB_FETCH_COUNT = 100,
	LB_TIME_SCALE = 1000,
	LB_STORE_FASTEST_PREFIX = "Race_Fastest_W",
	LB_STORE_MOST_TIME_PREFIX = "Race_MostTime_W",
	LB_BAN_STORE = "RaceLeaderboardBans",
	LB_BAN_KEY = "BannedUsers",
	LB_BAN_TOPIC = "RaceLeaderboardBanSync",
	TAG_CHRONO_TOGGLE = "ChronoToggleButton",
	TAG_CHRONO_LABEL = "ChronoTextLabel",
	TAG_LEADERBOARD = "ChronoLeaderboard",
	TIME_PLACEHOLDER = "--:--.---",
	COLOR_AHEAD = "#1dff68",
	COLOR_BEHIND = "#ff4d4d",
	COLOR_GOLD = "#ffd700",
	COLOR_TOGGLE_OFF = "#ff0000",
	RANK_COLORS = {
		Color3.fromRGB(255, 215, 0),
		Color3.fromRGB(82, 151, 255),
		Color3.fromRGB(240, 240, 240),
		Color3.fromRGB(205, 127, 50)
	},
	RANK_STROKE_DEFAULT = Color3.fromRGB(255, 255, 255),
	DEFAULT_THUMB = "rbxassetid://2319523583"
}