local MarketplaceService = game:GetService("MarketplaceService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local PurchaseCue = require(ReplicatedStorage:WaitForChild("GameServices"):WaitForChild("PurchaseCue"))
local services = game.ReplicatedStorage:WaitForChild("Services")
local Monetization = require(services.Monetization)
local reusable = game.ReplicatedStorage:WaitForChild("Remotes"):WaitForChild("Reusable")
local SFX = game.SoundService:WaitForChild("SFX")
local localPlayer = game.Players.LocalPlayer
localPlayer.PlayerGui:WaitForChild("Main")
local _ = workspace.CurrentCamera
local rBXGeneral = game.TextChatService:WaitForChild("TextChannels"):WaitForChild("RBXGeneral")
reusable:WaitForChild("ServerMessage").OnClientEvent:Connect(function(p, color: Color3)
	local v = color or Color3.fromRGB(255, 55, 55)
	rBXGeneral:DisplaySystemMessage(string.format("<font color='#%s'>%s</font>", v:ToHex(), p))
end)
reusable:WaitForChild("PurchaseEnded").OnClientEvent:Connect(function()
	Monetization:CloseBuyPrompt(localPlayer)
end)
reusable.Purchase.OnClientEvent:Connect(function()
	SFX.Purchase:Play()
end)
reusable:WaitForChild("OpenBuyPrompt").OnClientEvent:Connect(function(p, p2)
	Monetization:OpenBuyPrompt(localPlayer, p, p2)
end)
reusable:WaitForChild("PromptPurchase").OnClientEvent:Connect(function(p, p2)
	if p2 == true then
		PurchaseCue.Play()
		MarketplaceService:PromptGamePassPurchase(localPlayer, p)
	else
		PurchaseCue.Play()
		MarketplaceService:PromptProductPurchase(localPlayer, p)
	end
end)
reusable:WaitForChild("Error").OnClientEvent:Connect(function()
	SFX.Error:Play()
end)