return {
	MOUSE_RANGE = 300,
	WINDUP = 0.3,
	CAST_DURATION = 1,
	SWIRL_HITBOX_OFFSET = CFrame.new(0, 3, -24),
	SWIRL_HITBOX_SIZE = vector.create(26, 23.4, 67.6),
	SWIRL_DAMAGE = 20,
	SWIRL_STUN = 1.5,
	SWIRL_BLOCK_BREAK = 2,
	SWIRL_RAGDOLL_DURATION = 1.5,
	SWIRL_KNOCKBACK = 55,
	SWIRL_LAUNCH = 20,
	FROST_DURATION = 4,
	SLOW_VALUE = "WintryGaleSlow",
	SLOW_FACTOR = -0.3,
	SLOW_DURATION = 4
}