local _ = {
	STRAIGHT_MIN_SPEED = 110,
	STRAIGHT_MAX_SPEED = 130,
	EMITTER_DIM_DEFAULT = 80
}
return {
	MIN_SPLASH_FPS = 40,
	STRAIGHT_MIN_SPEED = 110,
	STRAIGHT_MAX_SPEED = 130,
	EMITTER_DIM_DEFAULT = 80,
	CHECK_CHARACTER_INSIDE = false,
	FADE_INSIDE_CHECK = 1,
	MAX_VOLUME = 1,
	MAX_SPREAD = 10,
	EMITTER_DIM_MAXFORWARD = 100,
	EMITTER_UP_MODIFIER = 20,
	STRAIGHT_MAX_RATE = 300,
	OCCLUDED_SPLASH_NUM = 4,
	SPLASH_OFFSET_Y = 50,
	OCCLUDECHECK_OFFSET_XZ_MIN = -80,
	OCCLUDECHECK_OFFSET_XZ_MAX = 80,
	UPDATE_PERIOD = 10
}