local createVector = vector.create
return {
	MOUSE_RANGE = 500,
	HOLD_PAUSE_AT = 0.25,
	ENDLAG = 0.35,
	HITBOX_DELAY = 0.1,
	SWING_ANIM_SPEED = 1.5,
	HITBOX_SIZE = createVector(18, 14, 20),
	HITBOX_OFFSET = CFrame.new(0, 0, -8.5),
	DAMAGE = 12,
	STUN = 1,
	BLOCK_BREAK = 2.6,
	SWITCH_BLOCK_BREAK = 5,
	KNOCKBACK = 28,
	KNOCKBACK_DURATION = 0.25,
	SWITCH_WINDOW = 4,
	SWITCH_DURATION = 1,
	SWITCH_BACK_OFFSET = 10,
	SWITCH_HEIGHT_OFFSET = 7,
	SWITCH_HITBOX_DELAY = 0.4,
	SWITCH_VFX_LEAD = 0.1,
	SWITCH_HITBOX_SIZE = createVector(25, 25, 25),
	SWITCH_HITBOX_OFFSET = CFrame.new(0, 0, -6)
}