return {
	Font = true,
	Size = true,
	ScaleSize = true,
	MinimumSize = true,
	MaximumSize = true,
	Color = true,
	Transparency = true,
	Pixelated = true,
	Offset = true,
	Rotation = true,
	StrokeSize = true,
	StrokeColor = true,
	StrokeTransparency = true,
	ShadowOffset = true,
	ShadowColor = true,
	ShadowTransparency = true,
	LineHeight = true,
	CharacterSpacing = true,
	Truncate = true,
	XAlignment = true,
	YAlignment = true,
	WordSorting = true,
	LineSorting = true,
	Dynamic = true
}