return function()
	local parentModule = require(script.Parent)
	describe("Constructor", function()
		it("should create a new symbol", function()
			local v = parentModule("Test")
			expect(v).to.be.a("userdata")
			expect(v == v).to.equal(true)
			expect((tostring(v))).to.equal("Symbol(Test)")
		end)
		it("should create a new symbol with no name", function()
			local v = parentModule()
			expect(v).to.be.a("userdata")
			expect(v == v).to.equal(true)
			expect((tostring(v))).to.equal("Symbol()")
		end)
		it("should be unique regardless of the name", function()
			expect(parentModule("Test") == parentModule("Test")).to.equal(false)
			expect(parentModule() == parentModule()).to.equal(false)
			expect(parentModule("Test") == parentModule()).to.equal(false)
			expect(parentModule("Test1") == parentModule("Test2")).to.equal(false)
		end)
		it("should be useable as a table key", function()
			local v = parentModule()
			local v2 = {
				[v] = 100
			}
			expect(v2[v]).to.equal(100)
		end)
	end)
end