local chroma = require(script:WaitForChild("chroma"))
require(script:WaitForChild("io"):WaitForChild("cmyk"))
require(script:WaitForChild("io"):WaitForChild("css"))
require(script:WaitForChild("io"):WaitForChild("gl"))
require(script:WaitForChild("io"):WaitForChild("hcg"))
require(script:WaitForChild("io"):WaitForChild("hex"))
require(script:WaitForChild("io"):WaitForChild("hsi"))
require(script:WaitForChild("io"):WaitForChild("hsl"))
require(script:WaitForChild("io"):WaitForChild("hsv"))
require(script:WaitForChild("io"):WaitForChild("lab"))
require(script:WaitForChild("io"):WaitForChild("lch"))
require(script:WaitForChild("io"):WaitForChild("named"))
require(script:WaitForChild("io"):WaitForChild("num"))
require(script:WaitForChild("io"):WaitForChild("rgb"))
require(script:WaitForChild("io"):WaitForChild("temp"))
require(script:WaitForChild("io"):WaitForChild("oklab"))
require(script:WaitForChild("io"):WaitForChild("oklch"))
require(script:WaitForChild("io"):WaitForChild("roblox"))
require(script:WaitForChild("ops"):WaitForChild("alpha"))
require(script:WaitForChild("ops"):WaitForChild("clipped"))
require(script:WaitForChild("ops"):WaitForChild("darken"))
require(script:WaitForChild("ops"):WaitForChild("get"))
require(script:WaitForChild("ops"):WaitForChild("luminance"))
require(script:WaitForChild("ops"):WaitForChild("mix"))
require(script:WaitForChild("ops"):WaitForChild("premultiply"))
require(script:WaitForChild("ops"):WaitForChild("saturate"))
require(script:WaitForChild("ops"):WaitForChild("set"))
require(script:WaitForChild("interpolator"):WaitForChild("rgb"))
require(script:WaitForChild("interpolator"):WaitForChild("lrgb"))
require(script:WaitForChild("interpolator"):WaitForChild("lab"))
require(script:WaitForChild("interpolator"):WaitForChild("lch"))
require(script:WaitForChild("interpolator"):WaitForChild("num"))
require(script:WaitForChild("interpolator"):WaitForChild("hcg"))
require(script:WaitForChild("interpolator"):WaitForChild("hsi"))
require(script:WaitForChild("interpolator"):WaitForChild("hsl"))
require(script:WaitForChild("interpolator"):WaitForChild("hsv"))
require(script:WaitForChild("interpolator"):WaitForChild("oklab"))
require(script:WaitForChild("interpolator"):WaitForChild("oklch"))
chroma.average = require(script:WaitForChild("generator"):WaitForChild("average"))
chroma.bezier = require(script:WaitForChild("generator"):WaitForChild("bezier"))
chroma.blend = require(script:WaitForChild("generator"):WaitForChild("blend"))
chroma.cubehelix = require(script:WaitForChild("generator"):WaitForChild("cubehelix"))
chroma.mix = require(script:WaitForChild("generator"):WaitForChild("mix"))
chroma.interpolate = require(script:WaitForChild("generator"):WaitForChild("mix"))
chroma.random = require(script:WaitForChild("generator"):WaitForChild("random"))
chroma.scale = require(script:WaitForChild("generator"):WaitForChild("scale"))
local analyze = require(script:WaitForChild("utils"):WaitForChild("analyze"))
chroma.analyze = analyze.analyze
chroma.contrast = require(script:WaitForChild("utils"):WaitForChild("contrast"))
chroma.deltaE = require(script:WaitForChild("utils"):WaitForChild("delta-e"))
chroma.distance = require(script:WaitForChild("utils"):WaitForChild("distance"))
local analyze2 = require(script:WaitForChild("utils"):WaitForChild("analyze"))
chroma.limits = analyze2.limits
chroma.valid = require(script:WaitForChild("utils"):WaitForChild("valid"))
chroma.scales = require(script:WaitForChild("utils"):WaitForChild("scales"))
chroma.colors = require(script:WaitForChild("colors"):WaitForChild("w3cx11"))
chroma.brewer = require(script:WaitForChild("colors"):WaitForChild("colorbrewer"))
return chroma