return {
	SERVER_FLAG_CHANCE = 0.001,
	GLOBAL_FLAG_CHANCE = 0.00001,
	SERVER_FLAG_LIMIT = 250,
	GLOBAL_FLAG_LIMIT = 100,
	SERVER_FLAG_TTL = 86400,
	GLOBAL_MEMORYSTORE_NAME = "CatchFlags_Global_v1",
	GLOBAL_MEMORYSTORE_EXPIRY = 21600,
	GLOBAL_MESSAGING_TOPIC = "CatchFlags_GlobalAdd",
	GLOBAL_MESSAGING_CLEAR_TOPIC = "CatchFlags_GlobalClear",
	GLOBAL_HYDRATE_INTERVAL = 90,
	RENDER_RADIUS = 250,
	LOD_UPDATE_INTERVAL = 0.5,
	REPLION_CHANNEL = "CatchFlags"
}