return {
	PLAYER_SPAWNED_VEHICLE = "PlayerSpawnedVehicle",
	PLAYER_STARTED_DRIVING = "PlayerStartedDriving",
	PLAYER_STOPPED_DRIVING = "PlayerStoppedDriving",
	PLAYER_STARTED_DRIVING_LEGACY = "PlayerStartedDrivingLegacy",
	PLAYER_STOPPED_DRIVING_LEGACY = "PlayerStoppedDrivingLegacy",
	CHARACTER_ENTERED_VEHICLE = "CharacterEnteredVehicle",
	CHARACTER_EXITED_VEHICLE = "CharacterExitedVehicle",
	MAX_SPEED_CHANGED = "MaxSpeedChanged",
	DRIFT_STRENGTH_CHANGED = "DriftStrengthChanged",
	LOCK_STATE_CHANGED = "LockStateChanged",
	SUSPENSION_HEIGHT_CHANGED = "SuspensionHeightChanged",
	VEHICLE_DESTROYED = "VehicleDestroyed",
	PROMPT_COLOR_GAMEPASS_NEEDED = "PromptColorGamepassNeeded",
	TURBO_CHANGED = "TurboChanged",
	TEXT_CHANGED = "TextChanged",
	TEXT_COLOR_CHANGED = "TextColorChanged",
	TEXT_EDIT_REQUESTED = "TextEditRequested",
	UNDERGLOW_CHANGED = "UnderglowChanged",
	UNDERGLOW_SIZE_CHANGED = "UnderglowSizeChanged",
	NO_MOTOR_VEHICLE_SPEED_CHANGED = "NoMotorVehicleSpeedChanged",
	NO_MOTOR_VEHICLE_SPAWN_FROM_UPSELL = "NoMotorVehicleSpawnFromUpsell",
	BOOST_CHANGED = "BoostChanged",
	SET_BOOST = "SetBoost",
	SET_THROTTLE_FLOAT = "SetThrottleFloat",
	SET_DRIVE_SETTING = "SetDriveSetting"
}