local createVector = vector.create
return {
	IMPULSE_VELOCITY = 50,
	MAX_VELOCITY_FOR_BOOST = 10,
	IMPULSE_VELOCITY_WHILE_MOVING = 20,
	COOLDOWN_SECONDS = 2,
	MULTIPLIER = 1.5,
	DEFAULT_VEHICLE_BOOST_START_SOUND_ID = "rbxassetid://138272299064780",
	DEFAULT_VEHICLE_BOOST_END_SOUND_ID = "rbxassetid://79458671601821",
	DEFAULT_MAX_PROGRESS = 35,
	PROGRESS_TICK_INTERVAL_SECONDS = 0.1,
	REFILL_DELAY_AFTER_USE_SECONDS = 0.5,
	MAX_FIELD_OF_VIEW_INCREASE = 120,
	EFFECT_CHANGE_START_SPEED = 5,
	EFFECT_CHANGE_END_SPEED = 250,
	EFFECT_SPEED_FRACTION = 0.8,
	MAX_PARTICLE_RATE = 30,
	PARTICLE_OFFSET = createVector(0, 0, -10),
	MIN_EMISSION_SPEED = 40,
	MIN_EMISSION_SPEED_EXIT = 34,
	AIM_SMOOTHING = 8,
	CAMERA_SHAKE_MAGNITUDE = 1.5,
	CAMERA_SHAKE_ROUGHNESS = 4,
	CAMERA_SHAKE_FADE_IN = 0.2,
	CAMERA_SHAKE_FADE_OUT = 0.3,
	CAMERA_SHAKE_DURATION = 0.8,
	CAMERA_SHAKE_POSITION_INFLUENCE = createVector(0.4, 0.4, 0.4),
	CAMERA_SHAKE_ROTATION_INFLUENCE = createVector(0, 0, 0),
	DEFAULT_COLORS = { Color3.fromRGB(0, 86, 255), (Color3.fromRGB(255, 0, 0)) },
	BAR_COLOR_STOPS = {
		{
			position = 0,
			color = Color3.fromRGB(80, 200, 255)
		},
		{
			position = 0.5,
			color = Color3.fromRGB(80, 200, 255)
		},
		{
			position = 0.78,
			color = Color3.fromRGB(255, 235, 60)
		},
		{
			position = 1,
			color = Color3.fromRGB(255, 40, 20)
		}
	},
	FIRE_PARTICLES_ENABLED = true,
	FIRE_PARTICLE_COLOR_HOT = Color3.fromRGB(255, 230, 60),
	FIRE_PARTICLE_COLOR_COOL = Color3.fromRGB(255, 40, 20),
	FIRE_PARTICLES_PER_TICK = 3,
	FIRE_PARTICLE_MIN_SIZE_PIXELS = 4,
	FIRE_PARTICLE_MAX_SIZE_PIXELS = 10,
	FIRE_PARTICLE_LIFETIME_SECONDS = 0.45,
	FIRE_PARTICLE_RISE_SCALE = 0.35,
	FIRE_PARTICLE_POOL_SIZE = 24,
	FIRE_PARTICLE_SHRINK_FACTOR = 0.8,
	VEHICLE_BOOST_NOT_OWNED = "Requires Boost & Vehicle Customisation Gamepass"
}