return function()
	local createSignal = require(script.Parent.createSignal)
	local createSpy = require(script.Parent.createSpy)
	it("should fire subscribers and disconnect them", function()
		local signal = createSignal()
		local spy = createSpy()
		local v = signal:subscribe(spy.value)
		expect(spy.callCount).to.equal(0)
		local v2 = {}
		signal:fire(1, v2, "hello")
		expect(spy.callCount).to.equal(1)
		spy:assertCalledWith(1, v2, "hello")
		v()
		signal:fire()
		expect(spy.callCount).to.equal(1)
	end)
	it("should handle multiple subscribers", function()
		local signal = createSignal()
		local spy = createSpy()
		local spy2 = createSpy()
		local v = signal:subscribe(spy.value)
		local v2 = signal:subscribe(spy2.value)
		expect(spy.callCount).to.equal(0)
		expect(spy2.callCount).to.equal(0)
		local v3 = {}
		signal:fire(v3, 67)
		expect(spy.callCount).to.equal(1)
		spy:assertCalledWith(v3, 67)
		expect(spy2.callCount).to.equal(1)
		spy2:assertCalledWith(v3, 67)
		v()
		signal:fire(67, v3)
		expect(spy.callCount).to.equal(1)
		expect(spy2.callCount).to.equal(2)
		spy2:assertCalledWith(67, v3)
		v2()
	end)
	it("should stop firing a connection if disconnected mid-fire", function()
		local signal = createSignal()
		local v = nil
		local v2 = nil
		local spy = createSpy(function()
			v2()
		end)
		local spy2 = createSpy(function()
			v()
		end)
		v = signal:subscribe(spy.value)
		v2 = signal:subscribe(spy2.value)
		signal:fire()
		expect(spy.callCount + spy2.callCount).to.equal(1)
	end)
	it("should allow adding listener in the middle of firing", function()
		local signal = createSignal()
		local v = nil
		local spy = createSpy()
		local v2 = signal:subscribe(function(_, _)
			v = signal:subscribe(spy.value)
		end)
		expect(spy.callCount).to.equal(0)
		local v3 = {}
		signal:fire(v3, 67)
		expect(spy.callCount).to.equal(0)
		signal:fire(67, v3)
		expect(spy.callCount).to.equal(1)
		spy:assertCalledWith(67, v3)
		v()
		v2()
		signal:fire(v3)
		expect(spy.callCount).to.equal(1)
	end)
	it("should have one connection instance when add the same listener multiple times", function()
		local signal = createSignal()
		local spy = createSpy()
		local v = signal:subscribe(spy.value)
		expect(spy.callCount).to.equal(0)
		local v2 = {}
		signal:fire(v2, 67)
		expect(spy.callCount).to.equal(1)
		spy:assertCalledWith(v2, 67)
		local v3 = signal:subscribe(spy.value)
		signal:fire(67, v2)
		expect(spy.callCount).to.equal(2)
		spy:assertCalledWith(67, v2)
		v3()
		signal:fire(v2)
		expect(spy.callCount).to.equal(2)
		v()
		signal:fire(v2)
		expect(spy.callCount).to.equal(2)
	end)
end