return {
	["Los Chihuaninis"] = {},
	["Los Gattitos"] = {},
	["Los Cucarachas"] = {},
	["Los Quesadillas"] = {},
	["Los Burritos"] = {},
	["Chihuanini Taconini"] = {},
	["Gattito Tacoto"] = {},
	["Los Tipi Tacos"] = {},
	["Quesadilla Crocodila"] = {},
	["Burrito Bandito"] = {},
	["Los Nooo My Hotspotsitos"] = {},
	["Tipi Topi Taco"] = {},
	["Capi Taco"] = {},
	["Bombardini Tortinii"] = {},
	["Nooo My Hotspot"] = {},
	["La Cucaracha"] = {},
	["Mariachi Corazoni"] = {},
	["Quesadillo Vampiro"] = {},
	["La Taco Combinasion"] = {},
	["Chillin Chili"] = {},
	["Tacorita Bicicleta"] = {},
	["Chipso and Queso"] = {}
}