return {
	HOLD_FREEZE_MARK = 0.67,
	RELEASE_TO_HITBOX = 0.4,
	POS_PART_NAME = "PosPartFlesh Barrage",
	MOUSE_RANGE = 80,
	TENTACLE_COUNT = 31,
	TENTACLE_INTERVAL = 0.1,
	TENTACLE_RADIUS = 10,
	TENTACLE_ANGLE = 35,
	TENTACLE_HEIGHT = 15,
	TENTACLE_HITBOX_WIDTH = 10,
	BARRAGE_DAMAGE = 3.5,
	BARRAGE_STUN = 0.75,
	BARRAGE_BLOCK_BREAK = 1,
	TENTACLE_HIT_CAP = 8
}