return {
	WINDUP = 0.35,
	RADIUS = 12.5,
	FIELD_DURATION = 1,
	BLOCK_BREAK = 2,
	KNOCKBACK = 28,
	KNOCKBACK_DURATION = 0.3,
	DEBUFF_VALUE = "DisruptionPulseDebuff",
	DEBUFF_DURATION = 3,
	DEBUFF_DAMAGE_FACTOR = -0.1,
	DEBUFF_SPEED_FACTOR = -0.1
}