return {
	GumGum = "RubberRubber",
	GumFruit = "RubberFruit",
	["Gum Fruit"] = "Rubber Fruit",
	Gum = "Rubber",
	["Permanent Gum"] = "Permanent Rubber",
	PawPaw = "PalmPalm",
	PawFruit = "PalmFruit",
	["Paw Fruit"] = "Palm Fruit",
	Paw = "Palm",
	["Permanent Paw"] = "Permanent Palm",
	OpOp = "ControlControl",
	OpFruit = "ControlFruit",
	["Op Fruit"] = "Control Fruit",
	Op = "Control",
	["Permanent Op"] = "Permanent Control",
	HumanHuman = "TelekinesisTelekinesis",
	HumanFruit = "TelekinesisFruit",
	["Human Fruit"] = "Telekinesis Fruit",
	Human = "Telekinesis",
	["Permanent Human"] = "Permanent Telekinesis",
	Bisento = "Quake Spear",
	Bullitus = "Bubble",
	None = "Combat",
	DarkLeg = "Dark Leg",
	DragonClaw = "Dragon Claw",
	WaterStyle = "Water Style"
}