local Config = require(script.Parent.Config)
return function()
	local screenGui = Instance.new("ScreenGui")
	screenGui.Name = "MouseLockGui"
	screenGui.ResetOnSpawn = false
	local frame = Instance.new("Frame")
	frame.Name = "MiddleIcon"
	frame.Size = UDim2.new(0.075, 0, 0.075, 0)
	frame.Position = UDim2.new(0.495, 0, 0.45, 0)
	frame.AnchorPoint = Vector2.new(0.5, 0.5)
	frame.BackgroundTransparency = 1
	frame.ZIndex = 10
	frame.Visible = true
	frame.Name = "MiddleIcon"
	frame.Parent = screenGui
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "MouseLockLabel"
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.Size = UDim2.new(1, 0, 1, 0)
	imageLabel.Position = UDim2.new(0.5, 0, 0.5, 0)
	imageLabel.BackgroundTransparency = 1
	imageLabel.ImageTransparency = 0.5
	imageLabel.Image = Config.MouseLockIcon
	imageLabel.ScaleType = Enum.ScaleType.Fit
	imageLabel.Visible = false
	imageLabel.Parent = frame
	local frame2 = Instance.new("Frame")
	frame2.Name = "BottomLeftControl"
	frame2.Size = UDim2.new(0.1, 0, 0.1, 0)
	frame2.Position = UDim2.new(0.99, 0, 1, 0)
	frame2.AnchorPoint = Vector2.new(1, 1)
	frame2.BackgroundTransparency = 1
	frame2.ZIndex = 10
	frame2.Parent = screenGui
	local imageButton = Instance.new("ImageButton")
	imageButton.Name = "MouseLockLabel"
	imageButton.Size = UDim2.new(1, 0, 1, 0)
	imageButton.AnchorPoint = Vector2.new(0.5, 0.5)
	imageButton.Position = UDim2.new(0.5, 0, 0.5, 0)
	imageButton.BackgroundTransparency = 1
	imageButton.Image = Config.MobileLockOffImage
	imageButton.ImageTransparency = 0.25
	imageButton.Visible = true
	imageButton.Parent = frame2
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.AspectRatio = 1
	uIAspectRatioConstraint.DominantAxis = "Height"
	uIAspectRatioConstraint.Parent = frame2
	local uIAspectRatioConstraint2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint2.AspectRatio = 1
	uIAspectRatioConstraint2.DominantAxis = "Height"
	uIAspectRatioConstraint2.Parent = frame
	return screenGui
end