return {
	MAX_RANGE = 60,
	BEAM_ARC_HEIGHT = 100,
	HOLD_FREEZE_AT = 0.15,
	TRAVEL_SEGMENTS = 10,
	MAX_HANG_TIME = 0.5,
	IMPACT_HITBOX_SIZE = vector.create(32, 13, 32),
	IMPACT_HITBOX_OFFSET = CFrame.new(0, 0, -7),
	IMPACT_GROUND_PROBE_UP = 6,
	IMPACT_GROUND_PROBE_DOWN = 40,
	IMPACT_DAMAGE = 22,
	IMPACT_RAGDOLL = 1.5,
	IMPACT_KNOCKBACK = 30,
	IMPACT_KNOCKUP = 12,
	IMPACT_KNOCK_DURATION = 0.4,
	IMPACT_BLOCK_BREAK = 1
}