local sharedAdminEvent = script:FindFirstAncestor("SharedAdminEvent")
require(sharedAdminEvent.Types)
return {
	Identity = "Madness",
	DisplayName = "Madness Event",
	Duration = 180,
	RunGlobally = true,
	Issueable = true,
	RunInTradePlaza = true,
	Actions = {
		"Announcement",
		"Multiplier",
		"Lighting",
		"Fish",
		"Mutation",
		"StartSound",
		"Icon"
	},
	Arguments = {
		"<b><font color='#000000'><stroke color='#ffffff' th='2'>MADNESS</stroke></font></b> HAS ARRIVED! (START FISHING <b>ANYWHERE!</b>)",
		{
			luck = 5555555555,
			xp = 3,
			length = 3
		},
		"Madness",
		{
			["Golden Nessie"] = 2,
			["Golden Scylla"] = 2,
			["Golden Coin"] = 2,
			["Black Iron Bucket"] = 2,
			Poltergeist = 2,
			Ghoul = 2,
			Ghost = 2,
			Fridge = 2,
			Snowman = 2,
			Snowflake = 2,
			Flashlight = 2,
			Singularity = 2,
			["Mango Whale"] = 2,
			Frank = 2,
			["Mustard Hat"] = 2,
			["Alien Buddy"] = 2,
			Parasite = 2,
			UFO = 2,
			["Broken Scylla"] = 2,
			["Gargantuan Taco"] = 2,
			Moon = 2,
			["Rocket Ship"] = 2,
			["8-Bit Mr. Tentacles"] = 2,
			["Dr. Ishmael"] = 2,
			Cheezburger = 2,
			Venoblossom = 2,
			["Lightning Bolt"] = 2,
			["Fischipedia Accurate Pickle"] = 2,
			["Supersized Floppy"] = 2,
			["Supersized Mosslurker"] = 2,
			["Supersized Scylla"] = 2,
			["Supersized Driftwood"] = 2,
			["🐋"] = 3,
			["🦈"] = 3,
			["🦑"] = 3,
			["🐡"] = 3,
			["🐟"] = 3,
			["Baby Bloop Fish"] = 3,
			["Bloop Cosmetic Crate"] = 3,
			["Ancient Kraken"] = 3,
			["Ancient Orca"] = 3,
			Moby = 3,
			["Bloop Fish"] = 3,
			Mosslurker = 3
		},
		{
			Tormented = 6.25,
			Lightened = 6.25,
			Surreal = 6.25,
			Radiant = 6.25,
			Mace = 6.25,
			Spectral = 6.25,
			Glacial = 6.25,
			Chlorowoken = 6.25,
			Female = 6.25,
			Lustrous = 6.25,
			Haunted = 6.25,
			Venomous = 6.25,
			Chilled = 6.25,
			Mango = 6.25,
			Mayhem = 6.25,
			Madness = 6.25
		},
		81751962847320,
		94402287239574,
		"MADNESS"
	}
}