return function()
	local Type = require(script.Parent.Parent.Type)
	local Component = require(script.Parent.Parent.Component)
	it("should be extendable", function()
		local extended = Component:extend("The Senate")
		expect(extended).to.be.ok()
		expect(Type.of(extended)).to.equal(Type.StatefulComponentClass)
	end)
	it("should prevent extending a user component", function()
		local extended = Component:extend("Sheev")
		expect(function()
			extended:extend("Frank")
		end).to.throw()
	end)
	it("should use a given name", function()
		local v = tostring((Component:extend("FooBar")))
		expect(v).to.be.a("string")
		expect(v:find("FooBar")).to.be.ok()
	end)
end