return {
	Name = "Twisted Looey",
	Rarity = "Common",
	Icon = "rbxassetid://116451358719686",
	VisionRadius = 60,
	InstantRadius = 26,
	WalkSpeed = 10,
	RunSpeed = 18,
	InterestTime = 1.5,
	HearingRadius = 125,
	Damage = 1,
	WaitTime = 1,
	LineOfSight = 0.4,
	KillRadius = 3.33,
	HitCooldown = 3,
	ChaseAbility = false,
	AbilityCooldown = 0,
	UseBehaviorTree = true,
	PatrolGroupTag = "BlottSiblings",
	StaresAtBlottHands = true,
	BlottHandStareDuration = 3,
	BlottHandStareCooldown = 25,
	BlottHandGlobalCooldown = 15,
	BlottHandStareDistance = 7,
	BlottHandGuardRadius = 150,
	BlottHandStareAnimation = "rbxassetid://0",
	HangsNearBlott = true,
	BlottIdleRadius = 30,
	BlottIdleFarTrigger = 60,
	BlottIdleCooldown = 8,
	CustomPatrol = function(p)
		return p.PatrolModule.buildHandStare(p) or p.PatrolModule.buildIdleNearBlott(p) or p.PatrolModule.buildGroupPatrol(p)
	end
}