local screenGui = Instance.new("ScreenGui")
screenGui.Name = "ScreenGui"
screenGui.ResetOnSpawn = false
screenGui.IgnoreGuiInset = true
local frame = Instance.new("Frame")
frame.Name = "Frame"
frame.BackgroundColor3 = Color3.new()
frame.BackgroundTransparency = 1
frame.BorderColor3 = Color3.new()
frame.BorderSizePixel = 0
frame.Size = UDim2.fromScale(1, 1)
local frame2 = Instance.new("Frame")
frame2.Name = "Frame"
frame2.BackgroundTransparency = 1
frame2.Size = UDim2.fromOffset(568, 546)
frame2.ZIndex = 5
local uIStroke = Instance.new("UIStroke")
uIStroke.Name = "UIStroke"
uIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
uIStroke.Thickness = 10000
uIStroke.Transparency = 0.1
uIStroke.Parent = frame2
local uICorner = Instance.new("UICorner")
uICorner.Name = "UICorner"
uICorner.BottomLeftRadius = UDim.new(1, 0)
uICorner.BottomRightRadius = UDim.new(1, 0)
uICorner.CornerRadius = UDim.new(1, 0)
uICorner.TopLeftRadius = UDim.new(1, 0)
uICorner.TopRightRadius = UDim.new(1, 0)
uICorner.Parent = frame2
frame2.Parent = frame
frame.Parent = screenGui
return screenGui