return function()
	local createElement = require(script.Parent.createElement)
	local createReconciler = require(script.Parent.createReconciler)
	local Logging = require(script.Parent.Logging)
	local NoopRenderer = require(script.Parent.NoopRenderer)
	local createReconcilerCompat = require(script.Parent.createReconcilerCompat)
	local reconciler = createReconciler(NoopRenderer)
	local reconcilerCompat = createReconcilerCompat(reconciler)
	it("reify should only warn once per call site", function()
		local capture = Logging.capture(function()
			local reify = reconcilerCompat.reify(createElement("StringValue"))
			reconciler.unmountVirtualTree(reify)
			local reify2 = reconcilerCompat.reify(createElement("StringValue"))
			reconciler.unmountVirtualTree(reify2)
		end)
		expect(#capture.warnings).to.equal(1)
		expect(capture.warnings[1]:find("reify")).to.be.ok()
		local capture2 = Logging.capture(function()
			local reify = reconcilerCompat.reify(createElement("StringValue"))
			reconciler.unmountVirtualTree(reify)
		end)
		expect(#capture2.warnings).to.equal(1)
		expect(capture2.warnings[1]:find("reify")).to.be.ok()
	end)
	it("teardown should only warn once per call site", function()
		local capture = Logging.capture(function()
			local v = reconciler.mountVirtualTree(createElement("StringValue"))
			reconcilerCompat.teardown(v)
			local v2 = reconciler.mountVirtualTree(createElement("StringValue"))
			reconcilerCompat.teardown(v2)
		end)
		expect(#capture.warnings).to.equal(1)
		expect(capture.warnings[1]:find("teardown")).to.be.ok()
		local capture2 = Logging.capture(function()
			local v = reconciler.mountVirtualTree(createElement("StringValue"))
			reconcilerCompat.teardown(v)
		end)
		expect(#capture2.warnings).to.equal(1)
		expect(capture2.warnings[1]:find("teardown")).to.be.ok()
	end)
	it("update should only warn once per call site", function()
		local capture = Logging.capture(function()
			for _ = 1, 2 do
				local v = reconciler.mountVirtualTree(createElement("StringValue"))
				reconcilerCompat.reconcile(v, createElement("StringValue"))
				reconciler.unmountVirtualTree(v)
			end
		end)
		expect(#capture.warnings).to.equal(1)
		expect(capture.warnings[1]:find("reconcile")).to.be.ok()
		local capture2 = Logging.capture(function()
			local v = reconciler.mountVirtualTree(createElement("StringValue"))
			reconcilerCompat.reconcile(v, createElement("StringValue"))
			reconciler.unmountVirtualTree(v)
		end)
		expect(#capture2.warnings).to.equal(1)
		expect(capture2.warnings[1]:find("reconcile")).to.be.ok()
	end)
end