local createVector = vector.create
return {
	MIN_HOLD_DUR = 0.35,
	RELEASE_DUR = 2.64,
	HOLD_NR_DUR = 0.42,
	HOLD_ANIM_SPEED = 2,
	RELEASE_ANIM_SKIP_TO = 0.77,
	HITBOX_ONE_SIZE = createVector(32, 40, 32),
	HITBOX_ONE_OFFSET = CFrame.new(-0.5, -2.8, 0.5),
	HITBOX_ONE_DAMAGE = 12,
	HITBOX_ONE_STUN = 1.7,
	HITBOX_ONE_RAGDOLL = 1.7,
	HITBOX_ONE_PULL_DUR = 1.7,
	HITBOX_TWO_DELAY = 1.5,
	HITBOX_TWO_SIZE = createVector(40, 50, 40),
	HITBOX_TWO_OFFSET = CFrame.new(-0.5, -2.8, 0.5),
	HITBOX_TWO_DAMAGE = 15,
	HITBOX_TWO_STUN = 1.7,
	HITBOX_TWO_RAGDOLL = 1.7,
	HITBOX_TWO_KNOCKBACK = 40,
	HITBOX_TWO_KNOCKUP = 15,
	BLOCK_DAMAGE = 3
}