local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Net = require(ReplicatedStorage.Modules.Net)
local MapTransitionEffect = require(ReplicatedStorage.Controllers.MapServices.Transitions.MapTransitionEffect)
local Sound = require(ReplicatedStorage.Util.Sound)
Net:RemoteEvent("FishmenCaveEntry").OnClientEvent:Connect(function()
	Sound:Play("UnderwaterCityBonusMoments.Bubble_Teleport_Whirlpool_Cutscene_01")
	MapTransitionEffect.Play()
	task.delay(1.75, MapTransitionEffect.StopEarly)
end)