local Util = require(game.ReplicatedStorage.Util)
local sound = Util.Sound
game.ReplicatedStorage:WaitForChild("Remotes"):WaitForChild("Leviathan").OnClientEvent:Connect(function(p)
	if p == "Appear" then
		task.spawn(function()
			local v = sound:Play("WaterLoop", nil, 1700, 0.7)
			local v2 = sound:Play("SmokeFlightLoop", nil, 1700, 0.4)
			wait(1.2)
			sound:Play("WaterSplash3_22", nil, 1700, 1)
			wait(1.2)
			sound:Play("WaterSplash3_22", nil, 1700, 1)
			wait(2)
			sound:Play("WaterSplash3_22", nil, 1700, 1)
			wait(1.6)
			sound:Play("CLaunch__9985086322", workspace.CurrentCamera.CFrame, 1700, 0.2)
			sound:Play("BreathIn", workspace.CurrentCamera.CFrame, 1700, 0.5)
			sound:Kill(v)
			sound:Kill(v2)
		end)
		local Intro = require(script.Intro)
		local intro = Intro()
		intro:Play()
		wait(14)
		intro:Destroy()
	end
end)