local UserInputService = game:GetService("UserInputService")
return function(studsOffset: Vector3, onActivated, p)
	local billboardGui = Instance.new("BillboardGui")
	billboardGui.Name = "InteractionUI"
	billboardGui.MaxDistance = 200
	billboardGui.Size = UDim2.fromScale(3, 0.7)
	billboardGui.StudsOffset = studsOffset
	billboardGui.ResetOnSpawn = false
	billboardGui.Active = true
	billboardGui.ClipsDescendants = false
	local textButton = Instance.new("TextButton")
	textButton.Name = "Button"
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.BackgroundTransparency = 1
	textButton.Text = ""
	textButton.Parent = billboardGui
	textButton.Activated:Connect(onActivated)
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "NameOfEvent"
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/Nunito.json")
	textLabel.Size = UDim2.fromScale(1, 1)
	textLabel.Text = "Register"
	textLabel.TextColor3 = Color3.new()
	textLabel.TextScaled = true
	textLabel.ZIndex = 2
	textLabel.Parent = billboardGui
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "ImageLabel"
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxasset://textures/ui/ImageSet/AE/img_set_1x_2.png"
	imageLabel.ImageRectOffset = Vector2.new(0, 25)
	imageLabel.ImageRectSize = Vector2.new(24, 24)
	imageLabel.Position = UDim2.fromScale(-0.2, -0.1)
	imageLabel.ScaleType = Enum.ScaleType.Slice
	imageLabel.Size = UDim2.fromScale(1.4, 1.2)
	imageLabel.SliceCenter = Rect.new(12, 12, 12, 12)
	imageLabel.Parent = textLabel
	local imageLabel2 = Instance.new("ImageLabel")
	imageLabel2.Name = "Selected"
	imageLabel2.BackgroundTransparency = 1
	imageLabel2.Image = "rbxasset://textures/ui/ImageSet/AE/img_set_1x_2.png"
	imageLabel2.ImageRectOffset = Vector2.new(0, 1)
	imageLabel2.ImageRectSize = Vector2.new(24, 23)
	imageLabel2.ScaleType = Enum.ScaleType.Slice
	imageLabel2.Size = UDim2.fromScale(1, 1)
	imageLabel2.SliceCenter = Rect.new(12, 12, 12, 12)
	imageLabel2.ZIndex = 2
	imageLabel2.Parent = imageLabel
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Name = "Hotkey"
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new("rbxasset://fonts/families/Nunito.json")
	textLabel2.Position = UDim2.fromScale(0.6, 0.05)
	textLabel2.Size = UDim2.fromScale(0.6, 0.55)
	textLabel2.Text = UserInputService:GetStringForKeyCode(p)
	textLabel2.TextColor3 = Color3.new()
	textLabel2.TextScaled = true
	textLabel2.ZIndex = 2
	textLabel2.Parent = imageLabel2
	return billboardGui, textLabel, textLabel2
end