return table.freeze({
	ANALYTICS_IDLE_THRESHOLD_SECONDS = 60,
	TELEPORT_IDLE_THRESHOLD_SECONDS = 1020,
	CLIENT_FALLBACK_IDLE_THRESHOLD_SECONDS = 1110,
	SERVER_MIN_OBSERVED_IDLE_SECONDS = 945,
	IDLE_POLL_INTERVAL_SECONDS = 1,
	TELEPORT_REQUEST_RETRY_INTERVAL_SECONDS = 45,
	SERVER_TELEPORT_SPACING_SECONDS = 1,
	RESTORE_READY_TIMEOUT_SECONDS = 30,
	RESTORE_SETTLE_SECONDS = 0.35,
	RESTORE_SPAWN_CONFIRM_DISTANCE = 25,
	TELEPORT_ATTEMPTS = 2,
	TELEPORT_RETRY_DELAY_SECONDS = 1,
	TELEPORT_DATA_KEY = "AfkRestore"
})