return {
	GUARD_COLLISION_GROUP = "Guards",
	PLAYER_COLLISION_GROUP = "Players",
	LUCKY_BLOCK_COLLISION_GROUP = "LuckyBlocks",
	FOLLOW_ASSET_COLLISION_GROUP = "FollowAssets",
	GUARDS_NO_COLLIDE_COLLISION_GROUP = "GuardsNoCollide",
	CARRIED_EGG_COLLISION_GROUP = "CarriedEggs",
	FUSE_SHRINE_GATE_COLLISION_GROUP = "FuseShrineGate"
}