return {
	WINDUP = 0.3,
	HITBOX_SIZE = vector.create(60, 60, 60),
	DAMAGE = 60,
	BLOCK_BREAK = 5,
	IMPACT_STUN = 2,
	KNOCKBACK = 42,
	KNOCKUP = 22,
	KNOCKBACK_DURATION = 0.3,
	BURN_VALUE = "Flame Tick",
	BURN_DURATION = 5,
	SELF_DAMAGE_SHARE = 0.1,
	SELF_KNOCKBACK_MIN = 18,
	SELF_KNOCKBACK_MAX = 34,
	SELF_KNOCKUP_MIN = 24,
	SELF_KNOCKUP_MAX = 44
}