local createVector = vector.create
local Config = {
	STARTUP_AT = 0.56,
	SLASH_2_DELAY = 0.5,
	IMPACT_DELAY = 1,
	RECOVERY_DUR = 0.3,
	MOUSE_RANGE = 500,
	DRIFT_SPEED = 15,
	SLASH_DAMAGE = 5,
	SLASH_STUN = 2,
	SLASH_KNOCKBACK = 15,
	SLASH_KNOCKBACK_DURATION = 2,
	SLASH_BLOCK_BREAK = 2,
	SLASH_BLOCK_KNOCKBACK = 10,
	SLASH_HITBOX_SIZE = createVector(35, 12, 35)
}
Config.SLASH_HITBOX_OFFSET = CFrame.new(0, Config.SLASH_HITBOX_SIZE.Y / 2 - 3, -5)
Config.IMPACT_DAMAGE = 15
Config.IMPACT_STUN = 1.5
Config.IMPACT_RAGDOLL = 1.5
Config.IMPACT_KNOCKBACK = 40
Config.IMPACT_KNOCKUP = 15
Config.IMPACT_BLOCK_BREAK = 2
Config.IMPACT_BLOCK_KNOCKBACK = 10
Config.IMPACT_HITBOX_SIZE = createVector(35, 20, 35)
Config.IMPACT_HITBOX_OFFSET = CFrame.new(0, Config.IMPACT_HITBOX_SIZE.Y / 2 - 3, -10)
Config.RANKED_STUN_CUT = 0.3
return Config