local createVector = vector.create
return {
	MOUSE_RANGE = 80,
	STEER_RESPONSIVENESS = 40,
	DASH_SPEED = 45,
	DASH_REDUCED_SPEED = 10,
	SLOWDOWN_TIME = 0.75,
	MAX_DASH_DURATION = 3,
	CONTACT_CHECK_OFFSET = CFrame.new(0, 0, -7),
	CONTACT_CHECK_SIZE = createVector(8, 8, 15),
	DASH_HITBOX_OFFSET = CFrame.new(0, 0, -3),
	DASH_HITBOX_SIZE = createVector(9, 9, 12),
	DASH_HIT_INTERVAL = 0.1,
	VICTIM_HIT_COOLDOWN = 0.3,
	DASH_DAMAGE = 4.2,
	DASH_STUN = 0.5,
	DASH_BLOCK_BREAK = 0.675,
	DASH_KNOCKBACK = 2,
	DASH_UPWARD = 1
}