local GuiService = game:GetService("GuiService")
local screenGui = Instance.new("ScreenGui")
screenGui.Enabled = true
screenGui.DisplayOrder = 0
screenGui.IgnoreGuiInset = false
screenGui.ScreenInsets = Enum.ScreenInsets.TopbarSafeInsets
screenGui.ResetOnSpawn = false
screenGui.Name = "TopbarPlus"
local folder = Instance.new("Folder")
folder.Name = "ActiveItems"
folder.Parent = screenGui
local frame = Instance.new("Frame")
frame.BackgroundTransparency = 1
frame.Name = "TopbarContainer"
frame.Position = UDim2.new(0, 0, 0, 0)
frame.Size = UDim2.new(1, 0, 0, 36)
frame.Visible = true
frame.ZIndex = 1
frame.Parent = screenGui
frame.Active = false
GuiService:GetPropertyChangedSignal("TopbarInset"):Connect(function()
	local height = GuiService.TopbarInset.Height
	frame.Position = UDim2.new(0, 0, 0, height - 50)
end)
local height = GuiService.TopbarInset.Height
frame.Position = UDim2.new(0, 0, 0, height - 50)
local frame2 = Instance.new("Frame")
frame2.BackgroundTransparency = 1
frame2.Name = "IconContainer"
frame2.Position = UDim2.new(0, 104, 0, 4)
frame2.Visible = false
frame2.ZIndex = 1
frame2.Parent = frame
frame2.Active = false
local textButton = Instance.new("TextButton")
textButton.Name = "IconButton"
textButton.Visible = true
textButton.Text = ""
textButton.ZIndex = 10
textButton.BorderSizePixel = 0
textButton.AutoButtonColor = false
textButton.Parent = frame2
textButton.Active = true
textButton.TextTransparency = 1
textButton.RichText = true
local imageLabel = Instance.new("ImageLabel")
imageLabel.BackgroundTransparency = 1
imageLabel.Name = "IconImage"
imageLabel.AnchorPoint = Vector2.new(0, 0.5)
imageLabel.Visible = true
imageLabel.ZIndex = 11
imageLabel.ScaleType = Enum.ScaleType.Fit
imageLabel.Parent = textButton
imageLabel.Active = false
local textLabel = Instance.new("TextLabel")
textLabel.BackgroundTransparency = 1
textLabel.Name = "IconLabel"
textLabel.AnchorPoint = Vector2.new(0, 0.5)
textLabel.Position = UDim2.new(0.5, 0, 0.5, 0)
textLabel.Text = ""
textLabel.RichText = true
textLabel.TextScaled = false
textLabel.ClipsDescendants = true
textLabel.ZIndex = 11
textLabel.Active = false
textLabel.AutoLocalize = true
textLabel.Parent = textButton
local clone = textLabel:Clone()
clone.Name = "FakeIconLabel"
clone.AnchorPoint = Vector2.new(0, 0)
clone.Position = UDim2.new(0, 0, 0, 0)
clone.Size = UDim2.new(1, 0, 1, 0)
clone.TextTransparency = 1
clone.AutoLocalize = false
clone.Parent = textLabel.Parent
local uIGradient = Instance.new("UIGradient")
uIGradient.Name = "IconGradient"
uIGradient.Enabled = true
uIGradient.Parent = textButton
local uICorner = Instance.new("UICorner")
uICorner.Name = "IconCorner"
uICorner.Parent = textButton
local frame3 = Instance.new("Frame")
frame3.Name = "IconOverlay"
frame3.BackgroundTransparency = 1
frame3.Position = textButton.Position
frame3.Size = UDim2.new(1, 0, 1, 0)
frame3.Visible = true
frame3.ZIndex = textButton.ZIndex + 1
frame3.BorderSizePixel = 0
frame3.Parent = frame2
frame3.Active = false
local clone2 = uICorner:Clone()
clone2.Name = "IconOverlayCorner"
clone2.Parent = frame3
local imageLabel2 = Instance.new("ImageLabel")
imageLabel2.BackgroundTransparency = 1
imageLabel2.Name = "NoticeFrame"
imageLabel2.Position = UDim2.new(0.45, 0, 0, -2)
imageLabel2.Size = UDim2.new(1, 0, 0.7, 0)
imageLabel2.Visible = true
imageLabel2.ZIndex = 12
imageLabel2.ImageTransparency = 1
imageLabel2.ScaleType = Enum.ScaleType.Fit
imageLabel2.Parent = textButton
imageLabel2.Active = false
local textLabel2 = Instance.new("TextLabel")
textLabel2.Name = "NoticeLabel"
textLabel2.BackgroundTransparency = 1
textLabel2.Position = UDim2.new(0.25, 0, 0.15, 0)
textLabel2.Size = UDim2.new(0.5, 0, 0.7, 0)
textLabel2.Visible = true
textLabel2.ZIndex = 13
textLabel2.Font = Enum.Font.Arial
textLabel2.Text = "0"
textLabel2.TextTransparency = 1
textLabel2.TextScaled = true
textLabel2.Parent = imageLabel2
textLabel2.Active = false
local frame4 = Instance.new("Frame")
frame4.Name = "CaptionContainer"
frame4.BackgroundTransparency = 1
frame4.AnchorPoint = Vector2.new(0, 0)
frame4.ClipsDescendants = true
frame4.ZIndex = 30
frame4.Visible = true
frame4.Parent = frame2
frame4.Active = false
local frame5 = Instance.new("Frame")
frame5.Name = "CaptionFrame"
frame5.BorderSizePixel = 0
frame5.AnchorPoint = Vector2.new(0.5, 0.5)
frame5.Position = UDim2.new(0.5, 0, 0.5, 0)
frame5.Size = UDim2.new(1, 0, 1, 0)
frame5.ZIndex = 31
frame5.Parent = frame4
frame5.Active = false
local textLabel3 = Instance.new("TextLabel")
textLabel3.Name = "CaptionLabel"
textLabel3.BackgroundTransparency = 1
textLabel3.AnchorPoint = Vector2.new(0.5, 0.5)
textLabel3.Position = UDim2.new(0.5, 0, 0.56, 0)
textLabel3.TextXAlignment = Enum.TextXAlignment.Center
textLabel3.RichText = true
textLabel3.ZIndex = 32
textLabel3.Parent = frame4
textLabel3.Active = false
local uICorner2 = Instance.new("UICorner")
uICorner2.Name = "CaptionCorner"
uICorner2.Parent = frame5
local frame6 = Instance.new("Frame")
frame6.Name = "CaptionOverlineContainer"
frame6.BackgroundTransparency = 1
frame6.AnchorPoint = Vector2.new(0.5, 0.5)
frame6.Position = UDim2.new(0.5, 0, -0.5, 3)
frame6.Size = UDim2.new(1, 0, 1, 0)
frame6.ZIndex = 33
frame6.ClipsDescendants = true
frame6.Parent = frame4
frame6.Active = false
local frame7 = Instance.new("Frame")
frame7.Name = "CaptionOverline"
frame7.AnchorPoint = Vector2.new(0.5, 0.5)
frame7.Position = UDim2.new(0.5, 0, 1.5, -3)
frame7.Size = UDim2.new(1, 0, 1, 0)
frame7.ZIndex = 34
frame7.Parent = frame6
frame7.Active = false
local clone3 = uICorner2:Clone()
clone3.Name = "CaptionOverlineCorner"
clone3.Parent = frame7
local clone4 = frame5:Clone()
clone4.Name = "CaptionVisibilityBlocker"
clone4.BackgroundTransparency = 1
clone4.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
clone4.ZIndex -= 1
clone4.Parent = frame5
clone4.Active = false
clone4.CaptionCorner.Name = "CaptionVisibilityCorner"
local frame8 = Instance.new("Frame")
frame8.Name = "TipFrame"
frame8.BorderSizePixel = 0
frame8.AnchorPoint = Vector2.new(0, 0)
frame8.Position = UDim2.new(0, 50, 0, 50)
frame8.Size = UDim2.new(1, 0, 1, -8)
frame8.ZIndex = 40
frame8.Parent = frame2
frame8.Active = false
local uICorner3 = Instance.new("UICorner")
uICorner3.Name = "TipCorner"
uICorner3.CornerRadius = UDim.new(0.25, 0)
uICorner3.Parent = frame8
local textLabel4 = Instance.new("TextLabel")
textLabel4.Name = "TipLabel"
textLabel4.BackgroundTransparency = 1
textLabel4.TextScaled = false
textLabel4.TextSize = 12
textLabel4.Position = UDim2.new(0, 3, 0, 3)
textLabel4.Size = UDim2.new(1, -6, 1, -6)
textLabel4.ZIndex = 41
textLabel4.RichText = true
textLabel4.Parent = frame8
textLabel4.Active = false
local frame9 = Instance.new("Frame")
frame9.Name = "DropdownContainer"
frame9.BackgroundTransparency = 1
frame9.BorderSizePixel = 0
frame9.AnchorPoint = Vector2.new(0.5, 0)
frame9.ZIndex = -2
frame9.ClipsDescendants = true
frame9.Visible = true
frame9.Parent = frame2
frame9.Selectable = false
frame9.Active = false
local scrollingFrame = Instance.new("ScrollingFrame")
scrollingFrame.Name = "DropdownFrame"
scrollingFrame.BackgroundTransparency = 1
scrollingFrame.BorderSizePixel = 0
scrollingFrame.AnchorPoint = Vector2.new(0.5, 0)
scrollingFrame.Position = UDim2.new(0.5, 0, 0, 0)
scrollingFrame.Size = UDim2.new(0.5, 2, 1, 0)
scrollingFrame.ZIndex = -1
scrollingFrame.ClipsDescendants = false
scrollingFrame.Visible = true
scrollingFrame.TopImage = scrollingFrame.MidImage
scrollingFrame.BottomImage = scrollingFrame.MidImage
scrollingFrame.VerticalScrollBarInset = Enum.ScrollBarInset.Always
scrollingFrame.VerticalScrollBarPosition = Enum.VerticalScrollBarPosition.Right
scrollingFrame.Parent = frame9
scrollingFrame.Active = false
scrollingFrame.Selectable = false
scrollingFrame.ScrollingEnabled = false
local uIListLayout = Instance.new("UIListLayout")
uIListLayout.Name = "DropdownList"
uIListLayout.FillDirection = Enum.FillDirection.Vertical
uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout.Parent = scrollingFrame
local uIPadding = Instance.new("UIPadding")
uIPadding.Name = "DropdownPadding"
uIPadding.PaddingRight = UDim.new(0, 2)
uIPadding.Parent = scrollingFrame
local frame10 = Instance.new("Frame")
frame10.Name = "MenuContainer"
frame10.BackgroundTransparency = 1
frame10.BorderSizePixel = 0
frame10.AnchorPoint = Vector2.new(1, 0)
frame10.Size = UDim2.new(0, 500, 0, 50)
frame10.ZIndex = -2
frame10.ClipsDescendants = true
frame10.Visible = true
frame10.Parent = frame2
frame10.Active = false
frame10.Selectable = false
local scrollingFrame2 = Instance.new("ScrollingFrame")
scrollingFrame2.Name = "MenuFrame"
scrollingFrame2.BackgroundTransparency = 1
scrollingFrame2.BorderSizePixel = 0
scrollingFrame2.AnchorPoint = Vector2.new(0, 0)
scrollingFrame2.Position = UDim2.new(0, 0, 0, 0)
scrollingFrame2.Size = UDim2.new(1, 0, 1, 0)
scrollingFrame2.ZIndex = 9
scrollingFrame2.ClipsDescendants = false
scrollingFrame2.Visible = true
scrollingFrame2.TopImage = ""
scrollingFrame2.BottomImage = ""
scrollingFrame2.HorizontalScrollBarInset = Enum.ScrollBarInset.Always
scrollingFrame2.CanvasSize = UDim2.new(0, 0, 0, 0)
scrollingFrame2.Parent = frame10
scrollingFrame2.Active = false
scrollingFrame2.Selectable = false
scrollingFrame2.ScrollingEnabled = false
local uIListLayout2 = Instance.new("UIListLayout")
uIListLayout2.Name = "MenuList"
uIListLayout2.FillDirection = Enum.FillDirection.Horizontal
uIListLayout2.HorizontalAlignment = Enum.HorizontalAlignment.Right
uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout2.Parent = scrollingFrame2
local frame11 = Instance.new("Frame")
frame11.Name = "MenuInvisBlocker"
frame11.BackgroundTransparency = 1
frame11.Size = UDim2.new(0, -2, 1, 0)
frame11.Visible = true
frame11.LayoutOrder = 999999999
frame11.Parent = scrollingFrame2
frame11.Active = false
local sound = Instance.new("Sound")
sound.Name = "ClickSound"
sound.Volume = 0
sound.Parent = frame2
local imageLabel3 = Instance.new("ImageLabel")
imageLabel3.Name = "Indicator"
imageLabel3.BackgroundTransparency = 1
imageLabel3.Image = "rbxassetid://5278151556"
imageLabel3.Size = UDim2.new(0, 32, 0, 32)
imageLabel3.AnchorPoint = Vector2.new(0.5, 0)
imageLabel3.Position = UDim2.new(0.5, 0, 0, 5)
imageLabel3.ScaleType = Enum.ScaleType.Fit
imageLabel3.Visible = false
imageLabel3.Active = true
imageLabel3.Parent = screenGui
imageLabel3.Active = false
local Players = game:GetService("Players")
screenGui.Parent = Players.LocalPlayer.PlayerGui
return screenGui