local PianoController = require(script.Parent:WaitForChild("PianoController"))
local pianoGui = script.Parent:WaitForChild("PianoGui")
local mobilePianoGui = script.Parent:WaitForChild("MobilePianoGui")
local soundFontGui = script.Parent:WaitForChild("SoundFontGui")
local promptGui = script.Parent:WaitForChild("PromptGui")
local settingsGui = script.Parent:WaitForChild("SettingsGui")
local GuiModule = require(pianoGui:WaitForChild("GuiModule"))
local GuiModule2 = require(mobilePianoGui:WaitForChild("GuiModule"))
local GuiModule3 = require(soundFontGui:WaitForChild("GuiModule"))
local GuiModule4 = require(promptGui:WaitForChild("GuiModule"))
local GuiModule5 = require(settingsGui:WaitForChild("GuiModule"))
PianoController:Init()
GuiModule:Init()
GuiModule2:Init()
GuiModule3:Init()
GuiModule4:Init()
GuiModule5:Init()
task.spawn(function()
	PianoController:Start()
end)
task.spawn(function()
	GuiModule:Start()
end)
task.spawn(function()
	GuiModule2:Start()
end)
task.spawn(function()
	GuiModule3:Start()
end)
task.spawn(function()
	GuiModule4:Start()
end)
task.spawn(function()
	GuiModule5:Start()
end)
PianoController.Activated:ConnectOnce(function()
	local UserInputService = game:GetService("UserInputService")

	if not UserInputService.KeyboardEnabled then
		GuiModule4:ToggleEnabled(true)
	end
end)