local Players = game:GetService("Players")
local ButtonEffect = require(Players.LocalPlayer.PlayerScripts.Modules:WaitForChild("ButtonEffect"))
local PromptSystem = require(Players.LocalPlayer.PlayerScripts.Modules:WaitForChild("PromptSystem"))
local Page = require(Players.LocalPlayer.PlayerScripts.Modules:WaitForChild("Page"))
local ParticipationPrize = require(script:WaitForChild("ParticipationPrize"))
local GloryPayout = require(script:WaitForChild("GloryPayout"))
local ELOShield = require(script:WaitForChild("ELOShield"))
local TopReward = require(script:WaitForChild("TopReward"))
local Countdown = require(script:WaitForChild("Countdown"))
local Locked = require(script:WaitForChild("Locked"))
local Header = require(script:WaitForChild("Header"))
local Queues = require(script:WaitForChild("Queues"))
local Rank = require(script:WaitForChild("Rank"))
local object = setmetatable({}, Page)
object.__index = object

function object._new()
	local self = setmetatable(Page.new(script.Name), object)
	self.PromptsFrame = self.PageFrame:WaitForChild("Prompts")
	self.UnlockedFrame = self.PageFrame:WaitForChild("Unlocked")
	self.CloseButton = self.UnlockedFrame:WaitForChild("Close")
	self.List = self.UnlockedFrame:WaitForChild("List")
	self.Container = self.List:WaitForChild("Container")
	self.Layout = self.Container:WaitForChild("Layout")
	self.PromptSystem = PromptSystem.new(self.PromptsFrame)
	self.ParticipationPrize = ParticipationPrize.new(self)
	self.GloryPayout = GloryPayout.new(self)
	self.ELOShield = ELOShield.new(self)
	self.TopReward = TopReward.new(self)
	self.Countdown = Countdown.new(self)
	self.Locked = Locked.new(self)
	self.Header = Header.new(self)
	self.Queues = Queues.new(self)
	self.Rank = Rank.new(self)
	self:_Init()
	return self
end

function object:CloseRequest()
	self.OpenPage:Fire("Matchmaking")
end

function object.Open(data, ...)
	Page.Open(data, ...)
	data.ParticipationPrize:Open()
	data.GloryPayout:Open()
	data.ELOShield:Open()
	data.TopReward:Open()
	data.Countdown:Open()
	data.Locked:Open()
	data.Header:Open()
	data.Queues:Open()
	data.Rank:Open()
end

function object.Close(data, ...)
	data.ParticipationPrize:Close()
	data.GloryPayout:Close()
	data.TopReward:Close()
	data.ELOShield:Close()
	data.Countdown:Close()
	data.Locked:Close()
	data.Header:Close()
	data.Queues:Close()
	data.Rank:Close()
	Page.Close(data, ...)
end

function object:_UpdateList()
	self.CloseButton.Position = UDim2.new(0.975, 0, 0.0225, self.PageFrame.AbsoluteSize.Y * 0.125)
	self.List.Position = UDim2.new(0.5, 9, 0, self.PageFrame.AbsoluteSize.Y * 0.125)
	self.List.Size = UDim2.new(0.85, 0, 0, self.PageFrame.AbsoluteSize.Y * 0.75)
	self.List.CanvasSize = UDim2.new(0, 0, 0, self.Layout.AbsoluteContentSize.Y)
end

function object:_Init()
	self.CloseButton.MouseButton1Click:Connect(function()
		self:CloseRequest()
	end)
	self.Layout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
		self:_UpdateList()
	end)
	self.PageFrame:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		self:_UpdateList()
	end)
	self:_UpdateList()
	ButtonEffect:Add(self.CloseButton)
end

return object._new()