local createVector = vector.create
return {
	MAX_FRENZY_DURATION = 2.6,
	WALK_SPEED = 6,
	LOOP_FRAMES = 78,
	SHOT_FRAMES = {
		0,
		8,
		19,
		28,
		37,
		47,
		58,
		66
	},
	BURST_DAMAGE = 1,
	BURST_STUN = 1.3,
	BURST_KNOCKUP = 0.5,
	BURST_BLOCK_BREAK = 0.5,
	BURST_HITBOX_SIZE = createVector(17, 15, 17),
	FLIP_BACK_SPEED = 70,
	FLIP_BACK_DURATION = 0.3,
	EXPLOSION_DAMAGE = 18,
	EXPLOSION_STUN = 1.6,
	EXPLOSION_KNOCKBACK = 30,
	EXPLOSION_UPWARD = 10,
	EXPLOSION_BLOCK_BREAK = 2,
	EXPLOSION_HITBOX_SIZE = createVector(27, 45, 27),
	EXPLOSION_HITBOX_RAISE = 17.5
}