local ReplicatedStorage = game:GetService("ReplicatedStorage")
local PlaySound = require(ReplicatedStorage:WaitForChild("ModuleScript"):WaitForChild("PlaySound"))
script.Parent.MouseClick:Connect(function(_)
	PlaySound.PlaySound(game.Players.LocalPlayer, game.ReplicatedStorage.Sound_Effect.Meow)
end)