return {
	MAX_DURATION = 2.5,
	WINDUP = 0.3,
	SWEEP_AT = 0.5,
	STARTUP_BLOCK = 1.5,
	SNAP_AT = 0.4,
	THROW_AT = 1.55,
	GRAB_HITBOX_SIZE = vector.create(15, 10, 16),
	GRAB_HITBOX_OFFSET = CFrame.new(0, 0, -2),
	GRAB_VICTIM_OFFSET = CFrame.new(),
	GRAB_WALL_CLEARANCE = 7,
	SNAP_DAMAGE = 10,
	SLAM_DAMAGE = 18,
	SLAM_STUN = 1.6,
	SLAM_KNOCKBACK = 50,
	SNAP_BLOCK_BREAK = 2,
	SLAM_BLOCK_BREAK = 3
}