return {
	MOUSE_RANGE = 500,
	MAX_DISTANCE = 40,
	TELEPORT_WALL_OFFSET = 2.5,
	ANIM_FREEZE_AT = 0.2,
	BLINK_DELAY = 0.1,
	ENDLAG = 0.5,
	DASH_DAMAGE = 15,
	DASH_STUN = 1,
	DASH_KNOCKUP = 1,
	DASH_KNOCKBACK_DURATION = 1,
	DASH_BLOCK_BREAK = 3,
	DASH_HITBOX_WIDTH = 12,
	DASH_HITBOX_HEIGHT = 12
}