require(script.Parent.Types)
local Config = {
	DEFAULT_TRACKER_ID = "__default",
	BASE_TRACKER_SIZE = Vector2.new(60, 80),
	MIN_TRACKER_SCALE = 1.2,
	MAX_TRACKER_SCALE = 1.5,
	MAX_TRACKER_SPRING_SCALE = 1.55,
	CENTER_POP_RADIUS_SCREEN_WIDTH = 0.25,
	SCREEN_EDGE_PADDING = 8,
	EDGE_INDICATOR_SIZE = 36,
	EDGE_INDICATOR_ARROW_SIZE = Vector2.new(18, 16),
	EDGE_INDICATOR_ARROW_ORBIT_RADIUS = 34,
	TOP_VISUAL_EXTENT = 0.9,
	BOTTOM_VISUAL_EXTENT = 0.5,
	OFF_SCREEN_REST_Y_SCALE = 0.6,
	OFF_SCREEN_TRACKER_SCALE_MULTIPLIER = 0.85,
	SIDE_COMPASS_TRACKER_Y_OFFSET_SCALE = 1,
	SCALE_SPRING_STIFFNESS = 130,
	SCALE_SPRING_DAMPING = 13,
	MAX_PROJECTION_DELTA_TIME = 0.03333333333333333
}
Config.MIN_TRACKER_SPRING_SCALE = Config.MIN_TRACKER_SCALE * Config.OFF_SCREEN_TRACKER_SCALE_MULTIPLIER
Config.DEFAULT_EDGE_INDICATOR_OUTLINE_COLOR = Color3.new(1, 1, 1)
Config.DEFAULT_DESTROY_ON_APPROACH_DISTANCE = 5
Config.VIEWPORT_FRAME_SIZE = UDim2.fromScale(1, 0.9)
Config.ICON_BACKGROUND_IMAGE_OFFSET = UDim2.fromScale(0.15, -0.15)
Config.ICON_BACKGROUND_VIEWPORT_SIZE = UDim2.fromScale(0.85, 0.75)
Config.DEFAULT_ALERT_ICON_SETTINGS = {
	MaxDistance = 20,
	Icon = nil,
	Sprite = nil,
	Color = Color3.fromRGB(247, 239, 25),
	BackgroundColor = Color3.fromRGB(23, 23, 23),
	ImageColor = Color3.new(1, 1, 1),
	BorderColor = Color3.new()
}
Config.DEFAULT_ICON_SETTINGS = {
	CustomIcon = nil,
	Sprite = nil,
	ShowIsland = true
}
Config.DEFAULT_VIEWPORT_SETTINGS = {
	MinDistance = 20,
	Model = nil,
	UseIconAsBackground = true
}
return Config