local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage.Data.CashPacks)
require(ReplicatedStorage.Shared.Types.AssetItem)
require(ReplicatedStorage.Shared.Types.BanjoCricket)
require(ReplicatedStorage.Shared.Types.BossMastery)
require(ReplicatedStorage.Shared.Types.Eggs)
require(ReplicatedStorage.Shared.Types.FuseMachine)
require(ReplicatedStorage.Shared.Types.GuardTutorial)
require(ReplicatedStorage.Shared.Types.MonsterParasite)
require(ReplicatedStorage.Shared.Types.OnboardingQuestline)
require(ReplicatedStorage.Shared.Types.Rift)
require(ReplicatedStorage.Shared.Types.Sakura)
require(ReplicatedStorage.Shared.Types.ShrineFusion)
require(ReplicatedStorage.Shared.Types.Scramble)
require(ReplicatedStorage.Shared.Types.ScrambleFinalHits)
return {}