local ReplicatedStorage = game:GetService("ReplicatedStorage")
local AssetItem = require(ReplicatedStorage.Shared.Types.AssetItem)
local BanjoCricket = require(ReplicatedStorage.Shared.Types.BanjoCricket)
local BossMastery = require(ReplicatedStorage.Shared.Types.BossMastery)
local Eggs = require(ReplicatedStorage.Shared.Types.Eggs)
local FuseMachine = require(ReplicatedStorage.Shared.Types.FuseMachine)
local GuardTutorial = require(ReplicatedStorage.Shared.Types.GuardTutorial)
local MonsterParasite = require(ReplicatedStorage.Shared.Types.MonsterParasite)
local OnboardingQuestline = require(ReplicatedStorage.Shared.Types.OnboardingQuestline)
local Rift = require(ReplicatedStorage.Shared.Types.Rift)
local Sakura = require(ReplicatedStorage.Shared.Types.Sakura)
local ShrineFusion = require(ReplicatedStorage.Shared.Types.ShrineFusion)
local t = require(ReplicatedStorage.Packages.t)
local Scramble = require(ReplicatedStorage.Shared.Types.Scramble)
local SchemaFields = {
	Scramble = Scramble.State
}
local ScrambleFinalHits = require(ReplicatedStorage.Shared.Types.ScrambleFinalHits)
SchemaFields.ScrambleFinalHits = ScrambleFinalHits.State
SchemaFields.MechaScramblerObtained = t.boolean
SchemaFields.Money = t.number
SchemaFields.PeakBaseRate = t.number
SchemaFields.CashPackQuote = t.interface({
	Day = t.number,
	PeakBaseRate = t.number,
	Amounts = t.array(t.number)
})
SchemaFields.CashPackReceipts = t.map(t.string, t.number)
SchemaFields.PendingCashPackPurchases = t.map(t.string, t.interface({
	Token = t.string,
	ProductId = t.number,
	RecipientId = t.number
}))
SchemaFields.SpeedPower = t.number
SchemaFields.Inventory = t.map(t.string, AssetItem.SerializedAssetItemData)
SchemaFields.EquippedAssets = t.array(t.string)
SchemaFields.GuardTutorialProgress = GuardTutorial.SchemaValidation.Progress
SchemaFields.LastLogout = t.number
SchemaFields.LastJoinedPlaceVersion = t.number
SchemaFields.PendingOfflineMoney = t.number
SchemaFields.PendingOfflineAnchorLogoutAt = t.number
SchemaFields.EarningsBoostExpiresAt = t.number
SchemaFields.AdEggBoostExpiresAt = t.number
SchemaFields.Gamepasses = t.map(t.string, t.boolean)
SchemaFields.Products = t.map(t.string, t.boolean)
SchemaFields.ProductCredits = t.map(t.string, t.number)
SchemaFields.GiftReceipts = t.map(t.string, t.interface({
	Token = t.string,
	ProductId = t.number,
	RecipientId = t.number,
	State = t.union(t.literal("Pending"), t.literal("Applying"), t.literal("Complete"))
}))
SchemaFields.ReceivedGiftReceipts = t.map(t.string, t.boolean)
SchemaFields.GiftedOwnership = t.map(t.string, t.boolean)
SchemaFields.ClaimedCodes = t.array(t.string)
SchemaFields.ClaimedLikeMilestoneIds = t.map(t.string, t.boolean)
SchemaFields.StarterPackOfferExpires = t.number
SchemaFields.StarterPackOfferPending = t.boolean
SchemaFields.StarterPackOfferFinished = t.boolean
SchemaFields.Index = t.map(t.string, t.boolean)
SchemaFields.BiggestAssetWeight = t.optional(t.number)
SchemaFields.AutoSellRarities = t.map(t.string, t.boolean)
SchemaFields.Settings = t.interface({
	SFX = t.boolean,
	Music = t.boolean,
	AFK = t.optional(t.boolean),
	HideOtherPets = t.optional(t.boolean),
	HideSelfPets = t.optional(t.boolean),
	DisableVideos = t.optional(t.boolean),
	VirtualCursor = t.optional(t.boolean),
	SeenNavigationHint = t.optional(t.boolean)
})
SchemaFields.SkinInventory = t.optional(t.map(t.string, t.number))
SchemaFields.LuckyBlockInventory = t.map(t.string, t.string)
SchemaFields.LatestTreadmillMediaIndex = t.number
SchemaFields.ClaimedGroupReward = t.boolean
SchemaFields.DismissedGroupRewardPrompt = t.boolean
SchemaFields.FreeGiftsStartedAt = t.number
SchemaFields.FreeGiftsTime = t.number
SchemaFields.FreeGiftsActiveStartedAt = t.number
SchemaFields.FreeGiftsClaimed = t.map(t.string, t.boolean)
SchemaFields.FusionSlots = t.array(t.string)
SchemaFields.FusionLocked = t.boolean
SchemaFields.FusionEndsAt = t.optional(t.number)
SchemaFields.FusionDuration = t.number
SchemaFields.FusionReward = t.optional(AssetItem.SerializedAssetItemData)
SchemaFields.VIPFusionSlots = t.array(t.string)
SchemaFields.VIPFusionLocked = t.boolean
SchemaFields.VIPFusionEndsAt = t.optional(t.number)
SchemaFields.VIPFusionDuration = t.number
SchemaFields.VIPFusionReward = t.optional(AssetItem.SerializedAssetItemData)
SchemaFields.PrivateFusionSlots = t.array(t.string)
SchemaFields.PrivateFusionLocked = t.boolean
SchemaFields.PrivateFusionEndsAt = t.optional(t.number)
SchemaFields.PrivateFusionDuration = t.number
SchemaFields.PrivateFusionReward = t.optional(AssetItem.SerializedAssetItemData)
SchemaFields.VIPOfferExpires = t.number
SchemaFields.VIPOfferStarted = t.boolean
SchemaFields.MonetizationRobuxSpentTotal = t.number
SchemaFields.BaseUpgradeLevel = t.number
SchemaFields.TrailInventory = t.map(t.string, t.boolean)
SchemaFields.EquippedTrail = t.optional(t.string)
SchemaFields.VisitedGuardAreas = t.map(t.string, t.boolean)
SchemaFields.StarterPackOfferPausedSeconds = t.optional(t.number)
SchemaFields.StarterPackOfferPlaytimeSeconds = t.optional(t.number)
SchemaFields.TreadmillMediaFeedState = t.interface({
	Seed = t.number,
	CurrentIndex = t.number,
	AlgorithmVersion = t.number,
	HasSwappedRight = t.optional(t.boolean),
	ReleaseTrackingInitialized = t.boolean,
	FullFeedReleaseVersion = t.number,
	CompletedReleaseVersion = t.number,
	PendingReleaseVersion = t.number,
	PendingCurrentMediaKey = t.optional(t.string),
	SeenPendingMediaKeys = t.map(t.string, t.boolean)
})
SchemaFields.FreeGiftsLastResetDay = t.number
SchemaFields.SpeedBoostTierIndex = t.number
SchemaFields.BestRollDenominator = t.number
SchemaFields.IndexClaimedCategories = t.map(t.string, t.boolean)
SchemaFields.LikedTreadmillMedia = t.map(t.string, t.boolean)
SchemaFields.LikedCommentIds = t.map(t.string, t.number)
SchemaFields.CommentedTreadmillMedia = t.map(t.string, t.number)
SchemaFields.BestGuardRunDistance = t.number
SchemaFields.EggInventory = Eggs.SchemaValidation.EggInventory
SchemaFields.VisitedGears = t.map(t.string, t.boolean)
SchemaFields.GearInventory = t.map(t.string, t.number)
SchemaFields.GearAutoBuys = t.map(t.string, t.boolean)
SchemaFields.CurrentAreaEggClaims = t.interface({
	PeriodIndex = t.number,
	Slots = t.map(t.string, t.boolean)
})
SchemaFields.TemporarySpeedBoostRemainingSeconds = t.number
SchemaFields.TemporarySpeedBoostActiveStartedAt = t.number
SchemaFields.TreadmillUpgradeLevel = t.number
SchemaFields.HasRiddenTreadmill = t.boolean
SchemaFields.HasEquippedPhone = t.boolean
SchemaFields.HasPlacedFirstEgg = t.boolean
SchemaFields.GuardSpeedWarningsSeen = t.map(t.string, t.boolean)
SchemaFields.PetPenCapacityGuidance = t.interface({
	Triggered = t.boolean,
	PetsTabAcknowledged = t.boolean,
	EquipBestAcknowledged = t.boolean
})
SchemaFields.FusionEggReward = t.union(t.literal(false), FuseMachine.PendingEggReward)
SchemaFields.FusionInfoAcknowledged = t.boolean
SchemaFields.MonsterParasite = MonsterParasite.StateSchema
SchemaFields.SakuraCrystals = t.number
SchemaFields.Sakura = Sakura.State
SchemaFields.ShrineFusion = ShrineFusion.State
SchemaFields.Rift = Rift.State
SchemaFields.OnboardingQuestline = OnboardingQuestline.State
SchemaFields.RollbackRewards = t.map(t.string, t.boolean)
SchemaFields.BossTokens = t.number
SchemaFields.BossMastery = BossMastery.State
SchemaFields.BanjoCricket = BanjoCricket.State
SchemaFields.LimitedTimePopupsSeen = t.map(t.string, t.number)
return SchemaFields