game:GetService("StarterPlayer")
game:GetService("CollectionService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
game:GetService("ServerScriptService")
local packages = ReplicatedStorage:WaitForChild("Packages")
local Net = require(packages.Net)
script.Parent.Activated:Connect(function()
	local PlayerMouse = require(ReplicatedStorage.Packages.PlayerMouse)
	Net:RemoteEvent("UseItem"):FireServer(PlayerMouse.Hit.Position)
end)