return function()
	local getDefaultInstanceProperty = require(script.Parent.getDefaultInstanceProperty)
	it("should get default name string values", function()
		local _, v = getDefaultInstanceProperty("StringValue", "Name")
		expect(v).to.equal("Value")
	end)
	it("should get default empty string values", function()
		local _, v = getDefaultInstanceProperty("StringValue", "Value")
		expect(v).to.equal("")
	end)
	it("should get default number values", function()
		local _, v = getDefaultInstanceProperty("IntValue", "Value")
		expect(v).to.equal(0)
	end)
	it("should get nil default values", function()
		local _, v = getDefaultInstanceProperty("ObjectValue", "Value")
		expect(v).to.equal(nil)
	end)
	it("should get bool default values", function()
		local _, v = getDefaultInstanceProperty("BoolValue", "Value")
		expect(v).to.equal(false)
	end)
end