return {
	MOUSE_RANGE = 500,
	DASH_SPEED = 65,
	DASH_DECEL_TIME = 0.5,
	HOLD_MAX_DUR = 10,
	STAMINA_DRAIN_RATE = 0.025,
	RANKED_WINDUP = 0.2,
	SCAN_INTERVAL = 0.1,
	DASH_HITBOX_SIZE = vector.create(14, 10, 30),
	DASH_HITBOX_OFFSET = CFrame.new(0, 0, -5),
	BLOCK_BREAK = 0.5,
	GRAB_WALL_CLEARANCE = 7,
	ANIM_DURATION = 1.733,
	FINAL_HIT_AT = 1.45,
	FINAL_DAMAGE = 30,
	FINAL_STUN = 1,
	FINAL_RAGDOLL = 1,
	FINAL_KNOCKBACK = 50,
	FINAL_KNOCKUP = 15,
	FINAL_KNOCKBACK_DUR = 0.4,
	PVP = {
		RankedBlockDamage = 0.6
	}
}