local createVector = vector.create
local Config = {
	HOLD_FREEZE_MARK = 0.5,
	BRANCH_SIGNAL_TIMEOUT = 0.3,
	FAR_CAST_LOCK = 1.15,
	FAR_DAMAGE = 4,
	FAR_STUN = 0.8,
	FAR_BLOCK_KNOCKBACK = 40,
	FAR_PROJECTILE_SIZE = createVector(15, 15, 15),
	FAR_PROJECTILE_SPEED = 65,
	FAR_PROJECTILE_DURATION = 1.5,
	FAR_TICK_INTERVAL = 0.35,
	FAR_EXPLOSION_DAMAGE = 7,
	FAR_EXPLOSION_STUN = 1.25,
	FAR_EXPLOSION_KNOCKBACK = 50,
	CLOSE_FINISH_DAMAGE = 25,
	CLOSE_FINISH_STUN = 1.25,
	CLOSE_FINISH_KNOCKBACK = 60,
	CLOSE_FINISH_BLOCK_BREAK = 3,
	CLOSE_BARRAGE_HITBOX_SIZE = createVector(18, 18, 21),
	CLOSE_BARRAGE_HITBOX_OFFSET = CFrame.new(0, 0, -9),
	CLOSE_BARRAGE_DURATION = 0.9,
	CLOSE_BARRAGE_TICK_INTERVAL = 0.15,
	CLOSE_BARRAGE_DAMAGE = 1
}
Config.CLOSE_HOLD_DURATION = Config.CLOSE_BARRAGE_DURATION + 0.05
Config.PVP = {
	RankedAdScale = 0.8,
	RankedBlockDamage = 0.8
}
return Config