local ReplicatedStorage = game:GetService("ReplicatedStorage")
local battleDemo = ReplicatedStorage:WaitForChild("BattleDemo")
local BattleConfig = require(battleDemo:WaitForChild("BattleConfig"))
local DuelTableClient = require(battleDemo:WaitForChild("DuelTableClient"))
local DuelMatchClient = require(battleDemo:WaitForChild("DuelMatchClient"))
local DuelLaunchAimClient = require(battleDemo:WaitForChild("DuelLaunchAimClient"))
local DuelAimTutorialClient = require(battleDemo:WaitForChild("DuelAimTutorialClient"))
local SimBattleClient = require(ReplicatedStorage:WaitForChild("Engine"):WaitForChild("Service"):WaitForChild("SimBattleClient"))
local v = DuelTableClient.new()
DuelMatchClient.new(BattleConfig, v)
local v2 = DuelLaunchAimClient.new(BattleConfig)
DuelAimTutorialClient.new(v2)
SimBattleClient.start(battleDemo)
print("战斗客户端已启动")