return table.freeze({
	Enabled = false,
	Intensity = 1,
	SpringFrequency = 12,
	FOVFrequency = 8,
	RunFOV = 7,
	DashFOV = 5,
	RunBoostKickScale = 0.65,
	DiveFOV = 6,
	DivePitchKick = 0.28,
	DivePullbackKick = 12,
	DivePullback = 0.18,
	MaxPitchDegrees = 1.8,
	MaxRollDegrees = 2.4,
	RunRollDegrees = 0.9,
	AccelerationPitchDegrees = 0.9,
	DashRollKick = 0.42,
	DashPitchKick = 0.2,
	DashPullbackKick = 9,
	MaxPullback = 0.85,
	LateralLag = 0.12,
	BobHeight = 0.04,
	BobSide = 0.03,
	StepFrequency = 1.8,
	LandingKick = 1.2
})