return function()
	local Symbol = require(script.Parent.Symbol)
	describe("named", function()
		it("should give an opaque object", function()
			local named = Symbol.named("foo")
			expect(named).to.be.a("userdata")
		end)
		it("should coerce to the given name", function()
			local v = tostring((Symbol.named("foo"))):find("foo")
			expect(v).to.be.ok()
		end)
		it("should be unique when constructed", function()
			local named = Symbol.named("abc")
			local named2 = Symbol.named("abc")
			expect(named).never.to.equal(named2)
		end)
	end)
end