return function()
	local assertDeepEqual = require(script.Parent.assertDeepEqual)
	local createSpy = require(script.Parent.createSpy)
	local Logging = require(script.Parent.Logging)
	local SingleEventManager = require(script.Parent.SingleEventManager)
	describe("new", function()
		it("should create a SingleEventManager", function()
			local v = SingleEventManager.new()
			expect(v).to.be.ok()
		end)
	end)
	describe("connectEvent", function()
		it("should connect to events", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local spy = createSpy()
			v:connectEvent("Event", spy.value)
			v:resume()
			bindableEvent:Fire("foo")
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith(bindableEvent, "foo")
			bindableEvent:Fire("bar")
			expect(spy.callCount).to.equal(2)
			spy:assertCalledWith(bindableEvent, "bar")
			v:connectEvent("Event", nil)
			bindableEvent:Fire("baz")
			expect(spy.callCount).to.equal(2)
		end)
		it("should drop events until resumed initially", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local spy = createSpy()
			v:connectEvent("Event", spy.value)
			bindableEvent:Fire("foo")
			expect(spy.callCount).to.equal(0)
			v:resume()
			bindableEvent:Fire("bar")
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith(bindableEvent, "bar")
		end)
		it("should invoke suspended events when resumed", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local spy = createSpy()
			v:connectEvent("Event", spy.value)
			v:resume()
			bindableEvent:Fire("foo")
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith(bindableEvent, "foo")
			v:suspend()
			bindableEvent:Fire("bar")
			expect(spy.callCount).to.equal(1)
			v:resume()
			expect(spy.callCount).to.equal(2)
			spy:assertCalledWith(bindableEvent, "bar")
		end)
		it("should invoke events triggered during resumption in the correct order", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local v2 = {}
			local spy = createSpy(function(_, p)
				table.insert(v2, p)

				if p == 2 then
					bindableEvent:Fire(3)
				elseif p == 3 then
					bindableEvent:Fire(4)
				end
			end)
			v:connectEvent("Event", spy.value)
			v:suspend()
			bindableEvent:Fire(1)
			bindableEvent:Fire(2)
			v:resume()
			expect(spy.callCount).to.equal(4)
			assertDeepEqual(v2, {
				1,
				2,
				3,
				4
			})
		end)
		it("should not invoke events fired during suspension but disconnected before resumption", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local spy = createSpy()
			v:connectEvent("Event", spy.value)
			v:suspend()
			bindableEvent:Fire(1)
			v:connectEvent("Event", nil)
			v:resume()
			expect(spy.callCount).to.equal(0)
		end)
		it("should not yield events through the SingleEventManager when resuming", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			v:connectEvent("Event", function()
				coroutine.yield()
			end)
			v:resume()
			local thread = coroutine.create(function()
				bindableEvent:Fire(5)
			end)
			assert(coroutine.resume(thread))
			expect(coroutine.status(thread)).to.equal("dead")
			v:suspend()
			bindableEvent:Fire(5)
			local thread2 = coroutine.create(function()
				v:resume()
			end)
			assert(coroutine.resume(thread2))
			expect(coroutine.status(thread2)).to.equal("dead")
		end)
		it("should not throw errors through SingleEventManager when resuming", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			v:connectEvent("Event", function()
				error("Error from SingleEventManager test")
			end)
			v:resume()
			v:suspend()
			bindableEvent:Fire(5)
			local capture = Logging.capture(function()
				v:resume()
			end)
			expect(#capture.errors).to.equal(0)
			expect(#capture.warnings).to.equal(1)
			expect(#capture.infos).to.equal(0)
			expect(capture.warnings[1]:find("Error from SingleEventManager test")).to.be.ok()
		end)
		it("should not overflow with events if manager:resume() is invoked when resuming a suspended event", function()
			local bindableEvent = Instance.new("BindableEvent")
			local v = SingleEventManager.new(bindableEvent)
			local spy = createSpy(function(_, p)
				if p == 1 then
					v:suspend()
					bindableEvent:Fire(2)
					v:resume()
				end
			end)
			v:connectEvent("Event", spy.value)
			v:suspend()
			bindableEvent:Fire(1)
			v:resume()
			expect(spy.callCount).to.equal(2)
		end)
	end)
	describe("connectPropertyChange", function()
		it("should connect to property changes", function()
			local folder = Instance.new("Folder")
			local v = SingleEventManager.new(folder)
			local spy = createSpy()
			v:connectPropertyChange("Name", spy.value)
			v:resume()
			folder.Name = "foo"
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith(folder)
			folder.Name = "bar"
			expect(spy.callCount).to.equal(2)
			spy:assertCalledWith(folder)
			v:connectPropertyChange("Name")
			folder.Name = "baz"
			expect(spy.callCount).to.equal(2)
		end)
		it("should throw an error if the property is invalid", function()
			local folder = Instance.new("Folder")
			local v = SingleEventManager.new(folder)
			expect(function()
				v:connectPropertyChange("foo", function() end)
			end).to.throw()
		end)
	end)
end