local GlobalConfig = require(script.GlobalConfig)
local createReconciler = require(script.createReconciler)
local createReconcilerCompat = require(script.createReconcilerCompat)
local RobloxRenderer = require(script.RobloxRenderer)
local strict = require(script.strict)
local Binding = require(script.Binding)
local reconciler = createReconciler(RobloxRenderer)
local reconcilerCompat = createReconcilerCompat(reconciler)
return (strict({
	Component = require(script.Component),
	createElement = require(script.createElement),
	createFragment = require(script.createFragment),
	oneChild = require(script.oneChild),
	PureComponent = require(script.PureComponent),
	None = require(script.None),
	Portal = require(script.Portal),
	createRef = require(script.createRef),
	forwardRef = require(script.forwardRef),
	createBinding = Binding.create,
	joinBindings = Binding.join,
	createContext = require(script.createContext),
	Change = require(script.PropMarkers.Change),
	Children = require(script.PropMarkers.Children),
	Event = require(script.PropMarkers.Event),
	Constant = require(script.PropMarkers.Constant),
	Ref = require(script.PropMarkers.Ref),
	mount = reconciler.mountVirtualTree,
	unmount = reconciler.unmountVirtualTree,
	update = reconciler.updateVirtualTree,
	reify = reconcilerCompat.reify,
	teardown = reconcilerCompat.teardown,
	reconcile = reconcilerCompat.reconcile,
	setGlobalConfig = GlobalConfig.set,
	UNSTABLE = {}
}))