local Config = {
	STARTUP_DUR = 0.7,
	MOUSE_RANGE = 500,
	DASH_SPEED = 78,
	DASH_HITBOX_OFFSET = CFrame.new(0, 0, -9),
	DASH_HITBOX_SIZE = vector.create(7, 7, 20),
	DASH_BLOCK_BREAK = 5,
	CUTSCENE_LOCK_DUR = 7.65,
	CUTSCENE_VALUES_DUR = 7.5,
	CUTSCENE_IFRAME_DUR = 7.7,
	CUTSCENE_CORRECTOR_DUR = 7.6
}
Config.CUTSCENE_STUN = Config.CUTSCENE_VALUES_DUR
Config.CUTSCENE_INITIAL_HIT_AT = 0.3
Config.CUTSCENE_INITIAL_DAMAGE = 10
Config.CUTSCENE_SLASH_DELAYS = {
	2.098,
	0.715,
	0.587,
	0.377,
	0.586
}
Config.CUTSCENE_SLASH_DAMAGE = 5
Config.CUTSCENE_STOMP_AT = 5.922
Config.CUTSCENE_STOMP_DAMAGE = 22
Config.CUTSCENE_STOMP_STUN = Config.CUTSCENE_VALUES_DUR - Config.CUTSCENE_STOMP_AT
Config.PVP = {
	RankedCooldown = 1.4
}
return Config