local frame = Instance.new("Frame")
frame.Name = "Icon"
frame.AnchorPoint = Vector2.new(1, 1)
frame.BackgroundTransparency = 1
frame.LayoutOrder = 1
frame.Size = UDim2.fromOffset(44, 44)
local imageButton = Instance.new("ImageButton")
imageButton.Name = "Background"
imageButton.AnchorPoint = Vector2.new(0, 0.5)
imageButton.AutomaticSize = Enum.AutomaticSize.X
imageButton.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
imageButton.BackgroundTransparency = 0.3
imageButton.Position = UDim2.fromScale(0, 0.5)
imageButton.Size = UDim2.fromOffset(44, 44)
local imageLabel = Instance.new("ImageLabel")
imageLabel.Name = "Icon"
imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
imageLabel.BackgroundTransparency = 1
imageLabel.Position = UDim2.new(0, 22, 0.5, 0)
imageLabel.Size = UDim2.fromOffset(24, 24)
imageLabel.Parent = imageButton
local uICorner = Instance.new("UICorner")
uICorner.Name = "UICorner"
uICorner.CornerRadius = UDim.new(1, 0)
uICorner.Parent = imageButton
local frame2 = Instance.new("Frame")
frame2.Name = "StateOverlayRound"
frame2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
frame2.BackgroundTransparency = 1
frame2.Size = UDim2.fromScale(1, 1)
frame2.ZIndex = 2
local uICorner2 = Instance.new("UICorner")
uICorner2.Name = "UICorner"
uICorner2.CornerRadius = UDim.new(1, 0)
uICorner2.Parent = frame2
frame2.Parent = imageButton
local textLabel = Instance.new("TextLabel")
textLabel.Name = "Text"
textLabel.FontFace = Font.new("rbxasset://fonts/families/GothamSSm.json")
textLabel.Text = "Test, a large label!"
textLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
textLabel.TextSize = 14
textLabel.AutomaticSize = Enum.AutomaticSize.X
textLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
textLabel.BackgroundTransparency = 1
textLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
textLabel.BorderSizePixel = 0
textLabel.Size = UDim2.fromScale(0, 1)
textLabel.Visible = false
local uIPadding = Instance.new("UIPadding")
uIPadding.Name = "Inset"
uIPadding.PaddingLeft = UDim.new(0, 42)
uIPadding.PaddingRight = UDim.new(0, 12)
uIPadding.Parent = textLabel
textLabel.Parent = imageButton
imageButton.Parent = frame
local frame3 = Instance.new("Frame")
frame3.Name = "BadgeContainer"
frame3.BackgroundTransparency = 1
frame3.Size = UDim2.fromScale(1, 1)
frame3.Visible = false
frame3.ZIndex = 2
frame3.Parent = frame
local frame4 = Instance.new("Frame")
frame4.Name = "MenuContainer"
frame4.AnchorPoint = Vector2.new(1, 0)
frame4.AutomaticSize = Enum.AutomaticSize.Y
frame4.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
frame4.BackgroundTransparency = 0.3
frame4.Position = UDim2.new(1, 0, 0, 54)
frame4.Size = UDim2.fromOffset(240, 0)
frame4.Visible = false
local uICorner3 = Instance.new("UICorner")
uICorner3.Name = "UICorner"
uICorner3.CornerRadius = UDim.new(0, 10)
uICorner3.Parent = frame4
local uIPadding2 = Instance.new("UIPadding")
uIPadding2.Name = "UIPadding"
uIPadding2.PaddingBottom = UDim.new(0, 8)
uIPadding2.PaddingTop = UDim.new(0, 8)
uIPadding2.Parent = frame4
local scrollingFrame = Instance.new("ScrollingFrame")
scrollingFrame.Name = "ScrollingFrame"
scrollingFrame.AutomaticCanvasSize = Enum.AutomaticSize.XY
scrollingFrame.ScrollBarThickness = 1
scrollingFrame.ScrollingDirection = Enum.ScrollingDirection.Y
scrollingFrame.AutomaticSize = Enum.AutomaticSize.Y
scrollingFrame.BackgroundTransparency = 1
scrollingFrame.BorderSizePixel = 0
scrollingFrame.Selectable = false
scrollingFrame.SelectionGroup = false
scrollingFrame.Size = UDim2.fromScale(1, 0)
local uIListLayout = Instance.new("UIListLayout")
uIListLayout.Name = "UIListLayout"
uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
uIListLayout.Parent = scrollingFrame
local uISizeConstraint = Instance.new("UISizeConstraint")
uISizeConstraint.Name = "UISizeConstraint"
uISizeConstraint.MaxSize = Vector2.new(1e999, 232)
uISizeConstraint.Parent = scrollingFrame
local frame5 = Instance.new("Frame")
frame5.Name = "BottomPadding"
frame5.BackgroundTransparency = 1
frame5.LayoutOrder = 10000
frame5.Size = UDim2.fromOffset(0, 20)
frame5.Parent = scrollingFrame
scrollingFrame.Parent = frame4
frame4.Parent = frame
return frame