local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UIManager = require(ReplicatedStorage.Engine.Gui.UIManager)
local GachaService = require(ReplicatedStorage.Engine.Service.GachaService)
local TradePortalService = require(ReplicatedStorage.Engine.Service.TradePortalService)
UIManager.Init()
local GamepadUI = require(ReplicatedStorage.Engine.Service.GamepadUI)
GamepadUI.Init()
GachaService.client.initNewbieReward()
local LevelRewardService = require(ReplicatedStorage.Engine.Service.LevelRewardService)
LevelRewardService.client.init()
TradePortalService.client.init()