return function()
	local createSpy = require(script.Parent.createSpy)
	local Type = require(script.Parent.Type)
	local GlobalConfig = require(script.Parent.GlobalConfig)
	local Binding = require(script.Parent.Binding)
	describe("Binding.create", function()
		it("should return a Binding object and an update function", function()
			local v, v2 = Binding.create(1)
			expect(Type.of(v)).to.equal(Type.Binding)
			expect((typeof(v2))).to.equal("function")
		end)
		it("should support tostring on bindings", function()
			local v, v2 = Binding.create(1)
			expect((tostring(v))).to.equal("RoactBinding(1)")
			v2("foo")
			expect((tostring(v))).to.equal("RoactBinding(foo)")
		end)
	end)
	describe("Binding object", function()
		it("should provide a getter and setter", function()
			local v, v2 = Binding.create(1)
			expect(v:getValue()).to.equal(1)
			v2(3)
			expect(v:getValue()).to.equal(3)
		end)
		it("should let users subscribe and unsubscribe to its updates", function()
			local v, v2 = Binding.create(1)
			local spy = createSpy()
			local v3 = Binding.subscribe(v, spy.value)
			expect(spy.callCount).to.equal(0)
			v2(2)
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith(2)
			v3()
			v2(3)
			expect(spy.callCount).to.equal(1)
		end)
	end)
	describe("Mapped bindings", function()
		it("should be composable", function()
			local v, v2 = Binding.create("hi")
			local mapped = v:map(string.len)
			local mapped2 = mapped:map(function(p)
				return p % 2 == 0
			end)
			expect(v:getValue()).to.equal("hi")
			expect(mapped:getValue()).to.equal(2)
			expect(mapped2:getValue()).to.equal(true)
			v2("sup")
			expect(v:getValue()).to.equal("sup")
			expect(mapped:getValue()).to.equal(3)
			expect(mapped2:getValue()).to.equal(false)
		end)
		it("should cascade updates when subscribed", function()
			local v, v2 = Binding.create("hi")
			local spy = createSpy()
			local v3 = Binding.subscribe(v, spy.value)
			local mapped = v:map(string.len)
			local spy2 = createSpy()
			local v4 = Binding.subscribe(mapped, spy2.value)
			local mapped2 = mapped:map(function(p)
				return p % 2 == 0
			end)
			local spy3 = createSpy()
			local v5 = Binding.subscribe(mapped2, spy3.value)
			expect(spy.callCount).to.equal(0)
			expect(spy2.callCount).to.equal(0)
			expect(spy3.callCount).to.equal(0)
			v2("nice")
			expect(spy.callCount).to.equal(1)
			spy:assertCalledWith("nice")
			expect(spy2.callCount).to.equal(1)
			spy2:assertCalledWith(4)
			expect(spy3.callCount).to.equal(1)
			spy3:assertCalledWith(true)
			v3()
			v4()
			v5()
			v2("goodbye")
			expect(spy.callCount).to.equal(1)
			expect(spy3.callCount).to.equal(1)
			expect(spy2.callCount).to.equal(1)
		end)
		it("should throw when updated directly", function()
			local mapped = Binding.create(1):map(function(p)
				return p
			end)
			expect(function()
				Binding.update(mapped, 5)
			end).to.throw()
		end)
	end)
	describe("Binding.join", function()
		it("should have getValue", function()
			local v = Binding.create(1)
			local v2 = Binding.create(2)
			local foo = Binding.create(3)
			local value = Binding.join({
				v,
				v2,
				foo = foo
			}):getValue()
			expect(value).to.be.a("table")
			expect(value[1]).to.equal(1)
			expect(value[2]).to.equal(2)
			expect(value.foo).to.equal(3)
		end)
		it("should update when any one of the subscribed bindings updates", function()
			local v, v2 = Binding.create(1)
			local v3, v4 = Binding.create(2)
			local foo, v6 = Binding.create(3)
			local joined = Binding.join({
				v,
				v3,
				foo = foo
			})
			local spy = createSpy()
			Binding.subscribe(joined, spy.value)
			expect(spy.callCount).to.equal(0)
			v2(3)
			expect(spy.callCount).to.equal(1)
			local captureValues = spy:captureValues("value")
			expect(captureValues.value).to.be.a("table")
			expect(captureValues.value[1]).to.equal(3)
			expect(captureValues.value[2]).to.equal(2)
			expect(captureValues.value.foo).to.equal(3)
			v4(4)
			expect(spy.callCount).to.equal(2)
			local captureValues2 = spy:captureValues("value")
			expect(captureValues2.value).to.be.a("table")
			expect(captureValues2.value[1]).to.equal(3)
			expect(captureValues2.value[2]).to.equal(4)
			expect(captureValues2.value.foo).to.equal(3)
			v6(8)
			expect(spy.callCount).to.equal(3)
			local captureValues3 = spy:captureValues("value")
			expect(captureValues3.value).to.be.a("table")
			expect(captureValues3.value[1]).to.equal(3)
			expect(captureValues3.value[2]).to.equal(4)
			expect(captureValues3.value.foo).to.equal(8)
		end)
		it("should disconnect from all upstream bindings", function()
			local v, v2 = Binding.create(1)
			local v3, v4 = Binding.create(2)
			local joined = Binding.join({ v, v3 })
			local spy = createSpy()
			local v5 = Binding.subscribe(joined, spy.value)
			expect(spy.callCount).to.equal(0)
			v2(3)
			expect(spy.callCount).to.equal(1)
			v4(3)
			expect(spy.callCount).to.equal(2)
			v5()
			v2(4)
			expect(spy.callCount).to.equal(2)
			v4(2)
			expect(spy.callCount).to.equal(2)
			local value = joined:getValue()
			expect(value[1]).to.equal(4)
			expect(value[2]).to.equal(2)
		end)
		it("should be okay with calling disconnect multiple times", function()
			local joined = Binding.join({})
			local v = Binding.subscribe(joined, function() end)
			v()
			v()
		end)
		it("should throw if updated directly", function()
			local joined = Binding.join({})
			expect(function()
				Binding.update(joined, 0)
			end)
		end)
		it("should throw when a non-table value is passed", function()
			GlobalConfig.scoped({
				typeChecks = true
			}, function()
				expect(function()
					Binding.join("hi")
				end).to.throw()
			end)
		end)
		it("should throw when a non-binding value is passed via table", function()
			GlobalConfig.scoped({
				typeChecks = true
			}, function()
				expect(function()
					local v = { Binding.create(123), "abcde" }
					Binding.join(v)
				end).to.throw()
			end)
		end)
	end)
end