local ReplicatedStorage = game:GetService("ReplicatedStorage")
game:GetService("RunService")
local FastFlags = require(ReplicatedStorage.UserGenerated.FastFlags)
local Asserts = require(ReplicatedStorage.UserGenerated.Lang.Asserts)
local replicated = FastFlags.Replicated("ExistCounts.PublicBrainrots", Asserts.Array(Asserts.String), {
	"Raccooni Jandelini",
	"Pipi Corni",
	"Tim Cheese",
	"Noobini Pizzanini",
	"Trippi Troppi",
	"Malame Amarele",
	"Caramello Filtrello",
	"Puffaball",
	"Gorillo Subwoofero",
	"Brutto Gialutto",
	"Los Noobinis",
	"Avocadorilla",
	"Rhino Helicopterino",
	"Centrucci Nuclucci",
	"Stoppo Luminino",
	"Tob Tobi Tobi",
	"Ganganzelli Trulala",
	"Belula Beluga",
	"Pretzo Robo",
	"Dumborino Miracello",
	"Unclito Samito",
	"Cocofanto Elefanto",
	"Tralalero Tralala",
	"Hopilikalika Hopilikalako",
	"Quackini Snackini",
	"Kraken",
	"Bunny and Teddy",
	"Sammyni Cakini",
	"Rosey and Teddy",
	"Dragon Aquanini",
	"Digi Narwhal",
	"Hydra Bunny",
	"La Supreme Combinasion",
	"Los Amigos",
	"Los Sekolahs",
	"Los Chillis",
	"Rubrikiko",
	"Jelly Moby",
	"Antonio",
	"Signore Carapace",
	"La Food Combinasion",
	"Arcadragon",
	"Los Hackers",
	"Kalika Bros",
	"John Doe",
	"Gym Bros",
	"Los Tacoritas",
	"Love Love Love Sahur",
	"Duggy Bros",
	"Agarrini la Palini",
	"Elefanto Frigo",
	"Los Mariachis",
	"Fishino Clownino",
	"Dug dug dug",
	"Griffin",
	"Tirilikalika Tirilikalako",
	"Boppin Bunny",
	"Sammyni Fattini",
	"La Romantic Grande",
	"Cuadramat and Pakrahmatmamat",
	"Love Love Bear",
	"Dragon Gingerini",
	"Cloverat Clapat",
	"La Easter Grande",
	"Reinito Sleighito",
	"Foxini Lanternini",
	"La Casa Boo",
	"Jolly Jolly Sahur",
	"Ho Ho Ho Sahur",
	"Gobblino Uniciclino",
	"Tacorita Bicicleta",
	"Noo my examine",
	"Ginger Gerat",
	"Lovin Rose",
	"La Vacca Saturno Saturnita",
	"Ketupat Bros",
	"Guest 666",
	"Headless Horseman",
	"Strawberry Elephant",
	"Meowl",
	"Skibidi Toilet",
	"John Pork"
})
local replicated2 = FastFlags.Replicated("ExistCounts.GlossaryTraitMatchCountsEnabledV2", Asserts.Boolean, false)
return table.freeze({
	PublicBrainrots = replicated,
	GlossaryTraitMatchCountsEnabled = replicated2
})