local createSignalroblox = require(script.Parent.Parent["createSignal.roblox"])
local parent = script.Parent.Parent.Parent
local JestGlobals = require(parent.Dev.JestGlobals)
local expect = JestGlobals.expect
local jest = JestGlobals.jest
local it = JestGlobals.it
it("should fire subscribers and disconnect them", function()
	local signalroblox, v = createSignalroblox()
	local v2 = jest.fn()
	local v3 = signalroblox(function(...)
		v2(...)
	end)
	expect(v2).never.toBeCalled()
	local v4 = {}
	v(1, v4, "hello")
	expect(v2).toBeCalledTimes(1)
	expect(v2).toBeCalledWith(1, v4, "hello")
	v3()
	v()
	expect(v2).toBeCalledTimes(1)
end)
it("should handle multiple subscribers", function()
	local signalroblox, v = createSignalroblox()
	local v2 = jest.fn()
	local v3 = jest.fn()
	local v4 = signalroblox(function(...)
		v2(...)
	end)
	local v5 = signalroblox(function(...)
		v3(...)
	end)
	expect(v2).never.toBeCalled()
	expect(v3).never.toBeCalled()
	local v6 = {}
	v(v6, 67)
	expect(v2).toBeCalledTimes(1)
	expect(v2).toBeCalledWith(v6, 67)
	expect(v3).toBeCalledTimes(1)
	expect(v3).toBeCalledWith(v6, 67)
	v4()
	v(67, v6)
	expect(v2).toBeCalledTimes(1)
	expect(v3).toBeCalledTimes(2)
	expect(v3).toBeCalledWith(67, v6)
	v5()
end)
it("should stop firing a connection if disconnected mid-fire", function()
	local signalroblox, v = createSignalroblox()
	local v2 = nil
	local v3 = nil
	local v4 = jest.fn(function()
		v3()
	end)
	local v5 = jest.fn(function()
		v2()
	end)
	v2 = signalroblox(function(...)
		v4(...)
	end)
	v3 = signalroblox(function(...)
		v5(...)
	end)
	v()
	expect(#v4.mock.calls + #v5.mock.calls).toBe(1)
end)