return {
	CHARGE_DUR = 0.07,
	LAUNCH_FREEZE_AT = 0.8,
	FLIGHT_SPEED = 52.5,
	UNHOLD_CLEAN_DELAY = 0.4,
	PROJECTILE_SPAWN_OFFSET = CFrame.new(0, 5, -5),
	PROJECTILE_ARM_TIME = 0.2,
	PROJECTILE_LIFETIME = 12,
	CHAINSAW_GROUND_OFFSET = CFrame.new(0, 0, 10),
	CHAINSAW_HITBOX_SIZE = vector.create(31.3, 20.5, 36.6),
	CHAINSAW_DURATION = 1.5,
	CHAINSAW_TICK_INTERVAL = 0.1,
	CHAINSAW_DAMAGE = 1.5,
	CHAINSAW_STUN = 0.5,
	CHAINSAW_BLOCK_BREAK = 0.1
}