return function()
	local frame = Instance.new("Frame")
	frame.Name = "BigDropdown"
	frame.BackgroundTransparency = 1
	frame.Size = UDim2.new(1, 0, 0, 140)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "BG"
	frame2.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.fromScale(1, 1)
	frame2.ZIndex = 3
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "Top"
	frame3.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Size = UDim2.new(1, 0, 0, 18)
	frame3.ZIndex = 3
	local textBox = Instance.new("TextBox")
	textBox.AnchorPoint = Vector2.new(0, 0.5)
	textBox.BackgroundTransparency = 1
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new("rbxassetid://16658246179")
	textBox.PlaceholderColor3 = Color3.fromRGB(157, 157, 157)
	textBox.PlaceholderText = "Type to search"
	textBox.Position = UDim2.new(0, 6, 0.5, 0)
	textBox.Size = UDim2.new(1, -6, 0, 12)
	textBox.Text = ""
	textBox.TextColor3 = Color3.new(1, 1, 1)
	textBox.TextSize = 12
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.ZIndex = 5
	textBox.Parent = frame3
	frame3.Parent = frame
	local scrollingFrame = Instance.new("ScrollingFrame")
	scrollingFrame.Active = true
	scrollingFrame.AnchorPoint = Vector2.new(0, 1)
	scrollingFrame.BackgroundTransparency = 1
	scrollingFrame.BottomImage = "rbxassetid://7549380501"
	scrollingFrame.CanvasSize = UDim2.new()
	scrollingFrame.MidImage = "rbxassetid://7549380501"
	scrollingFrame.Position = UDim2.fromScale(0, 1)
	scrollingFrame.ScrollBarImageColor3 = Color3.fromRGB(44, 44, 44)
	scrollingFrame.ScrollBarThickness = 10
	scrollingFrame.Size = UDim2.new(1, 0, 1, -18)
	scrollingFrame.TopImage = "rbxassetid://7549380501"
	scrollingFrame.VerticalScrollBarInset = Enum.ScrollBarInset.Always
	scrollingFrame.ZIndex = 9
	local uIGridLayout = Instance.new("UIGridLayout")
	uIGridLayout.CellPadding = UDim2.new()
	uIGridLayout.CellSize = UDim2.new(1, 0, 0, 18)
	uIGridLayout.Parent = scrollingFrame
	local textButton = Instance.new("TextButton")
	textButton.Name = "ExampleButton"
	textButton.BackgroundColor3 = Color3.fromRGB(61, 61, 61)
	textButton.BorderColor3 = Color3.fromRGB(29, 145, 208)
	textButton.BorderMode = Enum.BorderMode.Inset
	textButton.BorderSizePixel = 0
	textButton.FontFace = Font.new("rbxassetid://16658221428")
	textButton.Size = UDim2.fromOffset(200, 50)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 12
	textButton.ZIndex = 20
	local textLabel = Instance.new("TextLabel")
	textLabel.AnchorPoint = Vector2.new(1, 0)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxassetid://16658246179")
	textLabel.Position = UDim2.fromScale(1, 0)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "BaseHuman/Dash/Forward"
	textLabel.TextColor3 = Color3.fromRGB(220, 220, 220)
	textLabel.TextSize = 12
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 21
	textLabel.Parent = textButton
	textButton.Parent = scrollingFrame
	scrollingFrame.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "ScrollBG"
	frame4.AnchorPoint = Vector2.new(1, 1)
	frame4.BackgroundColor3 = Color3.fromRGB(71, 71, 71)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 1)
	frame4.Size = UDim2.new(0, 10, 1, -18)
	frame4.ZIndex = 4
	frame4.Parent = frame
	return frame
end