return function()
	local frame = Instance.new("Frame")
	frame.Name = "Checkbox"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Position Y"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local frame5 = Instance.new("Frame")
	frame5.Name = "CheckboxCtn"
	frame5.BackgroundTransparency = 1
	frame5.Size = UDim2.fromScale(1, 1)
	frame5.ZIndex = 20
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.Parent = frame5
	local frame6 = Instance.new("Frame")
	frame6.Name = "Checkbox"
	frame6.AnchorPoint = Vector2.new(0.5, 0.5)
	frame6.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame6.Position = UDim2.fromScale(0.5, 0.5)
	frame6.Size = UDim2.fromScale(0.8, 0.8)
	frame6.ZIndex = 20
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Color = Color3.fromRGB(31, 31, 31)
	uIStroke.Parent = frame6
	local uICorner = Instance.new("UICorner")
	uICorner.BottomLeftRadius = UDim.new(0, 3)
	uICorner.BottomRightRadius = UDim.new(0, 3)
	uICorner.TopLeftRadius = UDim.new(0, 3)
	uICorner.TopRightRadius = UDim.new(0, 3)
	uICorner.Parent = frame6
	frame6.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 30
	textButton.Parent = frame5
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "Icon"
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxassetid://11242915823"
	imageLabel.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel.Size = UDim2.fromScale(0.8, 0.8)
	imageLabel.ZIndex = 24
	imageLabel.Parent = frame5
	local frame7 = Instance.new("Frame")
	frame7.Name = "DisabledCheckbox"
	frame7.AnchorPoint = Vector2.new(0.5, 0.5)
	frame7.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
	frame7.Position = UDim2.fromScale(0.5, 0.5)
	frame7.Size = UDim2.fromScale(0.8, 0.8)
	frame7.ZIndex = 18
	local uICorner2 = Instance.new("UICorner")
	uICorner2.BottomLeftRadius = UDim.new(0, 3)
	uICorner2.BottomRightRadius = UDim.new(0, 3)
	uICorner2.TopLeftRadius = UDim.new(0, 3)
	uICorner2.TopRightRadius = UDim.new(0, 3)
	uICorner2.Parent = frame7
	frame7.Parent = frame5
	frame5.Parent = frame4
	frame4.Parent = frame
	local frame8 = Instance.new("Frame")
	frame8.Name = "WhiteFrame"
	frame8.BackgroundTransparency = 1
	frame8.Size = UDim2.fromScale(1, 1)
	frame8.ZIndex = 50
	frame8.Parent = frame
	return frame
end