return function()
	local frame = Instance.new("Frame")
	frame.Name = "Color"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Color Selector"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local frame5 = Instance.new("Frame")
	frame5.Name = "Ctn"
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_2.Parent = frame5
	local frame6 = Instance.new("Frame")
	frame6.AnchorPoint = Vector2.new(0.5, 0.5)
	frame6.BackgroundColor3 = Color3.fromRGB(255, 62, 62)
	frame6.BorderColor3 = Color3.new()
	frame6.BorderSizePixel = 0
	frame6.Position = UDim2.fromScale(0.5, 0.5)
	frame6.Size = UDim2.fromScale(0.8, 0.8)
	frame6.ZIndex = 50
	local uIStroke_2 = Instance.new("UIStroke")
	uIStroke_2.Parent = frame6
	frame6.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.Name = "Btn"
	textButton.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
	textButton.BorderColor3 = Color3.fromRGB(34, 34, 34)
	textButton.BorderMode = Enum.BorderMode.Inset
	textButton.BorderSizePixel = 0
	textButton.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textButton.Position = UDim2.fromScale(0.5, 0.5)
	textButton.Size = UDim2.new(1, -2, 1, -2)
	textButton.Text = ""
	textButton.TextColor3 = Color3.fromRGB(229, 229, 229)
	textButton.TextSize = 14
	textButton.ZIndex = 30
	textButton.Parent = frame5
	frame5.Parent = frame4
	local frame7 = Instance.new("Frame")
	frame7.Name = "Selector"
	frame7.AnchorPoint = Vector2.new(0.5, 0)
	frame7.BackgroundTransparency = 1
	frame7.BorderMode = Enum.BorderMode.Inset
	frame7.Position = UDim2.fromScale(0, 1)
	frame7.Size = UDim2.new(2, 4, 5, 0)
	frame7.ZIndex = 9000000
	local frame8 = Instance.new("Frame")
	frame8.Name = "RatioedCtn"
	frame8.AnchorPoint = Vector2.new(0.5, 0.5)
	frame8.BackgroundTransparency = 1
	frame8.Position = UDim2.fromScale(0.5, 0.5)
	frame8.Size = UDim2.new(1, -8, 1, 0)
	local frame9 = Instance.new("Frame")
	frame9.Name = "Sliders"
	frame9.BackgroundTransparency = 1
	frame9.LayoutOrder = 1
	frame9.Size = UDim2.fromScale(1, 0.7)
	local frame10 = Instance.new("Frame")
	frame10.Name = "R"
	frame10.BackgroundColor3 = Color3.new(1, 1, 1)
	frame10.BorderColor3 = Color3.new()
	frame10.BorderSizePixel = 0
	frame10.LayoutOrder = 1
	frame10.Size = UDim2.fromScale(1, 1)
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "Interactibility"
	textButton2.BackgroundTransparency = 1
	textButton2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.TextColor3 = Color3.new()
	textButton2.TextSize = 14
	textButton2.ZIndex = 9000053
	textButton2.Parent = frame10
	local folder = Instance.new("Folder")
	folder.Name = "Items"
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = folder
	local frame11 = Instance.new("Frame")
	frame11.Name = "SliderCtn"
	frame11.AnchorPoint = Vector2.new(0, 0.5)
	frame11.BackgroundColor3 = Color3.new(1, 1, 1)
	frame11.BorderColor3 = Color3.new()
	frame11.BorderSizePixel = 0
	frame11.Position = UDim2.fromScale(0, 0.5)
	frame11.Size = UDim2.fromScale(0.9, 1)
	local frame12 = Instance.new("Frame")
	frame12.Name = "InnerSlider"
	frame12.AnchorPoint = Vector2.new(1, 0.5)
	frame12.BackgroundColor3 = Color3.new(1, 1, 1)
	frame12.BorderColor3 = Color3.new()
	frame12.BorderSizePixel = 0
	frame12.Position = UDim2.fromScale(1, 0.5)
	frame12.Size = UDim2.new(1, -4, 0.2, 0)
	frame12.ZIndex = 9000015
	local uIGradient = Instance.new("UIGradient")
	uIGradient.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.new()),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))
	})
	uIGradient.Parent = frame12
	local frame13 = Instance.new("Frame")
	frame13.Name = "Cursor"
	frame13.AnchorPoint = Vector2.new(0.5, 0.5)
	frame13.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame13.Position = UDim2.fromScale(0.5, 0.5)
	frame13.Size = UDim2.fromScale(4, 4)
	frame13.ZIndex = 9000021
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.AspectRatio = 0.25
	uIAspectRatioConstraint.Parent = frame13
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Transparency = 0.5
	uIStroke.Parent = frame13
	local uICorner = Instance.new("UICorner")
	uICorner.BottomLeftRadius = UDim.new(1, 0)
	uICorner.BottomRightRadius = UDim.new(1, 0)
	uICorner.TopLeftRadius = UDim.new(1, 0)
	uICorner.TopRightRadius = UDim.new(1, 0)
	uICorner.Parent = frame13
	frame13.Parent = frame12
	frame12.Parent = frame11
	frame11.Parent = folder
	local frame14 = Instance.new("Frame")
	frame14.Name = "NumCtn"
	frame14.AnchorPoint = Vector2.new(0, 0.5)
	frame14.BackgroundColor3 = Color3.new(1, 1, 1)
	frame14.BorderColor3 = Color3.new()
	frame14.BorderSizePixel = 0
	frame14.Position = UDim2.fromScale(0, 0.5)
	frame14.Size = UDim2.fromScale(1, 1)
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = frame14
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Name = "Title"
	textLabel2.AnchorPoint = Vector2.new(1, 0.5)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel2.Position = UDim2.fromScale(1, 0.5)
	textLabel2.Size = UDim2.new(1, -6, 1, 0)
	textLabel2.Text = "128"
	textLabel2.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel2.TextSize = 14
	textLabel2.ZIndex = 9000004
	textLabel2.Parent = frame14
	frame14.Parent = folder
	folder.Parent = frame10
	frame10.Parent = frame9
	local uIGridLayout = Instance.new("UIGridLayout")
	uIGridLayout.CellPadding = UDim2.new()
	uIGridLayout.CellSize = UDim2.fromScale(1, 0.333)
	uIGridLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIGridLayout.Parent = frame9
	local frame15 = Instance.new("Frame")
	frame15.Name = "G"
	frame15.BackgroundColor3 = Color3.new(1, 1, 1)
	frame15.BorderColor3 = Color3.new()
	frame15.BorderSizePixel = 0
	frame15.LayoutOrder = 1
	frame15.Size = UDim2.fromScale(1, 1)
	local textButton3 = Instance.new("TextButton")
	textButton3.Name = "Interactibility"
	textButton3.BackgroundTransparency = 1
	textButton3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton3.Size = UDim2.fromScale(1, 1)
	textButton3.Text = ""
	textButton3.TextColor3 = Color3.new()
	textButton3.TextSize = 14
	textButton3.ZIndex = 9000053
	textButton3.Parent = frame15
	local folder2 = Instance.new("Folder")
	folder2.Name = "Items"
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = folder2
	local frame16 = Instance.new("Frame")
	frame16.Name = "SliderCtn"
	frame16.AnchorPoint = Vector2.new(0, 0.5)
	frame16.BackgroundColor3 = Color3.new(1, 1, 1)
	frame16.BorderColor3 = Color3.new()
	frame16.BorderSizePixel = 0
	frame16.Position = UDim2.fromScale(0, 0.5)
	frame16.Size = UDim2.fromScale(0.9, 1)
	local frame17 = Instance.new("Frame")
	frame17.Name = "InnerSlider"
	frame17.AnchorPoint = Vector2.new(1, 0.5)
	frame17.BackgroundColor3 = Color3.new(1, 1, 1)
	frame17.BorderColor3 = Color3.new()
	frame17.BorderSizePixel = 0
	frame17.Position = UDim2.fromScale(1, 0.5)
	frame17.Size = UDim2.new(1, -4, 0.2, 0)
	frame17.ZIndex = 9000015
	local uIGradient2 = Instance.new("UIGradient")
	uIGradient2.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.new()),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))
	})
	uIGradient2.Parent = frame17
	local frame18 = Instance.new("Frame")
	frame18.Name = "Cursor"
	frame18.AnchorPoint = Vector2.new(0.5, 0.5)
	frame18.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame18.Position = UDim2.fromScale(0.5, 0.5)
	frame18.Size = UDim2.fromScale(4, 4)
	frame18.ZIndex = 9000021
	local uIAspectRatioConstraint2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint2.AspectRatio = 0.25
	uIAspectRatioConstraint2.Parent = frame18
	local uIStroke2 = Instance.new("UIStroke")
	uIStroke2.Transparency = 0.5
	uIStroke2.Parent = frame18
	local uICorner2 = Instance.new("UICorner")
	uICorner2.BottomLeftRadius = UDim.new(1, 0)
	uICorner2.BottomRightRadius = UDim.new(1, 0)
	uICorner2.TopLeftRadius = UDim.new(1, 0)
	uICorner2.TopRightRadius = UDim.new(1, 0)
	uICorner2.Parent = frame18
	frame18.Parent = frame17
	frame17.Parent = frame16
	frame16.Parent = folder2
	local frame19 = Instance.new("Frame")
	frame19.Name = "NumCtn"
	frame19.AnchorPoint = Vector2.new(0, 0.5)
	frame19.BackgroundColor3 = Color3.new(1, 1, 1)
	frame19.BorderColor3 = Color3.new()
	frame19.BorderSizePixel = 0
	frame19.Position = UDim2.fromScale(0, 0.5)
	frame19.Size = UDim2.fromScale(1, 1)
	local uIFlexItem2 = Instance.new("UIFlexItem")
	uIFlexItem2.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem2.Parent = frame19
	local textLabel3 = Instance.new("TextLabel")
	textLabel3.Name = "Title"
	textLabel3.AnchorPoint = Vector2.new(1, 0.5)
	textLabel3.BackgroundTransparency = 1
	textLabel3.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel3.Position = UDim2.fromScale(1, 0.5)
	textLabel3.Size = UDim2.new(1, -6, 1, 0)
	textLabel3.Text = "128"
	textLabel3.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel3.TextSize = 14
	textLabel3.ZIndex = 9000004
	textLabel3.Parent = frame19
	frame19.Parent = folder2
	folder2.Parent = frame15
	frame15.Parent = frame9
	local frame20 = Instance.new("Frame")
	frame20.Name = "B"
	frame20.BackgroundColor3 = Color3.new(1, 1, 1)
	frame20.BorderColor3 = Color3.new()
	frame20.BorderSizePixel = 0
	frame20.LayoutOrder = 1
	frame20.Size = UDim2.fromScale(1, 1)
	local textButton4 = Instance.new("TextButton")
	textButton4.Name = "Interactibility"
	textButton4.BackgroundTransparency = 1
	textButton4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton4.Size = UDim2.fromScale(1, 1)
	textButton4.Text = ""
	textButton4.TextColor3 = Color3.new()
	textButton4.TextSize = 14
	textButton4.ZIndex = 9000053
	textButton4.Parent = frame20
	local folder3 = Instance.new("Folder")
	folder3.Name = "Items"
	local uIListLayout3 = Instance.new("UIListLayout")
	uIListLayout3.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout3.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout3.Parent = folder3
	local frame21 = Instance.new("Frame")
	frame21.Name = "SliderCtn"
	frame21.AnchorPoint = Vector2.new(0, 0.5)
	frame21.BackgroundColor3 = Color3.new(1, 1, 1)
	frame21.BorderColor3 = Color3.new()
	frame21.BorderSizePixel = 0
	frame21.Position = UDim2.fromScale(0, 0.5)
	frame21.Size = UDim2.fromScale(0.9, 1)
	local frame22 = Instance.new("Frame")
	frame22.Name = "InnerSlider"
	frame22.AnchorPoint = Vector2.new(1, 0.5)
	frame22.BackgroundColor3 = Color3.new(1, 1, 1)
	frame22.BorderColor3 = Color3.new()
	frame22.BorderSizePixel = 0
	frame22.Position = UDim2.fromScale(1, 0.5)
	frame22.Size = UDim2.new(1, -4, 0.2, 0)
	frame22.ZIndex = 9000015
	local uIGradient3 = Instance.new("UIGradient")
	uIGradient3.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.new()),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 0, 0))
	})
	uIGradient3.Parent = frame22
	local frame23 = Instance.new("Frame")
	frame23.Name = "Cursor"
	frame23.AnchorPoint = Vector2.new(0.5, 0.5)
	frame23.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame23.Position = UDim2.fromScale(0.5, 0.5)
	frame23.Size = UDim2.fromScale(4, 4)
	frame23.ZIndex = 9000021
	local uIAspectRatioConstraint3 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint3.AspectRatio = 0.25
	uIAspectRatioConstraint3.Parent = frame23
	local uIStroke3 = Instance.new("UIStroke")
	uIStroke3.Transparency = 0.5
	uIStroke3.Parent = frame23
	local uICorner3 = Instance.new("UICorner")
	uICorner3.BottomLeftRadius = UDim.new(1, 0)
	uICorner3.BottomRightRadius = UDim.new(1, 0)
	uICorner3.TopLeftRadius = UDim.new(1, 0)
	uICorner3.TopRightRadius = UDim.new(1, 0)
	uICorner3.Parent = frame23
	frame23.Parent = frame22
	frame22.Parent = frame21
	frame21.Parent = folder3
	local frame24 = Instance.new("Frame")
	frame24.Name = "NumCtn"
	frame24.AnchorPoint = Vector2.new(0, 0.5)
	frame24.BackgroundColor3 = Color3.new(1, 1, 1)
	frame24.BorderColor3 = Color3.new()
	frame24.BorderSizePixel = 0
	frame24.Position = UDim2.fromScale(0, 0.5)
	frame24.Size = UDim2.fromScale(1, 1)
	local uIFlexItem3 = Instance.new("UIFlexItem")
	uIFlexItem3.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem3.Parent = frame24
	local textLabel4 = Instance.new("TextLabel")
	textLabel4.Name = "Title"
	textLabel4.AnchorPoint = Vector2.new(1, 0.5)
	textLabel4.BackgroundTransparency = 1
	textLabel4.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel4.Position = UDim2.fromScale(1, 0.5)
	textLabel4.Size = UDim2.new(1, -6, 1, 0)
	textLabel4.Text = "128"
	textLabel4.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel4.TextSize = 14
	textLabel4.ZIndex = 9000004
	textLabel4.Parent = frame24
	frame24.Parent = folder3
	folder3.Parent = frame20
	frame20.Parent = frame9
	frame9.Parent = frame8
	local frame25 = Instance.new("Frame")
	frame25.Name = "Others"
	frame25.BackgroundTransparency = 1
	frame25.LayoutOrder = 2
	frame25.Size = UDim2.fromScale(1, 1)
	local uIFlexItem4 = Instance.new("UIFlexItem")
	uIFlexItem4.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem4.Parent = frame25
	local frame26 = Instance.new("Frame")
	frame26.Name = "Mode"
	frame26.BackgroundColor3 = Color3.new(1, 1, 1)
	frame26.BorderColor3 = Color3.new()
	frame26.BorderSizePixel = 0
	frame26.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint4 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint4.AspectRatio = 2
	uIAspectRatioConstraint4.Parent = frame26
	local frame27 = Instance.new("Frame")
	frame27.Name = "BG"
	frame27.AnchorPoint = Vector2.new(0.5, 0.5)
	frame27.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame27.BorderColor3 = Color3.new()
	frame27.BorderSizePixel = 0
	frame27.Position = UDim2.fromScale(0.5, 0.5)
	frame27.Size = UDim2.fromScale(1, 1)
	frame27.ZIndex = 9000012
	frame27.Parent = frame26
	local textButton5 = Instance.new("TextButton")
	textButton5.Name = "Btn"
	textButton5.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton5.BackgroundColor3 = Color3.fromRGB(36, 126, 175)
	textButton5.BorderColor3 = Color3.fromRGB(34, 34, 34)
	textButton5.BorderMode = Enum.BorderMode.Inset
	textButton5.BorderSizePixel = 0
	textButton5.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textButton5.Position = UDim2.fromScale(0.5, 0.5)
	textButton5.Size = UDim2.new(1, -2, 1, -2)
	textButton5.Text = "RGB"
	textButton5.TextColor3 = Color3.fromRGB(229, 229, 229)
	textButton5.TextSize = 21
	textButton5.TextWrapped = true
	textButton5.ZIndex = 9000021
	textButton5.Parent = frame26
	frame26.Parent = frame25
	local uIListLayout4 = Instance.new("UIListLayout")
	uIListLayout4.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout4.HorizontalFlex = Enum.UIFlexAlignment.SpaceBetween
	uIListLayout4.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout4.Parent = frame25
	local uIPadding = Instance.new("UIPadding")
	uIPadding.PaddingBottom = UDim.new(0, 4)
	uIPadding.Parent = frame25
	local frame28 = Instance.new("Frame")
	frame28.Name = "HTML"
	frame28.AnchorPoint = Vector2.new(1, 0)
	frame28.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame28.BorderColor3 = Color3.new()
	frame28.BorderSizePixel = 0
	frame28.ClipsDescendants = true
	frame28.Position = UDim2.fromScale(1, 0)
	frame28.Size = UDim2.fromScale(1, 1)
	frame28.ZIndex = 9000018
	local textBox = Instance.new("TextBox")
	textBox.AnchorPoint = Vector2.new(1, 0)
	textBox.BackgroundTransparency = 1
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromScale(1, 0)
	textBox.Size = UDim2.new(1, -6, 1, 0)
	textBox.Text = "#FFFFFF"
	textBox.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox.TextSize = 14
	textBox.TextTruncate = Enum.TextTruncate.AtEnd
	textBox.ZIndex = 9000027
	textBox.Parent = frame28
	local uIAspectRatioConstraint5 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint5.AspectRatio = 3
	uIAspectRatioConstraint5.Parent = frame28
	local uIStroke4 = Instance.new("UIStroke")
	uIStroke4.Transparency = 0.6
	uIStroke4.Parent = frame28
	frame28.Parent = frame25
	frame25.Parent = frame8
	local uIListLayout5 = Instance.new("UIListLayout")
	uIListLayout5.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout5.Parent = frame8
	frame8.Parent = frame7
	local textButton6 = Instance.new("TextButton")
	textButton6.Name = "BG"
	textButton6.Active = false
	textButton6.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton6.AutoButtonColor = false
	textButton6.BackgroundColor3 = Color3.fromRGB(42, 42, 42)
	textButton6.BorderColor3 = Color3.new()
	textButton6.BorderSizePixel = 0
	textButton6.Position = UDim2.fromScale(0.5, 0.5)
	textButton6.Selectable = false
	textButton6.Size = UDim2.new(1, -4, 1, -2)
	textButton6.Text = ""
	textButton6.ZIndex = 8999998
	local uIStroke_3 = Instance.new("UIStroke")
	uIStroke_3.Parent = textButton6
	textButton6.Parent = frame7
	frame7.Parent = frame4
	local frame29 = Instance.new("Frame")
	frame29.Name = "NonEnabled"
	frame29.BackgroundColor3 = Color3.new(1, 1, 1)
	frame29.BackgroundTransparency = 0.9
	frame29.BorderColor3 = Color3.new()
	frame29.BorderSizePixel = 0
	frame29.Size = UDim2.fromScale(1, 1)
	frame29.Visible = false
	frame29.ZIndex = 900
	frame29.Parent = frame4
	frame4.Parent = frame
	local frame30 = Instance.new("Frame")
	frame30.Name = "WhiteFrame"
	frame30.BackgroundTransparency = 1
	frame30.Size = UDim2.fromScale(1, 1)
	frame30.ZIndex = 50
	frame30.Parent = frame
	return frame
end