return function()
	local frame = Instance.new("Frame")
	frame.Name = "Dropdown"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Position Y"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local frame5 = Instance.new("Frame")
	frame5.Name = "DropdownCtn"
	frame5.BackgroundColor3 = Color3.fromRGB(83, 83, 83)
	frame5.BorderColor3 = Color3.fromRGB(29, 32, 35)
	frame5.BorderMode = Enum.BorderMode.Inset
	frame5.Size = UDim2.fromScale(1, 1)
	frame5.ZIndex = 30
	local frame6 = Instance.new("Frame")
	frame6.Name = "Icon"
	frame6.AnchorPoint = Vector2.new(1, 0)
	frame6.BackgroundTransparency = 1
	frame6.Position = UDim2.fromScale(1, 0)
	frame6.Size = UDim2.fromScale(1, 1)
	frame6.ZIndex = 32
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.Parent = frame6
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "Logo"
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxassetid://80986199235506"
	imageLabel.ImageTransparency = 0.4
	imageLabel.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel.Rotation = 180
	imageLabel.Size = UDim2.fromScale(0.8, 0.8)
	imageLabel.ZIndex = 32
	imageLabel.Parent = frame6
	frame6.Parent = frame5
	local uIGradient = Instance.new("UIGradient")
	uIGradient.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(186, 186, 186)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(84, 96, 103))
	})
	uIGradient.Rotation = 90
	uIGradient.Parent = frame5
	local frame7 = Instance.new("Frame")
	frame7.Name = "Content"
	frame7.BackgroundTransparency = 1
	frame7.BorderMode = Enum.BorderMode.Inset
	frame7.ClipsDescendants = true
	frame7.Position = UDim2.fromScale(0, 1)
	frame7.SelectionGroup = true
	frame7.Size = UDim2.fromScale(1, 4)
	frame7.Visible = false
	local frame8 = Instance.new("Frame")
	frame8.Name = "Borders"
	frame8.AnchorPoint = Vector2.new(0.5, 0)
	frame8.BackgroundColor3 = Color3.fromRGB(29, 32, 35)
	frame8.BorderColor3 = Color3.new()
	frame8.BorderSizePixel = 0
	frame8.Position = UDim2.fromScale(0.5, 0)
	frame8.Size = UDim2.new(1, 2, 1, 1)
	frame8.ZIndex = 8999994
	frame8.Parent = frame7
	local frame9 = Instance.new("Frame")
	frame9.Name = "BG"
	frame9.BackgroundColor3 = Color3.fromRGB(42, 42, 42)
	frame9.BorderColor3 = Color3.new()
	frame9.BorderSizePixel = 0
	frame9.Size = UDim2.fromScale(1, 1)
	frame9.ZIndex = 8999998
	frame9.Parent = frame7
	local scrollingFrame = Instance.new("ScrollingFrame")
	scrollingFrame.Name = "InnerContent"
	scrollingFrame.BackgroundTransparency = 1
	scrollingFrame.BorderMode = Enum.BorderMode.Inset
	scrollingFrame.BottomImage = "rbxassetid://97294892232031"
	scrollingFrame.CanvasSize = UDim2.fromScale(0, 20)
	scrollingFrame.MidImage = "rbxassetid://97294892232031"
	scrollingFrame.ScrollBarImageTransparency = 0.8
	scrollingFrame.Selectable = false
	scrollingFrame.Size = UDim2.fromScale(1, 1)
	scrollingFrame.TopImage = "rbxassetid://97294892232031"
	scrollingFrame.ZIndex = 9000000
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = scrollingFrame
	local frame10 = Instance.new("Frame")
	frame10.Name = "Item"
	frame10.BackgroundTransparency = 1
	frame10.Size = UDim2.new(1, 0, 0, 20)
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new("rbxasset://fonts/families/RobotoCondensed.json")
	textLabel2.Position = UDim2.fromScale(0.5, 0.5)
	textLabel2.Size = UDim2.new(1, -8, 1, 0)
	textLabel2.Text = "Choice 1"
	textLabel2.TextColor3 = Color3.new(1, 1, 1)
	textLabel2.TextSize = 12
	textLabel2.TextTruncate = Enum.TextTruncate.AtEnd
	textLabel2.TextWrapped = true
	textLabel2.TextXAlignment = Enum.TextXAlignment.Left
	textLabel2.ZIndex = 9000001
	textLabel2.Parent = frame10
	local textButton = Instance.new("TextButton")
	textButton.AutoButtonColor = false
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 654653454
	textButton.Parent = frame10
	frame10.Parent = scrollingFrame
	scrollingFrame.Parent = frame7
	local frame11 = Instance.new("Frame")
	frame11.Name = "ScrollBG"
	frame11.AnchorPoint = Vector2.new(1, 0)
	frame11.BackgroundColor3 = Color3.new()
	frame11.BackgroundTransparency = 0.8
	frame11.BorderColor3 = Color3.new()
	frame11.BorderSizePixel = 0
	frame11.Position = UDim2.fromScale(1, 0)
	frame11.Size = UDim2.new(0, 12, 1, 0)
	frame11.ZIndex = 8999998
	frame11.Parent = frame7
	frame7.Parent = frame5
	local textBox = Instance.new("TextBox")
	textBox.Active = false
	textBox.AnchorPoint = Vector2.new(0, 0.5)
	textBox.BackgroundTransparency = 1
	textBox.FontFace = Font.new("rbxasset://fonts/families/RobotoCondensed.json")
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.new(0, 4, 0.5, 0)
	textBox.Selectable = false
	textBox.Size = UDim2.new(1, -21, 1, 0)
	textBox.Text = "Choice 1"
	textBox.TextColor3 = Color3.new(1, 1, 1)
	textBox.TextSize = 12
	textBox.TextTruncate = Enum.TextTruncate.AtEnd
	textBox.TextWrapped = true
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.ZIndex = 31
	textBox.Parent = frame5
	frame5.Parent = frame4
	local frame12 = Instance.new("Frame")
	frame12.Name = "Overlay"
	frame12.AnchorPoint = Vector2.new(0.5, 0.5)
	frame12.BackgroundColor3 = Color3.fromRGB(157, 157, 157)
	frame12.BackgroundTransparency = 0.8
	frame12.BorderColor3 = Color3.new()
	frame12.BorderSizePixel = 0
	frame12.Position = UDim2.fromScale(0.5, 0.5)
	frame12.Size = UDim2.fromScale(1, 1)
	frame12.Visible = false
	frame12.ZIndex = 40
	frame12.Parent = frame4
	frame4.Parent = frame
	local frame13 = Instance.new("Frame")
	frame13.Name = "WhiteFrame"
	frame13.BackgroundTransparency = 1
	frame13.Size = UDim2.fromScale(1, 1)
	frame13.ZIndex = 50
	frame13.Parent = frame
	return frame
end