return function()
	local frame = Instance.new("Frame")
	frame.Name = "Expandable"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.BorderSizePixel = 0
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	local frame2 = Instance.new("Frame")
	frame2.Name = "Top"
	frame2.AnchorPoint = Vector2.new(1, 0)
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Position = UDim2.fromScale(1, 0)
	frame2.Size = UDim2.new(1, 0, 0, 22)
	frame2.ZIndex = 15
	local frame3 = Instance.new("Frame")
	frame3.Name = "Ctn"
	frame3.BackgroundColor3 = Color3.fromRGB(83, 83, 83)
	frame3.BorderColor3 = Color3.fromRGB(29, 32, 35)
	frame3.BorderMode = Enum.BorderMode.Inset
	frame3.Size = UDim2.fromScale(1, 1)
	frame3.ZIndex = 30
	local frame4 = Instance.new("Frame")
	frame4.Name = "Icon"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundTransparency = 1
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Rotation = 90
	frame4.Size = UDim2.fromScale(1, 1)
	frame4.ZIndex = 32
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.Parent = frame4
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "Logo"
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxassetid://80986199235506"
	imageLabel.ImageTransparency = 0.4
	imageLabel.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel.Rotation = 180
	imageLabel.Size = UDim2.fromScale(0.8, 0.8)
	imageLabel.ZIndex = 32
	imageLabel.Parent = frame4
	frame4.Parent = frame3
	local uIGradient = Instance.new("UIGradient")
	uIGradient.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(186, 186, 186)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(84, 96, 103))
	})
	uIGradient.Rotation = 90
	uIGradient.Parent = frame3
	local textLabel = Instance.new("TextLabel")
	textLabel.AnchorPoint = Vector2.new(0, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel.Position = UDim2.new(0, 6, 0.5, 0)
	textLabel.Size = UDim2.new(1, -25, 1, 0)
	textLabel.Text = "Expendable Title"
	textLabel.TextColor3 = Color3.fromRGB(230, 230, 230)
	textLabel.TextSize = 14
	textLabel.TextTruncate = Enum.TextTruncate.AtEnd
	textLabel.TextWrapped = true
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 31
	textLabel.Parent = frame3
	frame3.Parent = frame2
	local frame5 = Instance.new("Frame")
	frame5.Name = "WhiteFrame"
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BackgroundTransparency = 0.85
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Size = UDim2.fromScale(1, 1)
	frame5.Visible = false
	frame5.ZIndex = 50
	frame5.Parent = frame2
	local textButton = Instance.new("TextButton")
	textButton.Name = "Interactibility"
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 1000
	textButton.Parent = frame2
	frame2.Parent = frame
	local frame6 = Instance.new("Frame")
	frame6.Name = "Content"
	frame6.BackgroundColor3 = Color3.new()
	frame6.BackgroundTransparency = 0.75
	frame6.BorderColor3 = Color3.new()
	frame6.BorderSizePixel = 0
	frame6.Position = UDim2.fromOffset(0, 22)
	frame6.Size = UDim2.fromScale(1, 0)
	local frame7 = Instance.new("Frame")
	frame7.Name = "InnerContent"
	frame7.BackgroundTransparency = 1
	frame7.ClipsDescendants = true
	frame7.Size = UDim2.new(1, 0, 1, 150)
	local frame8 = Instance.new("Frame")
	frame8.Name = "DeepContent"
	frame8.BackgroundTransparency = 1
	frame8.Size = UDim2.new(1, 0, 1, -150)
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.VerticalAlignment = Enum.VerticalAlignment.Bottom
	uIListLayout.Parent = frame8
	frame8.Parent = frame7
	frame7.Parent = frame6
	frame6.Parent = frame
	return frame
end