return function()
	local frame = Instance.new("Frame")
	frame.Name = "Field"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Position Y"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.ClipsDescendants = true
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local textBox = Instance.new("TextBox")
	textBox.AnchorPoint = Vector2.new(1, 0)
	textBox.BackgroundTransparency = 1
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromScale(1, 0)
	textBox.Size = UDim2.new(1, -6, 1, 0)
	textBox.Text = ""
	textBox.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox.TextSize = 14
	textBox.TextTruncate = Enum.TextTruncate.AtEnd
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.ZIndex = 800
	textBox.Parent = frame4
	local frame5 = Instance.new("Frame")
	frame5.Name = "NonEnabled"
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BackgroundTransparency = 0.9
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Size = UDim2.fromScale(1, 1)
	frame5.ZIndex = 900
	frame5.Parent = frame4
	frame4.Parent = frame
	local frame6 = Instance.new("Frame")
	frame6.Name = "WhiteFrame"
	frame6.BackgroundTransparency = 1
	frame6.Size = UDim2.fromScale(1, 1)
	frame6.ZIndex = 50
	frame6.Parent = frame
	return frame
end