return function()
	local frame = Instance.new("Frame")
	frame.Name = "Graph"
	frame.BackgroundTransparency = 1
	frame.Size = UDim2.new(1, 0, 0, 140)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "BG"
	frame2.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.fromScale(1, 1)
	frame2.ZIndex = 3
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "Content"
	frame3.BackgroundColor3 = Color3.new(1, 1, 1)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Size = UDim2.fromScale(1, 1)
	local frame4 = Instance.new("Frame")
	frame4.Name = "Top"
	frame4.BackgroundColor3 = Color3.fromRGB(44, 44, 44)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Size = UDim2.new(1, 0, 0, 18)
	frame4.ZIndex = 3
	local textLabel = Instance.new("TextLabel")
	textLabel.Active = true
	textLabel.AnchorPoint = Vector2.new(0, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxassetid://16658246179")
	textLabel.Position = UDim2.new(0, 6, 0.5, 0)
	textLabel.Selectable = true
	textLabel.Size = UDim2.new(1, -6, 0, 12)
	textLabel.Text = "Graph - Size"
	textLabel.TextColor3 = Color3.new(1, 1, 1)
	textLabel.TextSize = 12
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 5
	textLabel.Parent = frame4
	local frame5 = Instance.new("Frame")
	frame5.Name = "ButtonCtn"
	frame5.AnchorPoint = Vector2.new(0.5, 0.5)
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Position = UDim2.fromScale(0.5, 0.5)
	frame5.Size = UDim2.new(1, -4, 1, -2)
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.Name = "Linear"
	textButton.BackgroundColor3 = Color3.fromRGB(68, 72, 90)
	textButton.BorderColor3 = Color3.new()
	textButton.BorderSizePixel = 0
	textButton.FontFace = Font.new("rbxassetid://16658246179")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new(1, 1, 1)
	textButton.TextSize = 12
	textButton.ZIndex = 10
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.Parent = textButton
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Active = true
	textLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new("rbxassetid://16658246179", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	textLabel2.Position = UDim2.new(0.5, 1, 0.5, 1)
	textLabel2.Selectable = true
	textLabel2.Size = UDim2.fromScale(1, 1)
	textLabel2.Text = "R"
	textLabel2.TextColor3 = Color3.new(1, 1, 1)
	textLabel2.TextSize = 12
	textLabel2.ZIndex = 10
	textLabel2.Parent = textButton
	textButton.Parent = frame5
	frame5.Parent = frame4
	frame4.Parent = frame3
	local frame6 = Instance.new("Frame")
	frame6.Name = "Mid"
	frame6.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
	frame6.BorderColor3 = Color3.new()
	frame6.BorderSizePixel = 0
	frame6.LayoutOrder = 5
	frame6.Size = UDim2.new(1, 0, 0, 18)
	frame6.ZIndex = 3
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = frame6
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "MouseInteraction"
	textButton2.BackgroundTransparency = 1
	textButton2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.TextColor3 = Color3.new()
	textButton2.TextSize = 14
	textButton2.ZIndex = 4000
	textButton2.Parent = frame6
	local frame7 = Instance.new("Frame")
	frame7.Name = "InnerContent"
	frame7.AnchorPoint = Vector2.new(0.5, 0.5)
	frame7.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
	frame7.BorderColor3 = Color3.new()
	frame7.BorderSizePixel = 0
	frame7.ClipsDescendants = true
	frame7.Position = UDim2.fromScale(0.5, 0.5)
	frame7.Size = UDim2.new(1, -6, 1, -6)
	frame7.ZIndex = 5
	local frame8 = Instance.new("Frame")
	frame8.Name = "GraphContainer"
	frame8.AnchorPoint = Vector2.new(0.5, 0.5)
	frame8.BackgroundColor3 = Color3.new(1, 1, 1)
	frame8.BorderColor3 = Color3.new()
	frame8.BorderSizePixel = 0
	frame8.Position = UDim2.fromScale(0.5, 0.5)
	frame8.Size = UDim2.fromScale(1, 0.7)
	local folder = Instance.new("Folder")
	folder.Name = "Deco"
	local frame9 = Instance.new("Frame")
	frame9.Name = "X0.25"
	frame9.AnchorPoint = Vector2.new(0.5, 0.5)
	frame9.BackgroundColor3 = Color3.new(1, 1, 1)
	frame9.BackgroundTransparency = 0.95
	frame9.BorderColor3 = Color3.new()
	frame9.BorderSizePixel = 0
	frame9.Position = UDim2.fromScale(0.25, 0.5)
	frame9.Size = UDim2.new(0, 1, 10, 0)
	frame9.ZIndex = 10
	frame9.Parent = folder
	local frame10 = Instance.new("Frame")
	frame10.Name = "X0.5"
	frame10.AnchorPoint = Vector2.new(0.5, 0.5)
	frame10.BackgroundColor3 = Color3.new(1, 1, 1)
	frame10.BackgroundTransparency = 0.95
	frame10.BorderColor3 = Color3.new()
	frame10.BorderSizePixel = 0
	frame10.Position = UDim2.fromScale(0.5, 0.5)
	frame10.Size = UDim2.new(0, 1, 10, 0)
	frame10.ZIndex = 10
	frame10.Parent = folder
	local frame11 = Instance.new("Frame")
	frame11.Name = "X0.75"
	frame11.AnchorPoint = Vector2.new(0.5, 0.5)
	frame11.BackgroundColor3 = Color3.new(1, 1, 1)
	frame11.BackgroundTransparency = 0.95
	frame11.BorderColor3 = Color3.new()
	frame11.BorderSizePixel = 0
	frame11.Position = UDim2.fromScale(0.75, 0.5)
	frame11.Size = UDim2.new(0, 1, 10, 0)
	frame11.ZIndex = 10
	frame11.Parent = folder
	local frame12 = Instance.new("Frame")
	frame12.Name = "Y1"
	frame12.AnchorPoint = Vector2.new(0.5, 0.5)
	frame12.BackgroundColor3 = Color3.fromRGB(148, 189, 255)
	frame12.BackgroundTransparency = 0.6
	frame12.BorderColor3 = Color3.new()
	frame12.BorderSizePixel = 0
	frame12.Position = UDim2.fromScale(0.5, 0)
	frame12.Size = UDim2.new(10, 0, 0, 1)
	frame12.ZIndex = 10
	frame12.Parent = folder
	local frame13 = Instance.new("Frame")
	frame13.Name = "Y0"
	frame13.AnchorPoint = Vector2.new(0.5, 0.5)
	frame13.BackgroundColor3 = Color3.fromRGB(148, 189, 255)
	frame13.BackgroundTransparency = 0.6
	frame13.BorderColor3 = Color3.new()
	frame13.BorderSizePixel = 0
	frame13.Position = UDim2.fromScale(0.5, 1)
	frame13.Size = UDim2.new(10, 0, 0, 1)
	frame13.ZIndex = 10
	frame13.Parent = folder
	folder.Parent = frame8
	local frame14 = Instance.new("Frame")
	frame14.Name = "Start"
	frame14.AnchorPoint = Vector2.new(0.5, 0.5)
	frame14.BackgroundColor3 = Color3.fromRGB(123, 180, 255)
	frame14.Position = UDim2.fromScale(0, 1)
	frame14.Size = UDim2.fromOffset(10, 10)
	frame14.ZIndex = 15
	local uICorner = Instance.new("UICorner")
	uICorner.Parent = frame14
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Thickness = 2
	uIStroke.Parent = frame14
	frame14.Parent = frame8
	local frame15 = Instance.new("Frame")
	frame15.Name = "End"
	frame15.AnchorPoint = Vector2.new(0.5, 0.5)
	frame15.BackgroundColor3 = Color3.fromRGB(123, 180, 255)
	frame15.Position = UDim2.fromScale(1, 0)
	frame15.Size = UDim2.fromOffset(10, 10)
	frame15.ZIndex = 15
	local uICorner_2 = Instance.new("UICorner")
	uICorner_2.Parent = frame15
	local uIStroke2 = Instance.new("UIStroke")
	uIStroke2.Thickness = 2
	uIStroke2.Parent = frame15
	frame15.Parent = frame8
	local folder2 = Instance.new("Folder")
	folder2.Name = "Curve"
	folder2.Parent = frame8
	local folder3 = Instance.new("Folder")
	folder3.Name = "ControlPoints"
	local frame16 = Instance.new("Frame")
	frame16.Name = "Start"
	frame16.AnchorPoint = Vector2.new(0.5, 0.5)
	frame16.BackgroundColor3 = Color3.fromRGB(179, 255, 184)
	frame16.Position = UDim2.fromScale(0.5, 1)
	frame16.Size = UDim2.fromOffset(10, 10)
	frame16.ZIndex = 15
	local uICorner_3 = Instance.new("UICorner")
	uICorner_3.Parent = frame16
	local uIStroke3 = Instance.new("UIStroke")
	uIStroke3.Thickness = 2
	uIStroke3.Parent = frame16
	frame16.Parent = folder3
	local frame17 = Instance.new("Frame")
	frame17.Name = "End"
	frame17.AnchorPoint = Vector2.new(0.5, 0.5)
	frame17.BackgroundColor3 = Color3.fromRGB(255, 197, 197)
	frame17.Position = UDim2.fromScale(0.5, 0)
	frame17.Size = UDim2.fromOffset(10, 10)
	frame17.ZIndex = 15
	local uICorner_4 = Instance.new("UICorner")
	uICorner_4.Parent = frame17
	local uIStroke4 = Instance.new("UIStroke")
	uIStroke4.Thickness = 2
	uIStroke4.Parent = frame17
	frame17.Parent = folder3
	local frame18 = Instance.new("Frame")
	frame18.Name = "EndLine"
	frame18.BackgroundColor3 = Color3.new(1, 1, 1)
	frame18.BorderColor3 = Color3.new()
	frame18.BorderSizePixel = 0
	frame18.Position = UDim2.fromScale(0.5, 0)
	frame18.Size = UDim2.new(0.5, 0, 0, 1)
	frame18.ZIndex = 12
	frame18.Parent = folder3
	local frame19 = Instance.new("Frame")
	frame19.Name = "StartLine"
	frame19.BackgroundColor3 = Color3.new(1, 1, 1)
	frame19.BorderColor3 = Color3.new()
	frame19.BorderSizePixel = 0
	frame19.Position = UDim2.fromScale(0, 1)
	frame19.Size = UDim2.new(0.5, 0, 0, 1)
	frame19.ZIndex = 12
	frame19.Parent = folder3
	folder3.Parent = frame8
	frame8.Parent = frame7
	frame7.Parent = frame6
	frame6.Parent = frame3
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = frame3
	frame3.Parent = frame
	return frame
end