return function()
	local frame = Instance.new("Frame")
	frame.Name = "RichTextEditor"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 44)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "Top"
	frame2.BackgroundColor3 = Color3.new(1, 1, 1)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.LayoutOrder = -1
	frame2.Size = UDim2.new(1, 0, 0, 22)
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = frame2
	local frame3 = Instance.new("Frame")
	frame3.Name = "Bold"
	frame3.BackgroundTransparency = 1
	frame3.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_2.Parent = frame3
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.Name = "Icon"
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxassetid://136520094118200"
	imageLabel.ImageColor3 = Color3.fromRGB(193, 193, 193)
	imageLabel.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel.ResampleMode = Enum.ResamplerMode.Pixelated
	imageLabel.Size = UDim2.fromOffset(19, 19)
	imageLabel.Parent = frame3
	local textButton = Instance.new("TextButton")
	textButton.Name = "Interactibility"
	textButton.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Position = UDim2.fromScale(0.5, 0.5)
	textButton.Size = UDim2.fromOffset(19, 19)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 100
	textButton.Parent = frame3
	frame3.Parent = frame2
	local frame4 = Instance.new("Frame")
	frame4.Name = "Italic"
	frame4.BackgroundTransparency = 1
	frame4.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_3 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_3.Parent = frame4
	local imageLabel2 = Instance.new("ImageLabel")
	imageLabel2.Name = "Icon"
	imageLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel2.BackgroundTransparency = 1
	imageLabel2.Image = "rbxassetid://116924037406715"
	imageLabel2.ImageColor3 = Color3.fromRGB(193, 193, 193)
	imageLabel2.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel2.ResampleMode = Enum.ResamplerMode.Pixelated
	imageLabel2.Size = UDim2.fromOffset(19, 19)
	imageLabel2.Parent = frame4
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "Interactibility"
	textButton2.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton2.BackgroundTransparency = 1
	textButton2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton2.Position = UDim2.fromScale(0.5, 0.5)
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.TextColor3 = Color3.new()
	textButton2.TextSize = 14
	textButton2.ZIndex = 100
	textButton2.Parent = frame4
	frame4.Parent = frame2
	local frame5 = Instance.new("Frame")
	frame5.Name = "Underlined"
	frame5.BackgroundTransparency = 1
	frame5.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_4 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_4.Parent = frame5
	local imageLabel3 = Instance.new("ImageLabel")
	imageLabel3.Name = "Icon"
	imageLabel3.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel3.BackgroundTransparency = 1
	imageLabel3.Image = "rbxassetid://75881124683860"
	imageLabel3.ImageColor3 = Color3.fromRGB(193, 193, 193)
	imageLabel3.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel3.ResampleMode = Enum.ResamplerMode.Pixelated
	imageLabel3.Size = UDim2.fromOffset(19, 19)
	imageLabel3.Parent = frame5
	local textButton3 = Instance.new("TextButton")
	textButton3.Name = "Interactibility"
	textButton3.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton3.BackgroundTransparency = 1
	textButton3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton3.Position = UDim2.fromScale(0.5, 0.5)
	textButton3.Size = UDim2.fromScale(1, 1)
	textButton3.Text = ""
	textButton3.TextColor3 = Color3.new()
	textButton3.TextSize = 14
	textButton3.ZIndex = 100
	textButton3.Parent = frame5
	frame5.Parent = frame2
	local frame6 = Instance.new("Frame")
	frame6.Name = "FontColor"
	frame6.BackgroundTransparency = 1
	frame6.LayoutOrder = 10
	frame6.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_5 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_5.Parent = frame6
	local imageLabel4 = Instance.new("ImageLabel")
	imageLabel4.Name = "Icon"
	imageLabel4.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel4.BackgroundTransparency = 1
	imageLabel4.Image = "rbxassetid://120934513616003"
	imageLabel4.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel4.ResampleMode = Enum.ResamplerMode.Pixelated
	imageLabel4.Size = UDim2.fromOffset(19, 19)
	imageLabel4.Parent = frame6
	local textButton4 = Instance.new("TextButton")
	textButton4.Name = "Interactibility"
	textButton4.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton4.BackgroundTransparency = 1
	textButton4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton4.Position = UDim2.fromScale(0.5, 0.5)
	textButton4.Size = UDim2.fromScale(1, 1)
	textButton4.Text = ""
	textButton4.TextColor3 = Color3.new()
	textButton4.TextSize = 14
	textButton4.ZIndex = 100
	textButton4.Parent = frame6
	frame6.Parent = frame2
	local frame7 = Instance.new("Frame")
	frame7.Name = "InBetween"
	frame7.BackgroundTransparency = 1
	frame7.LayoutOrder = 99
	frame7.Size = UDim2.fromScale(1, 1)
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = frame7
	local textLabel = Instance.new("TextLabel")
	textLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel.Position = UDim2.fromScale(0.5, 0.5)
	textLabel.Size = UDim2.new(1, -8, 1, -7)
	textLabel.Text = "Dialog - Quatuar"
	textLabel.TextColor3 = Color3.fromRGB(213, 213, 213)
	textLabel.TextScaled = true
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Transparency = 0.8
	uIStroke.Parent = textLabel
	textLabel.Parent = frame7
	frame7.Parent = frame2
	local frame8 = Instance.new("Frame")
	frame8.Name = "Preview"
	frame8.BackgroundTransparency = 1
	frame8.LayoutOrder = 100
	frame8.Size = UDim2.fromScale(1, 1)
	frame8.Visible = false
	local uIAspectRatioConstraint_6 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_6.Parent = frame8
	local imageLabel5 = Instance.new("ImageLabel")
	imageLabel5.Name = "Icon"
	imageLabel5.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel5.BackgroundTransparency = 1
	imageLabel5.Image = "rbxassetid://96780248168539"
	imageLabel5.ImageColor3 = Color3.fromRGB(193, 193, 193)
	imageLabel5.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel5.ResampleMode = Enum.ResamplerMode.Pixelated
	imageLabel5.Size = UDim2.fromOffset(19, 19)
	imageLabel5.Parent = frame8
	local textButton5 = Instance.new("TextButton")
	textButton5.Name = "Interactibility"
	textButton5.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton5.BackgroundTransparency = 1
	textButton5.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton5.Position = UDim2.fromScale(0.5, 0.5)
	textButton5.Size = UDim2.fromScale(1, 1)
	textButton5.Text = ""
	textButton5.TextColor3 = Color3.new()
	textButton5.TextSize = 14
	textButton5.ZIndex = 100
	textButton5.Parent = frame8
	frame8.Parent = frame2
	local uIGradient = Instance.new("UIGradient")
	uIGradient.Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(54, 54, 54)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(40, 40, 40))
	})
	uIGradient.Rotation = 90
	uIGradient.Parent = frame2
	local frame9 = Instance.new("Frame")
	frame9.Name = "ColorBox"
	frame9.BackgroundTransparency = 1
	frame9.LayoutOrder = 11
	frame9.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.AspectRatio = 3.7
	uIAspectRatioConstraint.Parent = frame9
	local textBox = Instance.new("TextBox")
	textBox.AnchorPoint = Vector2.new(0.5, 0.5)
	textBox.BackgroundColor3 = Color3.fromRGB(33, 33, 33)
	textBox.BorderColor3 = Color3.fromRGB(18, 18, 18)
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromScale(0.5, 0.5)
	textBox.Size = UDim2.new(1, -4, 1, -4)
	textBox.Text = "255, 255, 255"
	textBox.TextColor3 = Color3.fromRGB(221, 221, 221)
	textBox.TextSize = 15
	textBox.ZIndex = 30
	textBox.Parent = frame9
	frame9.Parent = frame2
	frame2.Parent = frame
	local frame10 = Instance.new("Frame")
	frame10.Name = "Content"
	frame10.BackgroundColor3 = Color3.new(1, 1, 1)
	frame10.BackgroundTransparency = 0.95
	frame10.BorderColor3 = Color3.new()
	frame10.BorderSizePixel = 0
	frame10.LayoutOrder = 1
	frame10.Size = UDim2.new(1, 0, 0, 22)
	local uIFlexItem2 = Instance.new("UIFlexItem")
	uIFlexItem2.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem2.Parent = frame10
	local textBox2 = Instance.new("TextBox")
	textBox2.AnchorPoint = Vector2.new(0.5, 0.5)
	textBox2.BackgroundTransparency = 1
	textBox2.ClearTextOnFocus = false
	textBox2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox2.MultiLine = true
	textBox2.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox2.Position = UDim2.fromScale(0.5, 0.5)
	textBox2.RichText = true
	textBox2.Size = UDim2.new(1, -8, 1, -4)
	textBox2.Text = "This is a test of a text for testing"
	textBox2.TextColor3 = Color3.fromRGB(221, 221, 221)
	textBox2.TextSize = 15
	textBox2.TextWrapped = true
	textBox2.TextXAlignment = Enum.TextXAlignment.Left
	textBox2.TextYAlignment = Enum.TextYAlignment.Top
	textBox2.Parent = frame10
	frame10.Parent = frame
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = frame
	local frame11 = Instance.new("Frame")
	frame11.Name = "Separator"
	frame11.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame11.BorderColor3 = Color3.new()
	frame11.BorderSizePixel = 0
	frame11.Size = UDim2.new(1, 0, 0, 1)
	frame11.Parent = frame
	return frame
end