return function()
	local frame = Instance.new("Frame")
	frame.Name = "SequenceEditor"
	frame.BackgroundTransparency = 1
	frame.Size = UDim2.new(1, 0, 0, 140)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "BG"
	frame2.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.fromScale(1, 1)
	frame2.ZIndex = 3
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "Content"
	frame3.BackgroundColor3 = Color3.new(1, 1, 1)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Size = UDim2.fromScale(1, 1)
	local frame4 = Instance.new("Frame")
	frame4.Name = "Top"
	frame4.BackgroundColor3 = Color3.fromRGB(44, 44, 44)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Size = UDim2.new(1, 0, 0, 18)
	frame4.ZIndex = 3
	local textLabel = Instance.new("TextLabel")
	textLabel.Active = true
	textLabel.AnchorPoint = Vector2.new(0, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxassetid://16658246179")
	textLabel.Position = UDim2.new(0, 6, 0.5, 0)
	textLabel.Selectable = true
	textLabel.Size = UDim2.new(1, -6, 0, 12)
	textLabel.Text = "Graph - Size"
	textLabel.TextColor3 = Color3.new(1, 1, 1)
	textLabel.TextSize = 12
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 5
	textLabel.Parent = frame4
	local frame5 = Instance.new("Frame")
	frame5.Name = "ButtonCtn"
	frame5.AnchorPoint = Vector2.new(0.5, 0.5)
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Position = UDim2.fromScale(0.5, 0.5)
	frame5.Size = UDim2.new(1, -4, 1, -2)
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.Name = "Refresh"
	textButton.BackgroundColor3 = Color3.fromRGB(68, 72, 90)
	textButton.BorderColor3 = Color3.new()
	textButton.BorderSizePixel = 0
	textButton.FontFace = Font.new("rbxassetid://16658246179")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new(1, 1, 1)
	textButton.TextSize = 12
	textButton.ZIndex = 10
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.Parent = textButton
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Active = true
	textLabel2.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new("rbxassetid://16658246179", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	textLabel2.Position = UDim2.new(0.5, 1, 0.5, 1)
	textLabel2.Selectable = true
	textLabel2.Size = UDim2.fromScale(1, 1)
	textLabel2.Text = "R"
	textLabel2.TextColor3 = Color3.new(1, 1, 1)
	textLabel2.TextSize = 12
	textLabel2.ZIndex = 10
	textLabel2.Parent = textButton
	textButton.Parent = frame5
	frame5.Parent = frame4
	frame4.Parent = frame3
	local frame6 = Instance.new("Frame")
	frame6.Name = "Mid"
	frame6.BackgroundColor3 = Color3.fromRGB(38, 38, 38)
	frame6.BorderColor3 = Color3.new()
	frame6.BorderSizePixel = 0
	frame6.LayoutOrder = 5
	frame6.Size = UDim2.new(1, 0, 0, 18)
	frame6.ZIndex = 3
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = frame6
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "MouseInteraction"
	textButton2.BackgroundTransparency = 1
	textButton2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.TextColor3 = Color3.new()
	textButton2.TextSize = 14
	textButton2.ZIndex = 4000
	textButton2.Parent = frame6
	local frame7 = Instance.new("Frame")
	frame7.Name = "InnerContent"
	frame7.AnchorPoint = Vector2.new(0.5, 0.5)
	frame7.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
	frame7.BorderColor3 = Color3.new()
	frame7.BorderSizePixel = 0
	frame7.ClipsDescendants = true
	frame7.Position = UDim2.fromScale(0.5, 0.5)
	frame7.Size = UDim2.new(1, -6, 0.9, -6)
	frame7.ZIndex = 5
	local frame8 = Instance.new("Frame")
	frame8.Name = "SequenceContainer"
	frame8.AnchorPoint = Vector2.new(0.5, 0.5)
	frame8.BackgroundColor3 = Color3.new(1, 1, 1)
	frame8.BorderColor3 = Color3.new()
	frame8.BorderSizePixel = 0
	frame8.Position = UDim2.fromScale(0.5, 0.5)
	frame8.Size = UDim2.fromScale(1, 1)
	local folder = Instance.new("Folder")
	folder.Name = "Deco"
	local frame9 = Instance.new("Frame")
	frame9.Name = "X0.25"
	frame9.AnchorPoint = Vector2.new(0.5, 0.5)
	frame9.BackgroundColor3 = Color3.new(1, 1, 1)
	frame9.BackgroundTransparency = 0.85
	frame9.BorderColor3 = Color3.new()
	frame9.BorderSizePixel = 0
	frame9.Position = UDim2.fromScale(0.25, 0.5)
	frame9.Size = UDim2.new(0, 1, 10, 0)
	frame9.ZIndex = 10
	frame9.Parent = folder
	local frame10 = Instance.new("Frame")
	frame10.Name = "X0.5"
	frame10.AnchorPoint = Vector2.new(0.5, 0.5)
	frame10.BackgroundColor3 = Color3.new(1, 1, 1)
	frame10.BackgroundTransparency = 0.85
	frame10.BorderColor3 = Color3.new()
	frame10.BorderSizePixel = 0
	frame10.Position = UDim2.fromScale(0.5, 0.5)
	frame10.Size = UDim2.new(0, 1, 10, 0)
	frame10.ZIndex = 10
	frame10.Parent = folder
	local frame11 = Instance.new("Frame")
	frame11.Name = "X0.75"
	frame11.AnchorPoint = Vector2.new(0.5, 0.5)
	frame11.BackgroundColor3 = Color3.new(1, 1, 1)
	frame11.BackgroundTransparency = 0.85
	frame11.BorderColor3 = Color3.new()
	frame11.BorderSizePixel = 0
	frame11.Position = UDim2.fromScale(0.75, 0.5)
	frame11.Size = UDim2.new(0, 1, 10, 0)
	frame11.ZIndex = 10
	frame11.Parent = folder
	local frame12 = Instance.new("Frame")
	frame12.Name = "Y1"
	frame12.AnchorPoint = Vector2.new(0.5, 0.5)
	frame12.BackgroundColor3 = Color3.fromRGB(148, 189, 255)
	frame12.BackgroundTransparency = 0.6
	frame12.BorderColor3 = Color3.new()
	frame12.BorderSizePixel = 0
	frame12.Position = UDim2.fromScale(0.5, 0)
	frame12.Size = UDim2.new(10, 0, 0, 1)
	frame12.ZIndex = 10
	frame12.Parent = folder
	local frame13 = Instance.new("Frame")
	frame13.Name = "Y0"
	frame13.AnchorPoint = Vector2.new(0.5, 0.5)
	frame13.BackgroundColor3 = Color3.fromRGB(148, 189, 255)
	frame13.BackgroundTransparency = 0.6
	frame13.BorderColor3 = Color3.new()
	frame13.BorderSizePixel = 0
	frame13.Position = UDim2.fromScale(0.5, 1)
	frame13.Size = UDim2.new(10, 0, 0, 1)
	frame13.ZIndex = 10
	frame13.Parent = folder
	local frame14 = Instance.new("Frame")
	frame14.Name = "X0.125"
	frame14.AnchorPoint = Vector2.new(0.5, 0.5)
	frame14.BackgroundColor3 = Color3.new(1, 1, 1)
	frame14.BackgroundTransparency = 0.95
	frame14.BorderColor3 = Color3.new()
	frame14.BorderSizePixel = 0
	frame14.Position = UDim2.fromScale(0.125, 0.5)
	frame14.Size = UDim2.new(0, 1, 10, 0)
	frame14.ZIndex = 10
	frame14.Parent = folder
	local frame15 = Instance.new("Frame")
	frame15.Name = "X0.375"
	frame15.AnchorPoint = Vector2.new(0.5, 0.5)
	frame15.BackgroundColor3 = Color3.new(1, 1, 1)
	frame15.BackgroundTransparency = 0.95
	frame15.BorderColor3 = Color3.new()
	frame15.BorderSizePixel = 0
	frame15.Position = UDim2.fromScale(0.375, 0.5)
	frame15.Size = UDim2.new(0, 1, 10, 0)
	frame15.ZIndex = 10
	frame15.Parent = folder
	local frame16 = Instance.new("Frame")
	frame16.Name = "X0.625"
	frame16.AnchorPoint = Vector2.new(0.5, 0.5)
	frame16.BackgroundColor3 = Color3.new(1, 1, 1)
	frame16.BackgroundTransparency = 0.95
	frame16.BorderColor3 = Color3.new()
	frame16.BorderSizePixel = 0
	frame16.Position = UDim2.fromScale(0.625, 0.5)
	frame16.Size = UDim2.new(0, 1, 10, 0)
	frame16.ZIndex = 10
	frame16.Parent = folder
	local frame17 = Instance.new("Frame")
	frame17.Name = "X0.875"
	frame17.AnchorPoint = Vector2.new(0.5, 0.5)
	frame17.BackgroundColor3 = Color3.new(1, 1, 1)
	frame17.BackgroundTransparency = 0.95
	frame17.BorderColor3 = Color3.new()
	frame17.BorderSizePixel = 0
	frame17.Position = UDim2.fromScale(0.875, 0.5)
	frame17.Size = UDim2.new(0, 1, 10, 0)
	frame17.ZIndex = 10
	frame17.Parent = folder
	folder.Parent = frame8
	local folder2 = Instance.new("Folder")
	folder2.Name = "Curve"
	local frame18 = Instance.new("Frame")
	frame18.Name = "LineExample"
	frame18.AnchorPoint = Vector2.new(0.5, 0.5)
	frame18.BackgroundColor3 = Color3.new(1, 1, 1)
	frame18.BackgroundTransparency = 0.3
	frame18.BorderColor3 = Color3.new()
	frame18.BorderSizePixel = 0
	frame18.Position = UDim2.fromScale(0.5, 0.5)
	frame18.Size = UDim2.new(0.5, 0, 0, 1)
	frame18.ZIndex = 8
	frame18.Parent = folder2
	folder2.Parent = frame8
	local folder3 = Instance.new("Folder")
	folder3.Name = "ControlPoints"
	local frame19 = Instance.new("Frame")
	frame19.Name = "End"
	frame19.AnchorPoint = Vector2.new(0.5, 0.5)
	frame19.BackgroundColor3 = Color3.new(1, 1, 1)
	frame19.Position = UDim2.fromScale(1, 1)
	frame19.Size = UDim2.fromOffset(10, 10)
	frame19.ZIndex = 15
	local uICorner = Instance.new("UICorner")
	uICorner.BottomLeftRadius = UDim.new(1, 0)
	uICorner.BottomRightRadius = UDim.new(1, 0)
	uICorner.TopLeftRadius = UDim.new(1, 0)
	uICorner.TopRightRadius = UDim.new(1, 0)
	uICorner.Parent = frame19
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Transparency = 0.6
	uIStroke.Parent = frame19
	frame19.Parent = folder3
	local frame20 = Instance.new("Frame")
	frame20.Name = "Start"
	frame20.AnchorPoint = Vector2.new(0.5, 0.5)
	frame20.BackgroundColor3 = Color3.new(1, 1, 1)
	frame20.Position = UDim2.fromScale(0, 1)
	frame20.Size = UDim2.fromOffset(10, 10)
	frame20.ZIndex = 15
	local uICorner2 = Instance.new("UICorner")
	uICorner2.BottomLeftRadius = UDim.new(1, 0)
	uICorner2.BottomRightRadius = UDim.new(1, 0)
	uICorner2.TopLeftRadius = UDim.new(1, 0)
	uICorner2.TopRightRadius = UDim.new(1, 0)
	uICorner2.Parent = frame20
	local uIStroke2 = Instance.new("UIStroke")
	uIStroke2.Transparency = 0.6
	uIStroke2.Parent = frame20
	frame20.Parent = folder3
	folder3.Parent = frame8
	frame8.Parent = frame7
	local particleEmitter = Instance.new("ParticleEmitter")
	particleEmitter.LightInfluence = 1
	particleEmitter.Size = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 1),
		NumberSequenceKeypoint.new(0.385287, 5.125),
		NumberSequenceKeypoint.new(0.483791, 2.0625),
		NumberSequenceKeypoint.new(0.548628, 6.625),
		NumberSequenceKeypoint.new(0.63217, 2.125),
		NumberSequenceKeypoint.new(0.825436, 8),
		NumberSequenceKeypoint.new(1, 1)
	})
	particleEmitter.Parent = frame7
	frame7.Parent = frame6
	frame6.Parent = frame3
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = frame3
	local frame21 = Instance.new("Frame")
	frame21.Name = "Bottom"
	frame21.BackgroundColor3 = Color3.fromRGB(36, 36, 36)
	frame21.BorderColor3 = Color3.new()
	frame21.BorderSizePixel = 0
	frame21.LayoutOrder = 10
	frame21.Size = UDim2.new(1, 0, 0, 18)
	frame21.ZIndex = 3
	local frame22 = Instance.new("Frame")
	frame22.Name = "Ctn"
	frame22.AnchorPoint = Vector2.new(0.5, 0.5)
	frame22.BackgroundTransparency = 1
	frame22.Position = UDim2.fromScale(0.5, 0.5)
	frame22.Size = UDim2.new(1, -4, 1, -4)
	local uIListLayout3 = Instance.new("UIListLayout")
	uIListLayout3.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout3.HorizontalAlignment = Enum.HorizontalAlignment.Center
	uIListLayout3.HorizontalFlex = Enum.UIFlexAlignment.SpaceAround
	uIListLayout3.Padding = UDim.new(0, 2)
	uIListLayout3.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout3.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout3.Parent = frame22
	local frame23 = Instance.new("Frame")
	frame23.Name = "Max"
	frame23.BackgroundTransparency = 1
	frame23.LayoutOrder = 10
	frame23.Size = UDim2.new(0.2, -2, 1, 0)
	frame23.ZIndex = 10
	local textBox = Instance.new("TextBox")
	textBox.AnchorPoint = Vector2.new(1, 1)
	textBox.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	textBox.BorderColor3 = Color3.new()
	textBox.BorderSizePixel = 0
	textBox.FontFace = Font.new("rbxassetid://16658246179")
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromScale(1, 1)
	textBox.Size = UDim2.fromScale(0.35, 1)
	textBox.Text = "10"
	textBox.TextColor3 = Color3.new(1, 1, 1)
	textBox.TextSize = 14
	textBox.ZIndex = 10
	textBox.Parent = frame23
	local textLabel3 = Instance.new("TextLabel")
	textLabel3.BackgroundTransparency = 1
	textLabel3.FontFace = Font.new("rbxassetid://16658246179")
	textLabel3.LayoutOrder = -6
	textLabel3.Size = UDim2.fromScale(1, 1)
	textLabel3.Text = "Max: "
	textLabel3.TextColor3 = Color3.new(1, 1, 1)
	textLabel3.TextSize = 12
	textLabel3.TextXAlignment = Enum.TextXAlignment.Right
	textLabel3.ZIndex = 10
	local uIFlexItem2 = Instance.new("UIFlexItem")
	uIFlexItem2.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem2.Parent = textLabel3
	textLabel3.Parent = frame23
	local uIListLayout4 = Instance.new("UIListLayout")
	uIListLayout4.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout4.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout4.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout4.Parent = frame23
	frame23.Parent = frame22
	local frame24 = Instance.new("Frame")
	frame24.Name = "RemoveBtn"
	frame24.BackgroundTransparency = 1
	frame24.LayoutOrder = 50
	frame24.Size = UDim2.fromScale(0.1, 1)
	frame24.ZIndex = 10
	local uIListLayout5 = Instance.new("UIListLayout")
	uIListLayout5.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout5.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout5.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout5.Parent = frame24
	local textButton3 = Instance.new("TextButton")
	textButton3.Name = "Btn"
	textButton3.BackgroundColor3 = Color3.fromRGB(68, 72, 90)
	textButton3.BorderColor3 = Color3.new()
	textButton3.BorderSizePixel = 0
	textButton3.FontFace = Font.new("rbxassetid://16658246179")
	textButton3.Size = UDim2.new(0, 46, 1, 0)
	textButton3.Text = ""
	textButton3.TextColor3 = Color3.new(1, 1, 1)
	textButton3.TextSize = 12
	textButton3.ZIndex = 10
	local textLabel4 = Instance.new("TextLabel")
	textLabel4.Active = true
	textLabel4.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel4.BackgroundTransparency = 1
	textLabel4.FontFace = Font.new("rbxassetid://16658246179", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
	textLabel4.Position = UDim2.new(0.5, 1, 0.5, 1)
	textLabel4.Selectable = true
	textLabel4.Size = UDim2.fromScale(1, 1)
	textLabel4.Text = "Remove"
	textLabel4.TextColor3 = Color3.new(1, 1, 1)
	textLabel4.TextSize = 12
	textLabel4.ZIndex = 10
	textLabel4.Parent = textButton3
	textButton3.Parent = frame24
	frame24.Parent = frame22
	local frame25 = Instance.new("Frame")
	frame25.Name = "Time"
	frame25.BackgroundTransparency = 1
	frame25.LayoutOrder = -5
	frame25.Size = UDim2.new(0.2, -2, 1, 0)
	frame25.ZIndex = 10
	local textBox2 = Instance.new("TextBox")
	textBox2.AnchorPoint = Vector2.new(1, 1)
	textBox2.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	textBox2.BorderColor3 = Color3.new()
	textBox2.BorderSizePixel = 0
	textBox2.FontFace = Font.new("rbxassetid://16658246179")
	textBox2.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox2.Position = UDim2.fromScale(1, 1)
	textBox2.Size = UDim2.fromScale(0.35, 1)
	textBox2.Text = "10"
	textBox2.TextColor3 = Color3.new(1, 1, 1)
	textBox2.TextSize = 14
	textBox2.ZIndex = 10
	textBox2.Parent = frame25
	local textLabel5 = Instance.new("TextLabel")
	textLabel5.BackgroundTransparency = 1
	textLabel5.FontFace = Font.new("rbxassetid://16658246179")
	textLabel5.LayoutOrder = -6
	textLabel5.Size = UDim2.fromScale(1, 1)
	textLabel5.Text = "Time: "
	textLabel5.TextColor3 = Color3.new(1, 1, 1)
	textLabel5.TextSize = 12
	textLabel5.TextXAlignment = Enum.TextXAlignment.Right
	textLabel5.ZIndex = 10
	local uIFlexItem3 = Instance.new("UIFlexItem")
	uIFlexItem3.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem3.Parent = textLabel5
	textLabel5.Parent = frame25
	local uIListLayout6 = Instance.new("UIListLayout")
	uIListLayout6.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout6.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout6.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout6.Parent = frame25
	frame25.Parent = frame22
	local frame26 = Instance.new("Frame")
	frame26.Name = "Value"
	frame26.BackgroundTransparency = 1
	frame26.Size = UDim2.new(0.2, -2, 1, 0)
	frame26.ZIndex = 10
	local textBox3 = Instance.new("TextBox")
	textBox3.AnchorPoint = Vector2.new(1, 1)
	textBox3.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	textBox3.BorderColor3 = Color3.new()
	textBox3.BorderSizePixel = 0
	textBox3.FontFace = Font.new("rbxassetid://16658246179")
	textBox3.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox3.Position = UDim2.fromScale(1, 1)
	textBox3.Size = UDim2.fromScale(0.35, 1)
	textBox3.Text = "10"
	textBox3.TextColor3 = Color3.new(1, 1, 1)
	textBox3.TextSize = 14
	textBox3.ZIndex = 10
	textBox3.Parent = frame26
	local textLabel6 = Instance.new("TextLabel")
	textLabel6.BackgroundTransparency = 1
	textLabel6.FontFace = Font.new("rbxassetid://16658246179")
	textLabel6.LayoutOrder = -6
	textLabel6.Size = UDim2.fromScale(1, 1)
	textLabel6.Text = "Value: "
	textLabel6.TextColor3 = Color3.new(1, 1, 1)
	textLabel6.TextSize = 12
	textLabel6.TextXAlignment = Enum.TextXAlignment.Right
	textLabel6.ZIndex = 10
	local uIFlexItem4 = Instance.new("UIFlexItem")
	uIFlexItem4.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem4.Parent = textLabel6
	textLabel6.Parent = frame26
	local uIListLayout7 = Instance.new("UIListLayout")
	uIListLayout7.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout7.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout7.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout7.Parent = frame26
	frame26.Parent = frame22
	local frame27 = Instance.new("Frame")
	frame27.Name = "Min"
	frame27.BackgroundTransparency = 1
	frame27.LayoutOrder = 9
	frame27.Size = UDim2.new(0.2, -2, 1, 0)
	frame27.ZIndex = 10
	local textBox4 = Instance.new("TextBox")
	textBox4.AnchorPoint = Vector2.new(1, 1)
	textBox4.BackgroundColor3 = Color3.fromRGB(54, 54, 54)
	textBox4.BorderColor3 = Color3.new()
	textBox4.BorderSizePixel = 0
	textBox4.FontFace = Font.new("rbxassetid://16658246179")
	textBox4.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox4.Position = UDim2.fromScale(1, 1)
	textBox4.Size = UDim2.fromScale(0.35, 1)
	textBox4.Text = "0"
	textBox4.TextColor3 = Color3.new(1, 1, 1)
	textBox4.TextSize = 14
	textBox4.ZIndex = 10
	textBox4.Parent = frame27
	local textLabel7 = Instance.new("TextLabel")
	textLabel7.BackgroundTransparency = 1
	textLabel7.FontFace = Font.new("rbxassetid://16658246179")
	textLabel7.LayoutOrder = -6
	textLabel7.Size = UDim2.fromScale(1, 1)
	textLabel7.Text = "Min: "
	textLabel7.TextColor3 = Color3.new(1, 1, 1)
	textLabel7.TextSize = 12
	textLabel7.TextXAlignment = Enum.TextXAlignment.Right
	textLabel7.ZIndex = 10
	local uIFlexItem5 = Instance.new("UIFlexItem")
	uIFlexItem5.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem5.Parent = textLabel7
	textLabel7.Parent = frame27
	local uIListLayout8 = Instance.new("UIListLayout")
	uIListLayout8.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout8.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout8.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout8.Parent = frame27
	frame27.Parent = frame22
	frame22.Parent = frame21
	frame21.Parent = frame3
	frame3.Parent = frame
	return frame
end