return function()
	local frame = Instance.new("Frame")
	frame.Name = "Slider"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Slider"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local textBox = Instance.new("TextBox")
	textBox.BackgroundTransparency = 1
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromOffset(6, 0)
	textBox.Size = UDim2.fromScale(1, 1)
	textBox.Text = "0"
	textBox.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox.TextSize = 14
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.ZIndex = 800
	local uIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_2.Parent = textBox
	textBox.Parent = frame4
	local frame5 = Instance.new("Frame")
	frame5.Name = "SliderCtn"
	frame5.AnchorPoint = Vector2.new(1, 0)
	frame5.BackgroundTransparency = 1
	frame5.Position = UDim2.fromScale(1, 0)
	frame5.Size = UDim2.new(1, -26, 1, 0)
	local frame6 = Instance.new("Frame")
	frame6.Name = "SliderBar"
	frame6.AnchorPoint = Vector2.new(0.5, 0.5)
	frame6.BackgroundColor3 = Color3.new(1, 1, 1)
	frame6.BackgroundTransparency = 0.55
	frame6.BorderColor3 = Color3.new()
	frame6.Position = UDim2.fromScale(0.5, 0.5)
	frame6.Size = UDim2.fromScale(0.9, 0.15)
	frame6.ZIndex = 20
	local frame7 = Instance.new("Frame")
	frame7.Name = "Cursor"
	frame7.AnchorPoint = Vector2.new(0.5, 0.5)
	frame7.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame7.BorderColor3 = Color3.fromRGB(10, 10, 10)
	frame7.Position = UDim2.fromScale(0.5, 0.5)
	frame7.Size = UDim2.fromScale(5, 5)
	frame7.ZIndex = 30
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.AspectRatio = 0.3
	uIAspectRatioConstraint.Parent = frame7
	frame7.Parent = frame6
	local frame8 = Instance.new("Frame")
	frame8.Name = "SliderBG"
	frame8.AnchorPoint = Vector2.new(0, 0.5)
	frame8.BackgroundColor3 = Color3.fromRGB(93, 134, 172)
	frame8.BorderColor3 = Color3.new()
	frame8.BorderSizePixel = 0
	frame8.Position = UDim2.fromScale(0, 0.5)
	frame8.Size = UDim2.fromScale(0.5, 1)
	frame8.ZIndex = 25
	frame8.Parent = frame6
	frame6.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.Name = "SliderInteractibility"
	textButton.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Position = UDim2.fromScale(0.5, 0.5)
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 50
	textButton.Parent = frame5
	frame5.Parent = frame4
	frame4.Parent = frame
	local frame9 = Instance.new("Frame")
	frame9.Name = "WhiteFrame"
	frame9.BackgroundTransparency = 1
	frame9.Size = UDim2.fromScale(1, 1)
	frame9.ZIndex = 50
	frame9.Parent = frame
	return frame
end