return function()
	local frame = Instance.new("Frame")
	frame.Name = "Tab"
	frame.BackgroundColor3 = Color3.fromRGB(53, 53, 53)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.Size = UDim2.new(1, 0, 0, 100)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "TabCtn"
	frame2.BackgroundColor3 = Color3.new()
	frame2.BackgroundTransparency = 0.45
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(1, 0, 0, 18)
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Wraps = true
	uIListLayout.Parent = frame2
	local frame3 = Instance.new("Frame")
	frame3.Name = "TabFrameSelected"
	frame3.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame3.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderMode = Enum.BorderMode.Inset
	frame3.Size = UDim2.fromOffset(50, 18)
	frame3.ZIndex = 10
	local frame4 = Instance.new("Frame")
	frame4.Name = "DecoHighlight"
	frame4.BackgroundColor3 = Color3.fromRGB(53, 181, 255)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Size = UDim2.fromScale(1, 0.1)
	frame4.ZIndex = 20
	frame4.Parent = frame3
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel.Position = UDim2.fromScale(1, 0)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Camera"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 30
	textLabel.Parent = frame3
	local frame5 = Instance.new("Frame")
	frame5.Name = "WhiteFrame"
	frame5.BackgroundTransparency = 1
	frame5.Size = UDim2.fromScale(1, 1)
	frame5.ZIndex = 800
	frame5.Parent = frame3
	local textButton = Instance.new("TextButton")
	textButton.Name = "Interactibility"
	textButton.BackgroundTransparency = 1
	textButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton.Size = UDim2.fromScale(1, 1)
	textButton.Text = ""
	textButton.TextColor3 = Color3.new()
	textButton.TextSize = 14
	textButton.ZIndex = 3543456
	textButton.Parent = frame3
	frame3.Parent = frame2
	local frame6 = Instance.new("Frame")
	frame6.Name = "TabFrameUnSelected"
	frame6.BackgroundColor3 = Color3.fromRGB(64, 64, 64)
	frame6.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame6.BorderMode = Enum.BorderMode.Inset
	frame6.Size = UDim2.fromOffset(48, 18)
	frame6.ZIndex = 10
	local frame7 = Instance.new("Frame")
	frame7.Name = "DecoHighlight"
	frame7.BackgroundColor3 = Color3.fromRGB(53, 53, 53)
	frame7.BorderColor3 = Color3.new()
	frame7.BorderSizePixel = 0
	frame7.Size = UDim2.fromScale(1, 0.1)
	frame7.ZIndex = 20
	frame7.Parent = frame6
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Name = "Title"
	textLabel2.AnchorPoint = Vector2.new(1, 0)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel2.Position = UDim2.fromScale(1, 0)
	textLabel2.Size = UDim2.new(1, -6, 1, 0)
	textLabel2.Text = "Object"
	textLabel2.TextColor3 = Color3.fromRGB(170, 170, 170)
	textLabel2.TextSize = 14
	textLabel2.TextXAlignment = Enum.TextXAlignment.Left
	textLabel2.ZIndex = 30
	textLabel2.Parent = frame6
	local frame8 = Instance.new("Frame")
	frame8.Name = "WhiteFrame"
	frame8.BackgroundTransparency = 1
	frame8.Size = UDim2.fromScale(1, 1)
	frame8.ZIndex = 800
	frame8.Parent = frame6
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "Interactibility"
	textButton2.BackgroundTransparency = 1
	textButton2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.TextColor3 = Color3.new()
	textButton2.TextSize = 14
	textButton2.ZIndex = 3543456
	textButton2.Parent = frame6
	frame6.Parent = frame2
	frame2.Parent = frame
	local frame9 = Instance.new("Frame")
	frame9.Name = "ContentCtn"
	frame9.AnchorPoint = Vector2.new(0, 1)
	frame9.BackgroundTransparency = 1
	frame9.LayoutOrder = 8
	frame9.Position = UDim2.fromScale(0, 1)
	frame9.Size = UDim2.fromScale(1, 1)
	local frame10 = Instance.new("Frame")
	frame10.Name = "ContainerEx"
	frame10.BackgroundTransparency = 1
	frame10.Size = UDim2.fromScale(1, 1)
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.Parent = frame10
	frame10.Parent = frame9
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = frame9
	frame9.Parent = frame
	local uIListLayout3 = Instance.new("UIListLayout")
	uIListLayout3.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout3.Parent = frame
	return frame
end