return function()
	local frame = Instance.new("Frame")
	frame.Name = "Time"
	frame.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame.BorderColor3 = Color3.fromRGB(34, 34, 34)
	frame.BorderMode = Enum.BorderMode.Inset
	frame.LayoutOrder = 12
	frame.Size = UDim2.new(1, 0, 0, 22)
	frame.Visible = false
	local frame2 = Instance.new("Frame")
	frame2.Name = "Left"
	frame2.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame2.BorderColor3 = Color3.new()
	frame2.BorderSizePixel = 0
	frame2.Size = UDim2.new(0.5, -1, 1, 0)
	frame2.ZIndex = 15
	local textLabel = Instance.new("TextLabel")
	textLabel.Name = "Title"
	textLabel.AnchorPoint = Vector2.new(1, 0.5)
	textLabel.BackgroundTransparency = 1
	textLabel.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textLabel.Position = UDim2.fromScale(1, 0.5)
	textLabel.Size = UDim2.new(1, -6, 1, 0)
	textLabel.Text = "Time Selector"
	textLabel.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel.TextSize = 14
	textLabel.TextXAlignment = Enum.TextXAlignment.Left
	textLabel.ZIndex = 20
	textLabel.Parent = frame2
	frame2.Parent = frame
	local frame3 = Instance.new("Frame")
	frame3.Name = "BG"
	frame3.AnchorPoint = Vector2.new(0.5, 0.5)
	frame3.BackgroundColor3 = Color3.fromRGB(34, 34, 34)
	frame3.BorderColor3 = Color3.new()
	frame3.BorderSizePixel = 0
	frame3.Position = UDim2.fromScale(0.5, 0.5)
	frame3.Size = UDim2.new(1, 2, 1, 2)
	frame3.ZIndex = 10
	frame3.Parent = frame
	local frame4 = Instance.new("Frame")
	frame4.Name = "Right"
	frame4.AnchorPoint = Vector2.new(1, 0)
	frame4.BackgroundColor3 = Color3.fromRGB(46, 46, 46)
	frame4.BorderColor3 = Color3.new()
	frame4.BorderSizePixel = 0
	frame4.Position = UDim2.fromScale(1, 0)
	frame4.Size = UDim2.new(0.5, -1, 1, 0)
	frame4.ZIndex = 15
	local frame5 = Instance.new("Frame")
	frame5.Name = "Ctn"
	frame5.BackgroundColor3 = Color3.new(1, 1, 1)
	frame5.BorderColor3 = Color3.new()
	frame5.BorderSizePixel = 0
	frame5.Size = UDim2.fromScale(1, 1)
	local frame6 = Instance.new("Frame")
	frame6.Name = "NonEnabled"
	frame6.BackgroundColor3 = Color3.new(1, 1, 1)
	frame6.BackgroundTransparency = 0.9
	frame6.BorderColor3 = Color3.new()
	frame6.BorderSizePixel = 0
	frame6.Size = UDim2.fromScale(1, 1)
	frame6.Visible = false
	frame6.ZIndex = 900
	frame6.Parent = frame5
	local textButton = Instance.new("TextButton")
	textButton.Name = "Btn"
	textButton.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton.BackgroundTransparency = 1
	textButton.BorderMode = Enum.BorderMode.Inset
	textButton.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textButton.Position = UDim2.fromScale(0.5, 0.5)
	textButton.Size = UDim2.new(1, -2, 1, -2)
	textButton.Text = ""
	textButton.TextColor3 = Color3.fromRGB(229, 229, 229)
	textButton.TextSize = 14
	textButton.ZIndex = 850
	textButton.Parent = frame5
	local frame7 = Instance.new("Frame")
	frame7.Name = "TextCtn"
	frame7.AnchorPoint = Vector2.new(1, 0)
	frame7.BackgroundColor3 = Color3.new(1, 1, 1)
	frame7.BorderColor3 = Color3.new()
	frame7.BorderSizePixel = 0
	frame7.Position = UDim2.fromScale(1, 0)
	frame7.Size = UDim2.new(1, -6, 1, 0)
	local frame8 = Instance.new("Frame")
	frame8.Name = "IconCtn"
	frame8.AnchorPoint = Vector2.new(1, 0)
	frame8.BackgroundTransparency = 1
	frame8.LayoutOrder = 10
	frame8.Position = UDim2.fromScale(1, 0)
	frame8.Size = UDim2.fromScale(1, 1)
	local uIAspectRatioConstraint_2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint_2.Parent = frame8
	local imageLabel = Instance.new("ImageLabel")
	imageLabel.AnchorPoint = Vector2.new(0.5, 0.5)
	imageLabel.BackgroundTransparency = 1
	imageLabel.Image = "rbxassetid://4335485957"
	imageLabel.ImageTransparency = 0.8
	imageLabel.Position = UDim2.fromScale(0.5, 0.5)
	imageLabel.ScaleType = Enum.ScaleType.Fit
	imageLabel.Size = UDim2.fromScale(0.8, 0.8)
	imageLabel.ZIndex = 801
	imageLabel.Parent = frame8
	frame8.Parent = frame7
	local textBox = Instance.new("TextBox")
	textBox.Name = "TextLabel"
	textBox.Active = false
	textBox.AnchorPoint = Vector2.new(1, 0)
	textBox.BackgroundTransparency = 1
	textBox.ClearTextOnFocus = false
	textBox.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox.Interactable = false
	textBox.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox.Position = UDim2.fromScale(1, 0)
	textBox.Size = UDim2.fromScale(1, 1)
	textBox.Text = "Jan 4, 2026 4:35 PM"
	textBox.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox.TextEditable = false
	textBox.TextSize = 14
	textBox.TextTruncate = Enum.TextTruncate.AtEnd
	textBox.TextXAlignment = Enum.TextXAlignment.Left
	textBox.ZIndex = 802
	local uIFlexItem = Instance.new("UIFlexItem")
	uIFlexItem.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem.Parent = textBox
	textBox.Parent = frame7
	frame7.Parent = frame5
	frame5.Parent = frame4
	local frame9 = Instance.new("Frame")
	frame9.Name = "Selector"
	frame9.AnchorPoint = Vector2.new(0.5, 0)
	frame9.BackgroundTransparency = 1
	frame9.BorderMode = Enum.BorderMode.Inset
	frame9.Position = UDim2.fromScale(0, 1)
	frame9.Size = UDim2.new(2, 4, 2.25, 0)
	frame9.ZIndex = 9000000
	local frame10 = Instance.new("Frame")
	frame10.Name = "Ctn"
	frame10.AnchorPoint = Vector2.new(0, 0.5)
	frame10.BackgroundTransparency = 1
	frame10.Position = UDim2.new(0, -1, 0.5, 0)
	frame10.Size = UDim2.new(1, 0, 1, -2)
	local textButton2 = Instance.new("TextButton")
	textButton2.Name = "BG"
	textButton2.Active = false
	textButton2.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton2.AutoButtonColor = false
	textButton2.BackgroundColor3 = Color3.fromRGB(42, 42, 42)
	textButton2.BorderColor3 = Color3.new()
	textButton2.BorderSizePixel = 0
	textButton2.Position = UDim2.fromScale(0.5, 0.5)
	textButton2.Selectable = false
	textButton2.Size = UDim2.fromScale(1, 1)
	textButton2.Text = ""
	textButton2.ZIndex = 8999998
	local uIStroke = Instance.new("UIStroke")
	uIStroke.Parent = textButton2
	textButton2.Parent = frame10
	local folder = Instance.new("Folder")
	folder.Name = "Content"
	local uIListLayout = Instance.new("UIListLayout")
	uIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout.Parent = folder
	local frame11 = Instance.new("Frame")
	frame11.Name = "Top"
	frame11.BackgroundTransparency = 1
	frame11.Size = UDim2.fromScale(1, 1)
	local frame12 = Instance.new("Frame")
	frame12.Name = "Right"
	frame12.AnchorPoint = Vector2.new(0.5, 0)
	frame12.BackgroundTransparency = 1
	frame12.Position = UDim2.fromScale(0.5, 0)
	frame12.Size = UDim2.fromOffset(180, 40)
	local frame13 = Instance.new("Frame")
	frame13.Name = "Date"
	frame13.BackgroundTransparency = 1
	frame13.Size = UDim2.new(0, 108, 1, 0)
	local uIListLayout2 = Instance.new("UIListLayout")
	uIListLayout2.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout2.HorizontalAlignment = Enum.HorizontalAlignment.Center
	uIListLayout2.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout2.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout2.Parent = frame13
	local frame14 = Instance.new("Frame")
	frame14.Name = "Day"
	frame14.BackgroundTransparency = 1
	frame14.Size = UDim2.new(0, 30, 1, 0)
	frame14.ZIndex = 9000003
	local frame15 = Instance.new("Frame")
	frame15.Name = "Top"
	frame15.BackgroundTransparency = 1
	frame15.Size = UDim2.fromScale(1, 0.4)
	local textLabel2 = Instance.new("TextLabel")
	textLabel2.Name = "Title"
	textLabel2.AnchorPoint = Vector2.new(1, 0.5)
	textLabel2.BackgroundTransparency = 1
	textLabel2.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel2.Position = UDim2.fromScale(1, 0.5)
	textLabel2.Size = UDim2.fromScale(1, 1)
	textLabel2.Text = "D"
	textLabel2.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel2.TextSize = 14
	textLabel2.TextTransparency = 0.3
	textLabel2.ZIndex = 9000000
	textLabel2.Parent = frame15
	frame15.Parent = frame14
	local frame16 = Instance.new("Frame")
	frame16.Name = "Bottom"
	frame16.BackgroundTransparency = 1
	frame16.Size = UDim2.fromScale(1, 0.6)
	local frame17 = Instance.new("Frame")
	frame17.Name = "Ctn"
	frame17.AnchorPoint = Vector2.new(0.5, 0.5)
	frame17.BackgroundColor3 = Color3.new()
	frame17.BackgroundTransparency = 0.8
	frame17.Position = UDim2.fromScale(0.5, 0.5)
	frame17.Size = UDim2.fromScale(0.8, 0.8)
	frame17.ZIndex = 9000003
	local uICorner = Instance.new("UICorner")
	uICorner.BottomLeftRadius = UDim.new(0, 4)
	uICorner.BottomRightRadius = UDim.new(0, 4)
	uICorner.TopLeftRadius = UDim.new(0, 4)
	uICorner.TopRightRadius = UDim.new(0, 4)
	uICorner.Parent = frame17
	local textBox2 = Instance.new("TextBox")
	textBox2.Name = "Box"
	textBox2.Active = false
	textBox2.AnchorPoint = Vector2.new(1, 0.5)
	textBox2.BackgroundTransparency = 1
	textBox2.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox2.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox2.Position = UDim2.new(1, 0, 0.5, -1)
	textBox2.Selectable = false
	textBox2.Size = UDim2.fromScale(1, 1)
	textBox2.Text = "01"
	textBox2.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox2.TextSize = 14
	textBox2.TextTransparency = 0.1
	textBox2.ZIndex = 9000100
	textBox2.Parent = frame17
	frame17.Parent = frame16
	frame16.Parent = frame14
	local uIListLayout3 = Instance.new("UIListLayout")
	uIListLayout3.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout3.Parent = frame14
	frame14.Parent = frame13
	local frame18 = Instance.new("Frame")
	frame18.Name = "Border"
	frame18.AnchorPoint = Vector2.new(0.5, 0.5)
	frame18.BackgroundColor3 = Color3.new()
	frame18.BackgroundTransparency = 0.75
	frame18.BorderColor3 = Color3.new()
	frame18.BorderSizePixel = 0
	frame18.LayoutOrder = 1
	frame18.Size = UDim2.new(0, 1, 0.8, 0)
	frame18.ZIndex = 9000003
	frame18.Parent = frame13
	local frame19 = Instance.new("Frame")
	frame19.Name = "Month"
	frame19.BackgroundTransparency = 1
	frame19.LayoutOrder = 10
	frame19.Size = UDim2.new(0, 30, 1, 0)
	frame19.ZIndex = 9000003
	local frame20 = Instance.new("Frame")
	frame20.Name = "Top"
	frame20.BackgroundTransparency = 1
	frame20.Size = UDim2.fromScale(1, 0.4)
	local textLabel3 = Instance.new("TextLabel")
	textLabel3.Name = "Title"
	textLabel3.AnchorPoint = Vector2.new(1, 0.5)
	textLabel3.BackgroundTransparency = 1
	textLabel3.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel3.Position = UDim2.fromScale(1, 0.5)
	textLabel3.Size = UDim2.fromScale(1, 1)
	textLabel3.Text = "M"
	textLabel3.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel3.TextSize = 14
	textLabel3.TextTransparency = 0.3
	textLabel3.ZIndex = 9000000
	textLabel3.Parent = frame20
	frame20.Parent = frame19
	local frame21 = Instance.new("Frame")
	frame21.Name = "Bottom"
	frame21.BackgroundTransparency = 1
	frame21.Size = UDim2.fromScale(1, 0.6)
	local frame22 = Instance.new("Frame")
	frame22.Name = "Ctn"
	frame22.AnchorPoint = Vector2.new(0.5, 0.5)
	frame22.BackgroundColor3 = Color3.new()
	frame22.BackgroundTransparency = 0.8
	frame22.Position = UDim2.fromScale(0.5, 0.5)
	frame22.Size = UDim2.fromScale(0.8, 0.8)
	frame22.ZIndex = 9000003
	local uICorner2 = Instance.new("UICorner")
	uICorner2.BottomLeftRadius = UDim.new(0, 4)
	uICorner2.BottomRightRadius = UDim.new(0, 4)
	uICorner2.TopLeftRadius = UDim.new(0, 4)
	uICorner2.TopRightRadius = UDim.new(0, 4)
	uICorner2.Parent = frame22
	local textBox3 = Instance.new("TextBox")
	textBox3.Name = "Box"
	textBox3.Active = false
	textBox3.AnchorPoint = Vector2.new(1, 0.5)
	textBox3.BackgroundTransparency = 1
	textBox3.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox3.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox3.Position = UDim2.new(1, 0, 0.5, -1)
	textBox3.Selectable = false
	textBox3.Size = UDim2.fromScale(1, 1)
	textBox3.Text = "01"
	textBox3.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox3.TextSize = 14
	textBox3.TextTransparency = 0.1
	textBox3.ZIndex = 9000100
	textBox3.Parent = frame22
	frame22.Parent = frame21
	frame21.Parent = frame19
	local uIListLayout4 = Instance.new("UIListLayout")
	uIListLayout4.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout4.Parent = frame19
	frame19.Parent = frame13
	local frame23 = Instance.new("Frame")
	frame23.Name = "Border"
	frame23.AnchorPoint = Vector2.new(0.5, 0.5)
	frame23.BackgroundColor3 = Color3.new()
	frame23.BackgroundTransparency = 0.75
	frame23.BorderColor3 = Color3.new()
	frame23.BorderSizePixel = 0
	frame23.LayoutOrder = 11
	frame23.Size = UDim2.new(0, 1, 0.8, 0)
	frame23.ZIndex = 9000003
	frame23.Parent = frame13
	local frame24 = Instance.new("Frame")
	frame24.Name = "Year"
	frame24.BackgroundTransparency = 1
	frame24.LayoutOrder = 20
	frame24.Size = UDim2.new(0, 40, 1, 0)
	frame24.ZIndex = 9000003
	local frame25 = Instance.new("Frame")
	frame25.Name = "Top"
	frame25.BackgroundTransparency = 1
	frame25.Size = UDim2.fromScale(1, 0.4)
	local textLabel4 = Instance.new("TextLabel")
	textLabel4.Name = "Title"
	textLabel4.AnchorPoint = Vector2.new(1, 0.5)
	textLabel4.BackgroundTransparency = 1
	textLabel4.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel4.Position = UDim2.fromScale(1, 0.5)
	textLabel4.Size = UDim2.fromScale(1, 1)
	textLabel4.Text = "Y"
	textLabel4.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel4.TextSize = 14
	textLabel4.TextTransparency = 0.3
	textLabel4.ZIndex = 9000000
	textLabel4.Parent = frame25
	frame25.Parent = frame24
	local frame26 = Instance.new("Frame")
	frame26.Name = "Bottom"
	frame26.BackgroundTransparency = 1
	frame26.Size = UDim2.fromScale(1, 0.6)
	local frame27 = Instance.new("Frame")
	frame27.Name = "Ctn"
	frame27.AnchorPoint = Vector2.new(0.5, 0.5)
	frame27.BackgroundColor3 = Color3.new()
	frame27.BackgroundTransparency = 0.8
	frame27.Position = UDim2.fromScale(0.5, 0.5)
	frame27.Size = UDim2.fromScale(0.8, 0.8)
	frame27.ZIndex = 9000003
	local uICorner3 = Instance.new("UICorner")
	uICorner3.BottomLeftRadius = UDim.new(0, 4)
	uICorner3.BottomRightRadius = UDim.new(0, 4)
	uICorner3.TopLeftRadius = UDim.new(0, 4)
	uICorner3.TopRightRadius = UDim.new(0, 4)
	uICorner3.Parent = frame27
	local textBox4 = Instance.new("TextBox")
	textBox4.Name = "Box"
	textBox4.Active = false
	textBox4.AnchorPoint = Vector2.new(1, 0.5)
	textBox4.BackgroundTransparency = 1
	textBox4.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox4.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox4.Position = UDim2.new(1, 0, 0.5, -1)
	textBox4.Selectable = false
	textBox4.Size = UDim2.fromScale(1, 1)
	textBox4.Text = "2026"
	textBox4.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox4.TextSize = 14
	textBox4.TextTransparency = 0.1
	textBox4.ZIndex = 9000100
	textBox4.Parent = frame27
	frame27.Parent = frame26
	frame26.Parent = frame24
	local uIListLayout5 = Instance.new("UIListLayout")
	uIListLayout5.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout5.Parent = frame24
	frame24.Parent = frame13
	frame13.Parent = frame12
	local uIListLayout6 = Instance.new("UIListLayout")
	uIListLayout6.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout6.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout6.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout6.Parent = frame12
	local frame28 = Instance.new("Frame")
	frame28.Name = "Time"
	frame28.BackgroundTransparency = 1
	frame28.LayoutOrder = 20
	frame28.Size = UDim2.new(0, 70, 1, 0)
	local uIListLayout7 = Instance.new("UIListLayout")
	uIListLayout7.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout7.HorizontalAlignment = Enum.HorizontalAlignment.Center
	uIListLayout7.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout7.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout7.Parent = frame28
	local frame29 = Instance.new("Frame")
	frame29.Name = "Hour"
	frame29.BackgroundTransparency = 1
	frame29.Size = UDim2.new(0, 30, 1, 0)
	frame29.ZIndex = 9000003
	local frame30 = Instance.new("Frame")
	frame30.Name = "Top"
	frame30.BackgroundTransparency = 1
	frame30.Size = UDim2.fromScale(1, 0.4)
	local textLabel5 = Instance.new("TextLabel")
	textLabel5.Name = "Title"
	textLabel5.AnchorPoint = Vector2.new(1, 0.5)
	textLabel5.BackgroundTransparency = 1
	textLabel5.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel5.Position = UDim2.fromScale(1, 0.5)
	textLabel5.Size = UDim2.fromScale(1, 1)
	textLabel5.Text = "H"
	textLabel5.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel5.TextSize = 14
	textLabel5.TextTransparency = 0.3
	textLabel5.ZIndex = 9000000
	textLabel5.Parent = frame30
	frame30.Parent = frame29
	local frame31 = Instance.new("Frame")
	frame31.Name = "Bottom"
	frame31.BackgroundTransparency = 1
	frame31.Size = UDim2.fromScale(1, 0.6)
	local frame32 = Instance.new("Frame")
	frame32.Name = "Ctn"
	frame32.AnchorPoint = Vector2.new(0.5, 0.5)
	frame32.BackgroundColor3 = Color3.new()
	frame32.BackgroundTransparency = 0.8
	frame32.Position = UDim2.fromScale(0.5, 0.5)
	frame32.Size = UDim2.fromScale(0.8, 0.8)
	frame32.ZIndex = 9000003
	local uICorner4 = Instance.new("UICorner")
	uICorner4.BottomLeftRadius = UDim.new(0, 4)
	uICorner4.BottomRightRadius = UDim.new(0, 4)
	uICorner4.TopLeftRadius = UDim.new(0, 4)
	uICorner4.TopRightRadius = UDim.new(0, 4)
	uICorner4.Parent = frame32
	local textBox5 = Instance.new("TextBox")
	textBox5.Name = "Box"
	textBox5.Active = false
	textBox5.AnchorPoint = Vector2.new(1, 0.5)
	textBox5.BackgroundTransparency = 1
	textBox5.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox5.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox5.Position = UDim2.new(1, 0, 0.5, -1)
	textBox5.Selectable = false
	textBox5.Size = UDim2.fromScale(1, 1)
	textBox5.Text = "01"
	textBox5.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox5.TextSize = 14
	textBox5.TextTransparency = 0.1
	textBox5.ZIndex = 9000100
	textBox5.Parent = frame32
	frame32.Parent = frame31
	frame31.Parent = frame29
	local uIListLayout8 = Instance.new("UIListLayout")
	uIListLayout8.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout8.Parent = frame29
	frame29.Parent = frame28
	local frame33 = Instance.new("Frame")
	frame33.Name = "Border"
	frame33.AnchorPoint = Vector2.new(0.5, 0.5)
	frame33.BackgroundColor3 = Color3.new()
	frame33.BackgroundTransparency = 0.75
	frame33.BorderColor3 = Color3.new()
	frame33.BorderSizePixel = 0
	frame33.LayoutOrder = 1
	frame33.Size = UDim2.new(0, 1, 0.8, 0)
	frame33.ZIndex = 9000003
	frame33.Parent = frame28
	local frame34 = Instance.new("Frame")
	frame34.Name = "Minute"
	frame34.BackgroundTransparency = 1
	frame34.LayoutOrder = 10
	frame34.Size = UDim2.new(0, 30, 1, 0)
	frame34.ZIndex = 9000003
	local frame35 = Instance.new("Frame")
	frame35.Name = "Top"
	frame35.BackgroundTransparency = 1
	frame35.Size = UDim2.fromScale(1, 0.4)
	local textLabel6 = Instance.new("TextLabel")
	textLabel6.Name = "Title"
	textLabel6.AnchorPoint = Vector2.new(1, 0.5)
	textLabel6.BackgroundTransparency = 1
	textLabel6.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel6.Position = UDim2.fromScale(1, 0.5)
	textLabel6.Size = UDim2.fromScale(1, 1)
	textLabel6.Text = "M"
	textLabel6.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel6.TextSize = 14
	textLabel6.TextTransparency = 0.3
	textLabel6.ZIndex = 9000000
	textLabel6.Parent = frame35
	frame35.Parent = frame34
	local frame36 = Instance.new("Frame")
	frame36.Name = "Bottom"
	frame36.BackgroundTransparency = 1
	frame36.Size = UDim2.fromScale(1, 0.6)
	local frame37 = Instance.new("Frame")
	frame37.Name = "Ctn"
	frame37.AnchorPoint = Vector2.new(0.5, 0.5)
	frame37.BackgroundColor3 = Color3.new()
	frame37.BackgroundTransparency = 0.8
	frame37.Position = UDim2.fromScale(0.5, 0.5)
	frame37.Size = UDim2.fromScale(0.8, 0.8)
	frame37.ZIndex = 9000003
	local uICorner5 = Instance.new("UICorner")
	uICorner5.BottomLeftRadius = UDim.new(0, 4)
	uICorner5.BottomRightRadius = UDim.new(0, 4)
	uICorner5.TopLeftRadius = UDim.new(0, 4)
	uICorner5.TopRightRadius = UDim.new(0, 4)
	uICorner5.Parent = frame37
	local textBox6 = Instance.new("TextBox")
	textBox6.Name = "Box"
	textBox6.Active = false
	textBox6.AnchorPoint = Vector2.new(1, 0.5)
	textBox6.BackgroundTransparency = 1
	textBox6.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox6.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox6.Position = UDim2.new(1, 0, 0.5, -1)
	textBox6.Selectable = false
	textBox6.Size = UDim2.fromScale(1, 1)
	textBox6.Text = "01"
	textBox6.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox6.TextSize = 14
	textBox6.TextTransparency = 0.1
	textBox6.ZIndex = 9000100
	textBox6.Parent = frame37
	frame37.Parent = frame36
	frame36.Parent = frame34
	local uIListLayout9 = Instance.new("UIListLayout")
	uIListLayout9.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout9.Parent = frame34
	frame34.Parent = frame28
	frame28.Parent = frame12
	local frame38 = Instance.new("Frame")
	frame38.Name = "Border"
	frame38.AnchorPoint = Vector2.new(0.5, 0.5)
	frame38.BackgroundColor3 = Color3.new()
	frame38.BackgroundTransparency = 0.75
	frame38.BorderColor3 = Color3.new()
	frame38.BorderSizePixel = 0
	frame38.LayoutOrder = 10
	frame38.Size = UDim2.new(0, 2, 0.8, 0)
	frame38.ZIndex = 9000003
	frame38.Parent = frame12
	frame12.Parent = frame11
	local uIListLayout10 = Instance.new("UIListLayout")
	uIListLayout10.FillDirection = Enum.FillDirection.Horizontal
	uIListLayout10.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout10.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout10.Parent = frame11
	local frame39 = Instance.new("Frame")
	frame39.Name = "Left"
	frame39.BackgroundColor3 = Color3.new()
	frame39.BackgroundTransparency = 0.9
	frame39.BorderColor3 = Color3.new()
	frame39.BorderSizePixel = 0
	frame39.LayoutOrder = -5
	frame39.Size = UDim2.fromScale(1, 1)
	frame39.ZIndex = 9000000
	local uIFlexItem2 = Instance.new("UIFlexItem")
	uIFlexItem2.FlexMode = Enum.UIFlexMode.Fill
	uIFlexItem2.Parent = frame39
	local frame40 = Instance.new("Frame")
	frame40.Name = "SetToNow"
	frame40.AnchorPoint = Vector2.new(0.5, 0.5)
	frame40.BackgroundTransparency = 1
	frame40.LayoutOrder = -4
	frame40.Position = UDim2.fromScale(0.5, 0.5)
	frame40.Size = UDim2.fromScale(1, 0.35)
	frame40.ZIndex = 9000005
	local textButton3 = Instance.new("TextButton")
	textButton3.Name = "Btn"
	textButton3.AnchorPoint = Vector2.new(0.5, 0.5)
	textButton3.BackgroundTransparency = 1
	textButton3.BorderMode = Enum.BorderMode.Inset
	textButton3.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textButton3.Position = UDim2.fromScale(0.5, 0.5)
	textButton3.Size = UDim2.new(1, -2, 1, -2)
	textButton3.Text = ""
	textButton3.TextColor3 = Color3.fromRGB(229, 229, 229)
	textButton3.TextSize = 21
	textButton3.TextWrapped = true
	textButton3.ZIndex = 9000021
	textButton3.Parent = frame40
	local uIAspectRatioConstraint = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint.AspectRatio = 5.5
	uIAspectRatioConstraint.Parent = frame40
	local textLabel7 = Instance.new("TextLabel")
	textLabel7.Active = true
	textLabel7.AnchorPoint = Vector2.new(0.5, 0.5)
	textLabel7.BackgroundTransparency = 1
	textLabel7.BorderMode = Enum.BorderMode.Inset
	textLabel7.FontFace = Font.new(
		"rbxasset://fonts/families/SourceSansPro.json",
		Enum.FontWeight.Bold,
		Enum.FontStyle.Normal
	)
	textLabel7.Position = UDim2.fromScale(0.5, 0.5)
	textLabel7.Selectable = true
	textLabel7.Size = UDim2.fromScale(1, 0.9)
	textLabel7.Text = "Set to NOW"
	textLabel7.TextColor3 = Color3.fromRGB(229, 229, 229)
	textLabel7.TextScaled = true
	textLabel7.ZIndex = 9000018
	textLabel7.Parent = frame40
	local frame41 = Instance.new("Frame")
	frame41.Name = "BG"
	frame41.AnchorPoint = Vector2.new(0.5, 0.5)
	frame41.BackgroundColor3 = Color3.fromRGB(36, 126, 175)
	frame41.Position = UDim2.fromScale(0.5, 0.5)
	frame41.Size = UDim2.fromScale(1, 1)
	frame41.ZIndex = 9000012
	local uICorner6 = Instance.new("UICorner")
	uICorner6.BottomLeftRadius = UDim.new(0, 4)
	uICorner6.BottomRightRadius = UDim.new(0, 4)
	uICorner6.TopLeftRadius = UDim.new(0, 4)
	uICorner6.TopRightRadius = UDim.new(0, 4)
	uICorner6.Parent = frame41
	frame41.Parent = frame40
	local frame42 = Instance.new("Frame")
	frame42.Name = "Hover"
	frame42.AnchorPoint = Vector2.new(0.5, 0.5)
	frame42.BackgroundColor3 = Color3.new()
	frame42.BackgroundTransparency = 0.8
	frame42.Position = UDim2.fromScale(0.5, 0.5)
	frame42.Size = UDim2.fromScale(1, 1)
	frame42.Visible = false
	frame42.ZIndex = 9000080
	local uICorner7 = Instance.new("UICorner")
	uICorner7.BottomLeftRadius = UDim.new(0, 4)
	uICorner7.BottomRightRadius = UDim.new(0, 4)
	uICorner7.TopLeftRadius = UDim.new(0, 4)
	uICorner7.TopRightRadius = UDim.new(0, 4)
	uICorner7.Parent = frame42
	frame42.Parent = frame40
	frame40.Parent = frame39
	local uIListLayout11 = Instance.new("UIListLayout")
	uIListLayout11.HorizontalAlignment = Enum.HorizontalAlignment.Right
	uIListLayout11.Padding = UDim.new(0, 2)
	uIListLayout11.SortOrder = Enum.SortOrder.LayoutOrder
	uIListLayout11.VerticalAlignment = Enum.VerticalAlignment.Center
	uIListLayout11.VerticalFlex = Enum.UIFlexAlignment.SpaceEvenly
	uIListLayout11.Parent = frame39
	local uIPadding = Instance.new("UIPadding")
	uIPadding.PaddingRight = UDim.new(0, 4)
	uIPadding.Parent = frame39
	local frame43 = Instance.new("Frame")
	frame43.Name = "Timestamp"
	frame43.AnchorPoint = Vector2.new(0.5, 0.5)
	frame43.BackgroundTransparency = 1
	frame43.Position = UDim2.fromScale(0.5, 0.5)
	frame43.Size = UDim2.fromScale(1, 0.4)
	frame43.ZIndex = 9000005
	local frame44 = Instance.new("Frame")
	frame44.Name = "BG"
	frame44.AnchorPoint = Vector2.new(0.5, 0.5)
	frame44.BackgroundColor3 = Color3.new()
	frame44.BackgroundTransparency = 0.8
	frame44.Position = UDim2.fromScale(0.5, 0.5)
	frame44.Size = UDim2.fromScale(1, 1)
	frame44.ZIndex = 9000012
	local uICorner8 = Instance.new("UICorner")
	uICorner8.BottomLeftRadius = UDim.new(0, 4)
	uICorner8.BottomRightRadius = UDim.new(0, 4)
	uICorner8.TopLeftRadius = UDim.new(0, 4)
	uICorner8.TopRightRadius = UDim.new(0, 4)
	uICorner8.Parent = frame44
	frame44.Parent = frame43
	local textBox7 = Instance.new("TextBox")
	textBox7.Name = "Box"
	textBox7.AnchorPoint = Vector2.new(0.5, 0.5)
	textBox7.BackgroundTransparency = 1
	textBox7.BorderMode = Enum.BorderMode.Inset
	textBox7.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
	textBox7.PlaceholderColor3 = Color3.fromRGB(178, 178, 178)
	textBox7.Position = UDim2.fromScale(0.5, 0.5)
	textBox7.Size = UDim2.new(1, -8, 0.85, 0)
	textBox7.Text = "1767225660"
	textBox7.TextColor3 = Color3.fromRGB(229, 229, 229)
	textBox7.TextScaled = true
	textBox7.TextTransparency = 0.1
	textBox7.TextXAlignment = Enum.TextXAlignment.Right
	textBox7.ZIndex = 9000018
	textBox7.Parent = frame43
	local uIAspectRatioConstraint2 = Instance.new("UIAspectRatioConstraint")
	uIAspectRatioConstraint2.AspectRatio = 4.9
	uIAspectRatioConstraint2.Parent = frame43
	frame43.Parent = frame39
	frame39.Parent = frame11
	frame11.Parent = folder
	folder.Parent = frame10
	local frame45 = Instance.new("Frame")
	frame45.Name = "BottomBorder"
	frame45.AnchorPoint = Vector2.new(0, 1)
	frame45.BackgroundColor3 = Color3.new()
	frame45.BackgroundTransparency = 0.75
	frame45.BorderColor3 = Color3.new()
	frame45.BorderSizePixel = 0
	frame45.Position = UDim2.fromScale(0, 1)
	frame45.Size = UDim2.new(1, 0, 0, 1)
	frame45.ZIndex = 9000001
	frame45.Parent = frame10
	frame10.Parent = frame9
	frame9.Parent = frame4
	frame4.Parent = frame
	local frame46 = Instance.new("Frame")
	frame46.Name = "WhiteFrame"
	frame46.BackgroundTransparency = 1
	frame46.Size = UDim2.fromScale(1, 1)
	frame46.ZIndex = 50
	frame46.Parent = frame
	return frame
end