local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Observers = require(ReplicatedStorage.Packages.Observers)
local Utils = require(ReplicatedStorage.Common.Utils)
return Observers.observeTagNoAncestry("UI_SpecialTextBox", function(instance)
	local maid = Utils.Maid.new()
	local box = instance:WaitForChild("Box")
	local focusedBar = instance:WaitForChild("FocusedBar")
	maid:GiveTask(box.Focused:Connect(function()
		focusedBar.BackgroundColor3 = Color3.fromRGB(0, 162, 255)
		focusedBar.Size = UDim2.new(focusedBar.Size.X.Scale, focusedBar.Size.X.Offset, focusedBar.Size.Y.Scale, 3)
	end))
	maid:GiveTask(box.FocusLost:Connect(function()
		focusedBar.BackgroundColor3 = Color3.fromRGB(128, 128, 128)
		focusedBar.Size = UDim2.new(focusedBar.Size.X.Scale, focusedBar.Size.X.Offset, focusedBar.Size.Y.Scale, 1)
	end))
	return function()
		maid:Destroy()
	end
end)