return {
	MOUSE_RANGE = 500,
	ANIM_FREEZE_AT = 0.25,
	ENDLAG = 0.35,
	BLAST_AT = 0.2,
	PVP_WINDUP = 0.1,
	BLAST_HITBOX_OFFSET = CFrame.new(0, 0, -7),
	BLAST_HITBOX_SIZE = vector.create(27, 27, 27),
	BLAST_DAMAGE = 25,
	BLAST_STUN = 1.5,
	BLAST_RAGDOLL = 1.5,
	BLAST_KNOCKBACK = 35,
	BLAST_KNOCKUP = 25,
	BLAST_KNOCKBACK_DURATION = 0.15,
	BLAST_BLOCK_BREAK = 5
}