local CONSTANTS = require(game.ReplicatedStorage.React.Components.Map.CONSTANTS)
local v = {
	["Pirate Village"] = "Pirate Village",
	["Middle Town"] = "Middle Town",
	["Pirate Starter"] = "Pirate Starter",
	["Marine Starter"] = "Marine Starter",
	Fountain = "Fountain",
	Prison = "Prison",
	["Magma Village"] = "Magma Village",
	Desert = "Desert",
	["Marine Fortress"] = "Marine Fortress",
	["Frozen Village"] = "Frozen Village",
	Jungle = "Jungle",
	["Underwater City"] = "Underwater City",
	Colosseum = "Colosseum",
	Sky = "Sky",
	SkyArea2 = "SkyArea2",
	["Bandit Village"] = "Bandit Village",
	NE = "NE",
	SE = "SE",
	SW = "SW",
	NW = "NW",
	N = "N",
	S = "S",
	E = "E",
	W = "W"
}
return {
	TRIANGLES = {
		{ v.Sky, v.Colosseum, v["Marine Starter"] },
		{ v.Colosseum, v.Jungle, v["Marine Starter"] },
		{ v.Colosseum, v["Frozen Village"], v.Jungle },
		{ v["Frozen Village"], v.Colosseum, v["Underwater City"] },
		{ v.Sky, v["Marine Fortress"], v["Magma Village"] },
		{ v.Sky, v["Marine Fortress"], v["Marine Starter"] },
		{ v["Marine Starter"], v["Marine Fortress"], v["Bandit Village"] },
		{ v["Magma Village"], v["Marine Fortress"], v["Bandit Village"] },
		{ v["Marine Starter"], v["Pirate Village"], v["Bandit Village"] },
		{ v["Pirate Village"], v.Desert, v["Magma Village"] },
		{ v["Pirate Village"], v["Bandit Village"], v["Magma Village"] },
		{ v["Middle Town"], v["Marine Starter"], v["Pirate Village"] },
		{ v["Marine Starter"], v["Middle Town"], v.Jungle },
		{ v["Middle Town"], v["Pirate Starter"], v["Pirate Village"] },
		{ v["Frozen Village"], v["Middle Town"], v.Jungle },
		{ v["Frozen Village"], v["Pirate Starter"], v["Middle Town"] },
		{ v["Underwater City"], v["Frozen Village"], v["Pirate Starter"] },
		{ v["Underwater City"], v.Prison, v["Pirate Starter"] },
		{ v["Pirate Starter"], v.Desert, v.Prison },
		{ v.Prison, v.Desert, v.Fountain },
		{ v["Magma Village"], v.Desert, v.Fountain },
		{ v.NW, v.SkyArea2, v.SW },
		{ v.SkyArea2, v.SW, v["Magma Village"] },
		{ v.SW, v["Magma Village"], v.SE },
		{ v.Fountain, v.SE, v["Magma Village"] },
		{ v.SE, v.Fountain, v.NE },
		{ v.Prison, v.Fountain, v.NE },
		{ v.Prison, v["Underwater City"], v.NE },
		{ v.Colosseum, v["Underwater City"], v.NE },
		{ v.Colosseum, v.Sky, v.NW },
		{ v.NE, v.Colosseum, v.NW },
		{ v.SkyArea2, v.Sky, v["Magma Village"] },
		{ v.SkyArea2, v.Sky, v.NW },
		{ v["Pirate Village"], v["Pirate Starter"], v.Desert }
	},
	ISLAND_NAMES = v,
	WORLD_BUFFER = CONSTANTS.USE_REAL_SCALE and 1500 or 4000
}