return {
	MAX_DURATION = 1.5,
	WINDUP = 0.3,
	BUFF_DURATION = 8,
	BUFF_SKILL_NAME = "War Gale Wind",
	BUFF_STATE_VALUE = "WarChantBuff",
	BUFF_MARK_VALUE = "WarChantMark",
	BUFF_DAMAGE_FACTOR = 0.15,
	BUFF_SPEED_FACTOR = 0.15,
	COUNTER_DAMAGE = 18,
	COUNTER_STUN_DURATION = 1,
	COUNTER_LOCK_DURATION = 0.5
}